<?xml version="1.0" encoding="UTF-8"?>
<!--INACTIVE-->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
    <include schemaLocation="sharedTypes.xsd"/>
    <element name="amalgamateModule" type="fews:amalgamateModuleComplexType"/>
    <!--    -->
    <complexType name="amalgamateModuleComplexType">
        <sequence>
            <element name="task" type="fews:AmalgamateTaskComplexType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <!--    -->
    <complexType name="AmalgamateTaskComplexType">
        <sequence>
            <element name="maximumCombinedBlobLength" type="fews:TimeSpanComplexType"/>
            <element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

</schema>
