<?xml version="1.0" encoding="UTF-8"?>
<!--INACTIVE-->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="archiveRun" type="fews:ArchiveRunComplexType">
		<annotation>
			<documentation>Contains archive properties</documentation>
		</annotation>
	</element>
	<complexType name="ArchiveRunComplexType">
		<annotation>
			<documentation>Describes all archive activities</documentation>
		</annotation>
		<sequence>
			<element name="importDirectory" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Location from which forecast archive files are imported. Import happens each Archive run. Afterwards the files are deleted.</documentation>
				</annotation>
			</element>
			<element name="exportDirectory" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>All archives in the system that have been marked for export are exported to this directory.</documentation>
				</annotation>
			</element>
			<choice minOccurs="0">
				<element name="importArchiveRun" type="fews:ImportArchiveRunComplexType"/>
				<element name="exportArchiveRun" type="fews:ExportArchiveRunComplexType"/>
			</choice>
		</sequence>
	</complexType>
	<complexType name="ExportArchiveRunComplexType">
		<annotation>
			<documentation>Describes Export archive activity</documentation>
		</annotation>
		<sequence>
			<element name="archivePeriod" type="fews:RelativePeriodComplexType">
				<annotation>
					<documentation>Period over which to select approved forecasts.</documentation>
				</annotation>
			</element>
			<element name="workflow" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Retrieve runs produced by given workflows. If no workflow defined then retrieve all runs.</documentation>
				</annotation>
			</element>
			<element name="exportToFile" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Export the created archives to single ZIP file.</documentation>
				</annotation>
			</element>
			<element name="exportToDatabase" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Export the created archives to database table.</documentation>
				</annotation>
			</element>
			<element name="overrulingPeriod" type="fews:RelativePeriodComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional period to allow extra external historical data to be included in the archives.</documentation>
				</annotation>
			</element>
			<element name="excludeTimeSeriesExpiringWithin" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>FEWS-15681. To prevent archiving time series who expiring during the creation of the archie. This gives an error for technical reasons.</documentation>
				</annotation>
			</element>
			<element name="onlyApproved" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>Option to also archive non-approved forecast runs.</documentation>
				</annotation>
			</element>
			<element name="archiveType" type="fews:ArchiveTypeStringType" minOccurs="0">
				<annotation>
					<documentation>Indicates the Type of archive to export. If omitted, a ForecastArchive is assumed. Optional for backward compatibility</documentation>
				</annotation>
			</element>
			<element name="logEventConstraint" type="fews:LogEventConstraintComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description to be added to Archive Manifest</documentation>
				</annotation>
			</element>
			<element name="includeModuleInstanceId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>ModuleInstanceIds of TimeSeries to add to archive</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ImportArchiveRunComplexType">
		<annotation>
			<documentation>Describes Import archive activity</documentation>
		</annotation>
		<sequence>
			<element name="archiveType" type="fews:ArchiveTypeStringType" minOccurs="0">
				<annotation>
					<documentation>Indicates the Type of archive to import. If omitted, a ForecastArchive is assumed. Optional for backward compatibility</documentation>
				</annotation>
			</element>
			<element name="includeGrids" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>Indicates if  the grids should be imported from the archive. If omitted, the grids are imported</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="ArchiveTypeStringType">
		<annotation>
			<documentation>Describes the different types of Archive activities</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="ForecastArchive"/>
			<enumeration value="ThresholdEventsArchive"/>
			<enumeration value="TimeSeriesArchive"/>
			<enumeration value="ConfigurationArchive"/>
			<enumeration value="LogEntriesArchive"/>
		</restriction>
	</simpleType>
	<complexType name="LogEventConstraintComplexType">
		<attribute name="eventCode" type="fews:nonEmptyStringType"/>
		<attribute name="messageText" type="fews:nonEmptyStringType"/>
	</complexType>
</schema>
