<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="decisionModule.xsd"/>
	<!-- -->
	<!-- Top-level element Declaration -->
	<!-- -->
	<element name="Barriers" type="fews:BarriersComplexType"/>
	<!-- -->
	<!--complexType Definitions -->
	<!-- -->
	<complexType name="BarriersComplexType">
		<sequence>
			<element name="variable" type="fews:DecisionVariableDefinitionComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Definitions of variables that can be used as variables in the rules. A variable is always a time series. </documentation>
				</annotation>
			</element>
			<element name="barrier" type="fews:BarrierComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>One or more barriers.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="BarrierComplexType">
		<sequence>
			<element name="stateDefinition" type="fews:BarrierStateDefinitionComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of the different states in which the barrier can occur, always linked to a variableId of a timeseriesSet.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nameStringType" use="required"/>
	</complexType>
	<complexType name="BarrierStateComplexType">
		<sequence>
			<element name="parameterValue" maxOccurs="unbounded">
				<annotation>
					<documentation>Parameter definitions associated for this state</documentation>
				</annotation>
				<complexType>
					<attribute name="parameterId" type="fews:idStringType" use="required"/>
					<attribute name="value" type="float" use="required"/>
				</complexType>
			</element>
		</sequence>
		<attribute name="stateValueId" type="fews:idStringType" use="required"/>
		<attribute name="stateDefnitionId" type="fews:idStringType" use="required"/>
	</complexType>
	<complexType name="BarrierStateTransitionComplexType">
		<sequence>
			<element name="startStateValueId" type="fews:idStringType">
				<annotation>
					<documentation>stateValueId before transition</documentation>
				</annotation>
			</element>
			<element name="endStateValueId" type="fews:idStringType">
				<annotation>
					<documentation>stateValueId after transition</documentation>
				</annotation>
			</element>
			<element name="transitionValue" maxOccurs="unbounded">
				<annotation>
					<documentation>definition of values associated with this stateTransition</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="stateVariableId" type="fews:idStringType">
							<annotation>
								<documentation>Identifier of stateVariable associated with these transitionValues</documentation>
							</annotation>
						</element>
						<element name="timeOffset" minOccurs="0">
							<complexType>
								<attribute name="unit" type="fews:timeUnitEnumStringType" use="required"/>
								<attribute name="value" type="int" use="required"/>
							</complexType>
						</element>
						<choice>
							<sequence>
								<element name="value" maxOccurs="unbounded">
									<annotation>
										<documentation>Definition of levels (m) with their associated transition speed (m/s). Must be in descending order.</documentation>
									</annotation>
									<complexType>
										<simpleContent>
											<extension base="string">
												<attribute name="level" type="float" use="required"/>
												<attribute name="speed" type="float" use="required"/>
											</extension>
										</simpleContent>
									</complexType>
								</element>
							</sequence>
							<element name="constantValue" type="float">
								<annotation>
									<documentation>Constant speed value for this stateVariable</documentation>
								</annotation>
							</element>
						</choice>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<complexType name="BarrierStateDefinitionComplexType">
		<sequence>
			<element name="variableId" type="fews:idStringType">
				<annotation>
					<documentation>Identifier of a variable to use.</documentation>
				</annotation>
			</element>
			<element name="stateVariables">
				<complexType>
					<sequence>
						<element name="stateVariable" maxOccurs="unbounded">
							<complexType>
								<sequence>
									<element name="variableId" type="fews:idStringType"/>
								</sequence>
								<attribute name="id" type="fews:idStringType" use="required"/>
							</complexType>
						</element>
					</sequence>
				</complexType>
			</element>
			<element name="stateValue" type="fews:BarrierStateValueComplexType" maxOccurs="unbounded"/>
			<element name="transitions">
				<complexType>
					<sequence>
						<element name="stateTransition" type="fews:BarrierStateTransitionComplexType" maxOccurs="unbounded">
							<annotation>
								<documentation>Definition of transitionValues associated with the transition of one stateValue to another stateValue</documentation>
							</annotation>
						</element>
					</sequence>
				</complexType>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
	</complexType>
	<complexType name="BarrierStateValueComplexType">
		<sequence>
			<element name="stateVariableValue" maxOccurs="unbounded">
				<annotation>
					<documentation>stateVariable values associated for this state</documentation>
				</annotation>
				<complexType>
					<attribute name="stateVariableId" type="fews:idStringType" use="required"/>
					<attribute name="value" type="float" use="required"/>
				</complexType>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="value" type="string" use="required"/>
	</complexType>
</schema>
