<?xml version="1.0"?>
<!--this schema is only used to feed the castor source generator-->
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="annotationDisplay.xsd"/>
	<include schemaLocation="annotationMetadataSchema.xsd"/>
	<include schemaLocation="archives.xsd"/>
	<include schemaLocation="archiveMetaData.xsd"/>
	<include schemaLocation="archiveModuleDisplay.xsd"/>
	<include schemaLocation="exportArchiveModule.xsd"/>
	<include schemaLocation="branches.xsd"/>
	<include schemaLocation="calibration.xsd"/> <!--	legacy-->
	<include schemaLocation="chartLayer.xsd"/>
	<include schemaLocation="clientConfig.xsd"/>
	<include schemaLocation="coldModuleInstanceStateGroups.xsd"/>
	<include schemaLocation="configUpdateModule.xsd"/>
	<include schemaLocation="configurationManagement.xsd"/>
	<include schemaLocation="configRevisionSets.xsd"/>
	<include schemaLocation="correlationDisplay.xsd"/>
	<include schemaLocation="correlationEventSets.xsd"/>
	<include schemaLocation="correlationSets.xsd"/>
	<include schemaLocation="customFlagSources.xsd"/>
	<include schemaLocation="dataAnalysisDisplays.xsd"/>
	<include schemaLocation="dataDownloadDisplay.xsd"/>
	<include schemaLocation="deprecatedThresholds.xsd"/>
	<include schemaLocation="displayGroups.xsd"/>
	<include schemaLocation="documents.xsd"/>
	<include schemaLocation="documentDisplays.xsd"/>
	<include schemaLocation="doubleMassDisplay.xsd"/>
	<include schemaLocation="environmentAgencyTimeUnits.xsd"/> <!--	part of region config-->
	<include schemaLocation="errorModelSets.xsd"/>
	<include schemaLocation="eventActions.xsd"/>
	<include schemaLocation="explorer.xsd"/>
	<include schemaLocation="filters.xsd"/>
	<include schemaLocation="flagConversions.xsd"/>
	<include schemaLocation="forecasterAidSelectionPanel.xsd"/>
	<include schemaLocation="forecastLengthEstimator.xsd"/>
	<include schemaLocation="forecastManagement.xsd"/>
	<include schemaLocation="forecastProductInfoDisplay.xsd"/>
	<include schemaLocation="generalAdapterRun.xsd"/>
	<include schemaLocation="gridDisplay.xsd"/>
	<include schemaLocation="gridPlotGroups.xsd"/>
	<include schemaLocation="grids.xsd"/>
	<include schemaLocation="contentUpdateChecker.xsd"/>
	<include schemaLocation="historicalEvents.xsd"/>
	<include schemaLocation="idMap.xsd"/>
	<include schemaLocation="importArchiveModule.xsd"/>
	<include schemaLocation="launcher.xsd"/> <!--	legacy-->
	<include schemaLocation="locationIcons.xsd"/>
	<include schemaLocation="locations.xsd"/>
	<include schemaLocation="locationSets.xsd"/>
	<include schemaLocation="logDisplays.xsd"/>
	<include schemaLocation="qualifiers.xsd"/>
	<include schemaLocation="timeSteps.xsd"/>
	<include schemaLocation="lookupDisplay.xsd"/>
	<include schemaLocation="lookupSets.xsd"/>
	<include schemaLocation="manualForecastDisplay.xsd"/>
	<include schemaLocation="massBalance.xsd"/>
	<include schemaLocation="modifierDisplay.xsd"/>
	<include schemaLocation="modifierTypes.xsd"/>
	<include schemaLocation="modifierMigrationTool.xsd"/>
	<include schemaLocation="moduleDescriptors.xsd"/> <!--	legacy, still supported by ModuleInstanceDescriptor-->
	<include schemaLocation="moduleInstanceDescriptors.xsd"/>
	<include schemaLocation="moduleInstanceSets.xsd"/>
	<include schemaLocation="moduleConfigProperties.xsd"/>
	<include schemaLocation="moduleRunTableDisplay.xsd"/>
	<include schemaLocation="objectiveAnalyzerDisplay.xsd"/>
	<include schemaLocation="onTheFlyExpressionTimeSeries.xsd"/>
	<include schemaLocation="parameters.xsd"/>
	<include schemaLocation="pcRaster.xsd"/>
	<include schemaLocation="pcrTransformationSets.xsd"/>
	<include schemaLocation="performanceIndicatorSets.xsd"/>
	<include schemaLocation="polygons.xsd"/>
	<include schemaLocation="productInfo.xsd"/>
	<include schemaLocation="products.xsd"/>
	<include schemaLocation="ratingCurves.xsd"/>
	<include schemaLocation="reportExport.xsd"/>
	<include schemaLocation="reports.xsd"/>
	<include schemaLocation="scadaDisplay.xsd"/>
	<include schemaLocation="scenarios.xsd"/> <!--	legacy-->
	<include schemaLocation="secondaryValidation.xsd"/>
	<include schemaLocation="security.xsd"/> <!--	legacy, launcher-->
	<include schemaLocation="mc.xsd"/>
	<include schemaLocation="mcInstall.xsd"/>
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="systemMetrics.xsd"/>
	<include schemaLocation="systemMonitorDisplay.xsd"/>
	<include schemaLocation="taskProperties.xsd"/>
	<include schemaLocation="sampleProperties.xsd"/>
	<include schemaLocation="taskPropertiesPredefined.xsd"/>
	<include schemaLocation="taskRunDialog.xsd"/>
	<include schemaLocation="taskRunProperties.xsd"/>
	<include schemaLocation="thresholdEventsDisplay.xsd"/>
	<include schemaLocation="thresholdExport.xsd"/>
	<include schemaLocation="thresholdOverviewDisplay.xsd"/>
	<include schemaLocation="thresholds.xsd"/>
	<include schemaLocation="thresholdSkillScoreDisplay.xsd"/>
	<include schemaLocation="thresholdValueSets.xsd"/>
	<include schemaLocation="thresholdWarningLevels.xsd"/>
	<include schemaLocation="timeSeriesDisplay.xsd"/>
	<include schemaLocation="timeSeriesExportRun.xsd"/>
	<include schemaLocation="timeSeriesImportRun.xsd"/>
	<include schemaLocation="timeSeriesTableDisplay.xsd"/>
	<include schemaLocation="topology.xsd"/>
	<include schemaLocation="topologyGroup.xsd"/>
	<include schemaLocation="transformationCoefficientSets.xsd"/>
	<include schemaLocation="transformationModule.xsd"/>
	<include schemaLocation="transformationSets.xsd"/>
	<include schemaLocation="transformations.xsd"/>
	<include schemaLocation="transformationTypes.xsd"/>
	<include schemaLocation="travelTimes.xsd"/>
	<include schemaLocation="unitConversions.xsd"/>
	<include schemaLocation="validationRuleSets.xsd"/>
	<include schemaLocation="valueAttributeMaps.xsd"/>
	<include schemaLocation="valuePropertiesEntryDisplay.xsd"/>
	<include schemaLocation="webBrowserDisplay.xsd"/>
	<include schemaLocation="whatIf.xsd"/>
	<include schemaLocation="whatIfTemplates.xsd"/>
	<include schemaLocation="whatIfScenario.xsd"/> <!--	legacy-->
	<include schemaLocation="whatIfScenarioEditor.xsd"/> <!--	legacy-->
	<include schemaLocation="whatIfScenarioFilters.xsd"/> <!--	legacy-->
	<include schemaLocation="whatIfScenarios.xsd"/> <!--	legacy-->
	<include schemaLocation="workflow.xsd"/>
	<include schemaLocation="workflowDescriptors.xsd"/>
	<include schemaLocation="workflowLoopRunner.xsd"/>
	<include schemaLocation="workflowTestRun.xsd"/>
	<include schemaLocation="webOCDashboards.xsd"/>
	<include schemaLocation="webOCMicroFrontEnds.xsd"/>
	<include schemaLocation="webOCComponentSettings.xsd"/>
	<include schemaLocation="webOperatorClient.xsd"/>
	<include schemaLocation="webServices.xsd"/>
	<include schemaLocation="workflowTestRun.xsd"/>
	<include schemaLocation="permissions.xsd"/>
	<include schemaLocation="userGroups.xsd"/>
	<include schemaLocation="importAmalgamate.xsd"/>
	<include schemaLocation="taskList.xsd"/>
	<include schemaLocation="barriers.xsd"/> <!--decision module-->
	<include schemaLocation="decisionModule.xsd"/>
	<include schemaLocation="runInfoPanel.xsd"/>
	<include schemaLocation="clobHistoricalEvent.xsd"/>
	<include schemaLocation="colorSchemes.xsd"/>
	<include schemaLocation="customColors.xsd"/>
	<include schemaLocation="timeSeriesButtonsPanels.xsd"/>
	<include schemaLocation="sampleMetadataSchema.xsd"/>
	<include schemaLocation="externalTablesMirrorUpdate.xsd"/>
	<include schemaLocation="waterCoachDisplay.xsd"/>
	<include schemaLocation="waterCoachScript.xsd"/>
	<include schemaLocation="waterCoachDictionary.xsd"/>
	<include schemaLocation="flagSourceColumns.xsd"/>
	<include schemaLocation="forecastMixer.xsd"/>
	<include schemaLocation="floodPeriodsModule.xsd"/>
	<include schemaLocation="verificationAnalysisDisplay.xsd"/>
	<include schemaLocation="sampleDisplay.xsd"/>
	<include schemaLocation="baseBuildFileSet.xsd"/>
	<include schemaLocation="encodedPartitionSequences.xsd"/>
	<include schemaLocation="unreferencedNcFilesCleaner.xsd"/>
	<include schemaLocation="tabularConfigFilesDisplay.xsd"/>
	<include schemaLocation="dynamicReportDisplays.xsd"/>
</schema>
