<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- -->
	<element name="delft3dModel" type="fews:Delft3DModelComplexType"/>
	<!-- -->
	<complexType name="Delft3DModelComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="general" type="fews:Delft3DGeneralComplexType">
				<annotation>
					<documentation>General files and settings used by at least two parts of the adapter</documentation>
				</annotation>
			</element>
			<element name="preAdapter" type="fews:Delft3DPreAdapterComplexType" minOccurs="0">
				<annotation>
					<documentation>Files and settings used by the pre adapter (prepare the input)</documentation>
				</annotation>
			</element>
			<element name="postAdapter" type="fews:Delft3DPostAdapterComplexType" minOccurs="0">
				<annotation>
					<documentation>Information required to convert the results to PI files</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="Delft3DGeneralComplexType">
		<sequence>
			<element name="module">
				<annotation>
					<documentation>String indicating the type of Delft3D module</documentation>
				</annotation>
				<simpleType>
					<restriction base="string">
						<enumeration value="FLOW"/>
						<enumeration value="FLOW_FM"/>
						<enumeration value="WAQ"/>
						<enumeration value="ECO"/>
						<enumeration value="WAVE"/>
						<enumeration value="PART"/>
					</restriction>
				</simpleType>
			</element>
			<element name="runId" type="string">
				<annotation>
					<documentation>String used to identify the input and the template files</documentation>
				</annotation>
			</element>
			<element name="stateFileId" type="string" minOccurs="0">
				<annotation>
					<documentation>String used to identify the state files</documentation>
				</annotation>
			</element>
			<element name="workDir" type="fews:directoryStringType">
				<annotation>
					<documentation>Directory where the computational models will run</documentation>
				</annotation>
			</element>
			<element name="modelDir" type="fews:directoryStringType">
				<annotation>
					<documentation>Directory containing the template files</documentation>
				</annotation>
			</element>
			<element name="auxiliaryGridFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Name of the file with the auxiliary grid (see adapter documentation)</documentation>
				</annotation>
			</element>
			<element name="fieldFileFormat" type="string" minOccurs="0">
				<annotation>
					<documentation>Control the format of the meteo and other field files</documentation>
				</annotation>
			</element>
			<element name="outputTimeSeriesInOneFile" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Control the format of the meteo and other field files</documentation>
				</annotation>
			</element>
			<choice minOccurs="0">
				<element name="geoDatum" type="fews:geoDatumStringType">
					<annotation>
						<documentation>Indication of the coordinate system used - defaults to WGS-1984</documentation>
					</annotation>
				</element>
				<element name="gridDefinition" type="fews:GridDefinitionComplexType"/>
			</choice>
			<element name="timeZone" type="fews:TimeZoneComplexType" minOccurs="0">
				<annotation>
					<documentation>Time zone that the Delft3D modules use - defaults to GMT</documentation>
				</annotation>
			</element>
			<element name="online" minOccurs="0">
				<annotation>
					<documentation>Copies extra morphology files for the FLOW pre- and post-adapter</documentation>
				</annotation>
				<simpleType>
					<restriction base="string">
						<enumeration value="MORPHOLOGY"/>
					</restriction>
				</simpleType>
			</element>
			<element name="rstNcFileSubcript" type="string" minOccurs="0"/>
			<element name="warnAboutUnusedSeries" type="boolean" minOccurs="0" default="true"/>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="Delft3DPreAdapterComplexType">
		<sequence>
			<element name="steeringTimeSeriesName" type="string">
				<annotation>
					<documentation>Name of the time series that is used to determined the end time of the computation</documentation>
				</annotation>
			</element>
			<element name="initialConditionsId" type="string" minOccurs="0">
				<annotation>
					<documentation>Run-ID or other identifying part for the expected initial conditions file
						The actual name is constructed from this</documentation>
				</annotation>
			</element>
			<element name="useWaqMapFilesForInitialConditions" type="boolean" minOccurs="0" default="false">
				<annotation>
					<documentation>Determines whether to use the new style of initial conditions files (*_res.map) or
						the old style (*.ini/*.res). The value "true" is obligatory for all newer configurations.</documentation>
				</annotation>
			</element>
			<element name="runCommand" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Support for running several external commands to finish the preparation.
Main motivation: in this way we keep them close to the processing and make them part of the
run procedure. The commands will run after the actual pre adapter</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="Delft3DPostAdapterComplexType">
		<sequence>
			<element name="timeSeriesOutput" type="fews:Delft3DTimeSeriesOutputComplexType" minOccurs="0">
				<annotation>
					<documentation>List of time series to be exported to Delft-FEWS: combinations of parameter and location names
					(both external and internal names are to be given, as well as the layer)</documentation>
				</annotation>
			</element>
			<element name="mapOutput" type="fews:Delft3DMapStackOutputComplexType" minOccurs="0">
				<annotation>
					<documentation>List of map stacks to be exported to Delft-FEWS: combinations of parameter names and layers
					(as well as the internal FEWS names)</documentation>
				</annotation>
			</element>
			<element name="runCommand" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Support for running several external commands to finish the preparation.
Main motivation: in this way we keep them close to the processing and make them part of the
run procedure. The commands will run before the actual post adapter</documentation>
				</annotation>
			</element>
			<element name="invertTimeStamp" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Used to assign a inverted timestamp to the map data. This is used
to facilitate inverse modelling.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="Delft3DTimeSeriesOutputComplexType">
		<sequence>
			<element name="timeSeries" type="fews:Delft3DTimeSeriesComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Record for each combination of parameter and location that is to be exported to FEWS</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="Delft3DMapStackOutputComplexType">
		<sequence>
			<element name="formatForPart" type="fews:mapFileFormatEnumStringType" default="binary" minOccurs="0">
				<annotation>
					<documentation>The format of the map stack files to be used for PART</documentation>
				</annotation>
			</element>
			<element name="map" type="fews:Delft3DMapStackComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Record for each combination of parameter and layer that is to be exported to FEWS</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="Delft3DTimeSeriesComplexType">
		<annotation>
			<documentation>The parameter name is the name as returned by Delft3D-GPP, the location name is the location as returned by Delft3D-GPP.
				The layer is the layer number of interest. The fewsParameter and fewsLocation attributes are the internal
				names used in FEWS for the map stack</documentation>
		</annotation>
		<attribute name="parameter" type="string" use="required"/>
		<attribute name="location" type="string" use="required"/>
		<attribute name="layer" type="integer" use="required"/>
		<attribute name="fewsParameter" type="string" use="required"/>
		<attribute name="fewsLocation" type="string" use="required"/>
	</complexType>
	<!-- -->
	<complexType name="Delft3DMapStackComplexType">
		<annotation>
			<documentation>The parameter name is the name as returned by Delft3D-GPP, the layer is the layer number of interest.
				The fewsParameter and fewsLocation attributes are the internal names used in FEWS for the map stack</documentation>
		</annotation>
		<attribute name="parameter" type="string" use="required"/>
		<attribute name="layer" type="integer" use="required"/>
		<attribute name="fewsParameter" type="string" use="required"/>
		<attribute name="fewsLocation" type="string" use="required"/>
	</complexType>

	<simpleType name="mapFileFormatEnumStringType">
		<restriction base="string">
			<enumeration value="binary"/>
			<enumeration value="NEFIS"/>
		</restriction>
	</simpleType>
</schema>
