<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Dave Burrows (Environment Agency) -->
<xsd:schema targetNamespace="http://www.environment-agency.gov.uk/XMLSchemas/EAMetadataFormat" xmlns="http://www.environment-agency.gov.uk/XMLSchemas/EAMetadataFormat" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- 

	XML Architecture Schema for Environment Agency Metadata

	Purpose: 	To define the elements required for Environment Agency Metadata and to allow their inclusion/import into other EA Schema.

	Date: 2003-06-11

	Version: 1.0
	Author: Dave Burrows, Giles Colton, EA CIS Development Team

 	 -->
	<xsd:annotation>
		<xsd:appinfo xmlns:gms="http://www.govtalk.gov.uk/CM/gms" xmlns:dc="http://purl.org/dc/elements/1.1/">
			<dc:Contributor/>
			<dc:Coverage/>
			<dc:Creator> Environment Agency CIS Development Team </dc:Creator>
			<dc:Date>2003-06-11</dc:Date>
			<dc:Description>This schema defines the elements required for Environment Agency Metadata, allowing their inclusion/import into other EA Schema</dc:Description>
			<dc:Format/>
			<dc:Identifier>{http://www.environment-agency.gov.uk/XMLSchemas/EAMetadataFormat}v1.0</dc:Identifier>
			<dc:Language/>
			<dc:Publisher>Environment Agency</dc:Publisher>
			<dc:Relation/>
			<dc:Rights/>
			<dc:Source/>
			<dc:Subject/>>
			<dc:Title>Environment Agency Metadata Schema</dc:Title>
			<dc:Type/>
		</xsd:appinfo>
	</xsd:annotation>
	<!--
		               The following comply with Dublin Core Metadata Standards
	-->
	<xsd:element name="Contributor" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>An entity responsible for making contributions to the content of the resource (eg. a person, an organisation or a service). </xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Coverage" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>The extent or scope of the content of the resource (eg. time period, spatial location or jurisdiction).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Creator" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>An entity primarily responsible for making the content of the resource (eg. a person, an organisation or a service).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Date" type="xsd:date">
		<xsd:annotation>
			<xsd:documentation>A date of an event in the life cycle of the resource (eg. creation or availability date).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Description" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>An account of the content of the resource, which may include an abstract, a table of contents, reference to a graphical representation of content or a free text account of the content.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Format" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>The physical or digital manifestation of the resource, which may include the media-type or dimensions of the resource.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Identifier" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>An unambiguous reference to the resource within a given context (eg. a string or number conforming to a formal identification system).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Language" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>The language of the intellectual content of the resource.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Publisher" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>An entity responsible for making the resource available (eg. a person, an organisation or a service).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Relation" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>A reference to a related resource (eg. a string or number conforming to a formal identification system).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Rights" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>Information about rights held in and over the resource (eg. a rights management statement for the resource or reference to a service providing such information).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Source" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>A reference to a resource from which the present resource is derived (eg. the system supplying file).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Subject" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>A topic of the content of the resource expressed, typically, in keywords, key phrases or classification codes.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Title" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>A name given to a resource. Typically the name by which the resource is formally known.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Type" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>The nature or genre of the content of the resource (eg. terms describing general categories, functions, genres or aggregation levels).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<!--
		               The following comply with EA Specific Metadata Standards
	-->
	<xsd:element name="Keywords" type="String_255Type">
		<xsd:annotation>
			<xsd:documentation>Keywords associated with the subject of the resource.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="Time" type="xsd:time">
		<xsd:annotation>
			<xsd:documentation>A time of an event in the life cycle of the resource (eg. creation or availability time).</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	
	
	<xsd:simpleType name="String_255Type">
		<xsd:annotation>
			<xsd:documentation>String with a maximum length of 255 characters</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="255"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>
