<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.environment-agency.gov.uk/XMLSchemas/EATimeSeriesDataExchangeFormat" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:md="http://www.environment-agency.gov.uk/XMLSchemas/EAMetadataFormat" xmlns="http://www.environment-agency.gov.uk/XMLSchemas/EATimeSeriesDataExchangeFormat" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- 

	XML Architecture Schema for time-series data exchange

	Purpose: This schema is used to supply the base building data structures for time-series data exchange
		within, to and from the Environment Agency.

	Author:	Chris Beales, EA Data, Information and Environmental Assessment, and
		Simon Wood, HARP Build Stage Manager 
		based on an original design by Dave Burrows, and Giles Colton, EA CIS Development Team.

	For further information please refer to the document EATimeSeriesSchemaDescription.doc
		which is located at http://www.environment-agency.gov.uk/XMLSchemas/EATimeSeriesDataExchangeFormat/PlainEnglish/EATimeSeriesSchemaDescription.doc

	Version 1.3.2 created to correct a typo from 1.3, Modified 2011-03-28
	=====================================================================
	Edit: James Procter (james.procter@environment-agency.gov.uk)	
	Added unit "l/s/m" (Litres per second per metre) to replace the incorrectly specified "l/m/s"


	New requests during change process to 1.3.1, Modified 2010-11-19
	================================================================
	Edit: James Procter (james.procter@environment-agency.gov.uk)	
	Minor updates for major organisational change affecting telemetry & Met Office change
	- Added RegionType of "EA South East"
	- Added DataPeriodIntervalType of "5 Day"

	New requests during change process to 1.3, Modified 2010-02-15
	==============================================================
	Edit: James Procter (james.procter@environment-agency.gov.uk)
	Multiple changes for NFFS and Wave Height
	- New unit for NFFS (litres per metre per second "l/m/s")
	- Added Wave measurement parameters of "Water depth", "Significant wave height (Hm0)", "Average (zero crossing) wave period","Dominant (peak) wave period",
	"Dominant (peak) wave direction", "Wave spread", "Maximum wave height", "Wave spectra freq min", "Wave spectra freq max",
	"Wave spectra power", "Wave spectra direction", "Wave spectra spread"
	- Added Wave related units of "Hz", "m2/Hz"
	- Added additional ParametertypeQualifiers for spectral bands "Wave spectra freq band 1" to "Wave spectra freq band 16"
	- Added new optional fields to the station element for the location of external sites - "Latitude" (double-precision floating-point),
	 "Longitude" (double-precision floating-point), "ExternalIdentifier" (text)
	- Added parameter type "Diagnostic"
	- Added units of "Count" and "Decibels"	


	Current Version 1.3, Modified: 2009-10-22
	=========================================
	Edit: James Procter (james.procter@environment-agency.gov.uk)
	Multiple changes primarily for Water Quality, Air Quality, and Visitor Numbers - the majority for current and future needs of the EA WISKI system.

	- added units of "ppm", "ug/m3", "mg/m3", "cm/s"
	- added parameters of "Nitrate", "Chlorophyll", "Ammonium", "People Count", "Antecendant Precipitation Index (AP15)",
	"Catchment Wetness Index", "Interception Loss", "Area",  "Reservoir Capacity"
	- added specific parameters for WISKI - "Derived Conductivity - for WISKI", "Derived Dissolved Oxygen - for WISKI", "Derived Chloride - for WISKI".
	This is to overcome import limitations of the EA WISKI system which cannot manage the preferred method - use of the "Derived" Characteristic.
	- added qualifier types of "Concentration", "Saturation" and "Optical Saturation", "Optical Concentration", "Catchment", "Index", "Storage - Met Office", "Event - Met Office",
	"Gross", "Deployable"	
	- added quality flags of "Part Missing", "Infilled"
	- as part of above, increased max value of quality flag enumerated list to 69 from 67


	Current Version 1.2, Modified: 2006-05-30
	=========================================

	Edit: James Procter (james.procter@environment-agency.gov.uk)

	- added parameter of "Overtopping" for NFFS
	- added unit of "m2/s" (Metres Squared per Second) for overtopping
	- added qualifier "Naturalised" for hydrological datasets


	Current Version 1.1, Modified: 2004-06-29
	=========================================

	Edit: James Procter

	- modified Dublin Core date to current release - (dc:Date 2004-06-29 dc:Date)


	Current Version 1.1, Modified: 2004-05-05
	=========================================

	Edits & testing: Ian Dawes and Chris Beales

	- additional optional attribute field named productRef introduced to the SetOfValues element between 
		the qualifier and dataType fields to permit unique identification of Met Office gridded products. 
		This field can then be populated with the Agency's unique product references that are assigned to 
		every Met Office radar/gridded data stream.

	- new SimpleType called String_10Type added

	- Removal of the trailing space on the end of "deg " in UnitsType. 

	- Addition to ParameterType of
		- "Residual", "Total Wave", "Wind Wave", "Swell Wave" and "Freeze Level"

	- Addition to ParameterQualifierType of
		- "Height", "Period", "MOSES", "NWP"

	- Flag description changed from textual description to individually defined elements with attributes


	History
	=======

	Version: 1.0, Date: 2003-06-27

	- Original Release

	-->

	<xsd:annotation>
		<xsd:appinfo xmlns:gms="http://www.govtalk.gov.uk/CM/gms" xmlns:dc="http://purl.org/dc/elements/1.1/">
			<dc:Contributor/>
			<dc:Coverage/>
			<dc:Creator>EA Data, Information and Environmental Assessment; HARP and CIS Development</dc:Creator>
			<dc:Date>2011-03-28</dc:Date>
			<dc:Description>This schema is used to supply the base building data structures for time series data exchange within, to and from the Environment Agency</dc:Description>
			<dc:Format/>
			<dc:Identifier>{http://www.environment-agency.gov.uk/XMLSchemas/EATimeSeriesDataExchangeFormat}v1.3.2</dc:Identifier>
			<dc:Language/>
			<dc:Publisher>Environment Agency</dc:Publisher>
			<dc:Relation/>
			<dc:Rights/>
			<dc:Source/>
			<dc:Subject/>
			<dc:Title>Environment Agency Time Series Data Exchange Format Schema</dc:Title>
			<dc:Type/>
		</xsd:appinfo>
	</xsd:annotation>
	<xsd:import namespace="http://www.environment-agency.gov.uk/XMLSchemas/EAMetadataFormat" schemaLocation="EAMetadata.xsd"/>
	<xsd:element name="EATimeSeriesDataExchangeFormat">
		<xsd:annotation>
			<xsd:documentation>Hydrometric, Catchment Average Accumulations, National Tide Gauge Network, Tide Predictions, Surge and Wave forecasts.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="md:Publisher" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>The entity responsible for making the resource available (e.g. "Environment Agency")</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element ref="md:Source" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>The reference to the source (system) from which the data is derived (e.g. "Hydrometric Archive")</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element ref="md:Description" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>An account of the content of the data file (e.g. "Data request for Joe Bloggs")</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element ref="md:Creator" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>The entity primarily responsible for producing the content of the resource. This is preferably not a named person but a post or a department.</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element ref="md:Date" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>The date that the file was created in XML format (ccyy-mm-dd)</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element ref="md:Time" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>The time that the file was created in XML format (hh:mm:ss)</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element ref="md:Identifier" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>The hardware device (e.g. server identifier) from which the data file was created</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="Station" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>site, station, gauge, point or areal location identification details</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="SetofValues" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>set of values for a site, station, gauge, point or areal location</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Value" minOccurs="0" maxOccurs="unbounded">
											<xsd:annotation>
												<xsd:documentation>floating point, single precision value</xsd:documentation>
											</xsd:annotation>
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="xsd:float">
														<xsd:attribute name="date" type="xsd:date" use="required">
															<xsd:annotation>
																<xsd:documentation>value date (ccyy-mm-dd)</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="time" type="xsd:time" use="optional">
															<xsd:annotation>
																<xsd:documentation>value time (hh:mm:ss)</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag1" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>First data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag2" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Second data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag3" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Third data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag4" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Forth data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag5" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Fifth data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag6" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Sixth data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag7" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Seventh data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag8" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Eighth data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag9" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Ninth data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="flag10" type="DataQualityFlagType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Tenth data quality flag</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag1" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag1</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag2" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag2</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag3" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag3</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag4" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag4</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag5" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag5</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag6" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag6</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag7" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag7</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag8" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag8</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag9" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag9</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="percentFlag10" type="PercentageType" use="optional">
															<xsd:annotation>
																<xsd:documentation>Percentage relating to a derived value - indicates how much of the source data was considered to match flag10</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="Comment" minOccurs="0" maxOccurs="unbounded">
											<xsd:annotation>
												<xsd:documentation>comment relating to a set of values</xsd:documentation>
											</xsd:annotation>
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="xsd:string">
														<xsd:attribute name="startDate" type="xsd:date" use="optional">
															<xsd:annotation>
																<xsd:documentation>The start date of the period to which comment applies (ccyy-mm-dd)</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="startTime" type="xsd:time" use="optional">
															<xsd:annotation>
																<xsd:documentation>The start time of the period to which comment applies (hh:mm:ss)</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="endDate" type="xsd:date" use="optional">
															<xsd:annotation>
																<xsd:documentation>The end date of the period to which comment applies (ccyy-mm-dd)</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
														<xsd:attribute name="endTime" type="xsd:time" use="optional">
															<xsd:annotation>
																<xsd:documentation>The end time of the period to which comment applies (hh:mm:ss)</xsd:documentation>
															</xsd:annotation>
														</xsd:attribute>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="parameter" type="ParameterType" use="required">
										<xsd:annotation>
											<xsd:documentation>The parameter that is being measured (eg. Flow, Rainfall or Water Level).</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="qualifier" type="ParameterQualifierType" use="optional">
										<xsd:annotation>
											<xsd:documentation>Further clarification relating to the parameter, especially if there is more than one of the same parameter type (e.g. "Water level - Upstream Head" and "Water Level - Downstream Head")</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="productRef" type="String_10Type" use="optional">
										<xsd:annotation>
											<xsd:documentation>Met Office radar/gridded data stream unique product reference.
												Examples include:
												"N1" for the NWP Mesoscale, Forecast Total Rainrate
												"N2" for the NWP Mesoscale, Forecast Total Rain Accumulations
												"N3" for the NWP Mesoscale, Forecast Surface Temperature
												"H7" for the Nimrod, rainfall actual
												"H11" for the Nimrod, forecast accumulations
												"H13" for the Gandolf, forecast accumulations
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="dataType" type="DataTypeType" use="required">
										<xsd:annotation>
											<xsd:documentation>The specific way in which the parameter was either measured or is being presented (eg. Instantaneous, Maximum, Mean or Minimum)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="period" type="DataPeriodIntervalType" use="required">
										<xsd:annotation>
											<xsd:documentation>Period associated with the datatype (eg. 15 min, Daily, Annual, etc.).  When combined with the Data Type attribute, this attribute identifies the dataset (eg. Monthly Mean)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="interval" type="DataPeriodIntervalType" use="optional">
										<xsd:annotation>
											<xsd:documentation>Expected interval of data particularly applying to rolling accumulations where it is not the same as the data period (eg. 15 min, 1 h, Daily, etc.) - ie. Daily Means may be recorded on an hourly basis.</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="characteristic" type="CharacteristicType" use="optional">
										<xsd:annotation>
											<xsd:documentation>Description of data source (eg. Derived, Forecast, Measured, etc.).  This can be very useful to distinguish between measured, forecast and modelled data, etc.</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="pointReference" type="String_120Type" use="optional">
										<xsd:annotation>
											<xsd:documentation>A unique reference associated with the analogue input or instrument used to meak the measurement (eg. E123)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="units" type="UnitsType" use="required">
										<xsd:annotation>
											<xsd:documentation>The units with which the set of values have been recorded (eg. Amps, km2, mAOD, mm, etc.)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="startDate" type="xsd:date" use="optional">
										<xsd:annotation>
											<xsd:documentation>The start date for the set of values (ccyy-mm-dd)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="startTime" type="xsd:time" use="optional">
										<xsd:annotation>
											<xsd:documentation>The start time for the set of values (hh:mm:ss)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="endDate" type="xsd:date" use="optional">
										<xsd:annotation>
											<xsd:documentation>The end date for the set of values (ccyy-mm-dd)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="endTime" type="xsd:time" use="optional">
										<xsd:annotation>
											<xsd:documentation>The end time for the set of values (hh:mm:ss)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="dayOrigin" type="xsd:time" use="optional">
										<xsd:annotation>
											<xsd:documentation>The time at which a day value begins (eg. 09:00:00 for a water day or a rain day)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="valuesPerDay" type="xsd:unsignedInt" use="optional">
										<xsd:annotation>
											<xsd:documentation>The number of values expected for a 'normal' day (eg. 96 where 15 minute values are collected over a 24 hour period)</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="stationReference" type="String_60Type" use="required">
							<xsd:annotation>
								<xsd:documentation>Identifier associated with the station (eg. site/station/gauge/point/areal location identifier)</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="region" type="RegionType" use="optional">
							<xsd:annotation>
								<xsd:documentation>Environment Agency Region name</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="stationName" type="String_180Type" use="optional">
							<xsd:annotation>
								<xsd:documentation>Name of the station (eg. site/station/gauge/point/areal location name)</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="ngr" type="NgrType" use="optional">
							<xsd:annotation>
								<xsd:documentation>The Ordnance Survey grid reference of the station - in the format: XX (the sheet reference) followed by an even number of digits (minimum of 2, maximum of 12)</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="latitude" type="xsd:double" use="optional">
							<xsd:annotation>
								<xsd:documentation>The latitude of the station as double precision floating point.</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="longitude" type="xsd:double" use="optional">
							<xsd:annotation>
								<xsd:documentation>The longitude of the station as double precision floating point.</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="ExternalIdentifier" type="String_60Type" use="optional">
							<xsd:annotation>
								<xsd:documentation>An external identifier, such as The World Meteorological Organisation Identifier, for a monitoring site.</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="CharacteristicType">
		<xsd:annotation>
			<xsd:documentation>Description of data source (eg. Derived, Forecast, Measured, etc.)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Derived"/>
			<xsd:enumeration value="Forecast"/>
			<xsd:enumeration value="Interpolated"/>
			<xsd:enumeration value="Measured"/>
			<xsd:enumeration value="Modelled"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DataQualityFlagType">
		<xsd:annotation>
			<xsd:documentation>
				<flagDescriptions>
					<flagDefinition flagNumber="1" flagName="Good">Best data quality.</flagDefinition>
					<flagDefinition flagNumber="2" flagName="Suspect">Failed the latest quality control or there are strong grounds for suspecting the accuracy of the observation. This is better than missing.</flagDefinition>
					<flagDefinition flagNumber="3" flagName="Estimated">Estimated value (e.g. modelled value).</flagDefinition>
					<flagDefinition flagNumber="4" flagName="Unchecked">This value has not undergone sufficient quality control.</flagDefinition>
					<flagDefinition flagNumber="5" flagName="Missing">Gaps / missing data.</flagDefinition>
					<flagDefinition flagNumber="6" flagName="Complete">The source data set is complete (e.g. daily summary derived from all 96 values from a 15-min measured series).</flagDefinition>
					<flagDefinition flagNumber="7" flagName="Incomplete">The source data set is not complete, but enough data is provided to calculate the summary data.</flagDefinition>
					<flagDefinition flagNumber="8" flagName="Auto validated">The data has been subject to automatic validation routines.</flagDefinition>
					<flagDefinition flagNumber="9" flagName="Edited">The data value has been edited; this may be a manual or automatic process. This may be associated with a reason for edit and or comment.</flagDefinition>
					<flagDefinition flagNumber="10" flagName="Extrapolated">Flows are above or below the limit of a stage-discharge relationship and have been extrapolated. These flows will occur between Within Rating and Beyond Limit of Rating flags.</flagDefinition>
					<flagDefinition flagNumber="11" flagName="Within rating">The flows are within the upper and lower limits of the stage-discharge rating.</flagDefinition>
					<flagDefinition flagNumber="12" flagName="No rating">There is no rating present for this data.</flagDefinition>
					<flagDefinition flagNumber="13" flagName="Beyond upper limit">Beyond upper limit of rating when flows calculated using a stage-discharge equation.</flagDefinition>
					<flagDefinition flagNumber="14" flagName="Beyond lower limit">Beyond lower limit of rating when flows calculated using a stage-discharge equation.</flagDefinition>
					<flagDefinition flagNumber="15" flagName="Head only">Indicates the Upstream Head only has been used in the flow calculation.</flagDefinition>
					<flagDefinition flagNumber="16" flagName="Tail - modular">Indicates tail water level used in the flow calculation and the weir was found to be modular.</flagDefinition>
					<flagDefinition flagNumber="17" flagName="Tail - non-modular">Indicates tail water level used in the flow calculation. The weir was found to be non-modular so a reduction factor has been applied to the data.</flagDefinition>
					<flagDefinition flagNumber="18" flagName="Tail - extremely non-modular">Indicates tail water level used in the flow calculation. The weir was found to be extremely non-modular so a drowned flow reduction factor has been applied to the data.</flagDefinition>
					<flagDefinition flagNumber="19" flagName="Crest - modular">Indicates pressure-tapping level used in the flow calculation and the weir was found to be modular.</flagDefinition>
					<flagDefinition flagNumber="20" flagName="Crest - non-modular">Indicates pressure-tapping level used in the flow calculation. The weir was found to be non-modular so a reduction factor has been applied to the data.</flagDefinition>
					<flagDefinition flagNumber="21" flagName="Crest - extremely non-modular">Indicates pressure-tapping level used in the flow calculation. The weir was found to be extremely non-modular so a drowned flow reduction factor has been applied to the data.</flagDefinition>
					<flagDefinition flagNumber="22" flagName="Engineer on Site">Indicates an engineer is on site, some data values may be affected by their work.</flagDefinition>
					<flagDefinition flagNumber="23" flagName="Normal QC complete">The Quality Control procedures have been completed.</flagDefinition>
					<flagDefinition flagNumber="24" flagName="Test Calibration Data">The data has been generated during the process of testing and calibrating the sensor.</flagDefinition>
					<flagDefinition flagNumber="25" flagName="Item in Alarm">The item that is being recorded by the Telemetry system is in a state of alarm.</flagDefinition>
					<flagDefinition flagNumber="26" flagName="Off Scan/Disable">The telemetry outstation is set to Off Scan or has been disabled.</flagDefinition>
					<flagDefinition flagNumber="27" flagName="Out of Range">The data recorded is out of the minimum or maximum calibrated range of the measuring sensor.</flagDefinition>
					<flagDefinition flagNumber="28" flagName="Manually Entered Data">A user has manually updated the source system.</flagDefinition>
					<flagDefinition flagNumber="29" flagName="Master Station Override">The telemetry master station override is active. This may have affected the data.</flagDefinition>
					<flagDefinition flagNumber="30" flagName="Invalid State">This indicates the Digital Status is invalid from the source system.</flagDefinition>
					<flagDefinition flagNumber="31" flagName="Invalid Time">This indicates the time is invalid from the source system.</flagDefinition>
					<flagDefinition flagNumber="32" flagName="Trace">Some rain has fallen but it is too little to measure.</flagDefinition>
					<flagDefinition flagNumber="33" flagName="Accumulation (Start)">First value for an accumulated data block.</flagDefinition>
					<flagDefinition flagNumber="34" flagName="Accumulation">Rainfall that has accumulated over more than one day between readings for a storage type gauge. Note that there must be Start and End of accumulation flags.</flagDefinition>
					<flagDefinition flagNumber="35" flagName="Accumulation (End)">Last value for an accumulated data block.</flagDefinition>
					<flagDefinition flagNumber="36" flagName="Snow">Precipitation that has fallen as snow but has not been converted to rainfall equivalent.</flagDefinition>
					<flagDefinition flagNumber="37" flagName="Snow converted to rain">Precipitation that has fallen as snow that has been converted to rainfall equivalent.</flagDefinition>
					<flagDefinition flagNumber="38" flagName="Well Dry">Maximum depth of well reached (i.e. the bottom): there could be water at greater depth in the aquifer.</flagDefinition>
					<flagDefinition flagNumber="39" flagName="Automatic Estimate">Estimate/correction derived automatically from a program with no manual intervention.</flagDefinition>
					<flagDefinition flagNumber="40" flagName="Manual Estimate">Estimate/corrected value has been set manually (with or without assistance from a program).</flagDefinition>
					<flagDefinition flagNumber="41" flagName="Observer Estimate">Estimate/correction has been obtained retrospectively from the observer/station.</flagDefinition>
					<flagDefinition flagNumber="42" flagName="Derived Estimate"> Precipitation estimate/correction has bee derived from snow/rainfall equivalence, or trace estimate/correction has been set for consistency with present weather.                                                     </flagDefinition>
					<flagDefinition flagNumber="43" flagName="Units Correction">Correction has been obtained by changing units of measurement.</flagDefinition>
					<flagDefinition flagNumber="44" flagName="Systematic Correction">Correction has been obtained by applying a systematic adjustment.</flagDefinition>
					<flagDefinition flagNumber="45" flagName="Inaccessible">Measurement impossible, because of snow, etc.</flagDefinition>
					<flagDefinition flagNumber="46" flagName="Unavailable">An estimate where the original value is not available.</flagDefinition>
					<flagDefinition flagNumber="47" flagName="Unreliable Estimate">An unreliable estimate (used in radiation QC).</flagDefinition>
					<flagDefinition flagNumber="48" flagName="Correction">A correction (a reported value is assumed to be in error).</flagDefinition>
					<flagDefinition flagNumber="49" flagName="Reverted to Original">Value reverted to original.</flagDefinition>
					<flagDefinition flagNumber="50" flagName="Raw">Original value verified by observer.</flagDefinition>
					<flagDefinition flagNumber="51" flagName="Original">The data value is the original or raw value retrieved from an external source without any verification.</flagDefinition>
					<flagDefinition flagNumber="52" flagName="Completed">The original data value was missing and was replaced by a value that was derived by a model.</flagDefinition>
					<flagDefinition flagNumber="53" flagName="Failed SDB/MetDB">Failed Synoptic Database (SDB) or Met Office Database (MetDB) QC check.</flagDefinition>
					<flagDefinition flagNumber="54" flagName="Failed MIDAS">Failed MIDAS validation.</flagDefinition>
					<flagDefinition flagNumber="55" flagName="Position/Movement Failed">Failed climate QC marine position or movement check.</flagDefinition>
					<flagDefinition flagNumber="56" flagName="Range Failed">Failed climate QC range check.</flagDefinition>
					<flagDefinition flagNumber="57" flagName="Consistency Failed">Failed climate QC internal consistency check.</flagDefinition>
					<flagDefinition flagNumber="58" flagName="Sequence check Failed">Failed climate QC sequence check.</flagDefinition>
					<flagDefinition flagNumber="59" flagName="Areal check Failed">Failed climate QC areal check.</flagDefinition>
					<flagDefinition flagNumber="60" flagName="MO QC level 0">Initial climate QC program has not been run.</flagDefinition>
					<flagDefinition flagNumber="61" flagName="MO QC level 1">Initial climate QC program has been run.</flagDefinition>
					<flagDefinition flagNumber="62" flagName="MO QC level 2">Initial QC queries processed.</flagDefinition>
					<flagDefinition flagNumber="63" flagName="MO QC level 4">Further range or internal consistency or sequence checks job(s) run and queries processed.</flagDefinition>
					<flagDefinition flagNumber="64" flagName="MO QC level 6">Final (or only) areal or buddy job run and queries cessed.</flagDefinition>
					<flagDefinition flagNumber="65" flagName="MO QC level 8">Final (or only) monthly job(s) run and queries processed.</flagDefinition>
					<flagDefinition flagNumber="66" flagName="High Tide">Water level at High tide: note that this is usually a forecast.</flagDefinition>
					<flagDefinition flagNumber="67" flagName="Low Tide">Water level at Low tide: note that this is usually forecast.</flagDefinition>
					<flagDefinition flagNumber="68" flagName="Part Missing">Part of summary data is missing when values are infilled.</flagDefinition>
					<flagDefinition flagNumber="69" flagName="Infilled">Summary data infilled</flagDefinition>
				</flagDescriptions>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:unsignedByte">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="69"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DataPeriodIntervalType">
		<xsd:annotation>
			<xsd:documentation>Period associated with the datatype (eg. 15 min, Day, Year, etc.) and/or the expected interval that data is collected and stored (eg. "1 h") - applying particularly to rolling accumulations where it is not the same as the data period</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Unspecified"/>
			<xsd:enumeration value="1 s"/>
			<xsd:enumeration value="2 s"/>
			<xsd:enumeration value="3 s"/>
			<xsd:enumeration value="4 s"/>
			<xsd:enumeration value="5 s"/>
			<xsd:enumeration value="6 s"/>
			<xsd:enumeration value="10 s"/>
			<xsd:enumeration value="12 s"/>
			<xsd:enumeration value="15 s"/>
			<xsd:enumeration value="20 s"/>
			<xsd:enumeration value="30 s"/>
			<xsd:enumeration value="1 min"/>
			<xsd:enumeration value="2 min"/>
			<xsd:enumeration value="3 min"/>
			<xsd:enumeration value="4 min"/>
			<xsd:enumeration value="5 min"/>
			<xsd:enumeration value="6 min"/>
			<xsd:enumeration value="10 min"/>
			<xsd:enumeration value="12 min"/>
			<xsd:enumeration value="15 min"/>
			<xsd:enumeration value="20 min"/>
			<xsd:enumeration value="30 min"/>
			<xsd:enumeration value="1 h"/>
			<xsd:enumeration value="2 h"/>
			<xsd:enumeration value="3 h"/>
			<xsd:enumeration value="4 h"/>
			<xsd:enumeration value="6 h"/>
			<xsd:enumeration value="8 h"/>
			<xsd:enumeration value="12 h"/>
			<xsd:enumeration value="24 h"/>
			<xsd:enumeration value="48 h"/>
			<xsd:enumeration value="72 h"/>
			<xsd:enumeration value="Day"/>
			<xsd:enumeration value="5 Day"/>
			<xsd:enumeration value="Week"/>
			<xsd:enumeration value="Bi-weekly"/>
			<xsd:enumeration value="Month"/>
			<xsd:enumeration value="Quarterly"/>
			<xsd:enumeration value="Year"/>
			<xsd:enumeration value="Water Year"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DataTypeType">
		<xsd:annotation>
			<xsd:documentation>Specific type of data (eg. Instantaneous, Mean, Minimum, etc.)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Instantaneous"/>
			<xsd:enumeration value="Event"/>
			<xsd:enumeration value="Maximum"/>
			<xsd:enumeration value="Mean"/>
			<xsd:enumeration value="Minimum"/>
			<xsd:enumeration value="Cumulative Total"/>
			<xsd:enumeration value="Total"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="NgrType">
		<xsd:annotation>
			<xsd:documentation>NGR in the format: XX (the sheet reference) followed by an even number of digits (minimum of 2, maximum of 12)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Z]{2}\d{2}(\d{2})?(\d{2})?(\d{2})?(\d{2})?(\d{2})?"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ParameterType">
		<xsd:annotation>
			<xsd:documentation>The parameter that is being measured (eg. Flow, Rainfall or Water Level).</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Actual Evapotranspiration"/>
			<xsd:enumeration value="Ammonia"/>
			<xsd:enumeration value="Barometric Pressure"/>
			<xsd:enumeration value="Coil Current"/>
			<xsd:enumeration value="Conductivity (Field)"/>
			<xsd:enumeration value="Dissolved Oxygen"/>
			<xsd:enumeration value="Effective Rainfall"/>
			<xsd:enumeration value="Evaporation"/>
			<xsd:enumeration value="Flow"/>
			<xsd:enumeration value="Freeze Level"/>
			<xsd:enumeration value="Gate Position"/>
			<xsd:enumeration value="Gate Angle"/>
			<xsd:enumeration value="Overtopping"/>
			<xsd:enumeration value="pH"/>
			<xsd:enumeration value="Potential Evapotranspiration"/>
			<xsd:enumeration value="Probe Voltage"/>
			<xsd:enumeration value="Radiation"/>
			<xsd:enumeration value="Rainfall"/>
			<xsd:enumeration value="Relative Humidity"/>
			<xsd:enumeration value="Residual"/>
			<xsd:enumeration value="Salinity (In situ)"/>
			<xsd:enumeration value="Snow Level"/>
			<xsd:enumeration value="Soil Moisture Deficit"/>
			<xsd:enumeration value="State"/>
			<xsd:enumeration value="Sunshine Hours"/>
			<xsd:enumeration value="Swell Wave"/>
			<xsd:enumeration value="Temperature"/>
			<xsd:enumeration value="Total Wave"/>
			<xsd:enumeration value="Turbidity"/>
			<xsd:enumeration value="Vapour Pressure"/>
			<xsd:enumeration value="Velocity"/>
			<xsd:enumeration value="Voltage"/>
			<xsd:enumeration value="Water Level"/>
			<xsd:enumeration value="Wind"/>
			<xsd:enumeration value="Wind Wave"/>
			<xsd:enumeration value="Nitrate"/>
			<xsd:enumeration value="Derived Chloride - for WISKI"/>
			<xsd:enumeration value="Chlorophyll"/>
			<xsd:enumeration value="Ammonium"/>
			<xsd:enumeration value="Derived Conductivity - for WISKI"/>
			<xsd:enumeration value="Derived Dissolved Oxygen - for WISKI"/>
			<xsd:enumeration value="People Count"/>
			<xsd:enumeration value="Antecendant Precipitation Index (AP15)"/>
			<xsd:enumeration value="Catchment Wetness Index"/>
			<xsd:enumeration value="Interception Loss"/>
			<xsd:enumeration value="Area"/>
			<xsd:enumeration value="Carbon Monoxide"/>
			<xsd:enumeration value="Hydrogen Sulphide"/>
			<xsd:enumeration value="PM10 [TEOM]"/>
			<xsd:enumeration value="PM10 [TEOM FDMS]"/>
			<xsd:enumeration value="PM2.5 [TEOM]"/>
			<xsd:enumeration value="PM2.5 [TEOM FDMS]"/>
			<xsd:enumeration value="TSP [TEOM]"/>
			<xsd:enumeration value="Sulphur Dioxide"/>
			<xsd:enumeration value="Nitrogen Oxides"/>
			<xsd:enumeration value="Nitrogen Dioxide"/>
			<xsd:enumeration value="Nitric Oxide"/>
			<xsd:enumeration value="Total Nitrogen Compounds"/>
			<xsd:enumeration value="Methane"/>
			<xsd:enumeration value="Benzene"/>
			<xsd:enumeration value="1,3-Butadiene"/>
			<xsd:enumeration value="Toluene"/>
			<xsd:enumeration value="Ethylbenzene"/>
			<xsd:enumeration value="m and p-Xylene"/>
			<xsd:enumeration value="1-Butene"/>
			<xsd:enumeration value="iso-Butene"/>
			<xsd:enumeration value="trans-2-Butene"/>
			<xsd:enumeration value="cis-2-Butene"/>
			<xsd:enumeration value="n-Pentane"/>
			<xsd:enumeration value="iso-Pentane"/>
			<xsd:enumeration value="cis-2-Pentene"/>
			<xsd:enumeration value="trans-2-Pentene"/>
			<xsd:enumeration value="Water depth"/>
			<xsd:enumeration value="Significant wave height (Hm0)"/>
			<xsd:enumeration value="Average (zero crossing) wave period"/>
			<xsd:enumeration value="Dominant (peak) wave period"/>
			<xsd:enumeration value="Dominant (peak) wave direction"/>
			<xsd:enumeration value="Wave spread"/>
			<xsd:enumeration value="Maximum wave height"/>
			<xsd:enumeration value="Wave spectra freq min"/>
			<xsd:enumeration value="Wave spectra freq max"/>
			<xsd:enumeration value="Wave spectra power"/>
			<xsd:enumeration value="Wave spectra direction"/>
			<xsd:enumeration value="Wave spectra spread"/>
			<xsd:enumeration value="Diagnostic"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ParameterQualifierType">
		<xsd:annotation>
			<xsd:documentation>Further clarification relating to the parameter, especially if there is more than one of the same parameter type (e.g. "Water level - Stage" and "Water Level - Downstream Stage")</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Abstraction"/>
			<xsd:enumeration value="Air"/>
			<xsd:enumeration value="Areal"/>
			<xsd:enumeration value="as N"/>
			<xsd:enumeration value="as O"/>
			<xsd:enumeration value="Crest Tapping"/>
			<xsd:enumeration value="Crest Tapping (2)"/>
			<xsd:enumeration value="Direction"/>
			<xsd:enumeration value="Downstream Stage"/>
			<xsd:enumeration value="Dry Bulb"/>
			<xsd:enumeration value="Effluent Discharge"/>
			<xsd:enumeration value="Groundwater"/>
			<xsd:enumeration value="Height"/>
			<xsd:enumeration value="Logged"/>
			<xsd:enumeration value="Maximum"/>
			<xsd:enumeration value="Minimum"/>
			<xsd:enumeration value="MOSES"/>
			<xsd:enumeration value="Naturalised"/>
			<xsd:enumeration value="Net"/>
			<xsd:enumeration value="NWP"/>
			<xsd:enumeration value="Penstock"/>
			<xsd:enumeration value="Percentage of Saturated"/>
			<xsd:enumeration value="Percolation Tank"/>
			<xsd:enumeration value="Period"/>
			<xsd:enumeration value="Radar"/>
			<xsd:enumeration value="Reservoir Level"/>
			<xsd:enumeration value="Run"/>
			<xsd:enumeration value="Sluice Gate"/>
			<xsd:enumeration value="Soil"/>
			<xsd:enumeration value="Solar"/>
			<xsd:enumeration value="Speed"/>
			<xsd:enumeration value="Stage"/>
			<xsd:enumeration value="Storage Raingauge"/>
			<xsd:enumeration value="Sump Level"/>
			<xsd:enumeration value="Tidal Level"/>
			<xsd:enumeration value="Tipping Bucket Raingauge"/>
			<xsd:enumeration value="Unionized"/>
			<xsd:enumeration value="Water"/>
			<xsd:enumeration value="Wet Bulb"/>
			<xsd:enumeration value="1"/>
			<xsd:enumeration value="2"/>
			<xsd:enumeration value="3"/>
			<xsd:enumeration value="4"/>
			<xsd:enumeration value="5"/>
			<xsd:enumeration value="6"/>
			<xsd:enumeration value="7"/>
			<xsd:enumeration value="8"/>
			<xsd:enumeration value="9"/>
			<xsd:enumeration value="10"/>
			<xsd:enumeration value="11"/>
			<xsd:enumeration value="12"/>
			<xsd:enumeration value="13"/>
			<xsd:enumeration value="14"/>
			<xsd:enumeration value="15"/>
			<xsd:enumeration value="16"/>
			<xsd:enumeration value="17"/>
			<xsd:enumeration value="18"/>
			<xsd:enumeration value="19"/>
			<xsd:enumeration value="20"/>
			<xsd:enumeration value="Concentration"/>
			<xsd:enumeration value="Optical Saturation"/>
			<xsd:enumeration value="Saturation"/>
			<xsd:enumeration value="Optical Concentration"/>
			<xsd:enumeration value="Catchment"/>
			<xsd:enumeration value="Index"/>
			<xsd:enumeration value="Storage - Met Office"/>
			<xsd:enumeration value="Event - Met Office"/>
			<xsd:enumeration value="Gross"/>
			<xsd:enumeration value="Deployable"/>
			<xsd:enumeration value="Wave spectra freq band 1"/>
			<xsd:enumeration value="Wave spectra freq band 2"/>
			<xsd:enumeration value="Wave spectra freq band 3"/>
			<xsd:enumeration value="Wave spectra freq band 4"/>
			<xsd:enumeration value="Wave spectra freq band 5"/>
			<xsd:enumeration value="Wave spectra freq band 6"/>
			<xsd:enumeration value="Wave spectra freq band 7"/>
			<xsd:enumeration value="Wave spectra freq band 8"/>
			<xsd:enumeration value="Wave spectra freq band 9"/>
			<xsd:enumeration value="Wave spectra freq band 10"/>
			<xsd:enumeration value="Wave spectra freq band 11"/>
			<xsd:enumeration value="Wave spectra freq band 12"/>
			<xsd:enumeration value="Wave spectra freq band 13"/>
			<xsd:enumeration value="Wave spectra freq band 14"/>
			<xsd:enumeration value="Wave spectra freq band 15"/>
			<xsd:enumeration value="Wave spectra freq band 16"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PercentageType">
		<xsd:annotation>
			<xsd:documentation>Percentage value</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:float">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RegionType">
		<xsd:annotation>
			<xsd:documentation>Environment Agency Region name</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Anglian"/>
			<xsd:enumeration value="Head Office"/>
			<xsd:enumeration value="Midland"/>
			<xsd:enumeration value="North East"/>
			<xsd:enumeration value="North West"/>
			<xsd:enumeration value="South West"/>
			<xsd:enumeration value="Southern"/>
			<xsd:enumeration value="Thames"/>
			<xsd:enumeration value="EA Wales"/>
			<xsd:enumeration value="EA South East"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="UnitsType">
		<xsd:annotation>
			<xsd:documentation>Units for the set of values (eg. amps, km2, mAOD, mm, etc.)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="---"/>
			<xsd:enumeration value="%"/>
			<xsd:enumeration value="% opening"/>
			<xsd:enumeration value="% Sat"/>
			<xsd:enumeration value="1000m3"/>
			<xsd:enumeration value="1000m3/d"/>
			<xsd:enumeration value="10m3"/>
			<xsd:enumeration value="Amps"/>
			<xsd:enumeration value="Bar"/>
			<xsd:enumeration value="cm"/>
			<xsd:enumeration value="cm2"/>
			<xsd:enumeration value="cm3"/>
			<xsd:enumeration value="cm3/s"/>
			<xsd:enumeration value="deg"/>
			<xsd:enumeration value="deg opening"/>
			<xsd:enumeration value="deg C"/>
			<xsd:enumeration value="deg d"/>
			<xsd:enumeration value="deg F"/>
			<xsd:enumeration value="ft"/>
			<xsd:enumeration value="ft/s"/>
			<xsd:enumeration value="ft2"/>
			<xsd:enumeration value="FTU"/>
			<xsd:enumeration value="g/l"/>
			<xsd:enumeration value="Hazen"/>
			<xsd:enumeration value="in"/>
			<xsd:enumeration value="in2"/>
			<xsd:enumeration value="J"/>
			<xsd:enumeration value="J/cm2"/>
			<xsd:enumeration value="J/m2"/>
			<xsd:enumeration value="K"/>
			<xsd:enumeration value="km"/>
			<xsd:enumeration value="km2"/>
			<xsd:enumeration value="Knots"/>
			<xsd:enumeration value="kW"/>
			<xsd:enumeration value="kWh"/>
			<xsd:enumeration value="l/h"/>
			<xsd:enumeration value="l/s"/>
			<xsd:enumeration value="m"/>
			<xsd:enumeration value="m/s"/>
			<xsd:enumeration value="m2"/>  	
			<xsd:enumeration value="m2/s"/>
			<xsd:enumeration value="m3"/>
			<xsd:enumeration value="m3/d"/>
			<xsd:enumeration value="m3/h"/>
			<xsd:enumeration value="m3/s"/>
			<xsd:enumeration value="m3/year"/>
			<xsd:enumeration value="mA"/>
			<xsd:enumeration value="mAOD"/>
			<xsd:enumeration value="mASD"/>
			<xsd:enumeration value="mbar"/>
			<xsd:enumeration value="mBDAT"/>
			<xsd:enumeration value="mg/l"/>
			<xsd:enumeration value="micro g/l"/>
			<xsd:enumeration value="micro m"/>
			<xsd:enumeration value="micro S/cm"/>
			<xsd:enumeration value="micro V"/>
			<xsd:enumeration value="Mile"/>
			<xsd:enumeration value="min"/>
			<xsd:enumeration value="Ml"/>
			<xsd:enumeration value="Ml/d"/>
			<xsd:enumeration value="mm"/>
			<xsd:enumeration value="mm/d"/>
			<xsd:enumeration value="mm/h"/>
			<xsd:enumeration value="mmol/l"/>
			<xsd:enumeration value="mol/m3"/>
			<xsd:enumeration value="mph"/>
			<xsd:enumeration value="mS/cm"/>
			<xsd:enumeration value="mS/m"/>
			<xsd:enumeration value="mV"/>
			<xsd:enumeration value="mW/m2"/>
			<xsd:enumeration value="ng/l"/>
			<xsd:enumeration value="NTU"/>
			<xsd:enumeration value="NTU %"/>
			<xsd:enumeration value="on/off"/>
			<xsd:enumeration value="pH"/>
			<xsd:enumeration value="ppm"/>
			<xsd:enumeration value="ppt"/>
			<xsd:enumeration value="revs"/>
			<xsd:enumeration value="s"/>
			<xsd:enumeration value="Sec opening"/>
			<xsd:enumeration value="V"/>
			<xsd:enumeration value="W/m2"/>
			<xsd:enumeration value="ug/m3"/>
			<xsd:enumeration value="mg/m3"/>
			<xsd:enumeration value="l/m/s"/>
			<xsd:enumeration value="Hz"/>
			<xsd:enumeration value="m2/Hz"/>
			<xsd:enumeration value="cm/s"/>
			<xsd:enumeration value="Count"/>
			<xsd:enumeration value="Decibels"/>
			<xsd:enumeration value="l/s/m"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="String_10Type">
		<xsd:annotation>
			<xsd:documentation>String with a maximum length of 10 characters</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="String_60Type">
		<xsd:annotation>
			<xsd:documentation>String with a maximum length of 60 characters</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="String_120Type">
		<xsd:annotation>
			<xsd:documentation>String with a maximum length of 120 characters</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="120"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="String_180Type">
		<xsd:annotation>
			<xsd:documentation>String with a maximum length of 180 characters</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="180"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>
