<?xml version="1.0" encoding="UTF-8"?>
<!-- -->
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- -->
	<element name="fewsInstallationConfigurator" type="fews:FewsInstallationConfiguratorComplexType"/>
	<complexType name="FewsInstallationConfiguratorComplexType">
		<sequence>
			<element name="systemConfiguration" type="fews:FewsInstallationComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>The top-level element describing the necessary configuration parameters for 1 FEWS client-server entity.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FewsInstallationComplexType">
		<sequence>
			<element name="jmsServer" type="fews:JMSServerInstallComplexType" minOccurs="0">
				<annotation>
					<documentation>Contains information on the server providing the the JMS queues for this client-server entity.</documentation>
				</annotation>
			</element>
			<element name="dbServer" type="fews:DatabaseServerInstallComplexType">
				<annotation>
					<documentation>Contains information on the central database for this client-server entity.</documentation>
				</annotation>
			</element>
			<element name="masterController" type="fews:MasterControllerInstallComplexType">
				<annotation>
					<documentation>Contains information on the master controller for this client-server entity.</documentation>
				</annotation>
			</element>
			<element name="remoteMasterController" type="fews:RemoteMasterControllerInstallComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Contains information on the optional remote master controller(s) for this client-server entity.</documentation>
				</annotation>
			</element>
			<element name="forecastingShells" type="fews:ForecastingShellInstallComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Contains information on the Forecasting Shell instances for this client-server entity.</documentation>
				</annotation>
			</element>
			<element name="operatorClients" type="fews:ClientInstallComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="archiveServer" type="fews:ArchiveServerInstallComplexType" minOccurs="0">
				<annotation>
					<documentation>Contains information on the deltares archive server.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="MasterControllerInstallComplexType">
		<annotation>
			<documentation>Contains information on the master controller for the system.</documentation>
		</annotation>
		<sequence>
			<element name="mcId" type="fews:idStringType" default="NLWLMC00">
				<annotation>
					<documentation>The ID for this master controller. Will be part of all TaskIDs, TaskRunIDs etc. Generally of the form XXYYMC00, with XX=Country/client identifier and YY=Region identifier, e.g. NLWLMC00</documentation>
				</annotation>
			</element>
			<element name="mcRegionName" type="string" default="SouthEast">
				<annotation>
					<documentation>A free format string providing a human-readable name of the region for the system, e.g. "SouthEast". Is displayed in the Admin Interface.</documentation>
				</annotation>
			</element>
			<element name="mcOS" default="linux">
				<annotation>
					<documentation>The Operating System of the Master Controller machine (linux, windows or hpux).</documentation>
				</annotation>
				<simpleType>
					<restriction base="string">
						<enumeration value="windows"/>
						<enumeration value="linux"/>
						<enumeration value="hpux"/>
					</restriction>
				</simpleType>
			</element>
			<element name="mcJavaHome" type="fews:fileStringType" default="/opt/fews/java/jre1.8/">
				<annotation>
					<documentation>Java home directory of JRE, directory is assumed to contain a bin/ sub-directory with the JRE executable.</documentation>
				</annotation>
			</element>
			<element name="fewsmcHome" type="fews:fileStringType" default="/opt/fews/mc/mcs/nlwlmc00">
				<annotation>
					<documentation>The FEWSMC_HOME directory for the master Controller (previously NFFS_HOME). Is also used by the Admin Interface to find the fews.master.mc.conf file. Should use forward slashes for windows paths, e.g. C:/opt/fews/mc/mcs/nlwlmc00</documentation>
				</annotation>
			</element>
			<element name="mcRestartScript" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Path to restart script (usually restart.bat for Windows and build/scripts/restart.sh for Unix/Linux)</documentation>
				</annotation>
			</element>
			<element name="aiFilesDirBaseName" type="fews:fileStringType" default="/opt/fews/data/nlwlmc00/fromfss">
				<annotation>
					<documentation>Base path for the directories for DumpFiles, etc.</documentation>
				</annotation>
			</element>
			<element name="aiRestartScriptPath" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Restart command or script to restart the master controller from the Admin interface</documentation>
				</annotation>
			</element>
			<element name="aiRestartScriptArgs" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional space-separated arguments for the AI Restart script/command</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="RemoteMasterControllerInstallComplexType">
		<annotation>
			<documentation>Contains information on the optional remote master controller for the system.</documentation>
		</annotation>
		<choice>
			<element name="remoteDbServer" type="fews:DatabaseServerInstallComplexType">
				<annotation>
					<documentation>Since 2017.02 Contains information on the remote database for this client-server entity.</documentation>
				</annotation>
			</element>
			<element name="remoteJMSServer" type="fews:JMSServerInstallComplexType">
				<annotation>
					<documentation>Before 2017.02 The information on the server providing the JMS queues for the remote master controller.</documentation>
				</annotation>
			</element>
		</choice>
		<attribute name="remoteMcId" type="fews:idStringType" use="required">
			<annotation>
				<documentation>The ID of the remote master controller.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<simpleType name="clientModeEnumStringType">
		<restriction base="string">
			<enumeration value="direct database access"/>
			<enumeration value="synchronising client"/>
			<enumeration value="wis synchronising client"/>
		</restriction>
	</simpleType>
	<complexType name="ClientInstallComplexType">
		<sequence>
			<element name="ocDir" type="fews:fileStringType" default="d:/fews/">
				<annotation>
					<documentation>Root directory for the OC, this directory will contain directories like jre and region_home</documentation>
				</annotation>
			</element>
			<element name="clientMode" type="fews:clientModeEnumStringType">
				<annotation>
					<documentation>Defines how to connect to the central database. Options are direct database access, 'synchronising client'  and 'wis synchronising client'.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ForecastingShellInstallComplexType">
		<annotation>
			<documentation>Contains information on the forecasting shells of the system.</documentation>
		</annotation>
		<sequence>
			<element name="numberOfFSS" type="fews:positiveInteger" default="2">
				<annotation>
					<documentation>Number of FSS instances for this client-server entity (default: 2).</documentation>
				</annotation>
			</element>
			<element name="fssOS" default="windows">
				<annotation>
					<documentation>The Operating System of the Forecasting Shell machine (windows or linux).</documentation>
				</annotation>
				<simpleType>
					<restriction base="string">
						<enumeration value="windows"/>
						<enumeration value="linux"/>
						<enumeration value="both"/>
					</restriction>
				</simpleType>
			</element>
			<element name="fssJavaHome" type="fews:fileStringType" default="d:/opt/java/jre1.8/">
				<annotation>
					<documentation>Java home directory of JRE, directory is assumed to contain a bin/ sub-directory with the JRE java.exe executable.</documentation>
				</annotation>
			</element>
			<element name="fssRootDir" type="fews:fileStringType" default="d:/fews/">
				<annotation>
					<documentation>Root directory for the FSS, this directory will contain directories like FSS00/mcproxy/ and FSS00/FewsShell/.</documentation>
				</annotation>
			</element>
			<element name="fssRegionHomeName" type="fews:nameStringType" default="FewsWL">
				<annotation>
					<documentation>Region Home directory name for the FSS, must not contain spaces, e.g. FewsWL.</documentation>
				</annotation>
			</element>
			<element name="clientMode" type="fews:clientModeEnumStringType" default="synchronising client" minOccurs="0">
				<annotation>
					<documentation>Defines how to connect to the central database. Options are 'direct database access', 'synchronising client'  and 'wis synchronising client'. Forecastingshells are by default 'synchronising client'.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ArchiveServerInstallComplexType">
		<annotation>
			<documentation>Contains information on the deltares archive server.
			</documentation>
		</annotation>
		<sequence>
			<element name="archiveServerName" type="string" default="appserver01.deltares.nl">
				<annotation>
					<documentation>The server name or IP address of the archive server.</documentation>
				</annotation>
			</element>
			<element name="archiveServerPort" type="integer" >
				<annotation>
					<documentation>HTTP Port of tomcat instance hosting deltares-archive-server</documentation>
				</annotation>
			</element>
			<element name="archiveRootDir" type="fews:fileStringType" >
				<annotation>
					<documentation>Root directory of the archive server file store</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
