<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="interpolationSets.xsd"/>
	<!-- -->
	<element name="floodMapSets" type="fews:FloodMapSetsComplexType"/>
	<!-- -->
	<complexType name="FloodMapSetsComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="floodMapDirectories" type="fews:FloodMapDirectoriesCompexType"/>
			<element name="geoDatum" type="fews:geoDatumStringType" minOccurs="0"/>
			<element name="diagnosticFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Diagnostic file: Contains all messages produced by the pcr raster or interpolation module.</documentation>
				</annotation>
			</element>
			<element name="floodMapSet" type="fews:FloodMapSetComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<!-- -->
	<complexType name="FloodMapSetComplexType">
		<choice>
			<element name="longitudinalProfile" type="fews:LongitudinalProfileComplexType"/>
			<element name="floodExtentMap" type="fews:FloodExtentMapComplexType"/>
			<element name="floodMap" type="fews:FloodDemMapComplexType" maxOccurs="unbounded"/>
		</choice>
	</complexType>
	<!-- -->
	<complexType name="FloodMapDirectoriesCompexType">
		<sequence>
			<element name="rootDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Root directory of the module instance. This may be either a relative or absolute path. if Missing then the adapetr root dir is assumed</documentation>
				</annotation>
			</element>
			<element name="workDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Working directory for several activities.</documentation>
				</annotation>
			</element>
			<element name="outputDir" type="fews:directoryStringType">
				<annotation>
					<documentation>Directory to which the Flood Map will write Longitudinal / Flood Map to.</documentation>
				</annotation>
			</element>
			<element name="inputDir" type="fews:directoryStringType">
				<annotation>
					<documentation>Directory the Flood Map will get the data from.</documentation>
				</annotation>
			</element>
			<element name="pcrDir" type="fews:fileStringType" minOccurs="0"/>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="LongitudinalProfileComplexType">
		<all>
			<element name="branchFile" type="fews:fileStringType"/>
			<element name="timeSeriesFile" type="fews:fileStringType"/>
			<element name="profileFile" type="fews:fileStringType"/>
		</all>
	</complexType>
	<!-- -->
	<complexType name="FloodExtentMapComplexType">
		<sequence>
			<element name="input" type="fews:InputComplexType"/>
			<element name="interpolationOptions" type="fews:SpatialInterpolationComplexType"/>
			<element name="pcrScript" type="fews:PcrScriptComplexType" minOccurs="0"/>
			<element name="output" type="fews:OutputComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="FloodDemMapComplexType">
		<sequence>
			<element name="input" type="fews:InputComplexType"/>
			<element name="extrapolationOptions" type="fews:ExtrapolationComplexType"/>
			<element name="output" type="fews:OutputComplexType"/>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="GridFileOutputComplexType">
		<sequence>
			<element name="filename" type="fews:fileStringType"/>
			<element name="mapStackFilename" type="fews:fileStringType" minOccurs="0"/>
		</sequence>
	</complexType>
	<!-- -->
	<simpleType name="FloodMapOutputOptionEnumStringType">
		<restriction base="string">
			<enumeration value="maximumextent"/>
			<enumeration value="pertime"/>
			<enumeration value="contour"/>
		</restriction>
	</simpleType>
	<!-- -->
	<complexType name="PcrScriptComplexType">
		<sequence>
			<element name="pcrExecutableFilename" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>THIS FEATURE NOT SUPPORTED</documentation>
				</annotation>
			</element>
			<element name="pcrDllFileName" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>THIS FEATURE NOT SUPPORTED</documentation>
				</annotation>
			</element>
			<choice>
				<element name="pcrScriptFile" type="fews:fileStringType"/>
				<element name="pcrScriptXMLFile" type="fews:fileStringType"/>
			</choice>
			<element name="pcrArguments" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>THIS FEATURE NOT SUPPORTED</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="InputComplexType">
		<sequence>
			<choice>
				<element name="profileFile" type="fews:fileStringType"/>
				<element name="timeSeriesFile" type="fews:fileStringType"/>
			</choice>
			<element name="asciiDemFile" type="fews:fileStringType"/>
			<choice>
				<element name="xmlAxisFile" type="fews:fileStringType"/>
				<element name="asciiAxisFile" type="fews:fileStringType"/>
			</choice>
			<element name="asciiMapSectionFile" type="fews:fileStringType"/>
			<element name="xmlInterpolationOutlineFile" type="fews:fileStringType" minOccurs="0"/>
			<element name="geoReferenceFile" type="fews:fileStringType"/>
			<element name="locationId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Input location ID. Required when input file is of type PiTimeSeries.</documentation>
				</annotation>
			</element>
			<element name="parameterId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Input parameter ID. Required when input file is of type PiTimeSeries.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="OutputComplexType">
		<sequence>
			<element name="outputOption" type="fews:FloodMapOutputOptionEnumStringType"/>
			<element name="levelOutput" type="boolean" minOccurs="0"/>
			<element name="asciiGrid" type="fews:GridFileOutputComplexType" minOccurs="0"/>
			<element name="pcrGrid" type="fews:GridFileOutputComplexType" minOccurs="0"/>
			<element name="contour" type="fews:ContourOutputComplexType" minOccurs="0"/>
			<element name="bilGrid" type="fews:GridFileOutputComplexType" minOccurs="0"/>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="ExtrapolationComplexType">
		<sequence>
			<element name="extrapolationSteps" type="integer" minOccurs="0"/>
			<element name="cleanUpProfile" type="boolean" minOccurs="0"/>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="ContourOutputComplexType">
		<sequence>
			<element name="filename" type="fews:fileStringType"/>
			<element name="numberofContours" type="int"/>
		</sequence>
	</complexType>
</schema>
