<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="forecasterAidSelectionPanel" type="fews:forecasterAidSelectionPanelComplexType"/>
	<complexType name="forecasterAidSelectionPanelComplexType">
		<annotation>
			<documentation>Configures the ForecasterAidSelectionPanel</documentation>
		</annotation>
		<sequence>
			<element name="explorerLocationDocumentAttributeId" type="string">
				<annotation>
					<documentation>Since 2017.02 When an explorer location is selected the ForecasterAidSelectionPanel will select the document listed in this attribute, if applicable. If more than one location is selected, the document selection remains unchanged. If the attribute is not defined for the selected location or the document listed in the attribute is not currently visible in the ForecasterAidSelectionPanel, the document selection remains unchanged as well.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
