<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:fp="http://www.wldelft.nl/fews/FP" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews/FP" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<element name="forecastPairingTable" type="fp:ForecastPairingTableComplexType">
		<annotation>
			<documentation>Forecast Pairing table</documentation>
		</annotation>
	</element>
	<complexType name="ForecastPairingTableComplexType">
		<annotation>
			<documentation>All forecast pairings per flood period and forecast location</documentation>
		</annotation>
		<sequence minOccurs="1" maxOccurs="1">
			<element name="creationTime" type="fp:DateTimeComplexType"/>
			<element name="timeZone" type="fp:TimeZoneSimpleType" default="0.0">
				<annotation>
					<documentation>The timeZone (in decimal hours shift from GMT) e.g. -1.0 or 3.5. 
					</documentation>
				</annotation>
			</element>
			<sequence minOccurs="0" maxOccurs="unbounded">
				<element name="floodPeriod" type="fp:FloodPeriodComplexType">
					<annotation>
						<documentation>
					</documentation>
					</annotation>
				</element>
			</sequence>
		</sequence>
	</complexType>
	
	<complexType name="FloodPeriodComplexType">
		<annotation>
			<documentation>Flood period contains forecast locations that are part of a flood period</documentation>
		</annotation>
		<sequence minOccurs="1" maxOccurs="1">
			<element name="areaId" type="string" minOccurs="1" maxOccurs="1" />
			<element name="areaName" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="floodPeriodStart" type="fp:DateTimeComplexType" minOccurs="1" maxOccurs="1"/>
			<element name="floodPeriodEnd" type="fp:DateTimeComplexType" minOccurs="1" maxOccurs="1"/>
			<element name="description" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="status" type="string" minOccurs="1" maxOccurs="1"/>
			<sequence minOccurs="0" maxOccurs="unbounded">
				<element name="forecastLocation" type="fp:ForecastLocationComplexType">
					<annotation>
						<documentation>
						</documentation>
					</annotation>
				</element>
			</sequence>
		</sequence>
	</complexType>
	<complexType name="ForecastLocationComplexType">
		<annotation>
			<documentation>Flood pairings for a flood location</documentation>
		</annotation>
		<sequence minOccurs="1" maxOccurs="1">
			<element name="locationId" type="string" minOccurs="1" maxOccurs="1" />
			<element name="locationName" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="maximumForecastSeverity" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="maximumObservedSeverity" type="string" minOccurs="1" maxOccurs="1"/>
			<sequence minOccurs="0" maxOccurs="unbounded">
				<element name="forecastPairing" type="fp:ForecastPairingComplexType">
					<annotation>
						<documentation>
						</documentation>
					</annotation>
				</element>
			</sequence>
		</sequence>
	</complexType>
	<complexType name="ForecastPairingComplexType">
		<annotation>
			<documentation>All attributes of a forecast pairing</documentation>
		</annotation>
		<attribute name="forecastWarningNumber" type="integer">
			<annotation>
				<documentation>
					Sequence number of the forecast
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastDate" type="fp:dateType">
			<annotation>
				<documentation>
					The time the forecast was issued.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastTime" type="fp:timeType">
			<annotation>
				<documentation>
					The time the forecast was issued.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastTimeZone" type="string">
			<annotation>
				<documentation>
					The timeZone the forecast was issued for. For example: +10:00
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastPredictionType" type="string">
			<annotation>
				<documentation>
					The prediction time. Fore example Reach, Remain below
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastLevel" type="string">
			<annotation>
				<documentation>
					Level. For example: FloodClass
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastSeverity" type="string">
			<annotation>
				<documentation>
					Severity. For example: Minor
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastValue" type="float">
			<annotation>
				<documentation>
					Forecast value
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastMinValue" type="float">
			<annotation>
				<documentation>
					minimum Forecast value in case a value range was used.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastMaxValue" type="float">
			<annotation>
				<documentation>
					Maximum Forecast value in case a value range was used
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastTimeType" type="string">
			<annotation>
				<documentation>
					Forecast time type. For example: PartDay or Day.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastWarningDate" type="fp:dateType">
			<annotation>
				<documentation>
					Date of he forecast warning
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastWarningTime" type="fp:timeType">
			<annotation>
				<documentation>
					Time of the forecast warning
				</documentation>
			</annotation>
		</attribute>
		<attribute name="partOfDay" type="string">
			<annotation>
				<documentation>
					Part of day. For example: Afternoon, Overnight
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastPredictionStartDate" type="fp:dateType">
			<annotation>
				<documentation>
					Start date of the prediction in case of a time range
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastPredictionStartTime" type="fp:timeType">
			<annotation>
				<documentation>
					Start time of the prediction in case of a time range
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastPredictionEndDate" type="fp:dateType">
			<annotation>
				<documentation>
					End date of the prediction in case of a time range
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastPredictionEndTime" type="fp:timeType">
			<annotation>
				<documentation>
					End time of the prediction in case of a time range
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastLeadTime" type="float">
			<annotation>
				<documentation>
					difference in hours between the forecast waring time and the issued forecast time
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastWarningNextIssueText" type="string">
			<annotation>
				<documentation>
					Next Issue forecast warning text
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastWarningNextIssueDate" type="fp:dateType">
			<annotation>
				<documentation>
					Date of the next forecast warning issue time
				</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastWarningNextIssueTime" type="fp:timeType">
			<annotation>
				<documentation>
					Time of the next forecast warning issue time
				</documentation>
			</annotation>
		</attribute>
		<attribute name="observedCharacteristics" type="string">
			<annotation>
				<documentation>
					Observed 
				</documentation>
			</annotation>
		</attribute>
		<attribute name="observedDate" type="fp:dateType">
			<annotation>
				<documentation>
					Date of the observed threshold crossing
				</documentation>
			</annotation>
		</attribute>
		<attribute name="observedTime" type="fp:timeType">
			<annotation>
				<documentation>
					Time of the observed threshold crossing
				</documentation>
			</annotation>
		</attribute>
		<attribute name="observedValue" type="float">
			<annotation>
				<documentation>
					Value of the observed threshold crossing
				</documentation>
			</annotation>
		</attribute>
		<attribute name="observedLeadTime" type="float">
			<annotation>
				<documentation>
					Difference in hours between the forecast waring time and the observed thresold crossing time
				</documentation>
			</annotation>
		</attribute>
		<attribute name="pairingStatus" type="string">
			<annotation>
				<documentation>
					Status of the pairing
				</documentation>
			</annotation>
		</attribute>
		<attribute name="comments" type="string">
			<annotation>
				<documentation>
					Comments of the paired forecast
				</documentation>
			</annotation>
		</attribute>
		<attribute name="duplicate" type="string">
			<annotation>
				<documentation>
					Forecast marked as duplicate
				</documentation>
			</annotation>
		</attribute>

	</complexType>
	<complexType name="DateTimeComplexType">
		<attribute name="date" type="fp:dateType" use="required"/>
		<attribute name="time" type="fp:timeType" use="optional"/>
	</complexType>
	<simpleType name="dateType">
		<restriction base="date">
			<pattern value="\d\d\d\d-\d\d-\d\d"/>
		</restriction>
	</simpleType>
	<!-- -->
	<simpleType name="timeType">
		<restriction base="time">
			<pattern value="\d\d:\d\d:\d\d"/>
		</restriction>
	</simpleType>
	<simpleType name="TimeZoneSimpleType">
		<annotation>
			<documentation>The timeZone (in decimal hours shift from GMT) e.g. -1.0 or 3.5.
			</documentation>
		</annotation>
		<restriction base="double"/>
	</simpleType>

</schema>
