<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="geoReferenceDataSet" type="fews:GeoReferenceDataSetComplexType">
		<annotation>
			<documentation>LEGACY, NO LONGER USED</documentation>
		</annotation>
	</element>
	<!--Complex Types definitions for different types of Transformations-->
	<!--GeoReferenceDataSet-->
	<complexType name="GeoReferenceDataSetComplexType">
		<annotation>
			<documentation>GeoReferenceDataSet geo reference a Location (label) with spatial Flood Map Section</documentation>
		</annotation>
		<sequence>
			<element name="geoDatum" type="fews:geoDatumStringType"/>
			<element name="geoReferenceData" type="fews:GeoReferenceDataComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<!-- -->
	<complexType name="GeoReferenceDataComplexType">
		<sequence>
			<element name="mapSectionId" type="fews:idIntType"/>
			<element name="point" type="fews:PointComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="label" type="fews:idStringType" use="required"/>
	</complexType>
	<!-- -->
	<complexType name="PointComplexType">
		<annotation>
			<documentation>Each point element has two required attributes, X and Y that point to a geographical location.</documentation>
		</annotation>
		<attribute name="x" type="double" use="optional"/>
		<attribute name="y" type="double" use="optional"/>
	</complexType>
</schema>
