<?xml version="1.0" encoding="UTF-8"?><!-- Web OC only -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="logDisplays" type="fews:LogDisplaysComplexType"/>
	<complexType name="LogDisplaysComplexType">
		<sequence>
			<element name="logDisplay" type="fews:LogDisplayComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="LogDisplayComplexType">
		<annotation>
			<documentation>Configure a log display in the Web OC</documentation>
		</annotation>
		<sequence>
			<element name="relativeViewPeriod" type="fews:RelativePeriodComplexType" minOccurs="0"/>
			<element name="defaultLogRequestCount" type="integer" default="0" minOccurs="0">
				<annotation>
					<documentation>Configure the default number of log messages that are requested. Set to 0 if not configured.</documentation>
				</annotation>
			</element>
			<element name="systemLog" type="fews:LogDisplaySystemLogComplexType" minOccurs="0"/>
			<element name="manualLog" type="fews:LogDisplayManualLogComplexType" minOccurs="0"/>
			<element name="logDissemination" type="fews:LogDisplayLogDisseminationComplexType" minOccurs="0"/>
			<element name="viewPermission" type="string" minOccurs="0">
				<annotation>
					<documentation>set a permission to control who can view this log display in the Web OC</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<simpleType name="SystemLogLevelTypes">
		<annotation>
			<documentation>Log levels.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="ERROR"/>
			<enumeration value="WARN"/>
			<enumeration value="INFO"/>
		</restriction>
	</simpleType>
	<complexType name="LogDisplaySystemLogComplexType">
		<sequence>
			<element name="logLevel" type="fews:SystemLogLevelTypes" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation>Log Level that has to be displayed</documentation>
				</annotation>
			</element>
			<element name="eventCodes" type="fews:LogDisplaySystemEventCodesComplexType" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation>Log Levels that have to be displayed</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="enabled" type="boolean" default="true"/>
	</complexType>
	<complexType name="LogDisplaySystemEventCodesComplexType">
		<sequence>
			<element name="eventCode" type="string" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Event code to filter on</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="LogDisplayManualLogComplexType">
		<sequence>
			<element name="noteGroupId" type="string" minOccurs="0">
				<annotation>
					<documentation>Refer to an existing note group id from which a template can be used. If enabled, the noteGroupId is required.</documentation>
				</annotation>
			</element>
			<element name="createPermission" type="string" minOccurs="0">
				<annotation>
					<documentation>Set a permission to control who can create a log</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="enabled" type="boolean" default="true"/>
	</complexType>
	<complexType name="LogDisplayLogDisseminationComplexType">
		<sequence>
			<element name="disseminationActions" type="fews:LogDisplayLogDisseminationActionsComplexType" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation>
						<documentation>NOTE: Currenty the dissemination of log messages is configured in the LogDisplays.xml. We foresee that in the future (2026/2027) updates to the configuration and methods of (log) dissemination will be updated. Please be aware of this when configuring dissemination actions.</documentation>
					</documentation>
				</annotation>
			</element>
			<element name="permission" type="string" minOccurs="0">
				<annotation>
					<documentation>Set a permission to control who can disseminate a log</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="enabled" type="boolean" default="true"/>
	</complexType>
	<complexType name="LogDisplayLogDisseminationActionsComplexType">
		<sequence>
			<element name="action" type="fews:LogDisplayLogDisseminationActionComplexType" minOccurs="1" maxOccurs="unbounded"/>
			<element name="permission" type="string" minOccurs="0">
				<annotation>
					<documentation>Set a permission to control who can disseminate a log</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="LogDisplayLogDisseminationActionComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Description as displayed in the Web OC</documentation>
				</annotation>
			</element>
			<element name="iconId" type="string" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Icon to be used in the Web OC</documentation>
				</annotation>
			</element>
			<element name="eventCode" type="string" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Event code that will be used to write the action log</documentation>
				</annotation>
			</element>
			<element name="manualLog" type="boolean" default="true">
				<annotation>
					<documentation>Make the action available in the manual log display</documentation>
				</annotation>
			</element>
			<element name="systemLog" type="boolean" default="false">
				<annotation>
					<documentation>Make the action available in the system log display</documentation>
				</annotation>
			</element>
			<element name="maxLogCharacters" type="integer" minOccurs="0">
				<annotation>
					<documentation>Configure the max log message length that can be used for a dissemination, for example SMS has a limited length.</documentation>
				</annotation>
			</element>
			<element name="permission" type="string" minOccurs="0">
				<annotation>
					<documentation>Set a permission to control who can disseminate a log</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
	</complexType>
</schema>