<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews"
        targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
        version="1.0">
    <include schemaLocation="sharedTypes.xsd"/>
    <element name="massBalance" type="fews:MassBalanceComplexType">
        <annotation>
            <documentation>Module slices an area from a grid and compute the netVolume of all grid cells having their
                cell centre inside this area
            </documentation>
        </annotation>
    </element>

    <complexType name="MassBalanceComplexType">
        <choice maxOccurs="unbounded">
            <element name="horizontalFlux" type="fews:SliceHorizontalFluxComplexType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>activity computes net volume change of sliced area due to horizontal flux
                    </documentation>
                </annotation>
            </element>
            <element name="horizontalVelocity" type="fews:SliceHorizontalVelocityComplexType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>activity computes net volume change of sliced area due to horizontal flux (expressed as velocity)
                    </documentation>
                </annotation>
            </element>
            <element name="verticalFlux" type="fews:SliceVerticalFluxComplexType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>activity computes net volume change of sliced area due to vertical flux
                    </documentation>
                </annotation>
            </element>
            <element name="verticalVelocity" type="fews:SliceVerticalVelocityComplexType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>activity computes net volume change of sliced area due to vertical flux (expressed as velocity)
                    </documentation>
                </annotation>
            </element>
            <element name="storageChange" type="fews:SliceStorageChangeComplexType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>activity computes net volume change of sliced area due to storage change
                    </documentation>
                </annotation>
            </element>
        </choice>
    </complexType>

    <complexType name="SliceVerticalFluxComplexType">
        <annotation>
            <documentation>activity computes net volume change of sliced area due to vertical flux</documentation>
        </annotation>
        <sequence>
            <choice>
                <annotation>
                    <documentation>value type: grid</documentation>
                </annotation>
                <sequence>
                    <annotation>
                        <documentation>used for situations where the separate flux fields are know at upper and lower
                            face
                        </documentation>
                    </annotation>
                    <element name="upperFaceFluxFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                        <annotation>
                            <documentation>value type: grid</documentation>
                        </annotation>
                    </element>
                    <element name="lowerFaceFluxFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                        <annotation>
                            <documentation>value type: grid</documentation>
                        </annotation>
                    </element>
                </sequence>
                <element name="netVertFluxFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                    <annotation>
                        <documentation>used for situations where the net flux field is know for the grid time series
                        </documentation>
                    </annotation>
                </element>
            </choice>
            <element name="outputTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                <annotation>
                    <documentation>value type: scalar; location type: polygon or grid locationId defines sliced area
                    </documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="SliceVerticalVelocityComplexType">
        <annotation>
            <documentation>activity computes net volume change of sliced area due to vertical flux</documentation>
        </annotation>
        <sequence>
            <choice>
                <annotation>
                    <documentation>value type: grid</documentation>
                </annotation>
                <sequence>
                    <annotation>
                        <documentation>used for situations where the separate velocity fields are know at upper and lower
                            face
                        </documentation>
                    </annotation>
                    <element name="upperFaceVelocityFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                        <annotation>
                            <documentation>value type: grid</documentation>
                        </annotation>
                    </element>
                    <element name="lowerFaceVelocityFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                        <annotation>
                            <documentation>value type: grid</documentation>
                        </annotation>
                    </element>
                </sequence>
                <element name="netVertVelocityFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                    <annotation>
                        <documentation>used for situations where the net velocity field is know for the grid time series
                        </documentation>
                    </annotation>
                </element>
            </choice>
            <element name="outputTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                <annotation>
                    <documentation>value type: scalar; location type: polygon or grid locationId defines sliced area
                    </documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="SliceStorageChangeComplexType">
        <annotation>
            <documentation>activity computes net volume change of sliced area due to storage change</documentation>
        </annotation>
        <sequence>
            <element name="multiplyByCellSize" type="boolean" minOccurs="0" default="true"/>
            <choice>
                <annotation>
                    <documentation>value type: grid</documentation>
                </annotation>
                <element name="waterTableChangeTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                    <annotation>
                        <documentation>used for time series where water table change is directly related to net storage
                            change
                        </documentation>
                    </annotation>
                </element>
                <element name="storageChangeFluxFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                    <annotation>
                        <documentation>used for time series which have no direct relation between water table and net
                            storage change. Additional domain knowledge has been used to provide a grid time series
                            which accounts for e.g. porosity
                        </documentation>
                    </annotation>
                </element>
            </choice>
            <element name="outputTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                <annotation>
                    <documentation>value type: scalar; location type: polygon or grid; locationId defines sliced area
                    </documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="SliceHorizontalFluxComplexType">
        <annotation>
            <documentation>activity computes net volume change of sliced area due to horizontal flux</documentation>
        </annotation>
        <sequence>
            <element name="multiplyByCellSize" type="boolean" minOccurs="0" default="true"/>
            <element name="staggeredGrid" type="boolean" minOccurs="0" default="false"/>
            <element name="invertedYDirection" type="boolean" minOccurs="0" default="false"/>
            <element name="uFluxFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                <annotation>
                    <documentation>value type: grid</documentation>
                </annotation>
            </element>
            <element name="vFluxFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                <annotation>
                    <documentation>value type: grid</documentation>
                </annotation>
            </element>
            <element name="outputTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                <annotation>
                    <documentation>value type: scalar; location type polygon or grid; locationId defines sliced area
                    </documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="SliceHorizontalVelocityComplexType">
        <annotation>
            <documentation>activity computes net volume change of sliced area due to horizontal flux</documentation>
        </annotation>
        <sequence>
            <element name="staggeredGrid" type="boolean" minOccurs="0" default="false"/>
            <element name="invertedYDirection" type="boolean" minOccurs="0" default="false"/>
            <element name="uVelocityFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                <annotation>
                    <documentation>value type: grid</documentation>
                </annotation>
            </element>
            <element name="vVelocityFieldTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                <annotation>
                    <documentation>value type: grid</documentation>
                </annotation>
            </element>
            <element name="outputTimeSeriesSet" type="fews:TimeSeriesSetComplexType">
                <annotation>
                    <documentation>value type: scalar; location type polygon or grid; locationId defines sliced area
                    </documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
</schema>
