<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="onTheFlyExpressionTimeSeries">
		<complexType>
			<sequence>
				<element name="onTheFlyExpressionTimeSeriesDefinition" type="fews:OnTheFlyExpressionTimeSeriesDefinitionComplexType"/>
			</sequence>
		</complexType>
	</element>
	<complexType name="OnTheFlyExpressionTimeSeriesDefinitionComplexType">
		<sequence>
			<element name="name" type="fews:nonEmptyStringType"/>
			<element name="parameterGroupId" type="fews:idStringType"/>
			<element name="formula" type="fews:nonEmptyStringType"/>
			<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
</schema>