<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="openDACalibrationDisplay" type="fews:OpenDACalibrationDisplayComplexType"/>
	<complexType name="OpenDACalibrationDisplayComplexType">
		<sequence>
			<element name="fileExchangeDirectory" type="fews:directoryStringType"/>
			<element name="modelParametersFileName" type="fews:fileStringType"/>
			<element name="modelResultsFileName" type="fews:fileStringType"/>
			<element name="workflowId" type="fews:idStringType"/>
			<element name="openDABinDir" type="fews:directoryStringType">
				<annotation>
					<documentation>Directory which contains the binaries of OpenDA</documentation>
				</annotation>
			</element>
			<element name="calibrationParameter" type="fews:CalibrationParameterComplexType" maxOccurs="unbounded"/>
			<element name="observedTimeSeriesSet" type="fews:TimeSeriesSetComplexType"/>
			<element name="resultsTimeSeriesSet" type="fews:TimeSeriesSetComplexType"/>
		</sequence>
	</complexType>
	<complexType name="CalibrationParameterComplexType">
		<attribute name="label" type="fews:nonEmptyStringType" use="required"/>
		<attribute name="initialValue" type="double" use="required"/>
		<attribute name="stdDev" type="double" use="required"/>
		<attribute name="lowerBound" type="double"/>
		<attribute name="upperBound" type="double"/>
	</complexType>
</schema>