<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="reportExport" type="fews:ReportExportComplexType">
		<annotation>
			<documentation>Schema for report export settings</documentation>
		</annotation>
	</element>
	<complexType name="ReportExportComplexType">
		<sequence>
			<element name="reportExportRootDir" type="fews:fileStringType">
				<annotation>
					<documentation>Root directory to which the all reports are to be exported to. This directory is typically the root directory of the web server.</documentation>
				</annotation>
			</element>
			<element name="reportExportTelegramPhoto" type="fews:ReportExportTelegramPhotoComplexType" minOccurs="0">
				<annotation>
					<documentation>Configure export of report pages to the Telegram.org bot api as photos.</documentation>
				</annotation>
			</element>
			<element name="currentForecastReports" type="fews:CurrentForecastReportsComplexType" minOccurs="0">
				<annotation>
					<documentation>Exports the current forecast reports, also deletes older current forecasts unless incremental option is used.</documentation>
				</annotation>
			</element>
			<element name="exportForecastReports" type="fews:ExportForecastReportsComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated since 2011.01. Do not configure this.</documentation>
				</annotation>
			</element>
			<element name="exportSystemStatusReports" type="fews:ExportSystemStatusReportsComplexType" minOccurs="0">
				<annotation>
					<documentation>Export of most recent system reports.</documentation>
				</annotation>
			</element>
			<element name="dataFeedId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Id for data feed. Export status will be stored in database using this id</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.0"/>
	</complexType>
	<complexType name="CurrentForecastReportsComplexType">
		<sequence>
			<element name="currentForcastSubDir" type="string">
				<annotation>
					<documentation>Root directory for exporting current forecasts to.</documentation>
				</annotation>
			</element>
			<element name="zipReports" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Zip the reports or not.</documentation>
				</annotation>
			</element>
			<element name="dateTimeFormat" type="string" default="yyyy-MM-dd HH-mm" minOccurs="0">
				<annotation>
					<documentation>Date time format of the timestamp that is put in the output directory.</documentation>
				</annotation>
			</element>
			<element name="exportTimeZone" type="fews:TimeZoneComplexType" minOccurs="0">
				<annotation>
					<documentation>Time zone of the export data.</documentation>
				</annotation>
			</element>
			<element name="prefix" type="string" default="" minOccurs="0">
				<annotation>
					<documentation>Prefix for the destination zip file or directory.</documentation>
				</annotation>
			</element>
			<element name="numberCurrentForecasts" type="int" minOccurs="0">
				<annotation>
					<documentation>Number of most recent current forecast reports to keep in the output directory.</documentation>
				</annotation>
			</element>
			<element name="excludeModuleInstanceId" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional list of reports generated by report module instances that should not be included in the export of current forecasts. Should not be used together with includeModuleInstanceId.
					</documentation>
				</annotation>
			</element>
			<element name="includeModuleInstanceId" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>List of reports identified by moduleInstanceId of the report module instances that created them that should be included in the export of other system status reports. Should not be used together with excludeModuleInstanceId.
					</documentation>
				</annotation>
			</element>
			<element name="incremental" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>This option can be used for writing reports incrementally. When true, older forecast reports will not be deleted.</documentation>
				</annotation>
			</element>
			<element name="generatePdf" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Enable to generate each report html page as a pdf, in the global.properties the option REPORT_HTML2PDF_PROGRAM should be set to the path of the conversion program or shell script.
					</documentation>
				</annotation>
			</element>
			<element name="generateImage" minOccurs="0">
				<annotation>
					<documentation>Enable to generate each html as an image of the specified format/extension, in the global.properties the option REPORT_HTML2IMG_PROGRAM should be set to the path of the conversion program or shell script.
					</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="format" type="string" minOccurs="0">
							<annotation>
								<documentation>Image format file extension (i.e. PNG / JPG / BMP, default is JPG)</documentation>
							</annotation>

						</element>
						<element name="options" type="string" minOccurs="0">
							<annotation>
								<documentation>Command line options (i.e. --width 720) to be provided to the image conversion program.</documentation>
							</annotation>
						</element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<!--todo remove ExportForecastReportsComplexType, not used any more-->
	<complexType name="ExportForecastReportsComplexType">
		<sequence>
			<element name="exportForcastSubDir" type="string"/>
			<element name="numberForecastsToExport" type="int"/>
			<element name="excludeModuleInstanceId" type="string" minOccurs="0" maxOccurs="unbounded"/>
			<element name="includeModuleInstanceId" type="string" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="ExportSystemStatusReportsComplexType">
		<sequence>
			<choice>
				<sequence>
					<element name="exportSystemStatusSubDir" type="string">
						<annotation>
							<documentation>Root directory for exporting system status reports to.</documentation>
						</annotation>
					</element>
					<element name="zipReports" type="boolean" default="false" minOccurs="0">
						<annotation>
							<documentation>Zip the reports or not.</documentation>
						</annotation>
					</element>
					<element name="dateTimeFormat" type="string" minOccurs="0">
						<annotation>
							<documentation>Date time format of the timestamp that is put in the output directory.</documentation>
						</annotation>
					</element>
					<element name="prefix" type="string" minOccurs="0">
						<annotation>
							<documentation>Prefix for the destination or directory.</documentation>
						</annotation>
					</element>
				</sequence>
				<element name="exportSystemStatusZipFile" type="string">
					<annotation>
						<documentation>Name of the zip file to create</documentation>
					</annotation>
				</element>
			</choice>
			<element name="includeModuleInstanceId" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>List of reports identified by moduleInstanceId of the report module instances that created them that should be included in the export of other system status reports.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ReportExportTelegramPhotoComplexType">
		<sequence>
			<element name="telegramBotToken" type="string">
				<annotation>
					<documentation>Token of a Telegram.org bot which was created for this purpose, in encrypted form.</documentation>
				</annotation>
			</element>
			<element name="telegramChatId" type="string">
				<annotation>
					<documentation>Chat_id of a Telegram.org bot channel which was created for this purpose, in encrypted form.</documentation>
				</annotation>
			</element>
			<element name="telegramSendPhoto" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="reportTelegramFile" type="string">
							<annotation>
								<documentation>Image file (photo) to send. May contain wildcards (.i.e. "telegram_*.jpg") to send multiple files.</documentation>
							</annotation>
						</element>
						<element name="reportTelegramCaption" type="string" minOccurs="0">
							<annotation>
								<documentation>Optional caption for the photo.</documentation>
							</annotation>
						</element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</schema>
