<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="sampleDisplay" type="fews:SampleDisplayComplexType"/>
	<complexType name="SampleDisplayComplexType">
		<sequence>
			<element name="enableEditor" type="boolean" minOccurs="0" default="false">
				<annotation>
					<documentation>When true values, value properties and comments can be edited from the sample viewer. Also values can be removed and the data editor can be opened from the sample viewer</documentation>
				</annotation>
			</element>
			<element name="permissions" type="fews:SampleDisplayPermissionsComplexType" minOccurs="0">
				<annotation>
					<documentation>Hide sample module instance values for users without the specified permission</documentation>
				</annotation>
			</element>
			<element name="season" type="fews:SeasonComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Since 2021.01 it is possible to filter the samples based on the configured seasons.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SampleDisplayPermissionsComplexType">
		<sequence>
			<element name="editorPermission" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>When the user has this permission and "enableEditor" is set to true: values, value properties and comments can be edited from the sample viewer. Also values can be removed and the data editor can be opened from the sample viewer. When not defined, no special permission is required.</documentation>
				</annotation>
			</element>
			<element name="moduleInstance" type="fews:ModuleInstancePermissionComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="ModuleInstancePermissionComplexType">
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>reference to ModuleInstances.xml</documentation>
			</annotation>
		</attribute>
		<attribute name="viewPermission" type="fews:idStringType" use="required">
			<annotation>
				<documentation>reference to Permissions.xml</documentation>
			</annotation>
		</attribute>
	</complexType>
</schema>
