<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews/archive"
		targetNamespace="http://www.wldelft.nl/fews/archive" elementFormDefault="qualified"
		attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="archive_sharedTypes.xsd"/>
	<element name="simulationMetaData" type="fews:SimulationMetaDataComplexType"/>
	<complexType name="SimulationMetaDataComplexType">
		<sequence>
			<element name="version" type="fews:metaDataVersionType" minOccurs="0"/>
			<group ref="fews:SharedGeneralSettingsGroup" minOccurs="0"/>
			<element name="runInfo" type="fews:RunInfoFileComplexType" minOccurs="0"/>
			<element name="areaId" type="fews:idStringType"/>
			<element name="sourceId" type="fews:idStringType" minOccurs="0"/>
			<element name="creationTime" type="fews:DateTimeComplexType"/>
			<element name="timeSeriesType" type="fews:archiveTimeSeriesType"/>
			<element name="netcdf" type="fews:SimulationNetcdfComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="modifiers" type="fews:AppliedModifiersComplexType" minOccurs="0"/>
			<element name="whatIf" type="fews:AppliedWhatIfComplexType" minOccurs="0"/>
			<element name="reports" type="fews:GeneratedReportsComplexType" minOccurs="0"/>
			<element name="states" type="fews:ModuleStatesComplexType" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="RunInfoFileComplexType">
		<sequence>
			<element name="relativeFilePath" type="fews:fileStringType"/>
		</sequence>
	</complexType>
	<complexType name="AppliedModifiersComplexType">
		<sequence>
			<element name="relativeFilePath" type="fews:fileStringType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="AppliedWhatIfComplexType">
		<sequence>
			<element name="relativeFilePath" type="fews:fileStringType"/>
		</sequence>
	</complexType>
	<complexType name="GeneratedReportsComplexType">
		<sequence>
			<element name="relativeFilePath" type="fews:fileStringType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="ModuleStatesComplexType">
		<choice>
			<element name="relativeFilePath" type="fews:fileStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>Deprecated,  for backward compatibility only.  State time and moduleInstanceId are included in the file  path. For example, if the path is "modulestates\National_G2G_Historical20190728001500.zip", then moduleInstanceId is National_G2G_Historical, and state time is 20190728001500</documentation>
				</annotation>
			</element>
			<element name="state" type="fews:ModuleStateComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>SINCE 2019.02 Info about the state</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="ModuleStateComplexType">
		<sequence>
			<element name="moduleInstanceId" type="fews:idStringType">
				<annotation>
					<documentation>Id  of the module instance for which the state is valid</documentation>
				</annotation>
			</element>
			<element name="stateTime" type="fews:DateTimeComplexType">
				<annotation>
					<documentation>Time  for which the state is valid</documentation>
				</annotation>
			</element>
			<element name="ensembleId" type="string" minOccurs="0">
				<annotation>
					<documentation>The ensemble id of the state</documentation>
				</annotation>
			</element>
			<element name="relativeFilePath" type="fews:fileStringType">
				<annotation>
					<documentation>Path of  the state zip file, relative to the folder where  metaData.xml is stored. </documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>