<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews/archive"
		targetNamespace="http://www.wldelft.nl/fews/archive" elementFormDefault="qualified"
		attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="archive_sharedTypes.xsd"/>
	<element name="simulatedHistoricalMetaData" type="fews:SimulatedHistoricalMetaDataComplexType"/>
	<complexType name="SimulatedHistoricalMetaDataComplexType">
		<sequence>
			<group ref="fews:SharedGeneralSettingsGroup" minOccurs="0"/>
			<element name="creationTime" type="fews:DateTimeComplexType"/>
			<element name="netcdf" type="fews:SimulatedHistoricalNetcdfComplexType" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="SimulatedHistoricalNetcdfComplexType">
		<sequence>
			<element name="relativeFilePath" type="fews:nonEmptyStringType"/>
			<element name="valueType" type="fews:valueType"/>
			<element name="areaId" type="fews:idStringType"/>
			<element name="sourceId" type="fews:idStringType" minOccurs="0"/>
			<element name="startTime" type="fews:DateTimeComplexType"/>
			<element name="endTime" type="fews:DateTimeComplexType"/>
			<element name="header" type="fews:ContentHeaderComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
</schema>
