<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:sobek="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0">
	<element name="sobekAdvancedBatch" type="sobek:SobekAdvancedBatchComplexType">
		<annotation>
			<documentation>Definition of Sobek Advanced Batch activities</documentation>
		</annotation>
	</element>
	<complexType name="SobekAdvancedBatchComplexType">
		<sequence>
			<element name="general" type="sobek:GeneralComplexType">
				<annotation>
					<documentation>General - i.e. activity independent - settings for this General Adapter run. Notice that all file references should be relative to the current directory or the defined mainDir variable!</documentation>
				</annotation>
			</element>
			<element name="preProcessingActivities" type="sobek:ProcessingActivitiesComplexType" minOccurs="0">
				<annotation>
					<documentation>Preprocessing activities. Notice that all file references should be relative to the CMTWORK directory!</documentation>
				</annotation>
			</element>
			<element name="postProcessingActivities" type="sobek:ProcessingActivitiesComplexType" minOccurs="0">
				<annotation>
					<documentation>Postprocessing activities. Notice that all file references should be relative to the CMTWORK directory!</documentation>
				</annotation>
			</element>
			<element name="mapStack" type="sobek:MapStackComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>MapStack - Map data. Notice that all file references should be relative to the current directory or the defined mainDir variable!</documentation>
				</annotation>
			</element>
			<element name="parameters" type="sobek:ParametersComplexType" minOccurs="0">
				<annotation>
					<documentation>Definition of parameters. Notice that all file references should be relative to the CMTWORK directory!</documentation>
				</annotation>
			</element>
			<element name="jobs" type="sobek:JobsComplexType" minOccurs="0">
				<annotation>
					<documentation>Definition of jobs. Notice that all file references should be relative to the current directory or the defined mainDir variable!</documentation>
				</annotation>
			</element>
			<element name="outputs" type="sobek:OutputsComplexType" minOccurs="0">
				<annotation>
					<documentation>Definition of output locations. Notice that all file references should be relative to the current directory or the defined mainDir variable!</documentation>
				</annotation>
			</element>
			<element name="longitudinalProfileOutput" type="sobek:LongitudinalProfileComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of longitudinal profile with output</documentation>
				</annotation>
			</element>
			<element name="states" type="sobek:StatesComplexType" minOccurs="0">
				<annotation>
					<documentation>Definition of states. Notice that all file references should be relative to the current directory or the defined mainDir variable!</documentation>
				</annotation>
			</element>
			<element name="sideViewPaths" type="sobek:SideviewComplexType" minOccurs="0">
				<annotation>
					<documentation>List of Sideview paths. Notice that all file references should be relative to the current directory or the defined mainDir variable!</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ProcessingActivitiesComplexType">
		<sequence>
			<element name="skipActivities" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Flag to skip all Avtivities</documentation>
				</annotation>
			</element>
			<element name="activity" type="sobek:ProcessingComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of Activity</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="StatesComplexType">
		<sequence>
			<element name="stateXmlOutputFile" type="string">
				<annotation>
					<documentation>XML Output file for states</documentation>
				</annotation>
			</element>
			<element name="state" type="sobek:StateComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of State</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ParametersComplexType">
		<sequence>
			<element name="parameter" type="sobek:ParameterComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of parameter</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OutputsComplexType">
		<sequence>
			<element name="output" type="sobek:OutputComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of output location</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="JobsComplexType">
		<sequence>
			<element name="job" type="sobek:JobComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of output location</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ParameterComplexType">
		<sequence>
			<element name="description" type="string" default="" minOccurs="0">
				<annotation>
					<documentation>Description of group of parameters</documentation>
				</annotation>
			</element>
			<element name="subParameter" type="sobek:SubParameterComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of sub parameters</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SubParameterComplexType">
		<sequence>
			<element name="description" type="string" default="" minOccurs="0">
				<annotation>
					<documentation>Description of sub parameter, used as Sobek object ID</documentation>
				</annotation>
			</element>
			<element name="sobekObjectId" type="string" default="" minOccurs="0">
				<annotation>
					<documentation>ID of SOBEK object that should get the defined data, if not defined the description is used</documentation>
				</annotation>
			</element>
			<element name="type" type="sobek:SubParameterTypeSimpleType">
				<annotation>
					<documentation>Sub parameter type</documentation>
				</annotation>
			</element>
			<choice maxOccurs="unbounded">
				<element name="classValue" type="float">
					<annotation>
						<documentation>Value which should be used for the actual sub parameter</documentation>
					</annotation>
				</element>
				<sequence>
					<element name="classPiFile" type="sobek:fileStringType">
						<annotation>
							<documentation>PI file which should be used for the actual sub parameter</documentation>
						</annotation>
					</element>
					<element name="locationId" type="string">
						<annotation>
							<documentation>If the value is a PI_XML filename the location id of the timeseries should be defined here</documentation>
						</annotation>
					</element>
					<element name="parameterId" type="string">
						<annotation>
							<documentation>If the value is a PI_XML filename the parameter id of the timeseries should be defined here</documentation>
						</annotation>
					</element>
				</sequence>
				<element name="classFile" type="sobek:fileStringType">
					<annotation>
						<documentation>Reference to e.g. a PRN, meteo or restart file which should be used for the actual sub parameter, relative to the CMTWORK directory.</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<simpleType name="SubParameterTypeSimpleType">
		<restriction base="string">
			<enumeration value="undefined"/>
			<enumeration value="rainfallfile"/>
			<enumeration value="rrrestart"/>
			<enumeration value="flowrestart"/>
			<enumeration value="flow_hc_boundary"/>
			<enumeration value="flow_ht_boundary"/>
			<enumeration value="flow_qc_boundary"/>
			<enumeration value="flow_qt_boundary"/>
			<enumeration value="flow_htref_boundary"/>
			<enumeration value="flow_qtref_boundary"/>
			<enumeration value="windfile"/>
			<enumeration value="flow_latndc"/>
			<enumeration value="flow_latndt"/>
			<enumeration value="flow_latndref"/>
			<enumeration value="flow_latbrc"/>
			<enumeration value="flow_latbrt"/>
			<enumeration value="flow_latbrref"/>
			<enumeration value="flow_latdic"/>
			<enumeration value="flow_latdit"/>
			<enumeration value="flow_latdiref"/>
			<enumeration value="flsboundline_hc"/>
			<enumeration value="flsboundline_ht"/>
			<enumeration value="flsboundline_qc"/>
			<enumeration value="flsboundline_qt"/>
			<enumeration value="flsboundnode_hc"/>
			<enumeration value="flsboundnode_ht"/>
			<enumeration value="flsboundnode_qc"/>
			<enumeration value="flsboundnode_qt"/>
			<enumeration value="flsinitpoint"/>
			<enumeration value="rr_up_seepdef"/>
			<enumeration value="rr_up_stordef"/>
			<enumeration value="rr_up_alfadef"/>
			<enumeration value="rr_up_infdef"/>
			<enumeration value="rr_up_initdef"/>
			<enumeration value="rr_up_ernstdef"/>
			<enumeration value="rr_indusdemandtable"/>
			<enumeration value="rr_indusdischargetable"/>
			<enumeration value="evapfile"/>
			<enumeration value="rtc_par3"/>
			<enumeration value="rtc_rule"/>
			<enumeration value="rtc_maxf"/>
			<enumeration value="rtc_engd"/>
			<enumeration value="flow_timecontroller_timetbl"/>
			<enumeration value="flow_intervalcontrollersetpoint_timetbl"/>
			<enumeration value="flow_controllerpidsetpoint_timetbl"/>
			<enumeration value="1dwq_fraction_concentration_timetbl"/>
			<enumeration value="1dwq_boundary_concentration_timetbl"/>
			<enumeration value="2dwq_fraction_concentration_timetbl"/>
			<enumeration value="2dwq_boundary_concentration_timetbl"/>
			<enumeration value="fls_restart"/>
			<enumeration value="1dwq_restart"/>
			<enumeration value="2dwq_restart"/>
			<enumeration value="1d_flow_dam"/>
			<enumeration value="1d_flow_dambreak_hc_boundary"/>
			<enumeration value="1d_flow_dambreak_connectionnode"/>
			<enumeration value="rr_temperature"/>
			<enumeration value="1d_flow_lateral_dat_file"/>
			<enumeration value="rr_boundarytable"/>
			<enumeration value="1d_flow_boundary_dat_file"/>
			<enumeration value="1d_flow_control_def_file"/>
			<enumeration value="1d_flow_profile_def"/>
			<enumeration value="greenhouse_water_usage_file"/>
			<enumeration value="rr_runoff_rnf"/>
			<enumeration value="rr_openwater_target_level_timetable"/>
			<enumeration value="rr_openwater_target_level_timetable_file"/>
			<enumeration value="rr_timecontroller_tbl_file"/>
			<enumeration value="1d_flow_trigger_def_file"/>
			<enumeration value="wq_meteofile"/>
			<enumeration value="1dwq_boundary_concentration_timetbl_file"/>
			<enumeration value="2dwq_boundary_concentration_timetbl_file"/>
			<enumeration value="rr_boundarytable_file"/>
		</restriction>
	</simpleType>
	<complexType name="JobComplexType">
		<sequence>
			<element name="jobName" type="string" minOccurs="0">
				<annotation>
					<documentation>Project Directory, e.g. 'Tutorial.lit'</documentation>
				</annotation>
			</element>
			<element name="storeDir" type="string" minOccurs="0">
				<annotation>
					<documentation>Project Directory, e.g. 'Tutorial.lit'</documentation>
				</annotation>
			</element>
			<element name="parameter" type="sobek:JobParameterClassIndexComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Index of parameter</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="GeneralComplexType">
		<sequence>
			<element name="version" type="float">
				<annotation>
					<documentation>Version of Batch Data Structure</documentation>
				</annotation>
			</element>
			<element name="projectDir" type="sobek:directoryStringType">
				<annotation>
					<documentation>Project Directory, e.g. 'Tutorial.lit'</documentation>
				</annotation>
			</element>
			<element name="caseName" type="string">
				<annotation>
					<documentation>Case name, e.g. 'Example case'</documentation>
				</annotation>
			</element>
			<element name="caseDir" type="sobek:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Case directory of case relative to startup directory from Batch Tool, e.g. 'Tutorial.lit\3'. This directory will automatically updated by the Batch Tool, based on the caseName</documentation>
				</annotation>
			</element>
			<element name="showTablesFlipped" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Option to show all the input and output tables in the user interface flipped (true=horizontal, false = vertical)</documentation>
				</annotation>
			</element>
			<element name="mainDir" type="sobek:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Directory where project directory is located, like 'D:\Sobek'</documentation>
				</annotation>
			</element>
			<element name="netDir" type="sobek:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Location of global SOBEK directory, like 'D:\Sobek' or '\\SobekServer\Sobek210' etc. </documentation>
				</annotation>
			</element>
			<element name="resultsHisFile" type="sobek:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Output filename</documentation>
				</annotation>
			</element>
			<element name="dataPath" type="sobek:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Path where all kind of info files are stored</documentation>
				</annotation>
			</element>
			<element name="resultsSaved" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>If the results have been saved and are availalbe</documentation>
				</annotation>
			</element>
			<element name="parInfoFile" type="sobek:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Filename of file with parameter information</documentation>
				</annotation>
			</element>
			<element name="storeWorkDir" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Option to save the complete working directory</documentation>
				</annotation>
			</element>
			<element name="workDirStored" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Option to determine if working directory has been saved</documentation>
				</annotation>
			</element>
			<element name="storeOutputInOneFile" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Option to save all the output in one output file, which is required for FEWS</documentation>
				</annotation>
			</element>
			<element name="storeFEWSState" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Option to save state information, which is required for FEWS</documentation>
				</annotation>
			</element>
			<element name="fewsDiagnosticsFile" type="sobek:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Filename of FEWS diagnostics file</documentation>
				</annotation>
			</element>
			<element name="clearWorkingDirectories" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>Option to clear working directory after running the simulation</documentation>
				</annotation>
			</element>
			<element name="skipTimeSteps" type="integer" default="0" minOccurs="0">
				<annotation>
					<documentation>Number of timesteps to be skipped when converted FEWS ASCII Meteo file to Bui file.</documentation>
				</annotation>
			</element>
			<element name="useXMLBinFileType" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Option to write Delft-FEWS PI files with binary data section. Improves performence very much, but bad to check the contents of the PI files. Only use this if everything is going right.....</documentation>
				</annotation>
			</element>
			<sequence minOccurs="0">
				<element name="useParsenUpdateMode" type="boolean" default="false">
					<annotation>
						<documentation>Option to let the PARSEN of the Flow modules only update the time series in the NEFIS files. Might improve performence very much, but does not pick up any other updated data from the MDB files.</documentation>
					</annotation>
				</element>
				<element name="parsenMinimumTimeSeriesLength" type="sobek:nonNegativeLong" default="1000">
					<annotation>
						<documentation>If useParsenUpdateMode is TRUE, it is required to define the number of timesteps to generate in the time series tables. Value must be higher than zero.</documentation>
					</annotation>
				</element>
				<element name="parsenSourceFiles" type="sobek:fileStringType">
					<annotation>
						<documentation>If useParsenUpdateMode is TRUE, the source files which should be updated by the PARSEN must be defined here.</documentation>
					</annotation>
				</element>
			</sequence>
			<element name="openMI" type="sobek:OpenMiComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional element to define an additional OpenMI run, after the regular Sobek SIMULATE has run.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OpenMiComplexType">
		<sequence>
			<element name="runOnlyOpenMI" type="boolean" default="false">
				<annotation>
					<documentation>If FALSE, then OpenMI will be run after the normal SOBEK has completed. If TRUE, no SOBEK will be run, but only the OpenMI.</documentation>
				</annotation>
			</element>
			<element name="projectFile" type="sobek:fileStringType">
				<annotation>
					<documentation>Reference to OpenMI *.opr file. The adapter will update the triggerinvoke date (end date of the simulation period).</documentation>
				</annotation>
			</element>
			<element name="taskRun" type="sobek:fileStringType">
				<annotation>
					<documentation>Complete command to run OpenMI from command line, including arguments like reference to opr file</documentation>
				</annotation>
			</element>
			<element name="taskRunDiagnosticsFile" type="sobek:fileStringType" minOccurs="0">
				<annotation>
					<documentation>optional diagnostics file which might be produced by the taskRun</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="MapStackComplexType">
		<sequence>
			<element name="fileName" type="sobek:fileStringType">
				<annotation>
					<documentation>Map Stack XML Filename</documentation>
				</annotation>
			</element>
			<element name="fileMask" type="string">
				<annotation>
					<documentation>Mask for Sobek outputfiles (*.asc) to include in MapStack, like "dm1d????.asc"</documentation>
				</annotation>
			</element>
			<element name="geoDatum" type="string">
				<annotation>
					<documentation>Datum for Map Stack Files</documentation>
				</annotation>
			</element>
			<element name="locationId" type="string">
				<annotation>
					<documentation>Location for Map Stack Files</documentation>
				</annotation>
			</element>
			<element name="parameterId" type="string">
				<annotation>
					<documentation>Parameter for Map Stack Files</documentation>
				</annotation>
			</element>
			<element name="timeStep" type="string">
				<annotation>
					<documentation>Timestep for Map Stack Files</documentation>
				</annotation>
			</element>
			<element name="timeZone" type="sobek:TimeZoneSimpleType" minOccurs="0">
				<annotation>
					<documentation>Time Zone for Map Stack Files</documentation>
				</annotation>
			</element>
			<element name="module" type="sobek:MapstackModulesSimpleType" default="2dflow" minOccurs="0">
				<annotation>
					<documentation>To which 2D module the mapstack relates</documentation>
				</annotation>
			</element>
			<element name="mapStackActive" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Option to write or not to write the mapstack file</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OutputComplexType">
		<choice>
			<sequence>
				<element name="xmlFile" type="string">
					<annotation>
						<documentation>Reference to a PI-XML time series file, of which the headers will be read to identify which series should be read from the model results. In fact the file will be filled with data.</documentation>
					</annotation>
				</element>
				<element name="sobekFile" type="sobek:OutputFileSimpleType">
					<annotation>
						<documentation>Sobek output file</documentation>
					</annotation>
				</element>
			</sequence>
			<sequence>
				<annotation>
					<documentation>Use an explicit definition of one time series in one of the sobek outputfiles. All required time series should be listed individually.</documentation>
				</annotation>
				<element name="description" type="string" default="" minOccurs="0">
					<annotation>
						<documentation>Description of output object</documentation>
					</annotation>
				</element>
				<element name="sobekLocationId" type="string">
					<annotation>
						<documentation>ID of Sobek object</documentation>
					</annotation>
				</element>
				<element name="sobekFile" type="sobek:OutputFileSimpleType">
					<annotation>
						<documentation>Sobek output file</documentation>
					</annotation>
				</element>
				<element name="sobekParameterIndex" type="integer">
					<annotation>
						<documentation>Index Sobek parameter in the sobek output file</documentation>
					</annotation>
				</element>
				<element name="exportLocationId" type="string" minOccurs="0">
					<annotation>
						<documentation>Export ID of Sobek object</documentation>
					</annotation>
				</element>
				<element name="exportParameterId" type="string" minOccurs="0">
					<annotation>
						<documentation>Export ID of Sobek parameter</documentation>
					</annotation>
				</element>
				<element name="function" type="sobek:OutputFileFunctionSimpleType" default="none" minOccurs="0">
					<annotation>
						<documentation>Function to perform on output time series</documentation>
					</annotation>
				</element>
				<element name="functionTimeShift" type="float" default="0" minOccurs="0">
					<annotation>
						<documentation>Timeshift in days, to be used in functions and for which the first values will be ignored</documentation>
					</annotation>
				</element>
				<element name="outputFileFormat" type="sobek:OutputFileFormatSimpleType" default="sobek_his" minOccurs="0">
					<annotation>
						<documentation>Format of output file</documentation>
					</annotation>
				</element>
			</sequence>
		</choice>
	</complexType>
	<complexType name="LongitudinalProfileComplexType">
		<sequence>
			<element name="outputFileName" type="sobek:fileStringType">
				<annotation>
					<documentation>Filename of FEWS PI longitudinal output file</documentation>
				</annotation>
			</element>
			<element name="geoDatum" type="string">
				<annotation>
					<documentation>GeoDatum like 'Rijks Driehoekstelsel'</documentation>
				</annotation>
			</element>
			<element name="timeZone" type="sobek:TimeZoneSimpleType" minOccurs="0">
				<annotation>
					<documentation>Time Zone for Map Stack Files</documentation>
				</annotation>
			</element>
			<element name="profile" type="sobek:ProfileType" maxOccurs="unbounded">
				<annotation>
					<documentation>definition of profiles</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ProfileType">
		<sequence>
			<element name="locationID" type="string">
				<annotation>
					<documentation>Location ID of profile</documentation>
				</annotation>
			</element>
			<element name="parameterID" type="string">
				<annotation>
					<documentation>Parameter ID of profile</documentation>
				</annotation>
			</element>
			<element name="sobekFile" type="sobek:OutputFileSimpleType">
				<annotation>
					<documentation>Sobek output file</documentation>
				</annotation>
			</element>
			<element name="sobekParameterID" type="string">
				<annotation>
					<documentation>Parameter ID of Sobek objects</documentation>
				</annotation>
			</element>
			<element name="sobekPoints" type="sobek:SobekPointsType" maxOccurs="unbounded">
				<annotation>
					<documentation>List of Sobek objects</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SobekPointsType">
		<sequence>
			<element name="sobekLocationID" type="string">
				<annotation>
					<documentation>Location ID of Sobek object</documentation>
				</annotation>
			</element>
			<element name="exportLabel" type="string">
				<annotation>
					<documentation>Label of point in PI file</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="JobParameterClassIndexComplexType">
		<sequence>
			<element name="classIndex" type="long" default="-1">
				<annotation>
					<documentation>Index of class which will be used for this parameter in this job</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="MapstackModulesSimpleType">
		<restriction base="string">
			<enumeration value="2dflow"/>
			<enumeration value="2dwaq"/>
		</restriction>
	</simpleType>
	<simpleType name="OutputFileSimpleType">
		<restriction base="string">
			<enumeration value="calcpoint"/>
			<enumeration value="reachseg"/>
			<enumeration value="struc"/>
			<enumeration value="qwb"/>
			<enumeration value="ow_lvldt"/>
			<enumeration value="upflowdt"/>
			<enumeration value="rtcparal"/>
			<enumeration value="delwaq"/>
			<enumeration value="bndflodt"/>
			<enumeration value="flshis"/>
			<enumeration value="2ddelwaq"/>
			<enumeration value="pump"/>
			<enumeration value="measstat"/>
			<enumeration value="2dwqbal"/>
			<enumeration value="2dwqbo20"/>
			<enumeration value="3bareas"/>
			<enumeration value="3blinks"/>
			<enumeration value="balansdt"/>
			<enumeration value="bndfltot"/>
			<enumeration value="controll"/>
			<enumeration value="flowanal"/>
			<enumeration value="grnstrdt"/>
			<enumeration value="industdt"/>
			<enumeration value="nwrwarea"/>
			<enumeration value="nwrwsys"/>
			<enumeration value="plvstrdt"/>
			<enumeration value="pvstordt"/>
			<enumeration value="qlat"/>
			<enumeration value="reachflw"/>
			<enumeration value="reachvol"/>
			<enumeration value="rrbalans"/>
			<enumeration value="rrrunoff"/>
			<enumeration value="rsegsub"/>
			<enumeration value="rtc3ball"/>
			<enumeration value="rtcsball"/>
			<enumeration value="sacrmnto"/>
			<enumeration value="saltdt"/>
			<enumeration value="sfspills"/>
			<enumeration value="strflodt"/>
			<enumeration value="struc_sf"/>
			<enumeration value="timers"/>
			<enumeration value="triggers"/>
			<enumeration value="wqbal"/>
			<enumeration value="wqbou20"/>
			<enumeration value="wwtpdt"/>
		</restriction>
	</simpleType>
	<simpleType name="OutputFileFunctionSimpleType">
		<restriction base="string">
			<enumeration value="none"/>
			<enumeration value="sum"/>
			<enumeration value="mean"/>
			<enumeration value="max"/>
			<enumeration value="min"/>
		</restriction>
	</simpleType>
	<simpleType name="OutputFileFormatSimpleType">
		<restriction base="string">
			<enumeration value="sobek_his"/>
			<enumeration value="prn_ascii"/>
			<enumeration value="pi_xml"/>
		</restriction>
	</simpleType>
	<complexType name="ProcessingComplexType">
		<sequence>
			<element name="action" type="sobek:ProcessingActionSimpleType"/>
			<element name="source" type="string" minOccurs="0">
				<annotation>
					<documentation>any file or directory pattern and wildcards are allowed</documentation>
				</annotation>
			</element>
			<element name="target" type="string" minOccurs="0">
				<annotation>
					<documentation>not valid for destroy action</documentation>
				</annotation>
			</element>
			<element name="taskRun" type="sobek:fileStringType" minOccurs="0">
				<annotation>
					<documentation>complete command, including arguments</documentation>
				</annotation>
			</element>
			<element name="taskRunDiagnosticsFile" type="sobek:fileStringType" minOccurs="0">
				<annotation>
					<documentation>optional diagnostics file which might be produced by the taskRun</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="StateComplexType">
		<sequence>
			<element name="readLocation" type="string">
				<annotation>
					<documentation>state read location, relative to mainDir or current directory.</documentation>
				</annotation>
			</element>
			<element name="writeLocation" type="string">
				<annotation>
					<documentation>state write location, relative to mainDir or current directory.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="ProcessingActionSimpleType">
		<restriction base="string">
			<enumeration value="copy"/>
			<enumeration value="destroy"/>
			<enumeration value="move"/>
			<enumeration value="run"/>
		</restriction>
	</simpleType>
	<complexType name="SideviewComplexType">
		<sequence>
			<element name="sideViewPath" type="sobek:SideViewPathComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="SideViewPathComplexType">
		<sequence>
			<element name="IDSFile" type="sobek:fileStringType">
				<annotation>
					<documentation>IDS file with SideView path</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="idStringType">
		<restriction base="string">
			<maxLength value="64"/>
		</restriction>
	</simpleType>
	<!-- -->
	<simpleType name="idIntType">
		<restriction base="int"/>
	</simpleType>
	<!--    -->
	<simpleType name="versionStringType">
		<restriction base="string"/>
	</simpleType>
	<!--    -->
	<simpleType name="nameStringType">
		<restriction base="string"/>
	</simpleType>
	<!--    -->
	<simpleType name="directoryStringType">
		<restriction base="string"/>
	</simpleType>
	<!--    -->
	<simpleType name="fileStringType">
		<restriction base="string"/>
	</simpleType>
	<!--    -->
	<simpleType name="nonNegativeDouble">
		<restriction base="double">
			<minInclusive value="0"/>
		</restriction>
	</simpleType>
	<!--    -->
	<simpleType name="nonNegativeLong">
		<restriction base="long">
			<minInclusive value="0"/>
		</restriction>
	</simpleType>
	<!--    -->
	<simpleType name="percentageType">
		<restriction base="integer">
			<minInclusive value="0"/>
			<maxInclusive value="100"/>
		</restriction>
	</simpleType>
	<!---->
	<simpleType name="dateType">
		<restriction base="date">
			<pattern value="\d\d\d\d-\d\d-\d\d"/>
		</restriction>
	</simpleType>
	<!---->
	<simpleType name="timeType">
		<restriction base="time">
			<pattern value="\d\d:\d\d:\d\d"/>
		</restriction>
	</simpleType>
	<!---->
	<simpleType name="TimeZoneSimpleType">
		<annotation>
			<documentation>The timeZone (in decimal hours shift from GMT) e.g. -1.0 or 3.5. If not present GMT is assumed</documentation>
		</annotation>
		<restriction base="double"/>
	</simpleType>
</schema>
