<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="southernTransferFunctions" type="fews:SouthernTransferFunctionsConfigType">
		<annotation>
			<documentation>STF module adapter configuration items</documentation>
		</annotation>
		<!-- generalComplexType -->
	</element>
	<complexType name="SouthernTransferFunctionsFolderNamesComplexType">
		<annotation>
			<documentation>Folder names required by the Southern Transfer Function module</documentation>
		</annotation>
		<sequence>
			<element name="configDir" type="fews:directoryStringType"/>
			<element name="workDir" type="fews:directoryStringType"/>
			<element name="moduleDir" type="fews:directoryStringType"/>
			<element name="importDir" type="fews:directoryStringType"/>
			<element name="exportDir" type="fews:directoryStringType"/>
		</sequence>
	</complexType>
	<complexType name="SouthernTransferFunctionsFileNamesComplexType">
		<annotation>
			<documentation>File names required by the Southern Transfer Function module</documentation>
		</annotation>
		<sequence>
			<element name="configCsvFile" type="fews:fileStringType">
				<annotation>
					<documentation>Configuration file: Holds the information to identify which module to use. Also defines specific details about the lay-out of the inputInpFile. Each STF-Model has its own configuration file.</documentation>
				</annotation>
			</element>
			<element name="parameterCsvFile" type="fews:fileStringType">
				<annotation>
					<documentation>Parameter file: Contains all parameters that may be passed to the Southern Transfer Functions Module. For any given model however, not all parameter need to be supplied.</documentation>
				</annotation>
			</element>
			<element name="ratingsCsvFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Ratings file: (Optional) Is provided for backwards compatibility with the current Transfer function models.</documentation>
				</annotation>
			</element>
			<element name="inputInpFile" type="fews:fileStringType">
				<annotation>
					<documentation>Input data File: Is made up of two sections: the header and the data values, containing both observed data and possibly forecast data. This is a dynamic file and needs to be created upon every run of the Southern Transfer Functions Module.

The Input data file may contain up 10 a maximum of 10 input data series. The maximum length of a data series is 450 data values.

The data values in the input data file are provided in reverse order.</documentation>
				</annotation>
			</element>
			<element name="outputOutFile" type="fews:fileStringType" maxOccurs="2">
				<annotation>
					<documentation>The Output data file is very similar to the Input data file, with an important exception that it may contain a single data series only</documentation>
				</annotation>
			</element>
			<element name="inputXmlFile" type="fews:fileStringType">
				<annotation>
					<documentation>Input Xml File: Contains all time series required by the Southern Transfer Function. Each time series is made up of two sections: the header and the data values. Observed and forecast data are stored in separate time series arrays. This is a dynamic file and needs to be created upon every run of the Southern Transfer Functions Module.
</documentation>
				</annotation>
			</element>
			<element name="outputXmlFile" type="fews:fileStringType">
				<annotation>
					<documentation>Output Xml File: Contains the time series generated by the Southern Transfer Function.</documentation>
				</annotation>
			</element>
			<element name="diagnosticFile" type="fews:fileStringType">
				<annotation>
					<documentation>Diagnostic File: Contains all messages produced by the Southern Transfer Function module adapter components.</documentation>
				</annotation>
			</element>
			<element name="stfLogFile" type="fews:fileStringType">
				<annotation>
					<documentation>STF Module Log File: Contains messages produced by the Southern Transfer Function Module.

The STFPostProcessor is responsible for writing this information to the diagnostics file.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SouthernTransferFunctionsArgumentComplexType">
		<sequence>
			<element name="outputLocationId1" type="fews:idStringType">
				<annotation>
					<documentation>Sensor Id of 1st output time series of Southern Transfer Function module</documentation>
				</annotation>
			</element>
			<element name="outputLocationId2" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Sensor Id of 2nd output time series of Southern Transfer Function module</documentation>
				</annotation>
			</element>
			<element name="inputForecastParameterId1" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Parameter Id of input forecast Rainfall time series of Southern Transfer Function module</documentation>
				</annotation>
			</element>
			<element name="inputHistoricParameterId1" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Parameter Id of input historic Rainfall time series of Southern Transfer Function module</documentation>
				</annotation>
			</element>
			<element name="outputForecastParameterId1" type="fews:idStringType">
				<annotation>
					<documentation>Forecast parameter Id of 1st output time series of Southern Transfer Function module</documentation>
				</annotation>
			</element>
			<element name="outputHistoricParameterId1" type="fews:idStringType">
				<annotation>
					<documentation>Historic parameter Id of 1st output time series of Southern Transfer Function module</documentation>
				</annotation>
			</element>
			<element name="outputForecastParameterId2" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Forecast parameter Id of 2nd output time series of Southern Transfer Function module</documentation>
				</annotation>
			</element>
			<element name="outputHistoricParameterId2" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Historic parameter Id of 2nd output time series of Southern Transfer Function module</documentation>
				</annotation>
			</element>
			<element name="outputDataType1" type="fews:southernTransferFunctionsTimeSeriesType">
				<annotation>
					<documentation>
                        Type of data, either accumulative or instantaneous.
                        For accumulative data the time/date of the event is
                        the moment at which the data was gathered.
                    </documentation>
				</annotation>
			</element>
			<element name="outputDataType2" type="fews:southernTransferFunctionsTimeSeriesType" minOccurs="0">
				<annotation>
					<documentation>
                        Type of data, either accumulative or instantaneous.
                        For accumulative data the time/date of the event is
                        the moment at which the data was gathered.
                    </documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SouthernTransferFunctionsConfigType">
		<sequence>
			<element name="directories" type="fews:SouthernTransferFunctionsFolderNamesComplexType"/>
			<element name="files" type="fews:SouthernTransferFunctionsFileNamesComplexType"/>
			<element name="arguments" type="fews:SouthernTransferFunctionsArgumentComplexType"/>
		</sequence>
	</complexType>
	<simpleType name="southernTransferFunctionsTimeSeriesType">
		<annotation>
			<documentation>Type of data, either accumulative or instantaneous.
                        For accumulative data the time/date of the event is
                        the moment at which the data was gathered.
            </documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="accumulative"/>
			<enumeration value="instantaneous"/>
		</restriction>
	</simpleType>
</schema>
