<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="taskProperties.xsd"/>
	<!--The taskProperties, specified in this file, wil be used in ManualForecastDialog to create the tasks. -->
	<!--Instead of specifying of the taskProperties in the ManualForecastDialog-fields, the user can put the taskProperties-->
	<!--in this file. With the ManualForecast-button 'Run predefined' can the user select this file and run the tasks.-->
	<element name="taskPropertiesPredefined" type="fews:TaskPropertiesPredefinedComplexType">
		<annotation>
			<documentation> Collection of the task properties</documentation>
		</annotation>
	</element>
	<complexType name="TaskPropertiesPredefinedComplexType">
		<choice maxOccurs="unbounded">
			<element name="batchTask" type="fews:BatchTaskComplexType"/>
			<element name="taskProperties" type="fews:TaskPropertiesComplexType"/>
		</choice>
	</complexType>
	<complexType name="BatchTaskComplexType">
		<sequence>
			<element name="period" type="fews:PeriodComplexType"/>
			<choice>
				<element name="interval" type="fews:TimeSpanComplexType"/>
				<element name="intervalTimeStep" type="fews:TimeStepComplexType">
					<annotation>
						<documentation>Since 2019.02, each subsequent batch task has its T0 aligned to the start of the next cardinal timestep.</documentation>
					</annotation>
				</element>
			</choice>
			<element name="overrulingActiveModuleInstanceRuns" type="fews:OverrulingModuleInstanceRunKeyComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Since  2020.02  When any overrulingActiveModuleInstanceRun is configured, then the batch tool will search for an associated run with a T0 before or at the T0 of the batch task. The found module run will be used instead of current module run , and it  also overrules any activeModuleInstanceRun  that has been configured in taskProperties.</documentation>
				</annotation>
			</element>
			<element name="taskProperties" type="fews:TaskPropertiesComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="OverrulingModuleInstanceRunKeyComplexType">
		<sequence>
			<element name="moduleInstanceId" type="fews:idStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>The ID of the referenced module instance</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="workflowId" type="fews:idStringType" use="required"/>
	</complexType>
</schema>
