<?xml version="1.0" encoding="UTF-8"?>
<!--  Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="taskProperties.xsd"/>
	<!-- scheduledTasks -->
	<element name="taskList" type="fews:TaskListComplexType">
		<annotation>
			<documentation>A list of tasks as scheduled on a MC.</documentation>
		</annotation>
	</element>
	<!-- ScheduledTasksComplexType -->
	<complexType name="TaskListComplexType">
		<sequence>
			<element name="task" type="fews:TaskListEntryComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>A single task.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- ScheduledTaskComplexType -->
	<complexType name="TaskListEntryComplexType">
		<sequence>
			<group ref="fews:TaskGroup"/>
		</sequence>
	</complexType>
	<group name="TaskGroup">
		<sequence>
			<element name="taskStatus" type="fews:TaskStatusEnumStringType">
				<annotation>
					<documentation>Task status: pending, suspended, finished</documentation>
				</annotation>
			</element>
			<element name="taskTag" type="fews:maxLength64StringType" minOccurs="0">
				<annotation>
					<documentation>Task tag for events and action mappings</documentation>
				</annotation>
			</element>
			<element name="runOnFailOver" type="boolean">
				<annotation>
					<documentation>Task runs on remote MC on failover</documentation>
				</annotation>
			</element>
			<element name="suspendDutyInFailOver" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Since 2018.02. Only applicable when runOnFailOver is true. FailOver task will only run on duty MC when duty MC is not in failover. The top priority remote MC will run this FailOver task if duty is in failover.</documentation>
				</annotation>
			</element>
			<element name="runOption" type="fews:TaskRunOptionEnumStringType" minOccurs="0"/>
			<element name="taskProperties" type="fews:TaskPropertiesComplexType">
				<annotation>
					<documentation>Task properties</documentation>
				</annotation>
			</element>
		</sequence>
	</group>
	<simpleType name="TaskStatusEnumStringType">
		<annotation>
			<documentation>Enumeration of the valid types for the task status elements.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="P"/>
			<enumeration value="S"/>
			<enumeration value="D"/>
		</restriction>
	</simpleType>
	<simpleType name="TaskRunOptionEnumStringType">
		<annotation>
			<documentation>Enumeration controlling whether this task can or cannot not be run simultaneously.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="all">
				<annotation>
					<documentation>Allowed: Multiple instances of this workflow can run simultaneously.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="allOneAtATime">
				<annotation>
					<documentation>Not allowed: Running (and queued) instances of this workflow prevail.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="allMostRecentOnly">
				<annotation>
					<documentation>
						Not allowed: A running instance of this workflow prevails. Queued instances of this workflow wil be replace by a recent one.
                    </documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>
</schema>
