<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by tacoma (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--Top-level element Declaration -->
	<element name="thresholdOverviewDisplay" type="fews:ThresholdOverviewDisplayComplexType"/>
	<!--ThresholdOverview Display ComplexType-->
	<complexType name="ThresholdOverviewDisplayComplexType">
		<sequence>
			<element name="general" type="fews:ThresholdOverviewDisplayGeneralComplexType">
				<annotation>
					<documentation>Configures the main display (dialog)  </documentation>
				</annotation>
			</element>
			<element name="displayDescriptor" type="fews:ThresholdOverviewDisplayDescriptorComplexType">
				<annotation>
					<documentation>Configures the separate tabs</documentation>
				</annotation>
			</element>
			<element name="inputVariable" type="fews:VariableComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Defines  the time series that wil be used: time series to analyse (on thresholds) and  other time series, that wil be only  displayed. </documentation>
				</annotation>
			</element>
			<element name="columnAttributes" type="fews:ColumnAttributesComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Specifies which input variables should be displayed. Attribute 'analyse' indicates, whether the time series should be analysed (on thresholds). Attribute 'display' indicates whether the time series should be displayed in the tables.</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description with additional comments. This is never used in the code.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="ThresholdOverviewDisplayGeneralComplexType">
		<annotation>
			<documentation>Configures the main display (dialog)  </documentation>
		</annotation>
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="displayName" type="string">
				<annotation>
					<documentation>Title of the dialog</documentation>
				</annotation>
			</element>
			<element name="forecastFilter" type="fews:ForecastFilterComplexType" minOccurs="0">
				<annotation>
					<documentation>Filter to specify which forecast should be displayed in the dialog-combobox</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="ThresholdOverviewDisplayDescriptorComplexType">
		<annotation>
			<documentation>Configures the separate tabs</documentation>
		</annotation>
		<sequence>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description with additional comments. This is never used in the code.</documentation>
				</annotation>
			</element>
			<choice>
				<sequence>
					<element name="forecastTime" type="fews:ForecastTimeComplexType">
						<annotation>
							<documentation>Info to determine and display forecastTime </documentation>
						</annotation>
					</element>
					<element name="attributeNoCrossing" type="fews:ThresholdOverviewAttributeComplexType" minOccurs="0">
						<annotation>
							<documentation>configures how to display no crossings</documentation>
						</annotation>
					</element>
					<element name="attributeMissingValues" type="fews:ThresholdOverviewAttributeComplexType" minOccurs="0">
						<annotation>
							<documentation>configures how to display missing values</documentation>
						</annotation>
					</element>
					<element name="tab1" type="fews:Tab1ComplexType">
						<annotation>
							<documentation>Display of highest alarms</documentation>
						</annotation>
					</element>
					<element name="tab2" type="fews:Tab2ComplexType">
						<annotation>
							<documentation>Display of alarms  per aggregation time step</documentation>
						</annotation>
					</element>
					<element name="tab3" type="fews:Tab3ComplexType">
						<annotation>
							<documentation>Alarm Summary</documentation>
						</annotation>
					</element>
					<element name="tab4" type="fews:Tab4ComplexType" minOccurs="0">
						<annotation>
							<documentation>Details per location. If this element is not specified, no Tab4 wil be created.</documentation>
						</annotation>
					</element>
				</sequence>
				<element name="thresholdCrossingCountsTab" type="fews:ThresholdOverviewCrossingCountsTabComplexType" maxOccurs="unbounded">
					<annotation>
						<documentation>One or more ThresholdCrossingCountsTabs. Each tab shows a table with one row for each location. The table is divided into different sections. Each section displays threshold crossing counts depending on which thresholds have been crossed within a given time period. There is one section for each of the configured time periods.</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<!---->
	<complexType name="Tab1ComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description with additional comments. This is never used in the code.</documentation>
				</annotation>
			</element>
			<element name="tabName" type="string">
				<annotation>
					<documentation>The name to display for this tab.</documentation>
				</annotation>
			</element>
			<choice>
				<element name="columnHeader" type="string">
					<annotation>
						<documentation>This string wil be displayed in column-headers, followed by name of the day and peak time, for instance : (Monday 10:30:00)</documentation>
					</annotation>
				</element>
				<element name="dateTimeFormattingString" type="string">
					<annotation>
						<documentation>This string wil be used to format date/time  in the column-headers. In this case the layout of the headers  is for instance as follows : Mon 04:30 - 16:30</documentation>
					</annotation>
				</element>
			</choice>
			<element name="columnVariable" type="fews:idStringType"/>
			<element name="aggregationTimeStep" type="fews:TimeStepComplexType"/>
			<choice minOccurs="0">
				<element name="displayThresholdName" type="boolean">
					<annotation>
						<documentation>Parameter names are displayed by default</documentation>
					</annotation>
				</element>
				<element name="displayLabel" type="fews:highestThresholdLabelTypeEnumStringType">
					<annotation>
						<documentation>Different options for the text in a table cell to indicate the highest crossed threshold</documentation>
					</annotation>
				</element>
			</choice>
			<element name="columnHeaderToolTipText" type="string" minOccurs="0">
				<annotation>
					<documentation>text that wil appear as the first row in the tool tip text of the each column header.</documentation>
				</annotation>
			</element>
			<element name="columnWidth" type="fews:percentageType" minOccurs="0">
				<annotation>
					<documentation>Data column width as percentage of the ThresholdOverviewDisplay width</documentation>
				</annotation>
			</element>
			<element name="siteColumnWidth" type="fews:percentageType" minOccurs="0">
				<annotation>
					<documentation>Site column width as percentage of the hresholdOverviewDisplay  width</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="Tab2ComplexType">
		<sequence>
			<element name="tabName" type="string">
				<annotation>
					<documentation>The name to display for this tab.</documentation>
				</annotation>
			</element>
			<element name="aggregationTimeStep" type="fews:TimeStepComplexType"/>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description with additional comments. This is never used in the code.</documentation>
				</annotation>
			</element>
			<element name="columnWidth" type="fews:percentageType" minOccurs="0">
				<annotation>
					<documentation>Data column width as percentage of the ThresholdOverviewDisplay width</documentation>
				</annotation>
			</element>
			<element name="siteColumnWidth" type="fews:percentageType" minOccurs="0">
				<annotation>
					<documentation>Site column width as percentage of the hresholdOverviewDisplay  width</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="Tab3ComplexType">
		<sequence>
			<element name="tabName" type="string">
				<annotation>
					<documentation>The name to display for this tab.</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description with additional comments. This is never used in the code.</documentation>
				</annotation>
			</element>
			<choice>
				<element name="invisibleColumn" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>DEPRECATED . Use the elements column*   (e.g. columnLocationId) .  InvisibleColumn is an ption to specify column indices of one or more columns that should not be displayed. The available columns are ( in parenthesis column index)  :  LocationId (0), Location Name(1), Time(2), Parameter(3), Value(4), ThresholdValue(5), Threshold(6), Action(7).</documentation>
					</annotation>
					<simpleType>
						<restriction base="int">
							<minInclusive value="0"/>
							<maxInclusive value="7"/>
						</restriction>
					</simpleType>
				</element>
				<sequence>
					<element name="columnLocationId" type="fews:Tab3ColumnComplexType" minOccurs="0"/>
					<element name="columnLocationName" type="fews:Tab3ColumnComplexType" minOccurs="0"/>
					<element name="columnTime" type="fews:Tab3ColumnComplexType" minOccurs="0"/>
					<element name="columnParameter" type="fews:Tab3ColumnComplexType" minOccurs="0"/>
					<element name="columnValue" type="fews:Tab3ColumnComplexType" minOccurs="0"/>
					<element name="columnThresholdValue" type="fews:Tab3ColumnComplexType" minOccurs="0"/>
					<element name="columnThreshold" type="fews:Tab3ColumnComplexType" minOccurs="0"/>
					<element name="columnAction" type="fews:Tab3ColumnComplexType" minOccurs="0"/>
				</sequence>
			</choice>
		</sequence>
	</complexType>
	<!---->
	<complexType name="Tab4ComplexType">
		<annotation>
			<documentation>This table contains variables with an attribute display="true" in  columnAttributes </documentation>
		</annotation>
		<sequence>
			<element name="tabName" type="string">
				<annotation>
					<documentation>The name to display for this tab.</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description with additional comments. This is never used in the code.</documentation>
				</annotation>
			</element>
			<element name="timeColumnWidth" type="fews:percentageType" minOccurs="0">
				<annotation>
					<documentation>Width of the date/time column as percentage of the ThresholdOverviewDisplay width. NOTE:  widths of the other columns can be configured in columnAttributes </documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="ColumnAttributesComplexType">
		<attribute name="variableId" type="fews:idStringType" use="required"/>
		<attribute name="columnName" type="string" use="required"/>
		<attribute name="columnWidth" type="fews:percentageType">
			<annotation>
				<documentation>column width as percentage of the ThresholdOverviewDisplay width</documentation>
			</annotation>
		</attribute>
		<attribute name="attributeMapId" type="fews:idStringType" use="optional">
			<annotation>
				<documentation>If attributeMapId not specified, then for threshold crossings the information from the thresholdWarningLevels config file is used instead of a valueAttributeMap.</documentation>
			</annotation>
		</attribute>
		<attribute name="analyse" type="boolean" use="optional"/>
		<attribute name="display" type="boolean" use="optional"/>
		<attribute name="userUnit" type="string" use="optional"/>
		<attribute name="multiplier" type="float" use="optional"/>
		<attribute name="divider" type="float" use="optional"/>
		<attribute name="incrementer" type="float" use="optional"/>
	</complexType>
	<!---->
	<complexType name="ForecastTimeComplexType">
		<sequence>
			<element name="columnName" type="string">
				<annotation>
					<documentation>column name in the tables where ForecastTime is displayed</documentation>
				</annotation>
			</element>
			<element name="offsetVariable" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>time offset time series </documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="ForecastFilterComplexType">
		<sequence>
			<element name="workflowId" type="fews:idStringType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!---->
	<complexType name="ThresholdOverviewAttributeComplexType">
		<choice>
			<sequence>
				<element name="attributeMapId" type="fews:idStringType"/>
				<element name="attributeValue" type="float">
					<annotation>
						<documentation>Remark:  use float to specify a value  since ValueAttributeMap accepts only floats as values.</documentation>
					</annotation>
				</element>
			</sequence>
			<sequence>
				<element name="color" type="fews:colorStringType"/>
				<element name="text" type="string"/>
			</sequence>
		</choice>
	</complexType>
	<complexType name="ThresholdOverviewCrossingCountsTabComplexType">
		<sequence>
			<element name="tabName" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>The name to display for this tab.</documentation>
				</annotation>
			</element>
			<element name="thresholdGroupId" type="fews:idStringType">
				<annotation>
					<documentation>Id of a thresholdGroup that is defined in the thresholds configuration file. This tab displays all thresholds in the specified thresholdGroup.</documentation>
				</annotation>
			</element>
			<element name="relativePeriod" type="fews:RelativePeriodComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>One or more relative time periods. This tab has one section for each of the specified time periods. The time periods are relative to the timeZero of the displayed forecast. A relative period can be e.g. -3 to +3 hours or e.g. +3 to +6 hours (relative to timeZero).</documentation>
				</annotation>
			</element>
			<element name="countAllActiveThresholds" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>If true, then this tab counts all thresholds that are active (all thresholds that have been crossed). If false, then for a given location this tab only takes into account the active threshold with the most severe warning level. Default is false.</documentation>
				</annotation>
			</element>
			<element name="countWarningAreas" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>If true, then this tab counts warning areas, as follows. It is possible to define warning areas for a levelThresholdValue in the thresholdValueSets configuration file. If a crossed levelThresholdValue has warning areas defined, then the number of warning areas is counted for that levelThresholdValue. If a crossed levelThresholdValue has no warning areas defined, then a count of 1 is used for that levelThresholdValue. If this option is false, then for each crossed levelThresholdValue a count of 1 is used (i.e. the warning areas are ignored). Default is true.</documentation>
				</annotation>
			</element>
			<element name="multipleTimeSeriesHandlingType" type="fews:multipleTimeSeriesHandlingTypeEnumStringType" minOccurs="0">
				<annotation>
					<documentation>Optional element to choose the way to handle multiple time series. If in the configured inputVariables there are multiple time series available for a given location and period, then the time series for which a thresholdValueSet is defined are collected. The collected time series are handled according to the configured multipleTimeSeriesHandlingType. Currently only "add_crossing_counts" is available. If this element is not defined, then in the case that there are multiple time series available, a warning message is logged and the crossing counts of the time series are added by default.</documentation>
				</annotation>
			</element>
			<element name="noThresholdsDefinedText" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>If specified, then this text is shown in cells that correspond to data for which no thresholds are defined. Default is empty space.</documentation>
				</annotation>
			</element>
			<element name="noDataAvailableText" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>If specified, then this text is shown in cells for which no data is available. Default is "n/a".</documentation>
				</annotation>
			</element>
			<element name="crossingCountZeroText" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>If specified, then this text is shown in cells for which there are no threshold crossings. Default is "-".</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="Tab3ColumnComplexType">
		<attribute name="visible" type="boolean" use="optional" default="true">
			<annotation>
				<documentation>Use this attribute to hide the  the column.  The column is visible by default.</documentation>
			</annotation>
		</attribute>
		<attribute name="width" type="fews:percentageType" use="optional">
			<annotation>
				<documentation>Column width as percentage of the  ThresholdOverviewDisplay width. Is ignored if the column is not visible</documentation>
			</annotation>
		</attribute>
	</complexType>
	<simpleType name="multipleTimeSeriesHandlingTypeEnumStringType">
		<annotation>
			<documentation>Indicates the way to handle multiple time series when there are multiple time series available for a given location and period. Choose "add_crossing_counts" to add the threshold crossing counts of the individual time series.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="add_crossing_counts"/>
		</restriction>
	</simpleType>
	<simpleType name="highestThresholdLabelTypeEnumStringType">
		<annotation>
			<documentation>Different options for the text in a table cell to indicate the highest crossed threshold</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="parameter"/>
			<enumeration value="thresholdName"/>
			<enumeration value="levelThresholdValueLabel"/>
		</restriction>
	</simpleType>
</schema>
