<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews/topology"
		targetNamespace="http://www.wldelft.nl/fews/topology" elementFormDefault="qualified"
		version="1.0">
	<element name="topologyEditorDisplay" type="fews:TopologyEditorDisplayComplexType"/>
	<complexType name="TopologyEditorDisplayComplexType">
		<sequence>
			<element name="overviewPanel" type="fews:OverviewPanelComplexType">
				<annotation>
					<documentation>This panel shows all the features and links in the network. It is possible to group the features by using feature groups.</documentation>
				</annotation>
			</element>
			<element name="actionPanel" type="fews:ActionPanelComplexType"/>
			<element name="mapEditorPanel" type="fews:MapEditorComplexType">
				<annotation>
					<documentation>Configuration options for the map panel in which the network can be drawn.</documentation>
				</annotation>
			</element>
			<element name="featureType" type="fews:FeatureTypeComplexType" maxOccurs="unbounded"/>
			<element name="featureEditor" type="fews:FeatureEditorComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>This element can be used to schedule archive tasks</documentation>
				</annotation>
			</element>
			<element name="customEditor" type="fews:CustomEditorComplexType" minOccurs="0"/>
			<element name="featureTypeGroup" type="fews:FeatureTypeGroupComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="OverviewPanelComplexType">
		<sequence>
			<element name="featureTypeGroups" type="fews:FeatureTypeGroupsComplexType"/>
		</sequence>
	</complexType>
	<complexType name="FeatureTypeGroupsComplexType">
		<sequence>
			<element name="featureTypeGroupId" type="string" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="PropertiesComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description (this is never used in the code).</documentation>
				</annotation>
			</element>
			<choice maxOccurs="unbounded">
				<element name="string" type="fews:StringPropertyComplexType"/>
				<element name="double" type="fews:DoublePropertyComplexType"/>
				<element name="bool" type="fews:BoolPropertyComplexType"/>
			</choice>
		</sequence>
	</complexType>
	<complexType name="DoublePropertyComplexType">
		<attribute name="key" type="string" use="required"/>
		<attribute name="value" type="double" use="required"/>
	</complexType>
	<complexType name="BoolPropertyComplexType">
		<attribute name="key" type="string" use="required"/>
		<attribute name="value" type="boolean" use="required"/>
	</complexType>

	<complexType name="StringPropertyComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description (this is never used in the code).</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="key" type="string" use="required"/>
		<attribute name="value" type="string" use="required"/>
	</complexType>

	<complexType name="MapEditorComplexType">
		<sequence>
			<element name="linkDisplayOptions" type="fews:LinkComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="LinkComplexType">
		<sequence>
			<element name="linkId" type="string"/>
			<element name="color" type="fews:colorEnumStringType"/>
			<element name="lineStyle" type="string" minOccurs="0"/>
			<element name="lineThickness" type="integer" minOccurs="0"/>
		</sequence>
	</complexType>
	<simpleType name="colorEnumStringType">
		<annotation>
			<documentation>see http://www.columbia.edu/~sue/colors-on-white.html</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="alice blue"/>
			<enumeration value="white"/>
			<enumeration value="antique white"/>
			<enumeration value="antique white1"/>
			<enumeration value="antique white2"/>
			<enumeration value="antique white3"/>
			<enumeration value="antique white4"/>
			<enumeration value="aquamarine"/>
			<enumeration value="black"/>
			<enumeration value="blanched almond"/>
			<enumeration value="blue"/>
			<enumeration value="blue violet"/>
			<enumeration value="brown"/>
			<enumeration value="cadet blue"/>
			<enumeration value="cadet blue1"/>
			<enumeration value="cadet blue2"/>
			<enumeration value="cadet blue3"/>
			<enumeration value="cadet blue4"/>
			<enumeration value="coral"/>
			<enumeration value="cornflower blue"/>
			<enumeration value="cyan"/>
			<enumeration value="dark goldenrod"/>
			<enumeration value="dark goldenrod1"/>
			<enumeration value="dark goldenrod2"/>
			<enumeration value="dark goldenrod3"/>
			<enumeration value="dark goldenrod4"/>
			<enumeration value="dark green"/>
			<enumeration value="dark khaki"/>
			<enumeration value="dark olive green"/>
			<enumeration value="dark olive green1"/>
			<enumeration value="dark olive green2"/>
			<enumeration value="dark olive green3"/>
			<enumeration value="dark olive green4"/>
			<enumeration value="dark orange"/>
			<enumeration value="dark orange1"/>
			<enumeration value="dark orange2"/>
			<enumeration value="dark orange3"/>
			<enumeration value="dark orange4"/>
			<enumeration value="dark orchid"/>
			<enumeration value="dark orchid1"/>
			<enumeration value="dark orchid2"/>
			<enumeration value="dark orchid3"/>
			<enumeration value="dark orchid4"/>
			<enumeration value="dark salmon"/>
			<enumeration value="dark sea green"/>
			<enumeration value="dark sea green1"/>
			<enumeration value="dark sea green2"/>
			<enumeration value="dark sea green3"/>
			<enumeration value="dark sea green4"/>
			<enumeration value="dark slate blue"/>
			<enumeration value="dark slate gray"/>
			<enumeration value="dark slate gray1"/>
			<enumeration value="dark slate gray2"/>
			<enumeration value="dark slate gray3"/>
			<enumeration value="dark slate gray4"/>
			<enumeration value="dark turquoise"/>
			<enumeration value="dark violet"/>
			<enumeration value="deep pink"/>
			<enumeration value="deep pink2"/>
			<enumeration value="deep pink3"/>
			<enumeration value="deep pink4"/>
			<enumeration value="deep sky blue"/>
			<enumeration value="deep sky blue2"/>
			<enumeration value="deep sky blue3"/>
			<enumeration value="deep sky blue4"/>
			<enumeration value="dim gray"/>
			<enumeration value="dodger blue"/>
			<enumeration value="dodger blue2"/>
			<enumeration value="dodger blue3"/>
			<enumeration value="dodger blue4"/>
			<enumeration value="firebrick"/>
			<enumeration value="floral white"/>
			<enumeration value="forest green"/>
			<enumeration value="ghost white"/>
			<enumeration value="gold"/>
			<enumeration value="goldenrod"/>
			<enumeration value="gray"/>
			<enumeration value="gray0"/>
			<enumeration value="gray100"/>
			<enumeration value="gray18"/>
			<enumeration value="gray21"/>
			<enumeration value="gray23"/>
			<enumeration value="gray24"/>
			<enumeration value="gray25"/>
			<enumeration value="gray26"/>
			<enumeration value="gray27"/>
			<enumeration value="gray28"/>
			<enumeration value="gray29"/>
			<enumeration value="gray30"/>
			<enumeration value="gray31"/>
			<enumeration value="gray32"/>
			<enumeration value="gray34"/>
			<enumeration value="gray35"/>
			<enumeration value="gray36"/>
			<enumeration value="gray37"/>
			<enumeration value="gray38"/>
			<enumeration value="gray39"/>
			<enumeration value="gray40"/>
			<enumeration value="gray41"/>
			<enumeration value="gray42"/>
			<enumeration value="gray43"/>
			<enumeration value="gray44"/>
			<enumeration value="gray45"/>
			<enumeration value="gray46"/>
			<enumeration value="gray47"/>
			<enumeration value="gray48"/>
			<enumeration value="gray49"/>
			<enumeration value="gray50"/>
			<enumeration value="gray51"/>
			<enumeration value="gray52"/>
			<enumeration value="gray53"/>
			<enumeration value="gray54"/>
			<enumeration value="gray55"/>
			<enumeration value="gray56"/>
			<enumeration value="gray57"/>
			<enumeration value="gray58"/>
			<enumeration value="gray59"/>
			<enumeration value="gray60"/>
			<enumeration value="gray61"/>
			<enumeration value="gray62"/>
			<enumeration value="gray63"/>
			<enumeration value="gray64"/>
			<enumeration value="gray65"/>
			<enumeration value="gray66"/>
			<enumeration value="gray67"/>
			<enumeration value="gray68"/>
			<enumeration value="gray69"/>
			<enumeration value="gray70"/>
			<enumeration value="gray71"/>
			<enumeration value="gray72"/>
			<enumeration value="gray73"/>
			<enumeration value="gray74"/>
			<enumeration value="gray75"/>
			<enumeration value="gray76"/>
			<enumeration value="gray77"/>
			<enumeration value="gray78"/>
			<enumeration value="gray79"/>
			<enumeration value="gray80"/>
			<enumeration value="gray81"/>
			<enumeration value="gray82"/>
			<enumeration value="gray83"/>
			<enumeration value="gray84"/>
			<enumeration value="gray85"/>
			<enumeration value="gray86"/>
			<enumeration value="gray87"/>
			<enumeration value="gray88"/>
			<enumeration value="gray89"/>
			<enumeration value="gray90"/>
			<enumeration value="gray91"/>
			<enumeration value="gray92"/>
			<enumeration value="gray93"/>
			<enumeration value="gray94"/>
			<enumeration value="gray95"/>
			<enumeration value="gray96"/>
			<enumeration value="gray97"/>
			<enumeration value="gray98"/>
			<enumeration value="gray99"/>
			<enumeration value="green"/>
			<enumeration value="green yellow"/>
			<enumeration value="hot pink"/>
			<enumeration value="hot pink1"/>
			<enumeration value="hot pink2"/>
			<enumeration value="hot pink3"/>
			<enumeration value="hot pink4"/>
			<enumeration value="indian red"/>
			<enumeration value="indian red1"/>
			<enumeration value="indian red2"/>
			<enumeration value="indian red3"/>
			<enumeration value="indian red4"/>
			<enumeration value="khaki"/>
			<enumeration value="lavender blush"/>
			<enumeration value="lavender blush2"/>
			<enumeration value="lavender blush3"/>
			<enumeration value="lavender blush4"/>
			<enumeration value="lawn green"/>
			<enumeration value="lemon chiffon"/>
			<enumeration value="lemon chiffon2"/>
			<enumeration value="lemon chiffon3"/>
			<enumeration value="lemon chiffon4"/>
			<enumeration value="light blue"/>
			<enumeration value="light blue1"/>
			<enumeration value="light blue2"/>
			<enumeration value="light blue3"/>
			<enumeration value="light blue4"/>
			<enumeration value="light coral"/>
			<enumeration value="light cyan"/>
			<enumeration value="light cyan2"/>
			<enumeration value="light cyan3"/>
			<enumeration value="light cyan4"/>
			<enumeration value="light goldenrod"/>
			<enumeration value="light goldenrod1"/>
			<enumeration value="light goldenrod2"/>
			<enumeration value="light goldenrod3"/>
			<enumeration value="light goldenrod4"/>
			<enumeration value="light goldenrod yellow"/>
			<enumeration value="light pink"/>
			<enumeration value="light pink1"/>
			<enumeration value="light pink2"/>
			<enumeration value="light pink3"/>
			<enumeration value="light pink4"/>
			<enumeration value="light salmon"/>
			<enumeration value="light salmon2"/>
			<enumeration value="light salmon3"/>
			<enumeration value="light salmon4"/>
			<enumeration value="light sea green"/>
			<enumeration value="light sky blue"/>
			<enumeration value="light sky blue2"/>
			<enumeration value="light sky blue3"/>
			<enumeration value="light sky blue4"/>
			<enumeration value="light slate blue"/>
			<enumeration value="light slate gray"/>
			<enumeration value="light steel blue"/>
			<enumeration value="light steel blue1"/>
			<enumeration value="light steel blue2"/>
			<enumeration value="light steel blue3"/>
			<enumeration value="light steel blue4"/>
			<enumeration value="light yellow"/>
			<enumeration value="light yellow2"/>
			<enumeration value="light yellow3"/>
			<enumeration value="light yellow4"/>
			<enumeration value="lime green"/>
			<enumeration value="magenta"/>
			<enumeration value="maroon"/>
			<enumeration value="medium aquamarine"/>
			<enumeration value="medium blue"/>
			<enumeration value="medium forest green"/>
			<enumeration value="medium goldenrod"/>
			<enumeration value="medium orchid"/>
			<enumeration value="medium orchid1"/>
			<enumeration value="medium orchid2"/>
			<enumeration value="medium orchid3"/>
			<enumeration value="medium orchid4"/>
			<enumeration value="medium purple"/>
			<enumeration value="medium purple1"/>
			<enumeration value="medium purple2"/>
			<enumeration value="medium purple3"/>
			<enumeration value="medium purple4"/>
			<enumeration value="medium sea green"/>
			<enumeration value="medium slate blue"/>
			<enumeration value="medium spring green"/>
			<enumeration value="medium turquoise"/>
			<enumeration value="medium violet red"/>
			<enumeration value="midnight blue"/>
			<enumeration value="mint cream"/>
			<enumeration value="misty rose"/>
			<enumeration value="misty rose2"/>
			<enumeration value="misty rose3"/>
			<enumeration value="misty rose4"/>
			<enumeration value="navajo white"/>
			<enumeration value="navajo white2"/>
			<enumeration value="navajo white3"/>
			<enumeration value="navajo white4"/>
			<enumeration value="navy"/>
			<enumeration value="old lace"/>
			<enumeration value="olive drab"/>
			<enumeration value="olive drab1"/>
			<enumeration value="olive drab2"/>
			<enumeration value="olive drab3"/>
			<enumeration value="olive drab4"/>
			<enumeration value="orange"/>
			<enumeration value="orange red"/>
			<enumeration value="orange red2"/>
			<enumeration value="orange red3"/>
			<enumeration value="orange red4"/>
			<enumeration value="orchid"/>
			<enumeration value="pale goldenrod"/>
			<enumeration value="pale green"/>
			<enumeration value="pale green1"/>
			<enumeration value="pale green2"/>
			<enumeration value="pale green3"/>
			<enumeration value="pale green4"/>
			<enumeration value="pale turquoise"/>
			<enumeration value="pale turquoise1"/>
			<enumeration value="pale turquoise2"/>
			<enumeration value="pale turquoise3"/>
			<enumeration value="pale turquoise4"/>
			<enumeration value="pale violet red"/>
			<enumeration value="pale violet red1"/>
			<enumeration value="pale violet red2"/>
			<enumeration value="pale violet red3"/>
			<enumeration value="pale violet red4"/>
			<enumeration value="papaya whip"/>
			<enumeration value="peach puff"/>
			<enumeration value="peach puff2"/>
			<enumeration value="peach puff3"/>
			<enumeration value="peach puff4"/>
			<enumeration value="pink"/>
			<enumeration value="plum"/>
			<enumeration value="powder blue"/>
			<enumeration value="red"/>
			<enumeration value="rosy brown"/>
			<enumeration value="rosy brown1"/>
			<enumeration value="rosy brown2"/>
			<enumeration value="rosy brown3"/>
			<enumeration value="rosy brown4"/>
			<enumeration value="royal blue"/>
			<enumeration value="royal blue1"/>
			<enumeration value="royal blue2"/>
			<enumeration value="royal blue3"/>
			<enumeration value="royal blue4"/>
			<enumeration value="sandy brown"/>
			<enumeration value="sea green"/>
			<enumeration value="sea green1"/>
			<enumeration value="sea green2"/>
			<enumeration value="sea green3"/>
			<enumeration value="sea green4"/>
			<enumeration value="sienna"/>
			<enumeration value="sky blue"/>
			<enumeration value="sky blue1"/>
			<enumeration value="sky blue2"/>
			<enumeration value="sky blue3"/>
			<enumeration value="sky blue4"/>
			<enumeration value="slate blue"/>
			<enumeration value="slate blue1"/>
			<enumeration value="slate blue2"/>
			<enumeration value="slate blue3"/>
			<enumeration value="slate blue4"/>
			<enumeration value="slate gray"/>
			<enumeration value="slate gray1"/>
			<enumeration value="slate gray2"/>
			<enumeration value="slate gray3"/>
			<enumeration value="slate gray4"/>
			<enumeration value="spring green"/>
			<enumeration value="spring green1"/>
			<enumeration value="spring green2"/>
			<enumeration value="spring green3"/>
			<enumeration value="spring green4"/>
			<enumeration value="steel blue"/>
			<enumeration value="steel blue1"/>
			<enumeration value="steel blue2"/>
			<enumeration value="steel blue3"/>
			<enumeration value="steel blue4"/>
			<enumeration value="tan"/>
			<enumeration value="thistle"/>
			<enumeration value="turquoise"/>
			<enumeration value="violet"/>
			<enumeration value="violet red"/>
			<enumeration value="violet red1"/>
			<enumeration value="violet red2"/>
			<enumeration value="violet red3"/>
			<enumeration value="violet red4"/>
			<enumeration value="wheat"/>
			<enumeration value="yellow"/>
			<enumeration value="yellow green"/>
			<enumeration value="aquamarine1"/>
			<enumeration value="aquamarine2"/>
			<enumeration value="aquamarine3"/>
			<enumeration value="aquamarine4"/>
			<enumeration value="azure"/>
			<enumeration value="azure2"/>
			<enumeration value="azure3"/>
			<enumeration value="azure4"/>
			<enumeration value="beige"/>
			<enumeration value="bisque"/>
			<enumeration value="bisque2"/>
			<enumeration value="bisque3"/>
			<enumeration value="bisque4"/>
			<enumeration value="blue1"/>
			<enumeration value="blue2"/>
			<enumeration value="blue3"/>
			<enumeration value="blue4"/>
			<enumeration value="brown1"/>
			<enumeration value="brown2"/>
			<enumeration value="brown3"/>
			<enumeration value="burlywood1"/>
			<enumeration value="burlywood2"/>
			<enumeration value="burlywood3"/>
			<enumeration value="burlywood4"/>
			<enumeration value="chartreuse"/>
			<enumeration value="chartreuse2"/>
			<enumeration value="chartreuse3"/>
			<enumeration value="chartreuse4"/>
			<enumeration value="chocolate"/>
			<enumeration value="coral2"/>
			<enumeration value="coral3"/>
			<enumeration value="coral4"/>
			<enumeration value="cornsilk"/>
			<enumeration value="cornsilk2"/>
			<enumeration value="cornsilk3"/>
			<enumeration value="cornsilk4"/>
			<enumeration value="cyan1"/>
			<enumeration value="cyan2"/>
			<enumeration value="cyan3"/>
			<enumeration value="cyan4"/>
			<enumeration value="firebrick1"/>
			<enumeration value="firebrick2"/>
			<enumeration value="firebrick3"/>
			<enumeration value="gainsboro"/>
			<enumeration value="gold1"/>
			<enumeration value="gold2"/>
			<enumeration value="gold3"/>
			<enumeration value="gold4"/>
			<enumeration value="goldenrod1"/>
			<enumeration value="goldenrod2"/>
			<enumeration value="goldenrod3"/>
			<enumeration value="goldenrod4"/>
			<enumeration value="green1"/>
			<enumeration value="green2"/>
			<enumeration value="green3"/>
			<enumeration value="green4"/>
			<enumeration value="honeydew"/>
			<enumeration value="honeydew2"/>
			<enumeration value="honeydew3"/>
			<enumeration value="honeydew4"/>
			<enumeration value="ivory"/>
			<enumeration value="ivory2"/>
			<enumeration value="ivory3"/>
			<enumeration value="ivory4"/>
			<enumeration value="khaki1"/>
			<enumeration value="khaki2"/>
			<enumeration value="khaki3"/>
			<enumeration value="khaki4"/>
			<enumeration value="lavender"/>
			<enumeration value="linen"/>
			<enumeration value="magenta1"/>
			<enumeration value="magenta2"/>
			<enumeration value="magenta3"/>
			<enumeration value="maroon1"/>
			<enumeration value="maroon2"/>
			<enumeration value="maroon3"/>
			<enumeration value="maroon4"/>
			<enumeration value="moccasin"/>
			<enumeration value="orange1"/>
			<enumeration value="orange2"/>
			<enumeration value="orange3"/>
			<enumeration value="orange4"/>
			<enumeration value="orchid1"/>
			<enumeration value="orchid2"/>
			<enumeration value="orchid3"/>
			<enumeration value="orchid4"/>
			<enumeration value="peru"/>
			<enumeration value="pink2"/>
			<enumeration value="pink3"/>
			<enumeration value="pink4"/>
			<enumeration value="plum1"/>
			<enumeration value="plum2"/>
			<enumeration value="plum3"/>
			<enumeration value="plum4"/>
			<enumeration value="purple"/>
			<enumeration value="purple1"/>
			<enumeration value="purple2"/>
			<enumeration value="purple3"/>
			<enumeration value="purple4"/>
			<enumeration value="red1"/>
			<enumeration value="red2"/>
			<enumeration value="salmon1"/>
			<enumeration value="salmon2"/>
			<enumeration value="salmon3"/>
			<enumeration value="salmon4"/>
			<enumeration value="seashell"/>
			<enumeration value="seashell2"/>
			<enumeration value="seashell3"/>
			<enumeration value="seashell4"/>
			<enumeration value="sienna1"/>
			<enumeration value="sienna2"/>
			<enumeration value="sienna3"/>
			<enumeration value="sienna4"/>
			<enumeration value="snow"/>
			<enumeration value="snow2"/>
			<enumeration value="snow3"/>
			<enumeration value="snow4"/>
			<enumeration value="tan1"/>
			<enumeration value="tan2"/>
			<enumeration value="thistle1"/>
			<enumeration value="thistle2"/>
			<enumeration value="thistle3"/>
			<enumeration value="thistle4"/>
			<enumeration value="tomato"/>
			<enumeration value="tomato2"/>
			<enumeration value="tomato3"/>
			<enumeration value="turquoise1"/>
			<enumeration value="turquoise2"/>
			<enumeration value="turquoise3"/>
			<enumeration value="turquoise4"/>
			<enumeration value="wheat1"/>
			<enumeration value="wheat2"/>
			<enumeration value="wheat3"/>
			<enumeration value="wheat4"/>
			<enumeration value="yellow1"/>
		</restriction>
	</simpleType>
	<complexType name="ActionPanelComplexType">
		<sequence>
			<element name="actionPanelTab" type="fews:ActionPanelTabComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="ActionPanelTabComplexType">
		<sequence>
			<element name="featureTypeGroups" type="fews:FeatureTypeGroupsComplexType"/>
		</sequence>
		<attribute name="id" type="string" use="required"/>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="FeatureTypeComplexType">
		<attribute name="id" type="string" use="required"/>
		<attribute name="name" type="string" use="required"/>
		<attribute name="type" type="fews:nodeTypeEnumStringType" use="required"/>
		<attribute name="hasProperties" type="boolean" default="true"/>
	</complexType>
	<complexType name="FeatureEditorComplexType">
		<sequence>
			<sequence>
				<element name="featureType" type="string">
					<annotation>
						<documentation>The type of the feature</documentation>
					</annotation>
				</element>
				<element name="propertyEditorTab" type="fews:PropertyTabComplexType" maxOccurs="unbounded">
					<annotation>
						<appinfo>The table editor (property groups en properties) can be configured with this option.</appinfo>
					</annotation>
				</element>
			</sequence>
		</sequence>
	</complexType>
	<complexType name="CustomEditorComplexType">
		<sequence>
			<element name="sourcePriorityEditor" type="fews:SourcePriorityPanelComplexType"/>
		</sequence>
	</complexType>
	<complexType name="PropertyTabComplexType">
		<sequence>
			<element name="propertyGroup" type="fews:PropertyGroupComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Properties which belong to the same group will shown together in the display.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string">
			<annotation>
				<documentation>The properties will have an combined header with this configured name in the table.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="TablePropertyComplexType">
		<sequence>
			<element name="columnProperty" type="fews:PropertyComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>A single property can be defined with this option. The id is the key of the property. The name will be used for display purposes.</documentation>
				</annotation>
			</element>
			<element name="showGraph" type="boolean" minOccurs="0" default="true">
				<annotation>
					<documentation>Optional property to indicate if the graph should be shown or not</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"/>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="PropertyGroupComplexType">
		<sequence>
			<choice maxOccurs="unbounded">
				<element name="property" type="fews:PropertyComplexType">
					<annotation>
						<documentation>A single property can be defined with this option. The id is the key of the property. The name will be used for display purposes.</documentation>
					</annotation>
				</element>
				<element name="tableProperty" type="fews:TablePropertyComplexType">
					<annotation>
						<documentation>Properties which belong to the same group will shown together in the display.</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="PropertyComplexType">
		<attribute name="id" type="string" use="required"/>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="FeatureTypeGroupComplexType">
		<sequence>
			<element name="featureTypeId" type="string" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="string" use="required"/>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<simpleType name="nodeTypeEnumStringType">
		<restriction base="string">
			<enumeration value="node"/>
			<enumeration value="link"/>
		</restriction>
	</simpleType>
	<complexType name="SourcePriorityPanelComplexType">
		<sequence>
			<choice>
				<element name="featureType" type="string" maxOccurs="unbounded"/>
				<element name="featureTypeGroup" type="string" />
			</choice>
			<element name="tabName" type="string"/>
			<element name="workDirectory" type="string"/>
			<element name="binDirectory" type="string"/>
		</sequence>
	</complexType>
</schema>
