<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by tacoma (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="trendDisplay" type="fews:TrendDisplayComplexType"/>
	<!---->
	<complexType name="TrendDisplayComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="general" type="fews:TrendDisplayGeneralComplexType"/>
			<element name="group" type="fews:TrendGroupComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!---->
	<complexType name="TrendDisplayGeneralComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="displayName" type="string">
				<annotation>
					<documentation>Appears in the title bar of the dialog</documentation>
				</annotation>
			</element>
			<element name="agoPeriodLength" type="fews:RelativeTimeComplexType">
				<annotation>
					<documentation>Specifies the length of the period back in the time in relation to the time of the latest valid value. This is a default value for all groups. May be overwritten in separates groups</documentation>
				</annotation>
			</element>
			<element name="thresholdId" type="fews:idStringType"/>
		</sequence>
	</complexType>
	<!--    -->
	<complexType name="TrendGroupComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<choice>
				<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType" maxOccurs="unbounded">
					<annotation>
						<documentation>Specifies time series for the group</documentation>
					</annotation>
				</element>
				<element name="child" type="fews:TrendGroupChildComplexType" maxOccurs="unbounded">
					<annotation>
						<documentation>Specifies the Id of a subgroup</documentation>
					</annotation>
				</element>
			</choice>
			<element name="thresholdId" type="fews:idStringType" minOccurs="0"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nameStringType" use="optional"/>
	</complexType>
	<!---->
	<complexType name="TrendGroupChildComplexType">
		<annotation>
			<documentation>Specifies the Id of the subgroup</documentation>
		</annotation>
		<attribute name="foreignKey" type="fews:idStringType" use="required"/>
	</complexType>
</schema>
