<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="taskProperties.xsd"/>
	<include schemaLocation="whatIfScenario.xsd"/>
	<element name="whatIfScenarioFilters" type="fews:WhatIfScenarioFiltersComplexType"/>
	<complexType name="WhatIfScenarioFiltersComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="propertiesTabVisible" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Since 2016.01  If set to true, properties tab will become visible. The default value is false</documentation>
				</annotation>
			</element>
			<element name="enumerations" type="fews:WhatIfScenarioFiltersEnumerationsComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2015.02. Optional. One or more definitions of enumerations that can be used as selectable values for properties.</documentation>
				</annotation>
			</element>
			<element name="properties" type="fews:WhatIfScenarioFiltersPropertiesComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2015.02. Optional. One or more properties for which the values can be selected in the properties tab in the GUI. This currently only works for the WhatIfScenarioDialog. This only supports properties that can be referenced in nested workflow files and module config files between $ signs (e.g. $key$). In a what if scenario the values of these properties will be replaced with the values selected by the user. The property $MODULE_INSTANCE_ID$ is added automatically and should not be replaced in a what-if scenario. This only supports properties of type string.</documentation>
				</annotation>
			</element>
			<element name="variableSets" type="fews:VariableSetsComplexType" minOccurs="0"/>
			<element name="configFiles" type="fews:ConfigComplexType" minOccurs="0"/>
			<element name="relativeT0DateFormat" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Since 2015.01: Relative T0 date format can be used to display times in the User Defined Profile editor using a relative date format where dates are displayed relative to T0.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
		<attribute name="id" type="fews:idStringType" use="optional"/>
		<attribute name="name" type="fews:nameStringType" use="required"/>
	</complexType>
	<complexType name="VariableSetsComplexType">
		<sequence>
			<element name="variable" type="fews:VariableComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="WhatIfScenarioFiltersEnumerationsComplexType">
		<sequence>
			<element name="stringEnumeration" type="fews:WhatIfScenarioFiltersStringEnumerationComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>One or more definitions of enumerations of strings.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="WhatIfScenarioFiltersStringEnumerationComplexType">
		<sequence>
			<element name="string" type="string" maxOccurs="unbounded">
				<annotation>
					<documentation>One or more string values.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier for this enumeration. Use this identifier to refer to this enumeration in a property.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="WhatIfScenarioFiltersPropertiesComplexType">
		<sequence>
			<element name="property" type="fews:WhatIfScenarioFiltersPropertyComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>One or more properties. For each property specify the values that can be selected by the user. This only supports properties of type string.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="WhatIfScenarioFiltersPropertyComplexType">
		<sequence>
			<element name="enumerationId" type="fews:idStringType">
				<annotation>
					<documentation>Identifier of an enumeration. The values of the enumeration will be the values that the user is allowed to select for this property. Enumerations can be defined at the start of this config file. This only supports properties of type string.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="key" type="fews:nonEmptyStringType" use="required">
			<annotation>
				<documentation>The key for this property.</documentation>
			</annotation>
		</attribute>
	</complexType>
</schema>
