<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by tacoma (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="annotationsDisplay" type="fews:AnnotationsDisplayComplexType"/>
	<complexType name="AnnotationsDisplayComplexType">
		<sequence>
			<element name="valueTypes" type="fews:AnnotationDisplayValueTypesComplexType"/>
			<element name="properties" type="fews:AnnotationDisplayPropertiesComplexType"/>
		</sequence>
	</complexType>
	<complexType name="AnnotationDisplayValueTypesComplexType"></complexType>
	<complexType name="AnnotationDisplayPropertiesComplexType"></complexType>
</schema>