<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews/archive"
		targetNamespace="http://www.wldelft.nl/fews/archive" elementFormDefault="qualified"
		attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="archive_sharedTypes.xsd"/>
	<element name="archiveAmalgamate" type="fews:ArchiveAmalgamateComplexType"/>
	<complexType name="ArchiveAmalgamateComplexType">
		<sequence>
			<element name="allowMerge" type="boolean" default="false" minOccurs="0"/>
			<element name="area" type="fews:AmalgamateAreaComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="AmalgamateAreaComplexType">
		<sequence>
			<element name="areaId" type="fews:idStringType"/>
			<element name="lengthAmalgamatePeriod" type="fews:archiveAmalgamateLength"/>
		</sequence>
	</complexType>
	<simpleType name="archiveAmalgamateLength">
		<restriction base="integer">
			<minExclusive value="0"/>
			<maxInclusive value="31"/>
		</restriction>
	</simpleType>
</schema>