<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Frederik van den Broek (WL|Delft Hydraulics) -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by rooij_e (WL | Delft Hydraulics) -->
<!-- todo OA remove task properties, task properties are no longer needed because the task properties from a task are immutable -->
<!--  Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--ArchiveMetaData-->
	<element name="archiveMetaData" type="fews:ArchiveMetaDataComplexType">
		<annotation>
			<documentation>The archive properties of a particular task run.</documentation>
		</annotation>
	</element>
	<!-- ArchiveMetaFDataComplexType -->
	<complexType name="ArchiveMetaDataComplexType">
		<sequence>
			<element name="taskRunId" type="fews:idStringType">
				<annotation>
					<documentation>The ID of the task run.</documentation>
				</annotation>
			</element>
			<element name="dispatchTime" type="fews:DateTimeComplexType">
				<annotation>
					<documentation>Dispatch time of the taskRun to which this data belongs.</documentation>
				</annotation>
			</element>
			<element name="usedStates" minOccurs="0">
				<annotation>
					<documentation>All module instance (warm)states used during this TaskRun.</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="warmState" type="fews:WarmStateKeyComplexType" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="usedTimeSeriesBlobs" minOccurs="0">
				<annotation>
					<documentation>All time series blobs used or generated during this TaskRun.</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="timeSeriesBlob" type="fews:TimeSeriesBlobKeyComplexType" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="usedTaskRuns" minOccurs="0">
				<annotation>
					<documentation>All TaskRuns used by this TaskRun</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="taskRun" type="fews:TaskRunKeyComplexType" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="usedTasks" minOccurs="0">
				<annotation>
					<documentation>Deprecated not used any more</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="task" type="fews:TaskKeyComplexType" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="usedModuleInstanceRuns" minOccurs="0">
				<annotation>
					<documentation>All ModuleInstance runs used during this TaskRun</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="moduleInstanceRun" type="fews:ModuleInstanceRunKeyComplexType" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="usedFewsSessions" minOccurs="0">
				<annotation>
					<documentation>Deprecated no longer used</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="fewsSession" type="fews:FewsSessionKeyComplexType" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="usedWhatIfScenarios" minOccurs="0">
				<complexType>
					<annotation>
						<documentation>Deprecated not used any more</documentation>
					</annotation>
					<sequence>
						<element name="whatIfScenario" type="fews:WhatIfScenarioKeyComplexType" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
            <element name="usedModifierDescriptors" minOccurs="0">
                <annotation>
                    <documentation>All ModifierDescriptors runs used during this TaskRun</documentation>
                </annotation>
                <complexType>
                    <sequence>
                        <element name="modifierDescriptor" type="fews:ModifierDescriptorKeyComplexType" minOccurs="0" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
            <!-- TEMPORARILY DISABLED -->
			<!-- element name="moduleInstanceRunProperties" type="fews:ModuleInstanceRunComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>The run of a particular module instance.</documentation>
				</annotation>
			</element -->
			<!-- element name="activeConfigFiles" type="fews:ActiveConfigFilesComplexType">
				<annotation>
					<documentation>All active configuration files being used in this task run.</documentation>
				</annotation>
			</element -->
			<element name="latestAvailableData" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="latestAvailableTime" type="fews:DateTimeComplexType">
							<annotation>
								<documentation>Latest creation time available to forecasting shell server defined by attribute 'name'. This information is logged for every FSS, before the start of a forecast run.</documentation>
							</annotation>
						</element>
					</sequence>
					<attribute name="name" type="fews:idStringType" use="required">
						<annotation>
							<documentation>Name of forecasting shell server for which time is valid.</documentation>
						</annotation>
					</attribute>
				</complexType>
			</element>
			<element name="usedJre" type="fews:versionStringType" minOccurs="0">
				<annotation>
					<documentation>The JRE version that was used to execute this TaskRun</documentation>
				</annotation>
			</element>
			<element name="usedBuild" type="fews:versionStringType" minOccurs="0">
				<annotation>
					<documentation>The build number of the FEWS build that was used to execute this TaskRun</documentation>
				</annotation>
			</element>
			<element name="usedConfigurationVersion" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>The revision number of the Regional Configuration that was active during this TaskRun</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
