<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews"
        xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"
        version="1.1">
    <include schemaLocation="sharedTypes.xsd"/>
    <element name="chartLayer" type="fews:ChartLayerComplexType">
        <annotation>
            <documentation>Specified the configuration that is used in the chart layer</documentation>
        </annotation>
    </element>
    <complexType name="ChartLayerComplexType">
        <sequence>
            <element name="refreshInterval" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Refresh interval is obsolete. Since 2011.01 chart layer is refreshed instantly</documentation>
				</annotation>
			</element>
            <group ref="fews:ScaleRange"/>
            <element name="chartFormat" type="fews:ChartFormatComplexType" minOccurs="0" maxOccurs="unbounded"/>
            <element name="originalMapSize" type="fews:PixelDimension" minOccurs="0">
                <annotation>
                    <documentation>The width and height of the map when you designed this chart layer. Use F12 export - save current visible map as png file. The tool tip on the png in the Windows file explorer gives you the width/height</documentation>
                </annotation>
            </element>
            <element name="chart" type="fews:ChartLayerChartComplexType" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="version" type="fews:versionStringType" use="required" fixed="1.0"/>
    </complexType>

    <complexType name="ChartLayerChartComplexType">
        <complexContent>
            <extension base="fews:ChartComplexType">
                <sequence>
                    <element name="locationId" type="fews:idStringType"/>
                    <element name="xOffSetPixels" type="integer"/>
                    <element name="yOffSetPixels" type="integer"/>
                    <element name="inputVariable" type="fews:VariableComplexType" minOccurs="0" maxOccurs="unbounded"/>
                    <element name="filterId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded">
                        <annotation>
                            <documentation>The chart is visible when one of the specified filters is selected,
                                when no filter is specified the chart is always visible</documentation>
                        </annotation>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

</schema>
