<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="schemes" type="fews:ColorSchemesComplexType"/>
	<complexType name="ColorSchemesComplexType">
		<sequence>
			<element name="scheme" type="fews:ColorSchemeComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="optional" fixed="1.0"/>
	</complexType>
	<complexType name="ColorSchemeComplexType">
		<sequence>
			<element name="predefinedColorKeys" type="fews:PredefinedColorKeysComplexType"/>
			<element name="customColorKeys" type="fews:CustomColorKeysComplexType" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="fews:nameStringType" use="required"/>
	</complexType>
	<complexType name="PredefinedColorKeysComplexType">
		<sequence>
			<element name="alertYellow" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFDC23</documentation>
				</annotation>
			</element>
			<element name="alternateRow" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF, color of the alternate rows in tables. The colors of the table rows will alternate between this color and tableCellBackground. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="base" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 33628C.  Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="blankIcon" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000.  Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="blueGray" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = A9B0BE.  Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="border" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = C0C0C0, color of the borders around different gui elements</documentation>
				</annotation>
			</element>
			<element name="borderActive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = B4B4B4. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="borderButton" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 083F6B. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="borderDragging" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 646464. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="borderHighlight" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="borderInactive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = F4F7FC. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="buttonPressed" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = C0DCF3, since 2019.02. Color used as background color for pressed buttons. Default color = CFCFCF.</documentation>
				</annotation>
			</element>
			<element name="buttonRollover" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = D8E6F2, since 2019.02. Color used as background color for buttons when the mouse hovers over them. Default color = DEDEDE.</documentation>
				</annotation>
			</element>
			<element name="caret" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="cellCheckboxBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="chartBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="chartPanelValueMarker" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="classBreakDefaultGrad1" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="classBreakDefaultGrad2" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="colorChooser" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="control" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = F0F0F0. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="correlationItem" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = A0A0A0</documentation>
				</annotation>
			</element>
			<element name="correlationItemLabel" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FEFFDB</documentation>
				</annotation>
			</element>
			<element name="defaultArrow" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="defaultLine" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="defaultMapBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="desktop" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = ABABAB. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="desktopBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>Default color = FFFFFF, controls the background color of "desktop" in the dashboard panel, i.e., the area in which dashboard frames can be placed.. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="doubleMassCurveValueMarker" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 404040</documentation>
				</annotation>
			</element>
			<element name="dropLine" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 73A4D1. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="dummy" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="errorMessageForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="etchedBorderHighlight" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="etchedBorderShadow" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 868686. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="etchedSelectionBorderHighlight" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="etchedSelectionBorderShadow" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 868686. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="flagBarBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = C0C0C0</documentation>
				</annotation>
			</element>
			<element name="floatingForeground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 404040. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="flowDomainMarker" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFAF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="forecastListBoxTitle" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="generalBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = F0F0F0</documentation>
				</annotation>
			</element>
			<element name="generalBackgroundActive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 99B4D1. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalBackgroundDisabled" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = F0F0F0</documentation>
				</annotation>
			</element>
			<element name="generalBackgroundInactive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalBackgroundSelected" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = F0F0F0</documentation>
				</annotation>
			</element>
			<element name="generalDisabled" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = D6D9DF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalDragging" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 404040. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalFocus" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="generalForegroundDisabled" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 6D6D6D. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalForegroundDocking" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FF0000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalForegroundInactive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 6D6D6D. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalHighlight" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalLight" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = E3E3E3</documentation>
				</annotation>
			</element>
			<element name="generalShadow" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = A0A0A0. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalShadowDark" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 696969. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="generalShadowDisabled" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="green" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = B0B332. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="gridContour" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="gridDisplayCompassRoseBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="gridDisplayCompassRoseLeftHalf" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="gridDisplayCompassRoseRightHalf" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="gridDisplayComponentBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="gridDisplayDefaultCircleBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="gridDisplayEmptyImage" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="gridDisplayScaleBarSegmentEven" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="gridDisplayScaleBarSegmentOdd" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="gridDisplaySelectionForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FF00</documentation>
				</annotation>
			</element>
			<element name="gridDisplaySelectionRectangle" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 404040</documentation>
				</annotation>
			</element>
			<element name="gridDisplaySketchPoint" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="gridDisplayXorAlternation" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = C0C0C0</documentation>
				</annotation>
			</element>
			<element name="gridExcluded1" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000ff</documentation>
				</annotation>
			</element>
			<element name="gridExcluded2" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = ff0000</documentation>
				</annotation>
			</element>
			<element name="gridExcluded3" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 43b7ba</documentation>
				</annotation>
			</element>
			<element name="gridLines" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = C0C0C0</documentation>
				</annotation>
			</element>
			<element name="hash" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 808080. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="highlightedDateTick" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="highlightedDateTickMarker" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="iconLine" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 030303</documentation>
				</annotation>
			</element>
			<element name="info" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = F2F2BD. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="infoBlue" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 2F5CB4</documentation>
				</annotation>
			</element>
			<element name="labelBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="labelForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="locationResultsBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 404040</documentation>
				</annotation>
			</element>
			<element name="longitudinalValueMarker" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = f87a17</documentation>
				</annotation>
			</element>
			<element name="lookupRuleDefault" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00ffff</documentation>
				</annotation>
			</element>
			<element name="mapLabelBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 78FFFF</documentation>
				</annotation>
			</element>
			<element name="mapLabelCurrentTime" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="mapSelectionHighlight" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 404040</documentation>
				</annotation>
			</element>
			<element name="mapSelectionHighlightAlternate" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = C0C0C0</documentation>
				</annotation>
			</element>
			<element name="mapTrackCurrentTime" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFF00</documentation>
				</annotation>
			</element>
			<element name="mapTrackLine" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="menu" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = E3E3E3. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="modelStatusFailedBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FF0000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="modelStatusRunningBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FF00FF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="modelStatusSuccessfulBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 00FF00. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="modelUserProfileBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 00FF00. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="modelValueSetBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 00FF00. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="modelValueTunedBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 87CEFA. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="modifierLocked" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 808080</documentation>
				</annotation>
			</element>
			<element name="modifierPartlyActive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 0xFFFF00</documentation>
				</annotation>
			</element>
			<element name="orange" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = BF6204. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="originalValueMarker" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="panelBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="pcaValueMarker" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="percentageDomainMarker" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="plotAnnotationForeground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="plotAxisLabel" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="plotBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="plotGridLine" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2024.01. default color = C0C0C0</documentation>
				</annotation>
			</element>
  		    <element name="plotLabel" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="plotLegendLabel" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="plotLegendLabelSelected" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="plotLongitudinalMaximum" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FF0000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="plotLongitudinalMinimum" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 00FF00. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="plotLongitudinalRiverBed" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 980517. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="plotLongitudinalValue" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 0000FF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="plotLongitudinalValueMarker" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = f87a17. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="plotSlideBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 404040</documentation>
				</annotation>
			</element>
			<element name="plotTickLabel" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="plotTickMark" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="plotUnitInside" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="plotUnitOutside" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="plotWhatIfAxisLabel" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="plotWhatIfTickLabel" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="plotWhatIfTickMark" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="polygon" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FFFF</documentation>
				</annotation>
			</element>
			<element name="polygonSelected" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 500000</documentation>
				</annotation>
			</element>
			<element name="rainDomainMarker" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFF00. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="red" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = A92E22</documentation>
				</annotation>
			</element>
			<element name="scalarPlotMarker" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="scatterPlotSelectionBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="scenarioEditorDialogBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="scenarioEditorTitleBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = C0C0C0</documentation>
				</annotation>
			</element>
			<element name="scrollbar" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = CDD0D5. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="selectionBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 3399FF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="selectionBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="selectionBorderBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 808080. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="selectionForeground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="separatorForeground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = C0C0C0, color of the separators in menus and toolbars. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="shapeDefaultBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="shapeFillColor" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="shapeIconFill" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="shapeIconLine" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="sliderPanelBackgroundChanged" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFF00</documentation>
				</annotation>
			</element>
			<element name="sliderThumb" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 3672D0, since 2019.02. color of the thumb on sliders such as the time sliders and aggregation slider in the spatial display.</documentation>
				</annotation>
			</element>
			<element name="sortIcon" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = A0A0A0. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="statisticsXyEditable" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FFFF</documentation>
				</annotation>
			</element>
			<element name="statisticsXyNonEditable" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = E6E6E6</documentation>
				</annotation>
			</element>
			<element name="statusBarCapacity" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = addfff</documentation>
				</annotation>
			</element>
			<element name="statusBarCapacityWarning" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="statusBarConnecting" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = F79F81</documentation>
				</annotation>
			</element>
			<element name="statusBarFailover" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFC800</documentation>
				</annotation>
			</element>
			<element name="statusBarForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="statusBarIndexingBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF00FF</documentation>
				</annotation>
			</element>
			<element name="statusBarLabelHoverColor" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="statusBarLoggedOff" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="statusBarLoggedOn" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = D0F5A9</documentation>
				</annotation>
			</element>
			<element name="statusBarOkForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="statusBarProgress" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = addfff</documentation>
				</annotation>
			</element>
			<element name="statusBarFinished" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 5060b0</documentation>
				</annotation>
			</element>
			<element name="statusBarProgressOc" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FF0000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="statusBarRollingBarrel" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = f75431</documentation>
				</annotation>
			</element>
			<element name="statusBarSynchronising" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = F5A9F2</documentation>
				</annotation>
			</element>
			<element name="statusBarTimePausedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = F79F81</documentation>
				</annotation>
			</element>
			<element name="tableBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="tableCellBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="tableCellBoxWhiskerCategoryBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FFFF</documentation>
				</annotation>
			</element>
			<element name="tableCellBoxWhiskerValuesBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="tableCellCalibrationBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="tableCellCalibrationBackgroundChanged" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFA4</documentation>
				</annotation>
			</element>
			<element name="tableCellCalibrationForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="tableCellCalibrationForegroundSelected" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="tableCellChangedAndCommitted" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = deebdc</documentation>
				</annotation>
			</element>
			<element name="tableCellChangedAndUncommitted" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = e77471</documentation>
				</annotation>
			</element>
			<element name="tableCellChangedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFD8</documentation>
				</annotation>
			</element>
			<element name="tableCellChangedForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="tableCellColorPendingBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = C0C0C0</documentation>
				</annotation>
			</element>
			<element name="tableCellColorUnknownBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = ff00ff</documentation>
				</annotation>
			</element>
			<element name="tableCellColumnHeaderBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = C0C0C0</documentation>
				</annotation>
			</element>
			<element name="tableCellColumnHeaderForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="tableCellColumnHeaderIdForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="tableCellConfigActiveBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFF00. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="tableCellConfigActiveForeground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="tableCellConfigInactiveBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="tableCellConfigInactiveForeground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="tableCellDashedBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="tableCellDateBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FFFF</documentation>
				</annotation>
			</element>
			<element name="tableCellDateBeforeTzeroBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00C8FF</documentation>
				</annotation>
			</element>
			<element name="tableCellDateMidnightBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FF00</documentation>
				</annotation>
			</element>
			<element name="tableCellDateText" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="tableCellDateTextInvalidDate" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="tableCellDisabledBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 808080</documentation>
				</annotation>
			</element>
			<element name="tableCellEditableBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="tableCellEditableMissingBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = fee8c6</documentation>
				</annotation>
			</element>
			<element name="tableCellFilteredBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2019.02, default color = addfff, in some tables a cell can be double clicked to filter on that cell's value. If this has been done for a cell, that cell's background will have this color. Note that the time series table in the database viewer has a separate filtered color called timeSeriesFilteredBackground.</documentation>
				</annotation>
			</element>
			<element name="tableCellForecastExpiredForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="tableCellForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="tableCellHeaderBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = ece5c6</documentation>
				</annotation>
			</element>
			<element name="tableCellLineBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="tableCellNeverImportedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="tableCellNotEditableBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = E6E6E6</documentation>
				</annotation>
			</element>
			<element name="tableCellRunInfoRowSelectedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00ff00</documentation>
				</annotation>
			</element>
			<element name="tableCellRunningBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFD8</documentation>
				</annotation>
			</element>
			<element name="tableCellSavedForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF00FF</documentation>
				</annotation>
			</element>
			<element name="tableCellSelectedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = C0C0C0</documentation>
				</annotation>
			</element>
			<element name="tableCellSelectedForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="tableCellSelectionBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="tableCellTimeSeriesBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="tableRowTabBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="text" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="textBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="textBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="textDisabled" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 8E8F91</documentation>
				</annotation>
			</element>
			<element name="textForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 232324</documentation>
				</annotation>
			</element>
			<element name="textForegroundDisabled" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 8E8F91. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="textHighlight" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 39698A. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="textSelected" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="thresholdAttributeMissingValue" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFC8</documentation>
				</annotation>
			</element>
			<element name="thresholdAttributeNoCrossing" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FF00</documentation>
				</annotation>
			</element>
			<element name="thresholdDefaultClassBreak" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="thresholdSkillScoreMatching" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FF00</documentation>
				</annotation>
			</element>
			<element name="thresholdSkillScoreMissingForecast" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFF00</documentation>
				</annotation>
			</element>
			<element name="thresholdSkillScoreMissingObserved" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFC800</documentation>
				</annotation>
			</element>
			<element name="thresholdSkillScoreMissingObservedNoFalseAlarm" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFC8</documentation>
				</annotation>
			</element>
			<element name="thumb" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = F0F0F0. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="thumbnailDialogLineBorder" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 0000FF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="tick" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 232830. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="timeNavigationStartDay" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 000000</documentation>
				</annotation>
			</element>
			<element name="timeSeriesCalibrationLabelForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="timeSeriesCompare1" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FF00</documentation>
				</annotation>
			</element>
			<element name="timeSeriesCompare2" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="timeSeriesDefault" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 808080</documentation>
				</annotation>
			</element>
			<element name="timeSeriesDialogColumnHeaderColor" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="timeSeriesFilteredBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = addfff</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupBasisStatistics" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000ff</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupCompletedDoubtful" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 8a4117</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupCompletedReliable" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 3ea99f</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupCompletedUnreliable" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 800517</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupCorrectedDoubtful" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = fa9b3c</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupCorrectedReliable" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00ff00</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupCorrectedUnreliable" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = f75431</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupFlagComparison" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 152dc6</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupGeneral" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 736f6e</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupHardMax" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = e57ded</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupHardMin" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 4e387e</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupMissing" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 8e35ef</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupOriginalDoubtful" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = f87a17</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupOriginalReliable" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 41a317</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupOriginalUnreliable" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = ff0000</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupOscillation" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 12cccc</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupRateOfChange" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 3ea99f</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupSameReading" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = e57ded</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupSeriesComparison" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 736aff</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupSoftMax" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 8467d7</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupSoftMin" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 8e35ef</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupSpatialHomogeneity" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 4863a0</documentation>
				</annotation>
			</element>
			<element name="timeSeriesGroupTemporaryShift" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 82cafa</documentation>
				</annotation>
			</element>
			<element name="timeSeriesHydrograph" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="timeSeriesHydrographModified" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="timeSeriesListerConstantBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = ecd872</documentation>
				</annotation>
			</element>
			<element name="timeSeriesListerWarningForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="timeSeriesSelectedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = edebcb</documentation>
				</annotation>
			</element>
			<element name="title" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 3B3B3B. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="titleBorderDisabled" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 808080</documentation>
				</annotation>
			</element>
			<element name="toolScrollBarUiBackEnd" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFF4CC. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
            <element name="toolScrollBarUiBackStart" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
                <annotation>
                    <documentation>default color = FFD497. Color is no longer in use, configuration is optional since 2025.01</documentation>
                </annotation>
            </element>
            <element name="toolTipBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
                <annotation>
                    <documentation>default color = FFFFCC. Color is no longer in use, configuration is optional since 2025.01</documentation>
                </annotation>
            </element>
            <element name="track" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="trackForeground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = C8C8C8. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="trackHighlight" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="trackHighlightForeground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 404040. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="valueAboveDetectionRangeBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF2C71</documentation>
				</annotation>
			</element>
			<element name="valueAutomaticallyCompletedBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FF00FF  This background color is not used so far. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="valueAutomaticallyCompletedForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF00FF since 2017.02, FF8000 before 2017.02</documentation>
				</annotation>
			</element>
			<element name="valueAutomaticallyCorrectedBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FF3333  This background color is not used so far. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="valueAutomaticallyCorrectedForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF3333 since 2017.02, FF0000 before 2017.02</documentation>
				</annotation>
			</element>
			<element name="valueBelowDetectionRangeBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 00FF00</documentation>
				</annotation>
			</element>
			<element name="valueDoubtfulBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFC800</documentation>
				</annotation>
			</element>
			<element name="valueDriedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF00FF</documentation>
				</annotation>
			</element>
			<element name="valueHasCommentMarkerBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="valueIceBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 0000FF</documentation>
				</annotation>
			</element>
			<element name="valueInundatedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="valueManualCompletedBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FF8000  This background color is not used so far. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="valueManualCompletedForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF8000 since 2017.02, FF00FF before 2017.02</documentation>
				</annotation>
			</element>
			<element name="valueManualCorrectedBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FF0000  This background color is not used so far. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="valueManualCorrectedForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000 since 2017.02, FF3333 before 2017.02</documentation>
				</annotation>
			</element>
			<element name="valueMissingBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFFFF</documentation>
				</annotation>
			</element>
			<element name="valueModifiedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FF0000</documentation>
				</annotation>
			</element>
			<element name="valueNormalBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 3ea99f</documentation>
				</annotation>
			</element>
			<element name="valuePersistentUnreliableBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = e18b6b</documentation>
				</annotation>
			</element>
			<element name="valueAccumulationResetBackground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 0xf5f3d7</documentation>
				</annotation>
			</element>
			<element name="valueSourceCyclicForeground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 808080</documentation>
				</annotation>
			</element>
			<element name="valueUnmodifiedBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 3ea99f</documentation>
				</annotation>
			</element>
			<element name="valueUnreliableBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFF00</documentation>
				</annotation>
			</element>
			<element name="waterCoachBorder" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = FFFF00</documentation>
				</annotation>
			</element>
			<element name="window" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowButtonBackgroundActiveEnd" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFF4CC. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowButtonBackgroundActiveStart" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFD497. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowButtonBackgroundInactive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = F7F3EF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowButtonForeground" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowButtonForegroundUnavailable" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 808080. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowButtonMouseInBorder" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowButtonMouseOutBorder" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 808080. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarBackgroundActiveEnd" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 607BB7. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarBackgroundActiveStart" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 91B5FF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarBackgroundInactiveEnd" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = A7A49D. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarBackgroundInactiveStart" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = C1BDB6. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarIdBackgroundActive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = B7C8E8. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarIdBackgroundAnimating" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = C0C0C0. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarIdBackgroundFlashingOne" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = C0C0C0. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarIdBackgroundFlashingZero" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = B7C8E8. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarIdBackgroundGradientTop" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarIdBackgroundInactive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = C0C0C0. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarIdForegroundActive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 000000. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarIdForegroundInactive" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = 808080. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarTabForegroundSelected" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = FFFFFF. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="windowTitleBarTabForegroundUnselected" type="fews:PredefinedColorKeyComplexType" minOccurs="0">
				<annotation>
					<documentation>default color = D4D4D4. Color is no longer in use, configuration is optional since 2025.01</documentation>
				</annotation>
			</element>
			<element name="zoomSelectionBackground" type="fews:PredefinedColorKeyComplexType">
				<annotation>
					<documentation>default color = 808080</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="CustomColorKeysComplexType">
		<sequence>
			<element name="key" type="fews:CustomColorKeyComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="PredefinedColorKeyComplexType">
		<attribute name="color" type="fews:nonReferenceColorStringType"/>
	</complexType>
</schema>
