<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--Top-level element Declaration -->
	<element name="correlationDisplay" type="fews:CorrelationDisplayComplexType"/>
	<!--Correlation Display ComplexType-->
	<complexType name="CorrelationDisplayComplexType">
		<sequence>
			<element name="inputTimeSerieInfo" type="fews:TimeSeriesSetInfo">
				<annotation>
					<documentation>Historic time series sets information. 
Parameter id is required for calculating correlation. The other variables are required for running the forecast hydrograph.</documentation>
				</annotation>
			</element>
			<element name="eventSetsDescriptorId" type="fews:idStringType">
				<annotation>
					<documentation>Correlation event sets descriptor ID</documentation>
				</annotation>
			</element>
			<element name="travelTimesDescriptorId" type="fews:idStringType">
				<annotation>
					<documentation>Travel times descriptor ID</documentation>
				</annotation>
			</element>
			<element name="eventSelectionType">
				<annotation>
					<documentation>Selection type: event id selection or travel time selection.</documentation>
				</annotation>
				<simpleType>
					<restriction base="string">
						<enumeration value="eventid"/>
						<enumeration value="traveltime"/>
                        <enumeration value="combined"/>
					</restriction>
				</simpleType>
			</element>
			<element name="outputTimeSerieInfo" type="fews:TimeSeriesSetInfo" minOccurs="0">
				<annotation>
					<documentation>Forecast time series set information. If no forecast information is defined then no forecast can be saved. </documentation>
				</annotation>
			</element>
			<element name="correlationDisplayOptions" type="fews:CorrelationDisplayOptionsComplexType" minOccurs="0"/>
			<element name="defaultEquation" type="fews:CorrelationEquationsComplexType" minOccurs="0"/>
            <element name="userDefinedRelation" type="fews:UserDefinedRelationComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<complexType name="TimeSeriesSetInfo">
		<sequence>
			<element name="moduleInstanceId" type="fews:idStringType" minOccurs="0"/>
			<element name="parameterId" type="fews:idStringType"/>
            <element name="qualifierId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>Id that references an qualifier listed in the regionConfigFiles/Qualifiers.xsd
                    </documentation>
                </annotation>
            </element>
			<element name="timeSeriesType" type="fews:timeSeriesTypeEnumStringType" minOccurs="0"/>
			<element name="timeStep" type="fews:TimeStepComplexType" minOccurs="0"/>
			<element name="relativeViewPeriod" type="fews:TimeSeriesSetRelativePeriodComplexType" minOccurs="0"/>
			<element name="readWriteMode" type="fews:timeSeriesReadWriteModeEnumStringType" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="CorrelationDisplayOptionsComplexType">
		<sequence>
			<element name="scatterplotOptions" type="fews:ScatterPlotDisplayOptionsComplexType"/>
			<element name="equationOptions" type="fews:DisplayOptionsComplexType"/>
            <element name="displayOptions" type="fews:DisplayOptionsComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
    <complexType name="UserDefinedRelationComplexType">
        <sequence>
            <element name="referencePoints" type="fews:ReferencePointsComplexType"/>
            <element name="displayOptionKey" type="string" minOccurs="0"/>
            <element name="comment" type="string" minOccurs="0"/>
        </sequence>
        <attribute name="id" type="string" use="required"/>
        <attribute name="name" type="string" use="optional"/>
    </complexType>
	<complexType name="ScatterPlotDisplayOptionsComplexType">
		<sequence>
			<element name="preferredColor" type="fews:colorStringType" minOccurs="0"/>
			<element name="lineStyle" type="fews:chartLineStyleEnumStringType" minOccurs="0"/>
			<element name="markerStyle" type="fews:markerStyleEnumStringType" minOccurs="0"/>
			<element name="markerSize" type="fews:markerSizeIntegerType" minOccurs="0"/>
			<element name="markerFilled" type="boolean" minOccurs="0"/>
			<element name="thresholds" type="fews:CorrelationDisplayThresholdOptionsComplexType" minOccurs="0">
				<annotation>
					<documentation>Element to control whether thresholds should be visible. Applies to Scatter Plot and Travel Times Plot</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="key" type="string"/>
	</complexType>
	<complexType name="CorrelationDisplayThresholdOptionsComplexType">
		<attribute name="visible" type="boolean" use="required"/>
	</complexType>
</schema>
