<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="correlationEventSets.xsd"/>
	<!--Correlation Schema with element  correlationSets-->
	<element name="correlationSets" type="fews:CorrelationSetsComplexType">
		<annotation>
			<documentation>Correlation Sets element</documentation>
		</annotation>
	</element>
	<complexType name="CorrelationSetsComplexType">
		<annotation>
			<documentation>All available correlations present for different forecast locations</documentation>
		</annotation>
		<sequence>
			<element name="correlationSet" type="fews:CorrelationSetComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<complexType name="CorrelationSetComplexType">
		<annotation>
			<documentation>All available correlations for particular forecast location</documentation>
		</annotation>
		<sequence>
			<element name="inputTimeSerieSet" type="fews:TimeSeriesSetComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Time series sets contains the time series information of the input locations defined in the correlations</documentation>
				</annotation>
			</element>
			<element name="correlation" type="fews:CorrelationComplexType">
				<annotation>
					<documentation>Available correlation for this forecast location.</documentation>
				</annotation>
			</element>
			<element name="outputTimeSerieSet" type="fews:TimeSeriesSetComplexType">
				<annotation>
					<documentation>Time series set containing the time series information of the forecast location for this correlationSet</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="CorrelationComplexType">
		<annotation>
			<documentation>Correlation of for a particular forecast location</documentation>
		</annotation>
		<sequence>
			<element name="forecastLocationId" type="fews:idStringType">
				<annotation>
					<documentation>Forecast location to use for the correlation.</documentation>
				</annotation>
			</element>
			<element name="equationType" type="fews:CorrelationEquationsComplexType">
				<annotation>
					<documentation>Type of regression equation.</documentation>
				</annotation>
			</element>
			<element name="eventSetsDescriptorId" type="fews:idStringType">
				<annotation>
					<documentation>Correlation event sets descriptor ID</documentation>
				</annotation>
			</element>
			<element name="travelTimesDescriptorId" type="fews:idStringType">
				<annotation>
					<documentation>Travel times descriptor ID</documentation>
				</annotation>
			</element>
			<element name="eventSelectionType">
				<annotation>
					<documentation>Selection type: event id selection or travel time selection.</documentation>
				</annotation>
				<simpleType>
					<restriction base="string">
						<enumeration value="eventid"/>
						<enumeration value="traveltime"/>
					</restriction>
				</simpleType>
			</element>
			<element name="selectionCriteria" type="fews:SelectionCriteriaComplexType" minOccurs="0">
				<annotation>
					<documentation>Selection criteria used for selecting events for the forecast station.</documentation>
				</annotation>
			</element>
			<element name="comment" type="string" minOccurs="0">
				<annotation>
					<documentation>Comment describing this correlation.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SupportLocationComplexType">
		<annotation>
			<documentation>Available support locations for active forecast location</documentation>
		</annotation>
		<sequence>
			<element name="locationId" type="fews:idStringType">
				<annotation>
					<documentation>Location id. This is the same as the location Id in the event set</documentation>
				</annotation>
			</element>
			<element name="travelTime" type="fews:TimeSpanComplexType">
				<annotation>
					<documentation>Travel time from this support location to present forecast location.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SelectionCriteriaComplexType">
		<annotation>
			<documentation>Selection criteria on how the forecast station events are to be selected.</documentation>
		</annotation>
		<sequence>
			<element name="period" type="fews:SelectionPeriodComplexType" minOccurs="0">
				<annotation>
					<documentation>Time period for which to select data.</documentation>
				</annotation>
			</element>
			<element name="thresholds" type="fews:SelectionThresholdComplexType" minOccurs="0">
				<annotation>
					<documentation>Thresholds for which to select data.</documentation>
				</annotation>
			</element>
			<element name="tags" type="fews:SelectionTagsComplexType" minOccurs="0">
				<annotation>
					<documentation>Tags for which to select or exclude data.</documentation>
				</annotation>
			</element>
            <element name="travelTimes" type="fews:RelativePeriodComplexType" minOccurs="0">
                <annotation>
                    <documentation>Relative period for selecting travel times.</documentation>
                </annotation>
            </element>
		</sequence>
	</complexType>
	<complexType name="SelectionPeriodComplexType">
		<annotation>
			<documentation>Defines period for which events are to be selected</documentation>
		</annotation>
		<sequence>
			<element name="startDate" type="date">
				<annotation>
					<documentation>Start date of period</documentation>
				</annotation>
			</element>
			<element name="startTime" type="time" minOccurs="0">
				<annotation>
					<documentation>Start time of period</documentation>
				</annotation>
			</element>
			<element name="endDate" type="date">
				<annotation>
					<documentation>End date of period</documentation>
				</annotation>
			</element>
			<element name="endTime" type="time" minOccurs="0">
				<annotation>
					<documentation>End time of period</documentation>
				</annotation>
			</element>
			<element name="selectInsidePeriod" type="boolean">
				<annotation>
					<documentation>Boolean indicating whether selection lies within period or outside period.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SelectionThresholdComplexType">
		<annotation>
			<documentation>Defines thresholds for which events are to be selected</documentation>
		</annotation>
		<sequence>
			<element name="thresholdLimit" type="float">
				<annotation>
					<documentation>Limit of selection values</documentation>
				</annotation>
			</element>
			<element name="selectAboveLimit" type="boolean">
				<annotation>
					<documentation>Boolean indicating whether selection lies above limit (true) or below limit (false).</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SelectionTagsComplexType">
		<annotation>
			<documentation>Defines tags for which events are to be selected</documentation>
		</annotation>
		<sequence>
			<element name="tag" type="string" maxOccurs="unbounded">
				<annotation>
					<documentation>Tags for selection</documentation>
				</annotation>
			</element>
            <choice>
                <element name="include" type="boolean">
                    <annotation>
                        <documentation>Boolean indicating whether include the tags in list the selection list or to exclude them.</documentation>
                    </annotation>
                </element>
                <element name="operator">
                     <annotation>
                         <documentation>
                             Operator type: Operator for selecting event tags.
                         </documentation>
                     </annotation>
                     <simpleType>
                         <restriction base="string">
                             <enumeration value="and">
                                 <annotation>
                                     <documentation>AND: result = A AND B
                                     Result is true when both "A" and "B" are true, in all other cases the result is false.</documentation>
                                 </annotation>
                             </enumeration>
                             <enumeration value="nand">
                                 <annotation>
                                     <documentation>NOT AND: result = A NAND B
                                     Result is false when both "A" and "B" are true, in all other cases the result is true.
                                     This function is equivalent to NOT(A AND B)</documentation>
                                 </annotation>
                             </enumeration>
                             <enumeration value="nor">
                                 <annotation>
                                     <documentation>NOT OR: result = A NOR B
                                     Result is true when both "A" and "B" are false, in all other cases the result is false.
                                     This function is equivalent to NOT (A OR B)</documentation>
                                 </annotation>
                             </enumeration>
                             <enumeration value="not">
                                 <annotation>
                                     <documentation>NOT: result = NOT A
                                     Result is opposite "A". "NOT A" in false if "A" is true and if "A" is false "NOT A" is true.</documentation>
                                 </annotation>
                             </enumeration>
                             <enumeration value="or">
                                 <annotation>
                                     <documentation>OR: result = A OR B
                                     Result is true if "A" is true or "B" is true or if both are true. The result is false
                                     if both "A" and "B" are false</documentation>
                                 </annotation>
                             </enumeration>
                             <enumeration value="xor">
                                 <annotation>
                                     <documentation>eXclusive OR: result = A XOR B
                                     Result is true if "A" is true and "B" is false or if "A" is false and "B" is true. If both
                                     "A" and "B" are true or if they are both false the result if false.
                                     This function is equivalent to (A AND NOT B) OR (B AND NOT A)</documentation>
                                 </annotation>
                             </enumeration>
                         </restriction>
                     </simpleType>
                 </element>
            </choice>
		</sequence>
	</complexType>
</schema>
