<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--Correlation Schema with element  correlationSets-->
	<element name="correlationEventSets" type="fews:CorrelationEventSetsComplexType">
		<annotation>
			<documentation>Events</documentation>
		</annotation>
	</element>
	<complexType name="CorrelationEventSetsComplexType">
		<annotation>
			<documentation>Event sets of all location ids</documentation>
		</annotation>
		<sequence>
            <element name="timeZone" type="fews:timeZoneStringType" minOccurs="0"/>
			<element name="correlationEventSet" type="fews:CorrelationEventSetComplexType" maxOccurs="unbounded"/>
			<element name="comment" type="string" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="CorrelationEventSetComplexType">
		<annotation>
			<documentation>Set of events belonging to single location id</documentation>
		</annotation>
		<choice>
			<sequence>
				<element name="locationId" type="fews:idStringType">
					<annotation>
						<documentation>Location id</documentation>
					</annotation>
				</element>
				<element name="parameterId" type="fews:idStringType">
					<annotation>
						<documentation>Parameter id of the event data in the correlation sets</documentation>
					</annotation>
				</element>
				<element name="event" type="fews:CorrelationEventComplexType" maxOccurs="unbounded">
					<annotation>
						<documentation>Events of observed peak -discharges, -levels or other obtained from a large number of historical floods.</documentation>
					</annotation>
				</element>
			</sequence>
			<sequence>
				<element name="locationSetId" type="fews:idStringType">
					<annotation>
						<documentation>Id of the location set for which events should be included</documentation>
					</annotation>
				</element>
				<element name="eventIdAttributeId" type="fews:idStringType">
					<annotation>
						<documentation>Attribute id which specifies the id of the event</documentation>
					</annotation>
				</element>
				<element name="eventParameterLocationAttributeId" type="fews:idStringType">
					<annotation>
						<documentation>Attribute id which specifies which parameter belongs to the event</documentation>
					</annotation>
				</element>
				<element name="eventTimeLocationAttributeId" type="fews:idStringType">
					<annotation>
						<documentation>Attribute id which contains the time of the event</documentation>
					</annotation>
				</element>
				<element name="eventValueLocationAttributeId" type="fews:idStringType">
					<annotation>
						<documentation>Attribute id which contains the value of the event</documentation>
					</annotation>
				</element>
				<element name="eventTagLocationAttributeId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>Since 2023.02. Attribute id which contains a tag of the event</documentation>
					</annotation>
				</element>
				<element name="eventCommentLocationAttributeId" type="fews:idStringType" minOccurs="0">
					<annotation>
						<documentation>Since 2023.02. .Attribute id which contains the comment of the event</documentation>
					</annotation>
				</element>
			</sequence>
		</choice>
	</complexType>
	<complexType name="CorrelationEventComplexType">
		<annotation>
			<documentation>Single correlation event</documentation>
		</annotation>
		<attribute name="eventId" type="fews:idStringType" use="optional">
			<annotation>
				<documentation>Id of event. A single event that occurs at different locations must have the same eventId for each of the locations.</documentation>
			</annotation>
		</attribute>
		<attribute name="value" type="float" use="required">
			<annotation>
				<documentation>Data value for this event</documentation>
			</annotation>
		</attribute>
		<attribute name="date" type="date" use="required">
			<annotation>
				<documentation>Time event occurs at this location</documentation>
			</annotation>
		</attribute>
		<attribute name="time" type="time" use="optional">
			<annotation>
				<documentation>time of event (hh:mm:ss)</documentation>
			</annotation>
		</attribute>
		<attribute name="tag" type="string" use="optional">
			<annotation>
				<documentation>Tag indicating type of event</documentation>
			</annotation>
		</attribute>
        <attribute name="tag1" type="string" use="optional">
            <annotation>
                <documentation>Tag indicating type of event</documentation>
            </annotation>
        </attribute>
        <attribute name="tag2" type="string" use="optional">
            <annotation>
                <documentation>Tag indicating type of event</documentation>
            </annotation>
        </attribute>
        <attribute name="tag3" type="string" use="optional">
            <annotation>
                <documentation>Tag indicating type of event</documentation>
            </annotation>
        </attribute>
        <attribute name="tag4" type="string" use="optional">
            <annotation>
                <documentation>Tag indicating type of event</documentation>
            </annotation>
        </attribute>
        <attribute name="comment" type="string" use="optional">
            <annotation>
                <documentation>Event comment</documentation>
            </annotation>
        </attribute>
	</complexType>
</schema>
