<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by J (WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- -->
	<element name="dAFilter" type="fews:DAFilterComplexType"/>
	<!-- -->
	<complexType name="DAFilterComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="daExecutiveRootDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Directory of DaExecutive  - optional then is equal to root dir</documentation>
				</annotation>
			</element>
			<element name="referencePiTimeSeries" type="fews:fileStringType">
				<annotation>
					<documentation>reference PITimeSeries file to get the period</documentation>
				</annotation>
			</element>
			<element name="daExecutiveModelRunPeriodFile" type="fews:fileStringType">
				<annotation>
					<documentation>name (including directory path) of DA Executive model deploying configuration file.</documentation>
				</annotation>
			</element>
			<element name="diagnosticFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Diagnostic file: Contains all messages produced by the adapter.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<!-- -->
	<complexType name="DAFilterDirectoriesComplexType">
		<sequence>
			<element name="rootDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Root directory of the module instance. Option, if this rootDir is not given then the rootDir will be taken same as workingDir defined in GA</documentation>
				</annotation>
			</element>
			<element name="inputDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Directory of input files - optional  then inputDir is equal to root dir</documentation>
				</annotation>
			</element>
			<element name="outputDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Directory of output  files - optional -  then outputDir is equal to root dir</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
</schema>
