<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews"
		targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified"
		attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="dataAnalysisDisplays" type="fews:DataAnalysisDisplaysComplexType"/>
	<complexType name="DataAnalysisDisplaysComplexType">
		<sequence>
			<element name="dataAnalysisDisplay" type="fews:DataAnalysisDisplayComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>This element can be used to define data analysis displays.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="DataAnalysisDisplayComplexType">
		<sequence>
			<element name="relativeViewPeriod" type="fews:RelativePeriodComplexType"/>
			<element name="filters" type="fews:DataAnalysisFilterComplexType"/>
			<element name="selectionPanel" type="fews:SelectionPanelComplexType" minOccurs="0"/>
			<element name="toolBoxes" type="fews:ToolBoxesComplexType"/>
			<element name="exportArchiveProducts" type="fews:ExportArchiveProductComplexType" minOccurs="0">
				<annotation>
					<documentation>Defines the export archive product settings for this data analysis display. If omitted, no export will be performed.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Id of the data analysis display.</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nameStringType">
			<annotation>
				<documentation>Name of the data analysis display.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="DataAnalysisFilterComplexType">
		<sequence>
			<element name="filterId" type="fews:idStringType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="SelectionPanelComplexType">
		<sequence>
			<element name="locationSelection" type="fews:DataAnalysisLocationSelectionComplexType">
				<annotation>
					<documentation>For now it is only possible to define the name of the location selection panel. If omitted the name will default to Location</documentation>
				</annotation>
			</element>
			<element name="parameterSelection" type="fews:DataAnalysisParameterSelectionComplexType">
				<annotation>
					<documentation>For now it is only possible to define the name of the parameter selection panel. If omitted the name will default to Parameter</documentation>
				</annotation>
			</element>
			<element name="moduleInstanceSelection" type="fews:DataAnalysisModuleInstanceSelectionComplexType" minOccurs="0">
				<annotation>
					<documentation>If omitted it will not be possible to filter based on module instance ids</documentation>
				</annotation>
			</element>
			<element name="locationAttributeSelection" type="fews:DataAnalysisLocationAttributeSelectionComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>If omitted it will not be possible to filter based on location attributes</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="DataAnalysisLocationSelectionComplexType">
		<attribute name="name" type="fews:nameStringType"/>
	</complexType>
	<complexType name="DataAnalysisParameterSelectionComplexType">
		<attribute name="name" type="fews:nameStringType"/>
	</complexType>
	<complexType name="DataAnalysisModuleInstanceSelectionComplexType">
		<attribute name="name" type="fews:nameStringType"/>
	</complexType>
	<complexType name="DataAnalysisLocationAttributeSelectionComplexType">
		<attribute name="attributeId" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nameStringType" use="required"/>
	</complexType>
	<complexType name="ToolBoxesComplexType">
		<sequence>
			<element name="resampling" type="fews:emptyElement" minOccurs="0"/>
			<element name="correlation" type="fews:emptyElement" minOccurs="0"/>
			<element name="workflow" type="fews:DataAnalysisDisplayWorkflowComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DataAnalysisDisplayWorkflowComplexType">
		<sequence>
			<element name="workflowId" type="fews:idStringType"/>
			<element name="results" type="fews:DataAnalysisDisplayResultsComplexType"/>
			<element name="iconId" type="fews:idStringType" minOccurs="0"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nameStringType"/>
	</complexType>
	<complexType name="DataAnalysisDisplayResultsComplexType">
		<sequence>
			<element name="filterId" type="fews:idStringType" minOccurs="0"/>
			<element name="archiveProductId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="ExportArchiveProductComplexType">
		<sequence>
			<element name="metaData" type="fews:ExportArchiveProductMetaDataComplexType"/>
		</sequence>
		<attribute name="enabled" type="boolean" use="required"/>
	</complexType>
	<complexType name="ExportArchiveProductMetaDataComplexType">
		<sequence>
			<element name="properties" type="fews:ExportArchiveProductPropertiesComplexType"/>
			<element name="attributes" type="fews:ExportArchiveProductsAttributeComplexType" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="ExportArchiveProductPropertiesComplexType">
		<sequence>
			<element name="areaId" type="fews:idStringType"/>
			<element name="sourceId" type="fews:idStringType" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="ExportArchiveProductsAttributeComplexType">
		<sequence>
			<element name="attribute" type="fews:ExportArchiveProductAttributeComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Defines the attributes that will be added to the export archive product.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ExportArchiveProductAttributeComplexType">
		<attribute name="key" type="fews:idStringType" use="required"/>
		<attribute name="value" type="fews:idStringType" use="required"/>
	</complexType>
</schema>