<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews/archive"
		targetNamespace="http://www.wldelft.nl/fews/archive" elementFormDefault="qualified"
		attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="archive_sharedTypes.xsd"/>
	<element name="dataTypeInfo" type="fews:DataTypeInfoComplexType">
		<annotation>
			<documentation>Contains a list with  data types with per data type the associated sources</documentation>
		</annotation>
	</element>
	<complexType name="DataTypeInfoComplexType">
		<sequence>
			<element name="dataTypeSourcesMapping" type="fews:DataTypeSourcesMappingComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>data type and the sources  associated with this data type</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="DataTypeSourcesMappingComplexType">
		<sequence>
			<element name="dataTypeId" type="fews:idStringType">
				<annotation>
					<documentation>Data type Id</documentation>
				</annotation>
			</element>
			<group ref="fews:SourceElements" minOccurs="0"/>
		</sequence>
	</complexType>
	<group name="SourceElements">
		<sequence>
			<element name="sourceId" type="fews:idStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>List of the sources the data type is associated with .  Source Id  may refer to the sources configured in sources.xml.  It can also be  any string Id .</documentation>
				</annotation>
			</element>
		</sequence>
	</group>
</schema>
