<?xml version="1.0" encoding="UTF-8"?>
<!--INACTIVE-->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="documentDisplays" type="fews:DocumentDisplaysComplexType"/>
	<complexType name="DocumentDisplaysComplexType">
		<sequence>
			<element name="documentDisplay" type="fews:DocumentDisplayComplexType" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Document Display</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="DocumentDisplayComplexType">
		<sequence>
			<choice>
				<sequence>
					<element name="report" type="fews:DocumentDisplayReportComplexType" maxOccurs="1" minOccurs="0">
						<annotation>
							<documentation>Report</documentation>
						</annotation>
					</element>
				</sequence>
				<choice minOccurs="0">
					<element name="compose" type="fews:DocumentDisplayComposeComplexType">
						<annotation>
							<documentation>Compose</documentation>
						</annotation>
					</element>
					<element name="browser" type="fews:DocumentDisplayBrowserComplexType">
						<annotation>
							<documentation>Browser</documentation>
						</annotation>
					</element>
				</choice>
			</choice>
			<element name="relativeViewPeriod" type="fews:RelativePeriodComplexType" maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>Relative View Period</documentation>
				</annotation>
			</element>
			<element name="viewPermission" type="string" minOccurs="0"/>
			<element name="editPermission" type="string" minOccurs="0"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:idStringType" use="required"/>
	</complexType>

	<complexType name="DocumentDisplayReportComplexType">
		<sequence>
			<element name="archiveProductId" type="fews:idStringType" maxOccurs="1" minOccurs="0">
			</element>
			<element name="reportModuleInstanceId" type="fews:idStringType" maxOccurs="1" minOccurs="0">
			</element>
			<element name="showReports" type="fews:DocumentDisplayShowReportComplexType" maxOccurs="1" minOccurs="0">
			</element>
			<element name="editor" type="boolean" default="true" minOccurs="0" maxOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="DocumentDisplayShowReportComplexType">
		<sequence>
			<element name="productWorkflowStatusId" type="fews:idStringType" maxOccurs="unbounded" minOccurs="0"/>
		</sequence>
	</complexType>

	<complexType name="DocumentDisplayComposeComplexType">
		<sequence>
			<element name="composeId" type="fews:idStringType" maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<documentation>Compose Id</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="DocumentDisplayBrowserComplexType">
		<sequence>
			<element name="layout" type="fews:DocumentDisplayBrowserLayoutComposeComplexType" maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>Layout</documentation>
				</annotation>
			</element>
			<element name="archiveProducts" type="fews:DocumentDisplayBrowserArchiveProductsComplexType" maxOccurs="1" minOccurs="1">
				<annotation>
					<documentation>Archive Products</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="DocumentDisplayBrowserArchiveProductsComplexType">
		<sequence>
			<element name="archiveProductId" type="fews:idStringType" maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<documentation>Archive Product Id</documentation>
				</annotation>
			</element>
			<element name="archiveProductSetId" type="fews:idStringType" maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<documentation>Archive Product Set ID</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="DocumentDisplayBrowserLayoutComposeComplexType">
		<sequence>
			<element name="preview" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Archive Product Id</documentation>
				</annotation>
			</element>
			<element name="headers" type="fews:DocumentDisplayBrowserLayoutHeadersComplexType" maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>Headers</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="DocumentDisplayBrowserLayoutHeadersComplexType">
		<sequence>
			<element name="header" type="fews:DocumentDisplayHeaderComplexType" maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="DocumentDisplayHeaderComplexType">
		<simpleContent>
			<extension base="string">
				<attribute name="productProperty" type="fews:ProductPropertyStringType" use="optional"/>
				<attribute name="productAttribute" type="string" use="optional"/>
				<attribute name="name" type="string" use="required"/>
			</extension>
		</simpleContent>
	</complexType>

	<simpleType name="ProductPropertyStringType">
		<restriction base="string">
			<enumeration value="timeZero"/>
			<enumeration value="sourceId"/>
			<enumeration value="areaId"/>
		</restriction>
	</simpleType>
</schema>
