<?xml version="1.0" encoding="UTF-8"?>
<!--INACTIVE-->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="documents" type="fews:DocumentsComplexType"/>
	<complexType name="DocumentsComplexType">
		<sequence>
			<element name="documentWorkflow" type="fews:DocumentWorkflowComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>The possible status transitions which are possible</documentation>
				</annotation>
			</element>
			<element name="archiveProduct" type="fews:ArchiveProductComplexType" maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<documentation>Definition of the archive products</documentation>
				</annotation>
			</element>
			<element name="composeProduct" type="fews:ComposeDocumentComplexType" maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<documentation>Definition of products which are a combination of several items</documentation>
				</annotation>
			</element>
			<element name="archiveProductSet" type="fews:ArchiveProductSetComplexType" maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<documentation>Definition of archive product sets</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="DocumentWorkflowComplexType">
		<sequence>
			<element name="status" type="fews:StatusComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Status of the products</documentation>
				</annotation>
			</element>
			<element name="transition" type="fews:TransitionComplexType" maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<documentation>Possible transition of 1 status to another</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
	</complexType>
	<complexType name="StatusComplexType">
		<sequence>
			<element name="attribute" type="fews:DocumentAttributeComplexType"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="string" use="required"/>
		<attribute name="default" type="boolean"/>
	</complexType>
	<complexType name="DocumentAttributeComplexType">
		<attribute name="key" type="fews:idStringType" use="required"/>
		<attribute name="value" type="string" use="required"/>
	</complexType>
	<complexType name="TransitionComplexType">
		<sequence>
			<element name="fromStatus" type="string"/>
			<element name="toStatus" type="string"/>
			<element name="editPermission" type="string"/>
		</sequence>
	</complexType>
	<complexType name="ArchiveProductComplexType">
		<sequence>
			<element name="documentWorkflowId" type="string" minOccurs="0"/>
			<element name="areaId" type="string"/>
			<element name="sourceId" type="string"/>
			<element name="versionKey" type="string" maxOccurs="unbounded" minOccurs="0"/>
			<element name="attribute" type="fews:DocumentAttributeComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ComposeDocumentComplexType">
		<sequence>
			<element name="archiveProductId" type="string"/>
			<element name="template" type="fews:ComposeProductTemplateComplexType"/>
		</sequence>
		<attribute name="id" type="fews:idStringType"/>
		<attribute name="name" type="string"/>
	</complexType>
	<complexType name="ArchiveProductSetComplexType">
		<sequence>
			<element name="constraints" type="fews:ArchiveProductSetConstraintsComplexType"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
	</complexType>
	<complexType name="ArchiveProductSetConstraintsComplexType">
		<sequence>
			<element name="areaId" type="fews:idStringType"/>
			<element name="sourceId" type="fews:idStringType" minOccurs="0"/>
			<element name="allValid" type="fews:ArchiveProductSetValidationComplexType" minOccurs="0"/>
			<element name="anyValid" type="fews:ArchiveProductSetValidationComplexType" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="ArchiveProductSetValidationComplexType">
		<sequence>
			<element name="attributeTextEquals" type="fews:ArchiveProductSetAttributeTextEqualsComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="ArchiveProductSetAttributeTextEqualsComplexType">
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="equals" type="string" use="required"/>
	</complexType>
	<complexType name="ComposeProductTemplateComplexType">
		<sequence>
			<element name="archiveProductId" type="string"/>
		</sequence>
	</complexType>
	<complexType name="ContentComplexType">
		<sequence>
			<choice maxOccurs="unbounded">
				<element name="archiveProduct" type="fews:ArchiveProductDocumentComplexType"/>
				<element name="htmlDisplay" type="fews:HtmlDisplayComplexType"/>
				<element name="reportModule" type="fews:ReportModuleComplexType"/>
				<element name="schematicStatusDisplay" type="fews:SchematicStatusDisplayModuleComplexType"/>
			</choice>
		</sequence>
		<attribute id="id" name="id" type="fews:idStringType"/>
	</complexType>
	<complexType name="HtmlDisplayComplexType">
		<sequence>
			<element name="htmlDisplayId" type="fews:idStringType"/>
			<element name="locationId" type="fews:idStringType"/>
		</sequence>
		<attribute id="htmlDisplayElementId" name="id" type="fews:idStringType"/>
	</complexType>
	<complexType name="ReportModuleComplexType">
		<sequence>
			<element name="reportModuleInstanceId" type="fews:idStringType"/>
		</sequence>
		<attribute id="reportElementId" name="id" type="fews:idStringType"/>
	</complexType>
	<complexType name="SchematicStatusDisplayModuleComplexType">
		<sequence>
			<element name="schematicStatusDisplay" type="fews:idStringType"/>
		</sequence>
		<attribute id="schematicStatusDisplayElementId" name="id" type="fews:idStringType"/>
	</complexType>
	<complexType name="ArchiveProductDocumentComplexType">
		<sequence>
			<element name="archiveProductId" type="fews:idStringType"/>
		</sequence>
		<attribute id="archiveProductElementId" name="id" type="fews:idStringType"/>
	</complexType>
</schema>
