<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="dynamicReportDisplays" type="fews:DynamicReportDisplaysComplexType"/>
	<complexType name="DynamicReportDisplaysComplexType">
		<sequence>
			<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType" maxOccurs="unbounded"/>
			<element name="timeSeriesSets" type="fews:TimeSeriesSetReferencesComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="display" type="fews:DynamicReportDisplayComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>

	<simpleType name="SortEnumStringType">
		<restriction base="string">
			<enumeration value="ascending"/>
			<enumeration value="descending"/>
		</restriction>
	</simpleType>

	<complexType name="DynamicReportDisplayRequiredValueComplexType">
		<attribute name="function" type="string" use="required">
			<annotation>
				<documentation>?</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="DynamicReportDisplayFieldComplexType">
		<attribute name="id" type="string" use="required">
			<annotation>
				<documentation>?</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="string">
			<annotation>
				<documentation>?</documentation>
			</annotation>
		</attribute>
		<attribute name="function" type="string" use="required">
			<annotation>
				<documentation>?</documentation>
			</annotation>
		</attribute>
		<attribute name="sort" type="fews:SortEnumStringType">
			<annotation>
				<documentation>?</documentation>
			</annotation>
		</attribute>
		<attribute name="required" type="boolean">
			<annotation>
				<documentation>?</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="DynamicReportDisplayComplexType">
		<sequence>
			<element name="dataObject" type="fews:DataObjectComplexType" maxOccurs="unbounded"/>
			<element name="reportTemplateName" type="fews:fileStringType" minOccurs="0"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nameStringType"/>
	</complexType>

	<complexType name="DataObjectComplexType">
		<sequence>
			<element name="timeSeriesSetVariable" type="fews:TimeSeriesSetVariableComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="loopTimeSeriesSetVariable" type="fews:LoopTimeSeriesSetVariableComplexType" minOccurs="0"/>
			<choice minOccurs="0">
				<element name="loopLocationVariable" type="fews:LoopLocationVariableComplexType"/>
				<element name="selectedLocationVariable" type="fews:SelectedLocationVariableComplexType"/>
			</choice>
			<element name="selectedTimeVariable" type="fews:SelectedTimeVariableComplexType" minOccurs="0"/>
			<element name="loopEnsembleMemberVariable" type="fews:LoopEnsembleMemberVariableComplexType" minOccurs="0"/>
			<element name="requiredValue" type="fews:DynamicReportDisplayRequiredValueComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="field" type="fews:DynamicReportDisplayFieldComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
	</complexType>


	<complexType name="TimeSeriesSetVariableComplexType">
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="timeSeriesSetId" type="fews:nameStringType" use="required"/>
	</complexType>

	<complexType name="LoopTimeSeriesSetVariableComplexType">
		<attribute name="id" type="fews:nameStringType" use="required"/>
		<attribute name="timeSeriesSetsId" type="fews:idStringType" use="required"/>
	</complexType>

	<complexType name="LoopLocationVariableComplexType">
		<attribute name="id" type="fews:nameStringType" use="required"/>
		<attribute name="locationSetId" type="fews:idStringType"/>
	</complexType>

	<complexType name="SelectedLocationVariableComplexType">
		<attribute name="id" type="fews:nameStringType" use="required"/>
		<attribute name="validLocationSetId" type="fews:idStringType" use="required"/>
	</complexType>

	<complexType name="SelectedTimeVariableComplexType">
		<sequence>
			<element name="timeStep" type="fews:TimeStepComplexType"/>
			<element name="relativeViewPeriod" type="fews:RelativePeriodComplexType"/>
		</sequence>
		<attribute name="id" type="fews:nameStringType" use="required"/>
	</complexType>

	<complexType name="LoopEnsembleMemberVariableComplexType">
		<attribute name="name" type="fews:nameStringType" use="required"/>
		<attribute name="timeSeriesSetId" type="fews:idStringType"/>
	</complexType>
	<!--    -->
	<complexType name="TimeSeriesSetReferencesComplexType">
		<sequence>
			<element name="timeSeriesSetId" type="fews:idStringType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nameStringType"/>
	</complexType>
</schema>