<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="timeUnits" type="fews:TimeUnitsComplexType">
		<annotation>
			<documentation>root</documentation>
		</annotation>
	</element>
	<complexType name="TimeUnitsComplexType">
		<annotation>
			<documentation>Collection of all flag conversions</documentation>
		</annotation>
		<sequence>
			<element name="timeUnit" type="fews:TimeUnitComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="TimeUnitComplexType">
		<annotation>
			<documentation>A single flag conversion</documentation>
		</annotation>
		<sequence>
			<element name="unit" type="fews:environmentAgencyTimeUnitEnumStringType">
				<annotation>
					<documentation>Environment Agency time unit string (eg. '12 s')</documentation>
				</annotation>
			</element>
			<element name="milliseconds" type="long">
				<annotation>
					<documentation>Duration of time unit in milliseconds</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0"/>
		</sequence>
	</complexType>
	<simpleType name="environmentAgencyTimeUnitEnumStringType">
		<annotation>
			<documentation>List of Environment Agency time units</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="Unspecified"/>
			<enumeration value="1 s"/>
			<enumeration value="2 s"/>
			<enumeration value="3 s"/>
			<enumeration value="4 s"/>
			<enumeration value="5 s"/>
			<enumeration value="6 s"/>
			<enumeration value="10 s"/>
			<enumeration value="12 s"/>
			<enumeration value="15 s"/>
			<enumeration value="20 s"/>
			<enumeration value="30 s"/>
			<enumeration value="1 min"/>
			<enumeration value="2 min"/>
			<enumeration value="3 min"/>
			<enumeration value="4 min"/>
			<enumeration value="5 min"/>
			<enumeration value="6 min"/>
			<enumeration value="10 min"/>
			<enumeration value="12 min"/>
			<enumeration value="15 min"/>
			<enumeration value="20 min"/>
			<enumeration value="30 min"/>
			<enumeration value="1 h"/>
			<enumeration value="2 h"/>
			<enumeration value="3 h"/>
			<enumeration value="4 h"/>
			<enumeration value="6 h"/>
			<enumeration value="8 h"/>
			<enumeration value="12 h"/>
			<enumeration value="24 h"/>
			<enumeration value="48 h"/>
			<enumeration value="72 h"/>
			<enumeration value="Day"/>
			<enumeration value="Week"/>
			<enumeration value="Bi-weekly"/>
			<enumeration value="Month"/>
			<enumeration value="Quarterly"/>
			<enumeration value="Year"/>
			<enumeration value="Water Year"/>
		</restriction>
	</simpleType>
</schema>
