<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--Error model Schema with element  errorModelSets-->
	<element name="errorModelSets" type="fews:ErrorModelSetsComplexType">
		<annotation>
			<documentation>Error model Sets element</documentation>
		</annotation>
	</element>
	<complexType name="ErrorModelSetsComplexType">
		<annotation>
			<documentation>All available error models present </documentation>
		</annotation>
		<sequence>
			<element name="errorModelSet" type="fews:ErrorModelSetComplexType" maxOccurs="unbounded"/>
			<element name="logLevelCoefficientsInfo" type="fews:errorModelLogLevelEnumStringType" default="debug" minOccurs="0">
				<annotation>
					<documentation>Optional. Specify the log level for logging Error Model coefficients information. Default is 'debug'.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<complexType name="ErrorModelSetComplexType">
		<annotation>
			<documentation>Error model</documentation>
		</annotation>
		<sequence>
			<element name="inputVariable" type="fews:VariableComplexType" maxOccurs="unbounded"/>
			<choice>
				<element name="autoOrderMethod" type="fews:AutoOderMethodComplexType"/>
				<element name="fixedOrderMethod" type="fews:FixedOderMethodComplexType"/>
			</choice>
			<element name="interpolationOptions" type="fews:ErrorModelInterpolationComplexType" minOccurs="0">
				<annotation>
					<documentation>Interpolation options for filling the missing values of the Observed time series.</documentation>
				</annotation>
			</element>
			<element name="maxObserved" type="float" minOccurs="0">
				<annotation>
					<documentation>Maximum value to be used by error module. Higher values will be converted to NaN</documentation>
				</annotation>
			</element>
			<element name="minObserved" type="float" minOccurs="0">
				<annotation>
					<documentation>Minimum value to be used by error module. Lower values will be converted to NaN</documentation>
				</annotation>
			</element>
			<element name="maxResult" type="float" minOccurs="0">
				<annotation>
					<documentation>Maximum value to be generated by error module.</documentation>
				</annotation>
			</element>
			<element name="minResult" type="float" minOccurs="0">
				<annotation>
					<documentation>Minimum value to be generated by error module.</documentation>
				</annotation>
			</element>
			<element name="ignoreDoubtful" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Should the error module ignore doubtful input values</documentation>
				</annotation>
			</element>
			<element name="ignoreTrailingMissingsInSimulatedTimeSeries" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>If this is true, then all missing values after the last non-missing value in the simulated time series are ignored. If this is false, then gives an error message when there are missing values after the last non-missing value in the simulated time series. Default is false.</documentation>
				</annotation>
			</element>
			<element name="loopOverMultipleTimeSeries" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Since 2016.02. If this is true, then it is possible to configure locationSets in the input and output variables for this errorModel. This errorModel will then loop over these locations and run for each location separately. If this is false, then the observed input and output variables should contain only one location. Default is false. In any case, if the simulated input variables contain multiple time series for a given location, then these will be merged to create a single simulated input time series for that location. Note: looping over multiple ensemble members and/or qualifiers for the same location is not supported.</documentation>
				</annotation>
			</element>
			<element name="logLevelNoObservedValues" type="fews:errorModelLogLevelEnumStringType" default="warn" minOccurs="0">
				<annotation>
					<documentation>Optional. Specify the log level for the log message that is logged when all observed values are missing for a given input time series. Default is warn.</documentation>
				</annotation>
			</element>
			<element name="outputVariable" type="fews:VariableComplexType"/>
		</sequence>
	</complexType>
	<complexType name="AutoOderMethodComplexType">
		<sequence>
			<element name="orderSelection" type="fews:booleanStringAttributeAndPropertyType">
				<annotation>
					<documentation>Option to determine if the orders are to be derived automatically (with the maximums as defined below) or as given by 'order_ar' and 'order_ma'. You can reference a boolean location attribute with @ATTRIBUTE_ID@. The output location's attributes will be used.</documentation>
				</annotation>
			</element>
			<element name="order_ar" type="fews:intStringAttributeAndPropertyType" minOccurs="0">
				<annotation>
					<documentation>(maximum) order of the AR component, should be a value in the interval [0,50]. You can reference a numeric location attribute with @ATTRIBUTE_ID@. The output location's attributes will be used.</documentation>
				</annotation>
			</element>
			<element name="order_ma" type="fews:intStringAttributeAndPropertyType" minOccurs="0">
				<annotation>
					<documentation>(maximum) order of the MA component, should be a value in the interval [0,50]. You can reference a numeric location attribute with @ATTRIBUTE_ID@. The output location's attributes will be used.</documentation>
				</annotation>
			</element>
			<element name="parameters" type="fews:ErrorModelParametersComplexType" minOccurs="0"/>
			<element name="subtractMean" type="fews:booleanStringAttributeAndPropertyType">
				<annotation>
					<documentation>Option to determine if the mean is to be subtracted from the residuals. You can reference a boolean location attribute with @ATTRIBUTE_ID@. The output location's attributes will be used.</documentation>
				</annotation>
			</element>
			<element name="boxcoxTransformation" type="fews:booleanStringAttributeAndPropertyType">
				<annotation>
					<documentation>Option to apply a boxcox transformation to residuals. You can reference a boolean location attribute with @ATTRIBUTE_ID@. The output location's attributes will be used.</documentation>
				</annotation>
			</element>
			<element name="lambda" type="fews:floatStringAttributeAndPropertyType" minOccurs="0">
				<annotation>
					<documentation>A required parameter for theboxcox transformation option. You can reference a numeric location attribute with @ATTRIBUTE_ID@. The output location's attributes will be used.</documentation>
				</annotation>
			</element>
            <element name="analysisWindow" type="fews:TimeSeriesSetRelativePeriodComplexType" minOccurs="0">
                <annotation>
                    <documentation>Limit data window used to establish AR parameters</documentation>
                </annotation>
            </element>
            <element name="observedTimeSeriesId" type="fews:idStringType">
				<annotation>
					<documentation>Observed times series data</documentation>
				</annotation>
			</element>
			<element name="simulatedTimeSeriesId" type="fews:idStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>Simulated data generated by model. This series can contain data for the historic and forecast period.
                        Multiple series will be combined into single series. Series with higher index will be overlayed by series with lower index.
                    </documentation>
				</annotation>
			</element>
			<element name="outputTimeSeriesId" type="fews:idStringType">
				<annotation>
					<documentation>Updated time series data generated by the error model. This series can contain data for the historic and forecast period. Note: this is never used in the code, because there can be only one outputVariable.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FixedOderMethodComplexType">
		<sequence>
			<element name="correctionModel">
				<simpleType>
					<restriction base="string">
						<enumeration value="none"/>
						<enumeration value="ARMA + systematic"/>
						<enumeration value="systematic"/>
						<enumeration value="ARMA"/>
						<enumeration value="ARMA + log transformation"/>
						<enumeration value="ARMA + systematic + log transformation"/>
					</restriction>
				</simpleType>
			</element>
			<element name="order_ar" type="fews:intStringAttributeAndPropertyType" minOccurs="0">
				<annotation>
					<documentation>(maximum) order of the AR component, should be a value in the interval [0,50]. You can reference a numeric location attribute with @ATTRIBUTE_ID@. The output location's attributes will be used.</documentation>
				</annotation>
			</element>
			<element name="order_ma" type="fews:intStringAttributeAndPropertyType" minOccurs="0">
				<annotation>
					<documentation>(maximum) order of the ARMA component, should be a value in the interval [0,50]. You can reference a numeric location attribute with @ATTRIBUTE_ID@. The output location's attributes will be used.</documentation>
				</annotation>
			</element>
			<element name="observedTimeSeriesId" type="fews:idStringType">
				<annotation>
					<documentation>Observed times series data</documentation>
				</annotation>
			</element>
			<element name="simulatedTimeSeriesId" type="fews:idStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>Simulated data generated by model. This series can contain data for the historic and forecast period.
                        Multiple series will be combined into single series. Series with higher index will be overlayed by series with lower index.
                    </documentation>
				</annotation>
			</element>
			<element name="outputTimeSeriesId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Updated time series data generated by the error model. This series can contain data for the historic and forecast period. Note: this is never used in the code, because there can be only one outputVariable.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ErrorModelInterpolationComplexType">
		<sequence>
			<element name="interpolationType" type="fews:errorModelInterpolationEnumStringType"/>
			<element name="gapLength" type="int" minOccurs="0">
				<annotation>
					<documentation>Maximum allowed gap size that can be filled using interpolation.</documentation>
				</annotation>
			</element>
			<element name="defaultValue" type="float" minOccurs="0">
				<annotation>
					<documentation>Default value required for 'defaultValue' interpolation option. </documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="errorModelInterpolationEnumStringType">
		<restriction base="string">
			<enumeration value="defaultvalue"/>
			<enumeration value="linear"/>
			<enumeration value="block"/>
		</restriction>
	</simpleType>
	<complexType name="ErrorModelParametersComplexType">
		<sequence>
			<element name="parameter" type="fews:ErrorModelParameterComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Fixed parameters to use in the error model. You can reference a numeric location attribute with @ATTRIBUTE_ID@. The output location's attributes will be used.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ErrorModelParameterComplexType">
		<simpleContent>
			<extension base="fews:floatStringAttributeAndPropertyType">
				<attribute name="type" type="fews:errorModelParameterEnumStringType" use="required"/>
				<attribute name="order" use="required">
					<simpleType>
						<restriction base="int">
							<minInclusive value="1"/>
						</restriction>
					</simpleType>
				</attribute>
			</extension>
		</simpleContent>
	</complexType>
	<simpleType name="errorModelParameterEnumStringType">
		<restriction base="string">
			<enumeration value="ar"/>
			<enumeration value="ma"/>
		</restriction>
	</simpleType>
	<simpleType name="errorModelLogLevelEnumStringType">
		<restriction base="string">
			<enumeration value="error">
				<annotation>
					<documentation>Log error message.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="warn">
				<annotation>
					<documentation>Log warning message.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="info">
				<annotation>
					<documentation>Log info message.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="debug">
				<annotation>
					<documentation>Log info message.</documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>
</schema>
