<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="userGroups.xsd"/>
	<!-- -->
	<element name="explorer" type="fews:ExplorerComplexType">
		<annotation>
			<documentation>root element</documentation>
		</annotation>
	</element>
	<!-- -->
	<complexType name="DocumentViewerComplexType">
		<sequence>
			<element name="hostCredentials" type="fews:HostCredentialComplexType" maxOccurs="unbounded"/>
			<element name="proxySettings" type="fews:ProxySettingsComplexType" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="HostCredentialComplexType">
		<sequence>
			<element name="hostName" type="string" minOccurs="0"/>
			<group ref="fews:UserAndPassword">
				<annotation>
					<documentation>User name and password used for http authentication</documentation>
				</annotation>
			</group>
		</sequence>
	</complexType>
	<complexType name="ProxySettingsComplexType">
		<sequence>
			<element name="hostName" type="string"/>
			<element name="port" type="fews:nonNegativeIntegerStringType" />
		</sequence>
	</complexType>
	<complexType name="ExplorerComplexType">
		<annotation>
			<documentation> Root element type. Groups all other elements</documentation>
		</annotation>
		<all>
			<element name="description" type="string" minOccurs="0"/>
			<element name="systemInformation" type="fews:SystemInformationComplexType"/>
			<element name="timeSeriesStatus" type="fews:timeSeriesStatusEnumStringType" minOccurs="0">
				<annotation>
					<documentation>Since 2016.01, FEWS-13813. In non operational systems it is possible to load the system status information from the server</documentation>
				</annotation>
            </element>
			<element name="globalDatum" type="string" minOccurs="0"/>
			<element name="localDatum" type="string" minOccurs="0"/>
			<element name="systemUnitsLabel" type="string" minOccurs="0">
				<annotation>
					<documentation>FEWS-8698. Used as label in tool bar</documentation>
				</annotation>
			</element>
			<element name="displayUnitsLabel" type="string" minOccurs="0">
				<annotation>
					<documentation>FEWS-8698. Used as label in tool bar</documentation>
				</annotation>
			</element>
			<element name="units" type="fews:unitSystemEnumStringType" default="user" minOccurs="0">
				<annotation>
					<documentation>FEWS-8698. Displayed units in the user interface by default</documentation>
				</annotation>
			</element>
			<element name="dateTime" type="fews:ExplorerDateTimeSettingsComplexType" minOccurs="0"/>
			<element name="mapPanelName" type="string" minOccurs="0">
				<annotation>
					<documentation>Since 2016.01,  (back-ported to 2014.02). Overrules the default caption of the map tab</documentation>
				</annotation>
			</element>
			<element name="map" type="fews:GeoMapComplexType" minOccurs="0"/>
			<element name="showThresholdWarningIcons" type="boolean" minOccurs="0" default="true"/>
			<element name="fileMenu" type="fews:FileMenuComplexType" minOccurs="0"/>
			<element name="temporaryImportFormats" type="fews:temporaryImportFormatsComplexType" minOccurs="0" />
			<element name="interactiveExportFormats" type="fews:interactiveExportFormatsComplexType" minOccurs="0"/>
			<element name="statusBarConfig" type="fews:StatusBarComplexType" minOccurs="0"/>
			<element name="locationHistoryBarRelativePeriod" type="fews:RelativePeriodComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2014.02. FEWS-11231</documentation>
				</annotation>
			</element>
			<element name="showLocationsOutsideVisibilityPeriod" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Since 2016.02 build 81728. Locations with a start and end time that does not include system time will be visible with a specific icon</documentation>
				</annotation>
			</element>
			<element name="explorerTasks" type="fews:ExplorerTasksComplexType"/>
			<element name="userDashboards" type="fews:UserDashboardsComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2020.02.</documentation>
				</annotation>
			</element>
			<element name="predefinedDashboards" type="fews:PredefinedDashboardsComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2019.02. Used to set properties such as permission for predefined dasbhoards found in the dashboards.ini in the RootConfigFiles.</documentation>
				</annotation>
			</element>
			<element name="logPanelConfig" type="fews:LogPanelConfigComplexType" minOccurs="0">
				<annotation>
					<documentation>NOTE: this feature is not supported anymore (since 2007).</documentation>
				</annotation>
			</element>
			<element name="panelSizes" type="fews:PanelSizesComplexType" minOccurs="0"/>
			<element name="panelHeaderLabels" type="fews:PanelHeadersComplexType" minOccurs="0"/>
			<element name="explorerOptions" type="fews:ExplorerOptionsComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated, only used in combination with openmap.properties, settings moved to map and statusBar</documentation>
				</annotation>
			</element>
			<element name="zoomExtents" type="fews:DeprecatedZoomExtentsComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated, only used in combination with openmap.properties, settings moved to map</documentation>
				</annotation>
			</element>
			<element name="statusBar" type="fews:DeprecatedStatusBarComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated, only used in combination with openmap.properties, settings moved to statusBarConfig</documentation>
				</annotation>
			</element>
			<element name="restSettings" type="fews:DeprecatedRestSettingsComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated, only used in combination with openmap.properties, setting moved to dateTime</documentation>
				</annotation>
			</element>
			<element name="rollingBarrelOptions" type="fews:RollingBarrelOptionsComplexType" minOccurs="0">
				<annotation>
					<documentation>By default the rolling barrel is started at startup and then every 30 minutes</documentation>
				</annotation>
			</element>
			<element name="autoLogin" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>When autoLogin is true,  OC logs in automatically with default MC and default profile.  Next, the user can choose another MC/profile by logging off and subsequent logging in.</documentation>
				</annotation>
			</element>
			<element name="loginMinimumBuildNumber" type="positiveInteger" minOccurs="0">
				<annotation>
					<documentation>Minimum required build number to login. When the user tries to login with a build older
                        than the minimum required build number. The user asked to upgrade client application.</documentation>
				</annotation>
			</element>
			<element name="loginEarliestAllowedLocalDataStoreCreationDate" type="fews:DateTimeComplexType" minOccurs="0">
				<annotation>
					<documentation>When the user tries to login with a local data store that is created before the specified date the local data store should be recreated. The client is restarted and new local datastore is created after a confirmation of the user</documentation>
				</annotation>
			</element>
			<element name="parameterListConfig" type="fews:DeprecatedParameterListComplexType" minOccurs="0">
				<annotation>
					<documentation>Used for sorting the parameter list.</documentation>
				</annotation>
			</element>
			<element name="notification" type="fews:NotificationComplexType" minOccurs="0"/>
			<element name="logEventNotification" type="fews:LogEventNotificationComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2017.01. A popup will be displayed when a log entry with one of the specified event code is added while the an OC is running. A popup will not be displayed for log events
						added before the OC was started
					</documentation>
				</annotation>
			</element>
			<element name="forecasterNotesNotification" type="fews:ForecasterNotesNotificationComplexType" minOccurs="0"/>
			<element name="piServicePortRange" type="fews:PortRangeComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2022.02 the REST based embedded tomcat webservices will be started using a port specified in the port range. If not configured the embedded web service will not start automatically</documentation>
				</annotation>
			</element>
			<element name="vjdbcServicePortRange" type="fews:PortRangeComplexType" minOccurs="0">
				<annotation>
					<documentation>Port number for embedded vjbdc service to run on. If not configured jdbc service will not start automatically</documentation>
				</annotation>
			</element>

			<element name="someSeriesCompletelyMissingIconVisible" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>When true an orange cross for a parameter/location/node is visible when some (but
						not all) series has no data. For backward compatibility this warning is switched off by default.
					</documentation>
				</annotation>
			</element>
			<element name="documentViewer" type="fews:DocumentViewerComplexType" minOccurs="0"/>
			<element name="defaultColorSchemes" type="fews:DefaultColorSchemesComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2014.01. Sets the default color schemes. If a user has previously selected another color scheme (in the GUI), this color scheme will be used instead of the scheme's defined here. Otherwise, the color scheme assigned to the users usergroup is used. If the users usergroup is not assigned to a color scheme, the default global color scheme is used.
					</documentation>
				</annotation>
			</element>
			<element name="numberOfTimeSeriesBlobsForWarning" type="int" minOccurs="0">
				<annotation>
					<documentation>Since 2014.01. FEWS-10196. Number for the amount of time series blobs in database that indicates when the OC should give a popup warning on startup that FEWS is not designed for unlimited amount of data. Default is 1000000
					</documentation>
				</annotation>
			</element>
			<element name="showIconForUnacknowledgedWarnings" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Show an opaque warning icon when unacknowledged log warnings present in database</documentation>
				</annotation>
			</element>
			<element name="ocConfigDirPermission" type="string" minOccurs="0">
				<annotation>
					<documentation>When a local config dir in the OC region home is detected the user is asked to restart using this config dir. This feature is for testing purposes and can be disabled for normal users by specifying a required permission.  Fews will always first start with the database config before asking to restart. The permission from the original config is used.</documentation>
				</annotation>
			</element>
			<element name="debugMenuPermission" type="string" minOccurs="0"/>
			<element name="localDataStoreSnapshotDownload" type="fews:LocalDataStoreSnapshotDownloadComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2018.02  Applicable only to SA systems using firebird.  Optionally enables replacing of the localDataStore with a snapshot</documentation>
				</annotation>
			</element>
		</all>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<complexType name="DeprecatedStatusBarComplexType">
		<annotation>
			<documentation>Deprecated, only used in combination with openmap.properties, setting moved to dateTime</documentation>
		</annotation>
		<all>
			<element name="dateTimeFormat" type="fews:dateTimeFormatType">
				<annotation>
					<documentation>specifies how date/time  must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0"/>
			<element name="logMessageSearchPeriod" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated, ignored</documentation>
				</annotation>
			</element>
		</all>
	</complexType>
	<complexType name="ExplorerDateTimeSettingsComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<choice maxOccurs="unbounded">
				<element name="timeZoneOffset" type="fews:timeZoneOffsetStringType">
					<annotation>
						<documentation>This time zone will be used to show date/time in the GUI (time series editor, status bar, t0 of the forecasts ,..)</documentation>
					</annotation>
				</element>
				<element name="timeZoneName" type="fews:timeZoneStringType">
					<annotation>
						<documentation>This time zone will be used to show date/time in the GUI (time series editor, status bar, t0 of the forecasts ,..)</documentation>
					</annotation>
				</element>
			</choice>
			<element name="dateTimeFormat" type="fews:dateTimeFormatType">
				<annotation>
					<documentation>specifies how date/time should be displayed in FEWS except the clock in the status bar. see http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html</documentation>
				</annotation>
			</element>
			<element name="cardinalTimeStep" type="fews:TimeStepComplexType">
				<annotation>
					<documentation>Specifies the time step for entering the date/time in Explorer GUI</documentation>
				</annotation>
			</element>
			<element name="adjustSystemTimeAutomatically" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Specifies if the explorer's system time is adjusted automatically or not. Default: false for stand alone true for operational client. Since 2017.02, if not configured as true for a stand-alone, the system time will be stored in and read from the user settings.</documentation>
				</annotation>
			</element>
			<element name="systemTimeTrigger" type="fews:SystemTimeTriggerComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2014.01. Use this option to update the system time with the latest (external) forecast time of  all the specified time series.  If both external and simulated forecast series are configured, the latest forecast time of all the configured series will be used.  This option wil work only if the automatic updating of system time is allowed, typically it is in OC or if the option adjustSystemTimeAutomatically is true.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SystemTimeTriggerComplexType">
		<sequence>
			<element name="externalForecastTimeSeries" type="fews:TimeSeriesSetComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>The latest external forecast time of  all the specified time series is used to update system time</documentation>
				</annotation>
			</element>
			<element name="simulatedForecastTimeSeries" type="fews:TimeSeriesSetComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>The latest  forecast time of  all the specified time series is used to update system time</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="DeprecatedRestSettingsComplexType">
		<annotation>
			<documentation>groups simple configuration elements  that are left over i.e. not assigned to other complex types</documentation>
		</annotation>
		<all>
			<element name="defaultSelectedFilterId" type="fews:idStringType">
				<annotation>
					<documentation>Filter that should be default selected in the filter list box</documentation>
				</annotation>
			</element>
			<element name="geoDatum" type="fews:geoDatumStringType">
				<annotation>
					<documentation>geoDatum of the coordinates specified in the Explorer.xml </documentation>
				</annotation>
			</element>
			<element name="dateTimeFormat" type="fews:dateTimeFormatType">
				<annotation>
					<documentation>specifies how date/time should be displayed in the GUI's to view/edit time series</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0"/>
			<element name="cardinalTimestep" type="fews:TimeStepComplexType">
				<annotation>
					<documentation>Specifies the time step for entering the date/time  in Explorer GUI</documentation>
				</annotation>
			</element>
			<element name="timeZone" type="fews:TimeZoneComplexType" minOccurs="0">
				<annotation>
					<documentation>time zone in NFFS  will be set to this value. The time zone wil used to show date/time in the GUI (time series editor, status bar,  t0 of the forecasts ,..)</documentation>
				</annotation>
			</element>
		</all>
	</complexType>
	<!-- -->
	<!-- -->
	<complexType name="DeprecatedZoomExtentComplexType">
		<annotation>
			<documentation> zoomExtend type</documentation>
		</annotation>
		<all>
			<element name="left" type="float">
				<annotation>
					<documentation>X (latitude) of the upper left corner</documentation>
				</annotation>
			</element>
			<element name="right" type="float">
				<annotation>
					<documentation>X (latitude) of the lower right corner</documentation>
				</annotation>
			</element>
			<element name="top" type="float">
				<annotation>
					<documentation>Y (longitude) of the upper left corner</documentation>
				</annotation>
			</element>
			<element name="bottom" type="float">
				<annotation>
					<documentation>Y (longitude) of the lower right corner</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0"/>
			<element name="mnemonic" type="string">
				<annotation>
					<documentation>shortcut to the zoom extent</documentation>
				</annotation>
			</element>
		</all>
		<attribute name="title" type="fews:nameStringType" use="optional"/>
	</complexType>
	<!-- -->
	<!-- -->
	<complexType name="ExplorerTaskComplexType">
		<annotation>
			<documentation>explorerTask type</documentation>
		</annotation>
		<sequence>
			<element name="iconFile" type="string" minOccurs="0">
				<annotation>
					<documentation>icon that must be displayed in the toolbar button in the case that the task appears in the toolbar </documentation>
				</annotation>
			</element>
			<element name="mnemonic" type="string" minOccurs="0">
				<annotation>
					<documentation>shortcut to the task</documentation>
				</annotation>
			</element>
			<choice>
				<element name="displayConfigFileName" type="string">
					<annotation>
						<documentation>Since 2013.02. Config file of the display. The display to start is recognized by the schema name in the config file. The xml file should use one of the following xsd-s:  archivemoduledisplay.xsd, forecasteraidselectionpanel.xsd, forecasternotesdisplay.xsd, griddisplay.xsd, longitudinaldisplay.xsd, lookupdisplay.xsd, manualforecastdisplay.xsd, modifierdisplay.xsd, moduleruntabledisplay.xsd, objectiveanalyzerdisplay.xsd, prtfdisplay.xsd, runinfopanel.xsd, scadadisplay.xsd, systemmonitordisplay.xsd, taskrundialog.xsd, timeseriestabledisplay.xsd, thresholdoverviewdisplay.xsd, thresholdskillscoredisplay.xsd, trenddisplay.xsd, webservice.xsd, whatifscenarioeditor.xsd, whatifscenariofilters.xsd</documentation>
					</annotation>
				</element>
				<element name="predefinedDisplay" type="fews:predefinedDisplayEnumStringType">
					<annotation>
						<documentation>Since 2013.02. Display without display config file</documentation>
					</annotation>
				</element>
				<sequence>
					<element name="arguments" type="string" minOccurs="0">
						<annotation>
							<documentation>arguments of the task</documentation>
						</annotation>
					</element>
					<element name="workDir" type="string" minOccurs="0">
						<annotation>
							<documentation>working directory of the task</documentation>
						</annotation>
					</element>
					<choice>
						<sequence>
							<element name="taskClass" type="string">
								<annotation>
									<documentation>Deprecated and obsolete since 2013.02. class associated with the task. Use displayConfigFileName or predefinedDisplay</documentation>
								</annotation>
							</element>
							<element name="binDir" type="string" minOccurs="0">
								<annotation>
									<documentation>Unsupported feature. Custom bin dir with the jar file that contains the specified taskClass</documentation>
								</annotation>
							</element>
						</sequence>
						<element name="taskExe" type="string">
							<annotation>
								<documentation>executable associated with the task</documentation>
							</annotation>
						</element>
						<element name="taskUrl" type="string">
							<annotation>
								<documentation>opens an url</documentation>
							</annotation>
						</element>
						<element name="separator" type="fews:SeparatorComplexType">
							<annotation>
								<documentation>specifies a separator in the menu or toolbar. In this case only the elements 'menuBarTask' and 'toolbarTask' are used to determine whether the separator must be placed in the menu, or toolbar or both. All other elements are ignored.</documentation>
							</annotation>
							<!--arguments and work dir are allowed for separator for backward compatibility-->
						</element>
					</choice>
				</sequence>
				<sequence>
					<element name="pluginPanelClass" type="string">
						<annotation>
							<documentation>Since 2020.02 The class of the plugin panel. The class should extend JPanel!</documentation>
						</annotation>
					</element>
					<element name="pluginPanelFactoryMethod" type="string">
						<annotation>
							<documentation>Since 2020.02 The static method of the class which creates the panel.</documentation>
						</annotation>
					</element>
					<element name="pluginPanelFactoryMethodArguments" type="string" minOccurs="0">
						<annotation>
							<documentation>deprecated, please use on or more pluginPanelFactoryMethodArgument elements (see below) instead</documentation>
						</annotation>
					</element>
					<element name="pluginPanelFactoryMethodArgument" type="string" minOccurs="0" maxOccurs="10">
						<annotation>
							<documentation>Since 2023.02 one or more arguments of the factory method</documentation>
						</annotation>
					</element>
					<element name="pluginPanelBinDir" type="string" minOccurs="0">
						<annotation>
							<documentation>Since 2020.02 The bin dir which contains all files for the custom panel.</documentation>
						</annotation>
					</element>
				</sequence>

			</choice>
			<element name="description" type="string" minOccurs="0"/>
			<element name="toolbarTask" type="fews:ToolbarTaskComplexType" minOccurs="0">
				<annotation>
					<documentation>indication whether the task should appear as a button in the toolbar.
						When set this to true you have to set menu barTask to true to put the task also in the menu bar</documentation>
				</annotation>
			</element>
			<element name="menubarTask" type="boolean" minOccurs="0">
				<annotation>
					<documentation>indication whether the task should  appear in the menu bar.</documentation>
				</annotation>
			</element>
			<element name="menu" type="fews:menuEnumStringType" minOccurs="0">
				<annotation>
					<documentation>Adds the task in the file menu or in the tools menu, default is tools menu.</documentation>
				</annotation>
			</element>
			<element name="allowMultipleInstances" type="boolean" minOccurs="0">
				<annotation>
					<documentation>indication whether more than one instance of a task can be run at the same time</documentation>
				</annotation>
			</element>
			<element name="accelerator" type="string" minOccurs="0">
				<annotation>
					<documentation>Shortcut key. Note that the shortcut keys only work for tasks in the menu bar (set menuBarTask to true).
Specify as follows:  modifiers* (typeID | pressedReleasedID).
Example modifiers: shift, control, ctrl, alt, meta,.... 
EXAMPLES shortcuts: shift X,  alt shift  X, alt shift released X, control DELETE, INSERT</documentation>
				</annotation>
			</element>
			<element name="doubleClickLocationEnabled" type="boolean" minOccurs="0">
				<annotation>
					<documentation>When double clicked at a location at the map or in the list all the tasks with
                    doubleClickLocationEnabled set to true are started. The location is selected BEFORE
                    the tasks are started. E.g. You can start the time series dialog and jump to the shortcut chart of the clicked location</documentation>
				</annotation>
			</element>
			<element name="permission" type="string" minOccurs="0"/>
			<element name="toolWindow" type="boolean" minOccurs="0">
				<annotation>
					<documentation>In docking mode displays can be loaded as tool windows or as content. If this field is
                        missing then the display will automatically loaded as content.
                    </documentation>
				</annotation>
			</element>
			<element name="loadAtStartup" type="boolean" minOccurs="0">
				<annotation>
					<documentation>In docking mode some windows need to be loaded when the system starts. For these
                        windows the field must be set to true.
                    </documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<!--empty string for name is allowed for backwards compatibility, fews:nameStringType does not allow empty strings anymore-->
	</complexType>
	<!---->
	<complexType name="DeprecatedZoomExtentsComplexType">
		<annotation>
			<documentation> groups zoomExtent elements</documentation>
		</annotation>
		<sequence>
			<element name="zoomExtent" type="fews:DeprecatedZoomExtentComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Zoom extent in the Zoom menu</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ExplorerTasksComplexType">
		<annotation>
			<documentation>Groups explorerTasks and submenus containg explorerTasks </documentation>
		</annotation>
		<choice maxOccurs="unbounded">
			<element name="explorerTask" type="fews:ExplorerTaskComplexType">
				<annotation>
					<documentation>Task in the toolbar, or in the menu Tools, or in both </documentation>
				</annotation>
			</element>
			<element name="subMenu" type="fews:ExplorerTasksSubMenuComplexType">
				<annotation>
					<documentation>Since 2015.02 Sub menu containing explorerTasks and/or sub menus</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>

	<complexType name="DashboardComplexType">
		<sequence>
			<element name="permission" type="string" minOccurs="0">
				<annotation>
					<documentation>Only users with the configured permission will be able to see this predefined dashboard. By default, all users can see the dashboard.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required">
			<annotation>
				<documentation>Name of the predefined dashboard to which the configured settings should be applied. Case-sensitive.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="UserDashboardsComplexType">
		<sequence>
			<element name="enabled" type="boolean"/>
			<element name="permission" type="string" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="PredefinedDashboardsComplexType">
		<sequence>
			<element name="dashboard" type="fews:DashboardComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Allows setting properties such as permissions for a predefined dashboard present in the dashboards.ini file in the RootConfigFiles.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="LogPanelConfigComplexType">
		<annotation>
			<documentation>logging panel configuration</documentation>
		</annotation>
		<sequence>
			<element name="clientFilter" type="fews:ClientFilterComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!---->
	<complexType name="ClientFilterComplexType">
		<annotation>
			<documentation>log filter definitions per client</documentation>
		</annotation>
		<sequence>
			<element name="clientId" type="fews:idStringType">
				<annotation>
					<documentation>One of the ClientType's from clientConfig.xsd must be specified</documentation>
				</annotation>
			</element>
			<element name="logFilter" type="fews:LogFilterComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Specifies which log events will be printed to the log panel.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="LogFilterComplexType">
		<annotation>
			<documentation> log filter definition </documentation>
		</annotation>
		<sequence>
			<element name="level" type="fews:logLevelEnumStringType">
				<annotation>
					<documentation>Messages with this log level and higher will be logged to the log panel. One of the logLevelType's from eventTypes.xsd must be specified</documentation>
				</annotation>
			</element>
			<element name="eventType">
				<annotation>
					<documentation>Indicates which events will be logged to the log panel. Presently system or debug events.</documentation>
				</annotation>
				<simpleType>
					<restriction base="string">
						<enumeration value="system"/>
						<enumeration value="debug"/>
					</restriction>
				</simpleType>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="StatusBarComplexType">
		<annotation>
			<documentation>Status bar settings and options. The user can change these options through Options -> Explorer Options on the Status Bar tab. If the user uses this dialog, the chosen settings will be stored in the user settings and the stored values will overrule the configuration.</documentation>
		</annotation>
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="dateTimeFormat" type="fews:dateTimeFormatType">
				<annotation>
					<documentation>specifies how current time (clock) must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="timeGMT" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether the current GMT time must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="timeCurrent" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether the current local time must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="timeLastRefresh" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether the time of the last forecast refresh must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="statusOfSystem" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether the system status must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="mouseCoordinates" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether the mouse coordinates must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="userName" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether the user name must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="userGroup" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether the user group must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="logMessageSearchPeriod" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated, ignored</documentation>
				</annotation>
			</element>
			<element name="systemTimePauseButton" type="fews:SystemTimePauseButtonComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2014.01. With systemTimePauseButton we can pause (and start again) the automatic adjusting of the system time</documentation>
				</annotation>
			</element>
			<element name="scheduledTaskEndWarning" type="fews:ScheduledTaskEndWarningComplexType" minOccurs="0"/>
		</sequence>
	</complexType>
	<!---->
	<complexType name="ScheduledTaskEndWarningComplexType">
		<sequence>
			<element name="color" type="fews:colorStringType"/>
			<element name="time" type="fews:TimeSpanComplexType"/>
		</sequence>
	</complexType>
	<!---->
	<complexType name="PanelSizesComplexType">
		<annotation>
			<documentation>Used to determine default panel sizes. The panel sizes of the filter/location/parameter/qualifier/forecast panels will be stored in the user settings after the first use, which will overrule these default settings. If no panelSizes element is configured, the weights for the filter, location, parameter, qualifier and forecast panel will be 10, 25, 20, 20 and 5 respectively (and the qualifier panel will be hidden if the configuration contains no qualifiers).</documentation>
		</annotation>
		<sequence>
			<element name="loggingPanelSize" type="fews:percentageType" minOccurs="0">
				<annotation>
					<documentation>in % of the main window height. Deprecated, only used if docking=false in global properties</documentation>
				</annotation>
			</element>
			<element name="listsPanelSize" type="fews:percentageType" minOccurs="0">
				<annotation>
					<documentation>in % of the main window width. Deprecated, only used if docking=false in global properties</documentation>
				</annotation>
			</element>
			<element name="filterListSize" type="nonNegativeInteger">
				<annotation>
					<documentation>Weight of the filter panel. The % of the data viewer panel which will consist of the filter panel is equal to this weight divided by the total weight of all data viewer panels.</documentation>
				</annotation>
			</element>
			<element name="locationListSize" type="nonNegativeInteger">
				<annotation>
					<documentation>Weight of the location panel. The % of the data viewer panel which will consist of the location panel is equal to this weight divided by the total weight of all data viewer panels.</documentation>
				</annotation>
			</element>
			<element name="parameterListSize" type="nonNegativeInteger">
				<annotation>
					<documentation>Weight of the parameter panel. The % of the data viewer panel which will consist of the parameter panel is equal to this weight divided by the total weight of all data viewer panels.</documentation>
				</annotation>
			</element>
			<element name="qualifierListSize" type="nonNegativeInteger" minOccurs="0">
				<annotation>
					<documentation>Weight of the qualifier panel. If set to 0, the qualifier panel will be hidden. The % of the data viewer panel which will consist of the qualifier panel is equal to this weight divided by the total weight of all data viewer panels. Default: 20.</documentation>
				</annotation>
			</element>
			<element name="forecastListSize" type="nonNegativeInteger">
				<annotation>
					<documentation>Weight of the forecast panel. If set to 0, the forecast panel will be hidden. The % of the data viewer panel which will consist of the forecast panel is equal to this weight divided by the total weight of all data viewer panels.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="SystemInformationComplexType">
		<annotation>
			<documentation>system settings and options</documentation>
		</annotation>
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="systemCaption" type="string">
				<annotation>
					<documentation>Title that appears in the Fews Explorer title bar.</documentation>
				</annotation>
			</element>
			<element name="appendVersionInformationToSystemCaption" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Appends the buildnumber to the systemCaption in the Fews Explorer title bar</documentation>
				</annotation>
			</element>
			<choice>
				<element name="systemHelpFile" type="string" minOccurs="0">
					<annotation>
						<documentation>Name of the Fews help file</documentation>
					</annotation>
				</element>
				<element name="systemHelpUrl" type="anyURI" minOccurs="0">
					<annotation>
						<documentation>Since 2014.02 (build 56720) Url to a FEWS help web page. This can be any url.</documentation>
					</annotation>
				</element>
			</choice>
			<element name="regionId" type="string" minOccurs="0">
				<annotation>
					<documentation>Explicitly set Region Id. Overrules default ID obtained from the Region Home directory </documentation>
				</annotation>
			</element>
			<element name="licenceNumber" type="string" minOccurs="0">
				<annotation>
					<documentation>Available since 2025.01. Allows to configure the licence number of the end user that will be displayed in the about dialog.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="ExplorerOptionsComplexType">
		<annotation>
			<documentation>Deprecated, only used in combination with openmap.properties, status bar elements moved to status bar settings</documentation>
		</annotation>
		<all>
			<element name="legendScale" type="boolean">
				<annotation>
					<documentation>Indicates whether the legend scale must be displayed on the map</documentation>
				</annotation>
			</element>
			<element name="scaleBar" type="boolean">
				<annotation>
					<documentation>Indicates whether the scale bar must be displayed on the map</documentation>
				</annotation>
			</element>
			<element name="mapLayersLegend" type="boolean">
				<annotation>
					<documentation>Indicates whether the map layers legend must be displayed on the map</documentation>
				</annotation>
			</element>
			<element name="northArrow" type="boolean">
				<annotation>
					<documentation>Indicates whether the north arrow must be displayed on the map</documentation>
				</annotation>
			</element>
			<element name="dataOnStations" type="boolean">
				<annotation>
					<documentation>Indicates whether the data must be displayed near to the station on the map</documentation>
				</annotation>
			</element>
			<element name="timeGMT" type="boolean">
				<annotation>
					<documentation>Indicates whether the current GMT time must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="timeCurrent" type="boolean">
				<annotation>
					<documentation>Indicates whether the current local time must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="timeLastRefresh" type="boolean">
				<annotation>
					<documentation>Indicates whether the time of the last forecast refresh must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="statusOfSystem" type="boolean">
				<annotation>
					<documentation>Indicates whether the system status must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="mouseCoordinates" type="boolean">
				<annotation>
					<documentation>Indicates whether the mouse coordinates must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="userName" type="boolean">
				<annotation>
					<documentation>Indicates whether the user name must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="userGroup" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether the user group must be displayed in the status bar</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0"/>
		</all>
	</complexType>
	<complexType name="RollingBarrelOptionsComplexType">
		<sequence>
			<element name="type" type="fews:rollingBarrelEnumStringType"/>
			<element name="interval" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Default is 30 minutes</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="SeparatorComplexType">
		<annotation>
			<documentation>Empty type to specify the separator in the menu and or toolbar. </documentation>
		</annotation>
	</complexType>
	<!-- -->
	<simpleType name="rollingBarrelEnumStringType">
		<restriction base="string">
			<enumeration value="startup_only"/>
			<enumeration value="shutdown_only"/>
			<enumeration value="interval"/>
			<enumeration value="not_automatic"/>
		</restriction>
	</simpleType>
	<!---->
	<simpleType name="menuEnumStringType">
		<restriction base="string">
			<enumeration value="file"/>
			<enumeration value="tools"/>
		</restriction>
	</simpleType>
	<!---->
	<complexType name="PanelHeadersComplexType">
		<annotation>
			<documentation>optional header labels for the lists in the main window (location, parameters, etc.)</documentation>
		</annotation>
		<sequence>
			<element name="filterPanelHeader" type="string" minOccurs="0"/>
			<element name="locationPanelHeader" type="fews:PanelHeaderComplexType" minOccurs="0"/>
			<element name="parameterPanelHeader" type="fews:PanelHeaderComplexType" minOccurs="0"/>
			<element name="qualifierPanelHeader" type="fews:PanelHeaderComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2015.02 optional header label for qualifier panel in data viewer</documentation>
				</annotation>
			</element>
			<element name="forecastPanelHeader" type="string" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="NotificationComplexType">
		<annotation>
			<documentation>Settings for notifications (e.g. popups)</documentation>
		</annotation>
		<attribute name="enabled" type="boolean" use="required"/>
	</complexType>
	<complexType name="LogEventNotificationComplexType">
		<sequence>
			<element name="eventCodeId" type="fews:idStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>One of the event codes of the event codes that triggers the popup</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ForecasterNotesNotificationComplexType">
		<annotation>
			<documentation>If enabled , a notification will popup when a new forecaster note arrives. Forecaster note is a log messages created manually by the user in the ForecasterNotesDisplay or in BulletinBoard(Plus)</documentation>
		</annotation>
		<choice minOccurs="0">
			<element name="eventCode" type="fews:EventCodeComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>DEPRECATED sinds 2015.02.   If any 'eventCode' is configured, a notifications only pop ups if a message with this code arrives.  ExpiryTime configured at this place is always ignored </documentation>
				</annotation>
			</element>
			<element name="eventCodeId" type="fews:idStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>Since 2015.02 If any 'eventCodeId' is configured, a notifications only pop ups if a message with this code arrives.</documentation>
				</annotation>
			</element>
		</choice>
		<attribute name="enabled" type="boolean" use="required"/>
	</complexType>
	<!---->
	<complexType name="PortRangeComplexType">
		<annotation>
			<documentation>Settings for finding of a free port to create PiService</documentation>
		</annotation>
		<attribute name="start" use="required" type="fews:positiveIntegerStringType">
			<annotation>
				<documentation>port number to start the searching from</documentation>
			</annotation>
		</attribute>
		<attribute name="end" use="required" type="fews:positiveIntegerStringType">
			<annotation>
				<documentation>last port number for searching</documentation>
			</annotation>
		</attribute>
	</complexType>
	<!---->
	<complexType name="MenuItemComplexType">
		<attribute name="visible" type="boolean" default="false"/>
	</complexType>
	<!---->
	<complexType name="FileMenuComplexType">
		<sequence>
			<element name="openMostRecentCurrentForecast" type="fews:MenuItemComplexType" minOccurs="0">
				<annotation>
					<documentation>Open most recent current forecast and adjust system time</documentation>
				</annotation>
			</element>
			<element name="openMostRecentForecast" type="fews:MenuItemComplexType" minOccurs="0">
				<annotation>
					<documentation>Open most recent forecast and adjust system time</documentation>
				</annotation>
			</element>
			<element name="openLastForecast" type="fews:MenuItemComplexType" minOccurs="0">
				<annotation>
					<documentation>Open last forecast for selection</documentation>
				</annotation>
			</element>
			<element name="setSystemTimeToLast" type="fews:MenuItemComplexType" minOccurs="0">
				<annotation>
					<documentation>Set system time to last available</documentation>
				</annotation>
			</element>
			<element name="exportTimeSeries" type="fews:MenuItemComplexType" minOccurs="0">
				<annotation>
					<documentation>Export the time series, selected in the Explorer filters, to the chosen file format</documentation>
				</annotation>
			</element>
			<element name="deleteLocalDataStore" type="fews:MenuItemComplexType" minOccurs="0">
				<annotation>
					<documentation>Deletes the local datastore. Not visible in DDA mode</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="DeprecatedParameterListComplexType">
		<annotation>
			<documentation>Used for sorting the parameter list.
            </documentation>
		</annotation>
		<sequence>
			<element name="sortOption" type="fews:parameterSortOptionEnumStringType">
				<annotation>
					<documentation>Specifies how the parameter list must be sorted: default (as configured in
                        Parameters.xml) or by name.
                    </documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="parameterSortOptionEnumStringType">
		<restriction base="string">
			<enumeration value="default"/>
			<enumeration value="name"/>
		</restriction>
	</simpleType>
	<simpleType name="interactiveExportTypeEnumStringType">
		<restriction base="string">
			<enumeration value="pi-xml"/>
			<enumeration value="gin-xml"/>
			<enumeration value="csv"/>
			<enumeration value="dutch-csv"/>
			<enumeration value="csvdutch"/>
			<enumeration value="csvwithquality"/>
			<enumeration value="csvdutchwithquality"/>
			<enumeration value="generalCsv">
				<annotation>
					<documentation>Since 2014.02. FEWS-11939. Flexible CSV file format where the columns have to be specified in the 'table' element. This export type is available for and can be used multiple times as interactive time series export format</documentation>
				</annotation>
			</enumeration>
			<enumeration value="iBever"/>
			<enumeration value="kwaliteit-csv"/>
			<enumeration value="Hymos 4.03">
				<annotation>
					<documentation>Obsolete, not supported any more</documentation>
				</annotation>
			</enumeration>
			<enumeration value="Hymos 4.5">
				<annotation>
					<documentation>Obsolete, not supported any more</documentation>
				</annotation>
			</enumeration>
			<enumeration value="Menyanthes"/>
			<enumeration value="UM-Aquo">
				<annotation>
					<documentation>Obsolete, not supported any more</documentation>
				</annotation>
			</enumeration>
			<enumeration value="UM-Aquo-2009">
				<annotation>
					<documentation>Obsolete, not supported any more</documentation>
				</annotation>
			</enumeration>
			<enumeration value="dino-tuf"/>
		</restriction>
	</simpleType>
	<complexType name="temporaryImportFormatsComplexType">
		<sequence>
			<element name="temporaryImportFormat" type="fews:temporaryImportFormatComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="temporaryImportFormatComplexType">
		<sequence>
			<element name="name" type="string"/>
			<element name="table" type="fews:TableMetadataComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2022.02. FEWS-27628. Table layout description to specify column types of temporary import for CSV format</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="interactiveExportFormatsComplexType">
		<sequence>
			<element name="exportUnreliablePermission" type="string" minOccurs="0">
				<annotation>
					<documentation>Since 2016.01 #66715. When users don't have this permission unreliable values can not be exported
					</documentation>
				</annotation>
			</element>
			<element name="exportDoubtfulPermission" type="string" minOccurs="0">
				<annotation>
					<documentation>Since 2016.01 #66715. When users don't have this permission doubtful values can not be exported
					</documentation>
				</annotation>
			</element>
			<element name="interactiveExportFormat" type="fews:interactiveExportFormatComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="interactiveExportFormatComplexType">
		<sequence>
			<element name="name" type="string"/>
			<choice>
				<element name="exportType" type="fews:interactiveExportTypeEnumStringType"/>
				<sequence>
					<element name="serializerClassName" type="string">
						<annotation>
							<documentation>Fully qualifying name of a Java class that implements a time series serializer
								interface.
							</documentation>
						</annotation>
					</element>
					<element name="binDir" type="string" minOccurs="0">
						<annotation>
							<documentation>Directory with jar files and optionally native dlls. When not specified the
								bin dir and class loader of FEWS is used.
								When specified the java class is executed in a private class loader, it will not use any
								jar in the FEWS bin dir. Only one class loader is created per binDir
								, adapters should still not use static variables
							</documentation>
						</annotation>
					</element>
					<element name="fileFilter" type="string">
						<annotation>
							<documentation>File filter extension expected by serializer. </documentation>
						</annotation>
					</element>
					<element name="exportUnreliable" type="boolean" minOccurs="0">
						<annotation>
							<documentation>Indicates if this export format can export unreliable values. Defaults to false</documentation>
						</annotation>
					</element>
					<element name="properties" type="fews:PropertiesComplexType" minOccurs="0">
						<annotation>
							<documentation>Since 2010.02, Properties that are passed to the serializer. Very few external third party serializer need additional configuration. See documentation of the external third party serializer you are using.
                            </documentation>
						</annotation>
					</element>
				</sequence>
			</choice>
			<element name="IdMapId" type="string"/>
			<choice minOccurs="0">
				<element name="timeZoneOffset" type="fews:timeZoneOffsetStringType">
					<annotation>
						<documentation>This time zone offset will be used for the date and time in the export</documentation>
					</annotation>
				</element>
				<element name="timeZoneName" type="fews:timeZoneStringType">
					<annotation>
						<documentation>This time zone will be used for the date and time in the export</documentation>
					</annotation>
				</element>
			</choice>
			<element name="unitConversionsId" type="string" minOccurs="0"/>
			<element name="flagConversionsId" type="string" minOccurs="0"/>
			<choice minOccurs="0">
				<element name="exportMissingValue" type="double">
					<annotation>
						<documentation>Missing value definition for this time series. Defaults to NaN if not defined.</documentation>
					</annotation>
				</element>
				<element name="exportMissingValueString" type="string"/>
			</choice>
			<element name="table" type="fews:TableMetadataComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2014.02. FEWS-11939. Table layout description to specify column types of export format</documentation>
				</annotation>
			</element>
			<element name="convertValuesToEnumerationLabels" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Since 2017.01 Applies only to time series that are associated with a time series value enumeration (see Parameters.xsd). If this option is true, then the enumeration
						label is written to the file, and not the numerical value . Please note that this option is only applicable to those file formats where time series values can be stored as
						strings, for example CSV formats
					</documentation>
				</annotation>
			</element>
			<element name="exportAttribute" type="fews:ExportAttributeType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Since 2015.02. Location, Parameter or Qualifier attribute that can be used for export. Specification is needed to include it in the data available for export</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="predefinedDisplayEnumStringType">
		<restriction base="string">
			<enumeration value="time series dialog">
				<annotation>
					<documentation>
						Time Series Dialog
					</documentation>
				</annotation>
			</enumeration>
			<enumeration value="time series lister">
				<annotation>
					<documentation>
						time series lister
					</documentation>
				</annotation>
			</enumeration>
			<enumeration value="tabular config files display">
				<annotation>
					<documentation>Shows the tabular config files associated to the data viewer (explorer) selection</documentation>
				</annotation>
			</enumeration>
			<enumeration value="plot overview">
				<annotation>
					<documentation>
						plot overview
					</documentation>
				</annotation>
			</enumeration>
			<enumeration value="documents">
				<annotation>
					<documentation>
						documents
					</documentation>
				</annotation>
			</enumeration>
			<enumeration value="topology tree">
				<annotation>
					<documentation>
						topology tree
					</documentation>
				</annotation>
			</enumeration>
			<enumeration value="topology diagram">
				<annotation>
					<documentation>
						topology diagram
					</documentation>
				</annotation>
			</enumeration>
			<enumeration value="forecast management">
				<annotation>
					<documentation>
						forecast management
					</documentation>
				</annotation>
			</enumeration>
			<enumeration value="workflow navigator">
				<annotation>
					<documentation>
						workflow navigator
					</documentation>
				</annotation>
			</enumeration>
			<enumeration value="sample viewer">
				<annotation>
					<documentation>Since 2014.02</documentation>
				</annotation>
			</enumeration>
			<enumeration value="attribute filter">
				<annotation>
					<documentation>Since 2015.02 attribute filter</documentation>
				</annotation>
			</enumeration>
			<enumeration value="interval statistics">
				<annotation>
					<documentation>Since 2015.02 interval statistics</documentation>
				</annotation>
			</enumeration>
			<enumeration value="forecast product info">
				<annotation>
					<documentation>Since 2019.01 forecast product info</documentation>
				</annotation>
			</enumeration>
			<enumeration value="web browser">
				<annotation>
					<documentation>Since 2018.02 Web Browser Display using JCEF (Chromium Embedded)</documentation>
				</annotation>
			</enumeration>
			<enumeration value="annotation display">
				<annotation>
					<documentation>Since 2021.01</documentation>
				</annotation>
			</enumeration>
			<enumeration value="what if editor">
				<annotation>
					<documentation>Since 2022.01</documentation>
				</annotation>
			</enumeration>
			<enumeration value="threshold events display">
				<annotation>
					<documentation>Since 2023.01</documentation>
				</annotation>
			</enumeration>

		</restriction>
	</simpleType>
	<complexType name="SystemTimePauseButtonComplexType">
		<attribute name="visible" type="boolean" use="required">
			<annotation>
				<documentation>If  true, an icon 'pause'  or 'go' appears to the left of system time in the Explorer status bar.  Toggle this icon to stop or start automatic adjusting of system time	</documentation>
			</annotation>
		</attribute>
		<attribute name="paused" type="boolean" use="optional" default="false">
			<annotation>
				<documentation>Indicates if the system time should be paused after Fews start up. Default false	</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="DefaultColorSchemesComplexType">
		<sequence>
			<element name="defaultColorSchemeId" type="string">
				<annotation>
					<documentation>The global default color scheme, by default this is the first color scheme defined in the ColorSchemes.xml. If a user has not previously selected a color scheme, and is not part of a usergroup for which a different color scheme is defined, this color scheme is used by FEWS on start-up. If this is set to "no color scheme", FEWS will start with no color scheme applied.</documentation>
				</annotation>
			</element>
			<element name="defaultColorSchemeForGroup" type="fews:DefaultColorSchemeForGroupComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Defines a default color scheme for a certain user group. If a user in this group starts FEWS, and has not selected a different color scheme in a previous session, this color scheme will be used.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="DefaultColorSchemeForGroupComplexType">
		<sequence>
			<element name="userGroup" type="fews:UserGroupId" maxOccurs="unbounded">
				<annotation>
					<documentation>The id of the user group for which the default color scheme is to be applied.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="colorSchemeId" type="string">
			<annotation>
				<documentation>The id of the color scheme which is to be used as the default color scheme for this user group. If this is set to "no color scheme", FEWS will apply no color scheme for this group (by default).</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="ExplorerTasksSubMenuComplexType">
		<choice maxOccurs="unbounded">
			<element name="explorerTask" type="fews:ExplorerTaskComplexType">
				<annotation>
					<documentation>Task in the toolbar, or in the menu Tools, or in both</documentation>
				</annotation>
			</element>
			<element name="subMenu" type="fews:ExplorerTasksSubMenuComplexType">
				<annotation>
					<documentation>Sub menu containing explorerTasks and/or sub menus</documentation>
				</annotation>
			</element>
		</choice>
		<attribute name="name" type="fews:nonEmptyStringType" use="required">
			<annotation>
				<documentation>caption to display in the sub menu item</documentation>
			</annotation>
		</attribute>
	</complexType>
	<simpleType name="timeSeriesStatusEnumStringType">
		<restriction base="string">
			<enumeration value="current status">
				<annotation>
					<documentation>All the time series icons always represent the current situation. This is the default</documentation>
				</annotation>
			</enumeration>
			<enumeration value="remotely updated snapshot">
				<annotation>
					<documentation>The external historical time series icons always represent the situation from the time of creation of a snapshot stored in the central database. This snapshot is updated with a special workflow. When the configured view period in the filters goes back far in time updating the status info on the map and data viewer will take a long time and cause a huge load in the central database when using DDA. </documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>
	<complexType name="LocalDataStoreSnapshotDownloadComplexType">
		<annotation>
			<documentation>localDataStore snapshot</documentation>
		</annotation>
		<sequence>
			<element name="file" type="fews:fileStringType">
				<annotation>
					<documentation>Full path to the snapshot file</documentation>
				</annotation>
			</element>
			<element name="downloadEnabled" type="boolean">
				<annotation>
					<documentation>If download is enabled then the localDataStore can be replaced with the  snapshot specified with  'file' .  The downloading can be started  using menu File</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ToolbarTaskComplexType">
		<simpleContent>
			<extension base="boolean">
				<attribute name="buttonType" type="fews:ButtonTypeEnumStringType">
					<annotation>
						<documentation>Since 2019.02 The type of the button added to the toolbar. A button of type icon will use the configured iconFile or the default icon if no icon is configured. A button of type text will use the name of the task.</documentation>
					</annotation>
				</attribute>
			</extension>
		</simpleContent>
	</complexType>
	<simpleType name="ButtonTypeEnumStringType">
		<restriction base="string">
			<enumeration value="icon"/>
			<enumeration value="text"/>
		</restriction>
	</simpleType>
	<complexType name="PanelHeaderComplexType">
		<simpleContent>
			<extension base="string">
				<annotation>
					<documentation>Text to display in the header</documentation>
				</annotation>
				<attribute name="showCount" type="boolean" default="false">
					<annotation>
						<documentation>Indicates whether the header must be expanded with the counts selectable elements</documentation>
					</annotation>
				</attribute>
			</extension>
		</simpleContent>
	</complexType>
</schema>
