<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews"
		targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="externalTablesMirrorUpdate" type="fews:ExternalTablesMirrorUpdateComplexType">
		<annotation>
			<documentation>Since 2015.01. Copies all the time series from the open database to the fews blobbed time series mirror. While importing the data is compared with existing so only changed data is imported. The full open database is read so this can take several hours</documentation>
		</annotation>
	</element>
	<complexType name="ExternalTablesMirrorUpdateComplexType">
		<sequence>
			<element name="importManualEditsTable" type="boolean" default="true">
				<annotation>
					<documentation>Since 2015.01. Import the manual edit table. Already imported edits will be skipped</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>