<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="flagSourceColumns" type="fews:FlagSourceColumnsComplexType">
		<annotation>
			<documentation>Extra flag columns added to the time series. These columns can be displayed in the time series dialog.</documentation>
		</annotation>
	</element>
	<complexType name="FlagSourceColumnsComplexType">
		<sequence>
			<element name="column" type="fews:FlagSourceColumnComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="timeOfValidity" type="fews:TimeOfValidityComplexType" minOccurs="0">
				<annotation>
					<documentation>Flag source column used as base for the time of validity</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!--HistoricalEvent-->
	<complexType name="FlagSourceColumnComplexType">
		<sequence>
			<element name="storageKey" type="fews:storageKey">
				<annotation>
					<documentation>An integer between 0 to 127 that is used in the datastore to reference this column. After changing this key you have to delete the local datastore and MC database
					</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Long (descriptive) name of location (tool tip) or description</documentation>
				</annotation>
			</element>
			<element name="shortName" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>Short name used in the header of in the time series dialog. When not specified the id is used</documentation>
				</annotation>
			</element>
			<element name="toolTip" type="string" minOccurs="0">
				<annotation>
					<documentation>Tooltip to be displayed in the time series dialog when hovering the column header</documentation>
				</annotation>
			</element>
			<element name="editable" type="boolean" minOccurs="0" default="false">
				<annotation>
					<documentation>The column is not editable by default. Editable columns are also visible when empty</documentation>
				</annotation>
			</element>
			<element name="alwaysVisible" type="boolean" minOccurs="0" default="false">
				<annotation>
					<documentation>Makes this column also visible when this column is empty and you are not in edit mode</documentation>
				</annotation>
			</element>
			<element name="clearOnValueOrFlagChange" type="boolean" minOccurs="0" default="false">
				<annotation>
					<documentation>Automatically clear the flag source column when the value of flag is changed</documentation>
				</annotation>
			</element>
			<element name="backgroundColor" type="fews:colorStringType" minOccurs="0">
				<annotation>
					<documentation>Background color of this column in the the time series dialog</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Id of the column. This id is only used to reference this column from the rest of the configuration. This id is not stored in the database. This id can be changed at any time without the requirement of deleting the datastore</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nameStringType">
			<annotation>
				<documentation>Name of the column. When not specified the id is used as the name</documentation>
			</annotation>
		</attribute>
	</complexType>
	<simpleType name="storageKey">
		<restriction base="byte">
			<minInclusive value="0"/>
		</restriction>
	</simpleType>
	<complexType name="TimeOfValidityComplexType">
		<sequence>
			<element name="columnId" type="fews:idStringType">
				<annotation>
					<documentation>Flag source column used as base for the time of validity</documentation>
				</annotation>
			</element>
			<element name="defaultFlagSource" type="fews:idStringType">
				<annotation>
					<documentation>Flag source used to fill this column. Flag source should be predefined flag source or flag source defined in the customFlagSources.xml</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
