<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by tacoma (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="gribTimeSeriesReader" type="fews:GribTimeSeriesReaderComplexType">
		<annotation>
			<documentation>LEGACY, NO LONGER USED</documentation>
		</annotation>
	</element>
	<complexType name="GribTimeSeriesReaderComplexType">
		<annotation>
			<documentation>Additional configuration specific for reading grib files. Using of this config.file is optional. If not used, the grib-file data wil be read only according to the configuration as specified in  TimeSeriesImportRun config file.</documentation>
		</annotation>
		<sequence>
			<element name="recordDefinition" maxOccurs="unbounded">
				<complexType>
					<attribute name="parameterId" type="fews:idStringType" use="required">
						<annotation>
							<documentation>Parameter Id as used in the grib-files</documentation>
						</annotation>
					</attribute>
					<attribute name="levelId" type="fews:idStringType" use="required">
						<annotation>
							<documentation>Level Id (number).  See Grib documentation for the list of all available level Id's</documentation>
						</annotation>
					</attribute>
				</complexType>
			</element>
		</sequence>
	</complexType>
</schema>
