<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- -->
	<element name="hbvModel" type="fews:HbvModelComplexType"/>
	<!-- -->
	<complexType name="HbvModelComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="directories" type="fews:HbvFolderNamesComplexType"/>
			<element name="adapterfiles" type="fews:HbvAdapterFilesComplexType">
				<annotation>
					<documentation>files used by Adapter</documentation>
				</annotation>
			</element>
			<element name="modelFiles" type="fews:HbvModelFilesComplexType">
				<annotation>
					<documentation>files used by model, many AdapterFiles after updating are copied to ModelFiles as mentioned here during preprocessing and vice versa in postprocessing. For details reference the HBV adapter manual.</documentation>
				</annotation>
			</element>
			<element name="variables" type="fews:HbvVariablesComplexType" minOccurs="0">
				<annotation>
					<documentation>variables used by HBV model</documentation>
				</annotation>
			</element>
			<element name="actionSpec" type="fews:HbvActionSpecificationsComplexType" minOccurs="0">
				<annotation>
					<documentation>action Specification to specify extra actions to perform or not to perform</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<!-- -->
	<complexType name="HbvModelDirectoriesCompexType">
		<sequence>
			<element name="rootDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Root directory of the module instance. Option, if this rootDir is not given then the rootDir will be taken same as workingDir</documentation>
				</annotation>
			</element>
			<element name="keyDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Directory of key files (optional) then keyDir is equal to root dir</documentation>
				</annotation>
			</element>
			<element name="districtDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Directory of District directory(optional) then DistrictDir is equal to root dir</documentation>
				</annotation>
			</element>
			<element name="stateDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Directory of State files (optional) then stateDir is equal to root dir</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="HbvAdapterFilesComplexType">
		<sequence>
			<element name="stateFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>State xml file: Contains information on where to retrieve the state file that is to be used for the forecast.</documentation>
				</annotation>
			</element>
			<element name="inputFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Input Time series xml file: Contains all hindcast time series required by the hbv module adapters. </documentation>
				</annotation>
			</element>
			<element name="outputFile" type="fews:fileStringType">
				<annotation>
					<documentation>Output TimeSeries xml file: Contains the forecast time series generated by the hbv module adapter.</documentation>
				</annotation>
			</element>
			<element name="damFlowFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>damFlow XML file to be  converted to damflow.dat file format as understood by HBV model</documentation>
				</annotation>
			</element>
			<element name="outputFileAsBinary" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>When true the events in the PI time series file are written to a binary file instead of the xml file.
                        The written xml file will only contain the time series headers and optionally a time zone.
                        The binary file has the same name as the xml file only the extension is "bin" instead of "xml"
                        During PI time series import the bin file is automatically read when available. The byte order in the bin file is always
                        Intel x86.
                </documentation>
				</annotation>
			</element>
			<element name="diagnosticFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Diagnostic file: Contains all messages produced by the hbv module adapter.</documentation>
				</annotation>
			</element>
			<element name="hbvInitializationFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>hbv Initialization file (abq.ini)</documentation>
				</annotation>
			</element>
			<element name="propertiesFile" type="fews:HbvModelPropertiesFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>hbv Model properties file such as info.par, seq.par, dam.key etc.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="HbvModelFilesComplexType">
		<sequence>
			<element name="hbvInitializationFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>hbv Initialization file (abq.ini)</documentation>
				</annotation>
			</element>
			<element name="ptqFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>name of PTQ file without file extension such as key, par, dat</documentation>
				</annotation>
			</element>
			<element name="damFlowFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>name of damFlow file without extension, the standard extension of .dat is assumed. Make sure that you mention als the damFile (dam.key) file under propertiesFile </documentation>
				</annotation>
			</element>
			<element name="resFile" type="fews:fileStringType">
				<annotation>
					<documentation>name of Res file without file extensions such as key, par, dat</documentation>
				</annotation>
			</element>
			<element name="logFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>HBV module log file: Contains messages produced by the HBV modules.</documentation>
				</annotation>
			</element>
			<element name="propertiesFile" type="fews:HbvModelPropertiesFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>hbv Model properties file such as info.par, seq.par, dam.key etc.</documentation>
				</annotation>
			</element>
			<element name="deleteDosptqFile" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>to be set to false in forecast run (default delete dosptq file)</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="HbvVariablesComplexType">
		<sequence>
			<element name="damcheck" type="fews:HbvVariableEnumStringType" default="false" minOccurs="0">
				<annotation>
					<documentation>to set the Damcheck on or off</documentation>
				</annotation>
			</element>
			<element name="automaticCorrection" type="fews:HbvVariableEnumStringType" default="false" minOccurs="0">
				<annotation>
					<documentation>allow automatic correction or not</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="HbvModelPropertiesFilesComplexType">
		<sequence>
			<element name="infoFile" type="fews:fileStringType" default="info.par"/>
			<element name="ptqwFile" type="fews:fileStringType" default="ptqw.key"/>
			<element name="seqFile" type="fews:fileStringType" default="seq.par"/>
			<element name="damFile" type="fews:fileStringType" default="dam.key" minOccurs="0">
				<annotation>
					<documentation>dam key file is required to be present only when User Defined Discharge for forecast run. The name of this is always available for model file but optional for adapter files.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="HbvFolderNamesComplexType">
		<annotation>
			<documentation>Folder names required by the HbV modules</documentation>
		</annotation>
		<sequence>
			<element name="configDir" type="fews:directoryStringType"/>
			<element name="adapterDir" type="fews:directoryStringType"/>
			<element name="modelDirectories" type="fews:HbvModelDirectoriesCompexType" minOccurs="0"/>
			<element name="importDir" type="fews:directoryStringType" minOccurs="0"/>
			<element name="exportDir" type="fews:directoryStringType" minOccurs="0"/>
			<element name="workDir" type="fews:directoryStringType" minOccurs="0"/>
		</sequence>
	</complexType>
	<!-- -->
	<simpleType name="HbvVariableEnumStringType">
		<restriction base="string">
			<enumeration value="true"/>
			<enumeration value="false"/>
			<enumeration value="ask"/>
		</restriction>
	</simpleType>
	<simpleType name="HbvActionSpecificationEnumStringType">
		<restriction base="string">
			<enumeration value="noStateFileUpdate"/>
			<enumeration value="noStateFileCopy"/>
			<enumeration value="autoCorrectStateTimes">
                <annotation>
                    <documentation>The general adapter has an option to shift the exported times to handle a period over
                        10000 years. In this case the warm state written by hbv will not have a state time that is suitable for the
                        next hbv run.
                    </documentation>
                </annotation>
            </enumeration>
		</restriction>
	</simpleType>
	<complexType name="HbvActionSpecificationsComplexType">
		<sequence>
			<element name="action" type="fews:HbvActionSpecificationEnumStringType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
</schema>
