<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by WL | Delft Hydraulics (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--Transformation Schema with element  transformationSets-->
	<element name="historicalEvents" type="fews:HistoricalEventsComplexType">
		<annotation>
			<documentation>Historical Events element</documentation>
		</annotation>
	</element>
	<!--Complex Types definitions for different types of Transformations-->
	<!--HistoricalEvents-->
	<complexType name="HistoricalEventsComplexType">
		<annotation>
			<documentation>Historical Events contains one or more Historical Event</documentation>
		</annotation>
		<sequence>
			<choice maxOccurs="unbounded">
				<element name="historicalEvent" type="fews:HistoricalEventComplexType"/>
				<element name="historicalEventSet" type="fews:HistoricalEventSetComplexType"/>
			</choice>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.0"/>
	</complexType>
	<!--HistoricalEvent-->
	<complexType name="HistoricalEventComplexType">
		<annotation>
			<documentation>Historical Event Set defines a location id, parameter id and event data.</documentation>
		</annotation>
		<sequence>
			<element name="eventData" type="fews:VariableComplexType"/>
		</sequence>
		<attribute name="locationId" type="fews:idStringType" use="required"/>
		<attribute name="parameterId" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nameStringType" use="required"/>
	</complexType>
	<!--HistoricalEventSet-->
	<complexType name="HistoricalEventSetComplexType">
		<annotation>
			<documentation>Historical Event Set defines an applicable location/parameter id, and event data</documentation>
		</annotation>
		<sequence>
			<element name="historicalEvent" type="fews:HistoricalEventComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="name" type="fews:idStringType" use="required"/>
	</complexType>
</schema>
