<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews"
        xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"
        version="1.0">

    <include schemaLocation="sharedTypes.xsd"/>
    <element name="hymosTransferDbImportRun" type="fews:HymosTransferDbImportRunComplexType"/>

    <complexType name="HymosTransferDbImportRunComplexType">
        <annotation>
            <documentation>Configuration settings for the hymos transfer db import module</documentation>
        </annotation>
        <sequence>
            <element name="import" type="fews:HymosTransferDbImportRunTaskComplexType"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="HymosTransferDbImportRunTaskComplexType">
        <annotation>
            <documentation>Configuration settings for an import type</documentation>
        </annotation>
        <sequence>
            <element name="importDirectory" type="fews:directoryStringType" nillable="false">
                <annotation>
                    <documentation>Directory in which one or more hymos transfer databases are located</documentation>
                </annotation>
            </element>
            <element name="idMapId" type="fews:idStringType" minOccurs="0">
                <annotation>
                    <documentation>Id of IdMap to be used for locationId- and parameterId mapping</documentation>
                </annotation>
            </element>
            <element name="unitConversionsId" type="fews:idStringType" minOccurs="0">
                <annotation>
                    <documentation>Id of UnitConversions to be used for unit mapping</documentation>
                </annotation>
            </element>
            <element name="flagConversionsId" type="fews:idStringType" minOccurs="0">
                <annotation>
                    <documentation>Id of flagConversions to be used for flag mapping</documentation>
                </annotation>
            </element>
            <element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType" nillable="false" maxOccurs="unbounded"/>
            <element name="importTimeZone" type="fews:TimeZoneComplexType" minOccurs="0">
                <annotation>
                    <documentation>Time zone of times in the hymos transfer db.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
</schema>
