<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews"
		targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="importArchiveModule" type="fews:ImportArchiveModuleComplexType"/>
	<complexType name="ImportArchiveModuleComplexType">
		<sequence>
			<choice maxOccurs="unbounded">
				<element name="importSimulated" type="fews:ImportSimulatedComplexType"/>
				<element name="importSimulatedHistorical" type="fews:ImportSimulatedHistoricalComplexType"/>
				<element name="importObserved" type="fews:ImportObservedComplexType"/>
				<element name="importMessages" type="fews:ImportMessagesComplexType"/>
				<element name="importExternalForecast" type="fews:ImportExternalForecastComplexType"/>
				<element name="importHistoricalEvents" type="fews:ImportHistoricalEventsComplexType"/>
                <element name="importRatingCurves" type="fews:ImportRatingCurvesComplexType"/>
                <element name="importEditedData" type="fews:ImportEditedDataComplexType"/>
                <element name="importRequestedDataSets" type="fews:ImportRequestedDataSetsComplexType"/>
			</choice>
			<choice minOccurs="0">
				<annotation>
					<documentation>logErrorsAsWarnings</documentation>
				</annotation>
				<element name="logErrorsAsWarnings" type="boolean" default="false">
					<annotation>
						<documentation>Since 2018.02. Exceptions occuring in a parser as well as some not parser-specific log messages such as " Import folder ... does not exist" or " Can not connect to..." can be logged as Error or as Warning.  Use this option to change it. Default is logErrorsAsWarnings=true. Configure False if you wish clear alert notifications in SystemMonitor and Explorer statusBar </documentation>
					</annotation>
				</element>
				<element name="logErrorsAsWarningsToFileOnly" type="boolean" default="false">
					<annotation>
						<documentation>Since 2018.02. Exceptions occuring in a parser as well as some not parser-specific log messages such as " Import folder ... does not exist" or " Can not connect to..." can be logged to file and database. Set this option to true if you do not wish to log them to the database.</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="ImportSimulatedComplexType">
		<sequence>
			<element name="timeSeriesSetIdMap" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>The use of the id map is optional! First the mapping defined in the netcdf-file itself is used. Optionally the mapping defined here is also applied. The defined id mapping will only be applied for locations and parameters!</documentation>
				</annotation>
			</element>
			<element name="importFolder" type="fews:directoryStringType"/>
		</sequence>
	</complexType>
	<complexType name="ImportSimulatedHistoricalComplexType">
		<sequence>
			<element name="timeSeriesSetIdMap" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>The use of the id map is optional! First the mapping defined in the netcdf-file itself is used. Optionally the mapping defined here is also applied. The defined id mapping will only be applied for locations and parameters!</documentation>
				</annotation>
			</element>
			<element name="importFolder" type="fews:directoryStringType"/>
		</sequence>
	</complexType>
	<complexType name="ImportObservedComplexType">
		<sequence>
			<element name="timeSeriesSetIdMap" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>The use of the id map is optional! First the mapping defined in the netcdf-file itself is used. Optionally the mapping defined here is also applied. The defined id mapping will only be applied for locations and parameters!</documentation>
				</annotation>
			</element>
			<element name="importFolder" type="fews:directoryStringType"/>
		</sequence>
	</complexType>
	<complexType name="ImportMessagesComplexType">
		<sequence>
			<element name="importFolder" type="fews:directoryStringType"/>
		</sequence>
	</complexType>
	<complexType name="ImportExternalForecastComplexType">
		<sequence>
			<element name="timeSeriesSetIdMap" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>The use of the id map is optional! First the mapping defined in the netcdf-file itself is used. Optionally the mapping defined here is also applied. The defined id mapping will only be applied for locations and parameters!</documentation>
				</annotation>
			</element>
			<element name="importFolder" type="fews:directoryStringType"/>
		</sequence>
	</complexType>
	<complexType name="ImportHistoricalEventsComplexType">
		<sequence>
			<element name="importFolder" type="fews:directoryStringType"/>
			<element name="failedFolder" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Files that could not be imported due to an error are copied to this folder.
					</documentation>
				</annotation>
			</element>
			<element name="backupFolder" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>Successfully imported files are moved to this folder.</documentation>
				</annotation>
			</element>
			<element name="idMapId" type="fews:fileStringType">
				<annotation>
					<documentation>The use of the id map is optional! First the mapping defined in the netcdf-file itself is used. Optionally the mapping defined here is also applied. The defined id mapping will only be applied for locations and parameters!</documentation>
				</annotation>
			</element>
			<element name="dataFeedId" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>Since 2023.02. Optional id to record import in import status table.</documentation>
				</annotation>
			</element>
			<element name="disableDataFeedInfo" type="fews:emptyElement" minOccurs="0">
				<annotation>
					<documentation>Option disableDataFeedInfo indicates that no export status should be stored in database</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
    <complexType name="ImportRatingCurvesComplexType">
        <sequence>
            <element name="importFolder" type="fews:directoryStringType"/>
        </sequence>
    </complexType>
	<complexType name="ImportEditedDataComplexType">
		<sequence>
			<element name="importFolder" type="fews:directoryStringType"/>
		</sequence>
	</complexType>
	<complexType name="ImportRequestedDataSetsComplexType">
		<sequence>
			<element name="importFolder" type="fews:directoryStringType"/>
			<element name="dataFolderArchive" type="fews:directoryStringType"/>
		</sequence>
	</complexType>

</schema>
