<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by tacoma (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- -->
	<element name="launcher" type="fews:LauncherType"/>
	<complexType name="JavaAppType">
		<annotation>
			<documentation>
				No longer supported from 208.02. Use ExecutableType instead.
			</documentation>
		</annotation>
		<attribute name="region" type="string" use="required"/>
		<attribute name="operationMode" type="fews:operationModeEnumType" use="required"/>
		<attribute name="operationModeCaption" type="string"/>
		<attribute name="operationModeHidden" type="boolean" default="false">
			<annotation>
				<documentation>Since 2013.01. FEWS-8106</documentation>
			</annotation>
		</attribute>
		<attribute name="path" type="string"/>
		<attribute name="javaClass" type="string"/>
		<attribute name="jvmOption" type="string"/>
		<attribute name="argument" type="string"/>
		<!-- Use either "path" for an executable or "javaClass" for a java class with main method -->
	</complexType>
	<complexType name="WebPageType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="appPath" type="string" use="required"/>
		<attribute name="arg" type="string" use="required"/>
	</complexType>
	<complexType name="ExecutableType">
		<annotation>
			<documentation>
				Available since 2018.02. Use this instead of JavaAppType.
			</documentation>
		</annotation>
		<sequence>
			<element name="appPath" type="string">
				<annotation>
					<documentation>Path to the FEWS executable file. Has to be an absolute path.></documentation>
				</annotation>
			</element>
			<element name="region" type="string">
				<annotation>
					<documentation>Name of the region. Region Home folder should be configured in the argument list.></documentation>
				</annotation>
			</element>
			<element name="operationMode" type="fews:operationModeEnumType"/>
			<element name="operationModeCaption" type="string" minOccurs="0" />
			<element name="operationModeHidden" type="boolean" default="false" minOccurs="0"/>
			<element name="arguments" type="fews:ArgumentsComplexType" minOccurs="0">
				<annotation>
					<documentation>Arguments to be passed to the executable. Configure region home here. Arguments should start with '-D'. For ConfigManager configure the database url here.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="operationModeEnumType">
		<restriction base="string">
			<enumeration value="StandAlone"/>
			<enumeration value="OnLine"/>
			<enumeration value="OffLine"/>
			<enumeration value="Development"/>
			<enumeration value="Test"/>
		</restriction>
	</simpleType>
	<complexType name="ActionType">
		<sequence>
			<element name="buttonText" type="string" minOccurs="0">
				<annotation>
					<documentation>Since 2013.01. FEWS-8106</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0"/>
			<choice>
				<element name="webPage" type="fews:WebPageType" minOccurs="0" maxOccurs="unbounded"/>
				<element name="javaApp" type="fews:JavaAppType" minOccurs="0" maxOccurs="unbounded"/>
				<element name="executable" type="fews:ExecutableType" minOccurs="0" maxOccurs="unbounded"/>
			</choice>
		</sequence>
		<attribute name="id" type="string" use="required"/>
	</complexType>
	<complexType name="LauncherType">
		<sequence>
			<element name="language" minOccurs="0">
				<simpleType>
					<restriction base="string">
						<maxLength value="2"/>
					</restriction>
				</simpleType>
			</element>
			<element name="title" type="string" minOccurs="0"/>
			<element name="action" type="fews:ActionType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
</schema>
