<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by J (WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- -->
	<element name="lisFlood" type="fews:LisFloodComplexType"/>
	<!-- -->
	<complexType name="LisFloodComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="directories" type="fews:LisFloodDirectoriesCompexType"/>
			<element name="adapterfiles" type="fews:LisFloodAdapterFilesComplexType">
				<annotation>
					<documentation>files used by Adapter</documentation>
				</annotation>
			</element>
			<element name="modelFiles" type="fews:LisFloodModelFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>files used by model</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<!-- -->
	<complexType name="LisFloodAdapterFilesComplexType">
		<sequence>
			<element name="stateFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>State xml file: Contains information on where to retrieve the state file that is to be used for the forecast. relative to workDir</documentation>
				</annotation>
			</element>
			<element name="parameterFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>parameter files to update the LisFlood script file relative to workDir</documentation>
				</annotation>
			</element>
			<element name="diagnosticFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Diagnostic file: Contains all messages produced by the LisFlood module adapter.</documentation>
				</annotation>
			</element>
			<element name="inputMapStackFile" type="fews:fileStringType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>require for getting the correct period and checking if the number of files are correct</documentation>
				</annotation>
			</element>
			<element name="outputFile" type="fews:LisFloodOutputFileComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>output files of LisFlood to be converted to the PITimeSeries XML file. Presently only text TimeSeries output files from LisFlood are supported</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="LisFloodModelFilesComplexType">
		<sequence>
			<element name="LisFloodModFile" type="fews:fileStringType">
				<annotation>
					<documentation>LisFlood script file</documentation>
				</annotation>
			</element>
			<element name="logFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>LisFlood module log file: Contains messages produced by the LisFlood modules.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="LisFloodDirectoriesCompexType">
		<annotation>
			<documentation>Folder names required by the LisFlood modules</documentation>
		</annotation>
		<sequence>
			<element name="workDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>LisFlood script file directory and other data directory, if optional it is taken same as root dir</documentation>
				</annotation>
			</element>
			<element name="inputDir" type="fews:directoryStringType"/>
			<element name="outputDir" type="fews:directoryStringType" minOccurs="0"/>
			<element name="stateDir" type="fews:directoryStringType" minOccurs="0">
				<annotation>
					<documentation>if no stateDir is defined it is taken same as rootDir</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="LisFloodOutputFileComplexType">
		<annotation>
			<documentation>conversion file name is required if required for the correct location parameter or optionally on parameter</documentation>
		</annotation>
		<attribute name="fileType" type="fews:LisFloodOutputFileTypeEnumStringType" use="required"/>
		<attribute name="file" type="fews:fileStringType" use="required"/>
		<attribute name="xmlFile" type="fews:fileStringType" use="required"/>
		<attribute name="conversionFile" type="fews:fileStringType" use="optional"/>
		<attribute name="parameterID" type="fews:idStringType" use="optional"/>
		<attribute name="locationID" type="fews:idStringType" use="optional"/>
		<attribute name="locationIdPrefix" type="fews:idStringType" use="optional"/>
	</complexType>
	<!-- -->
	<complexType name="LisFloodLongTermAverageInputFileComplexType">
		<attribute name="inputFile" type="fews:fileStringType" use="required"/>
		<attribute name="outputFile" type="fews:fileStringType" use="required"/>
	</complexType>
	<!-- -->
	<simpleType name="LisFloodOutputFileTypeEnumStringType">
		<restriction base="string">
			<enumeration value="pcrastertimeseries"/>
			<enumeration value="pcrastermapstack"/>
		</restriction>
	</simpleType>
</schema>
