<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews/archive"
		targetNamespace="http://www.wldelft.nl/fews/archive" elementFormDefault="qualified"
		attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="archive_sharedTypes.xsd"/>
	<element name="logFileMetaData" type="fews:LogsMetaDataComplexType"/>
	<complexType name="LogsMetaDataComplexType">
		<sequence>
			<element name="relativeFilePath" type="fews:nonEmptyStringType"/>
			<element name="areaId" type="fews:idStringType"/>
			<element name="level" type="fews:idStringType" minOccurs="0"/>
			<element name="eventCode" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="creationTime" type="fews:DateTimeComplexType"/>
			<element name="startTime" type="fews:DateTimeComplexType"/>
			<element name="endTime" type="fews:DateTimeComplexType"/>
		</sequence>
	</complexType>
</schema>