<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--Top-level element Declaration -->
	<element name="lookupDisplay" type="fews:LookupDisplayComplexType"/>
	<!--Lookup DIsplay ComplexType-->
	<complexType name="LookupDisplayComplexType">
		<sequence>
			<element name="general" type="fews:LookupDisplayGeneralComplexType"/>
			<element name="lookupDisplayDescriptor" type="fews:LookupDisplayDescriptorComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<!--Lookup Display Descriptor Complex Type-->
	<complexType name="LookupDisplayDescriptorComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="workflowDescriptorId" type="fews:idStringType">
				<annotation>
					<documentation>workflowDescriptor ID for the to perform the Critical COndition Lookup...</documentation>
				</annotation>
			</element>
			<element name="prefixwhatifScenarioDescriptorID" type="string" minOccurs="0"/>
			<element name="inputVariable" type="fews:VariableComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>input variable - should be minimum  1 with a unique timeSeriesSet. Only LocationID is supported</documentation>
				</annotation>
			</element>
			<element name="outputVariable" type="fews:VariableComplexType">
				<annotation>
					<documentation>output variable - should be only 1 with a unique timeSeriesSet. You can use a locationSetId instead of Location. </documentation>
				</annotation>
			</element>
			<element name="subDir" type="fews:fileStringType" minOccurs="0"/>
			<element name="reportFileName" type="fews:fileStringType"/>
		</sequence>
		<attribute name="descriptorId" type="fews:idStringType" use="required"/>
	</complexType>
	<!-- -->
	<complexType name="LookupDisplayGeneralComplexType">
		<sequence>
			<element name="reportDirectory" type="fews:fileStringType"/>
			<element name="externalBrowser" type="fews:fileStringType" minOccurs="0"/>
		</sequence>
	</complexType>
</schema>
