<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by WL | Delft Hydraulics (WL | Delft Hydraulics) -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by tacoma (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--This file contains the configuration (i.e. settings) of the ManualForecastDialog. -->
	<!--If this file is not present, the default settings, as specified in the source code of  ManualForecastDialog, wil be used -->
	<element name="manualForecastDisplay" type="fews:ManualForecastDisplayComplexType"/>
	<complexType name="ManualForecastDisplayComplexType">
		<sequence>
			<element name="runningPredefined" type="fews:RunningPredefinedComplexType" minOccurs="0"/>
			<element name="coldState" type="fews:ManualForecastColdStateComplexType" minOccurs="0">
				<annotation>
					<documentation>General default cold state settings displayed in the dialog</documentation>
				</annotation>
			</element>
			<element name="warmState" type="fews:ManualForecastWarmStateComplexType" minOccurs="0">
				<annotation>
					<documentation>General default warm state settings displayed in the dialog</documentation>
				</annotation>
			</element>
			<element name="forecastLength" type="fews:TimeSpanComplexType" minOccurs="0"/>
			<element name="task" type="fews:ManualForecastTaskComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RunningPredefinedComplexType">
		<annotation>
			<documentation>Settings for running of the predefined tasks </documentation>
		</annotation>
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="directory" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>directory, where to search for the xml-file with predefined taskProperties. Default equal to the region main-directory. </documentation>
				</annotation>
			</element>
			<element name="buttonVisible" type="boolean">
				<annotation>
					<documentation>indication whether the button "Run predefined" must be visible or not. Default value is False</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ManualForecastColdStateComplexType">
		<sequence>
			<element name="startDate" type="fews:TimeSpanComplexType"/>
		</sequence>
	</complexType>
	<complexType name="ManualForecastWarmStateComplexType">
		<sequence>
			<element name="stateSearchPeriod" type="fews:RelativePeriodComplexType"/>
		</sequence>
	</complexType>
	<complexType name="ManualForecastTaskComplexType">
		<annotation>
			<documentation>Defines default settings as they appear in the display after selection of the workflow with id 'workflowId'. If not all settings are specified, then  the 'global' settings  (if any defined in this file) wil be used. Otherwise the setting as given in the code are used.</documentation>
		</annotation>
		<sequence>
			<element name="coldState" type="fews:ManualForecastColdStateComplexType" minOccurs="0"/>
			<element name="warmState" type="fews:ManualForecastWarmStateComplexType" minOccurs="0"/>
			<element name="forecastLength" type="fews:TimeSpanComplexType" minOccurs="0"/>
		</sequence>
		<attribute name="workflowId" type="fews:idStringType" use="required"/>
		<attribute name="stateSelection" type="boolean">
			<annotation>
				<documentation>Indication whether selection of states is allowed. Yes (allowed) by default.</documentation>
			</annotation>
		</attribute>
		<attribute name="forecastLengthSelection" type="boolean">
			<annotation>
				<documentation>Indication whether selection of forecast length  is allowed. Yes (allowed) by default.</documentation>
			</annotation>
		</attribute>
	</complexType>
</schema>
