<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews/archive"
		targetNamespace="http://www.wldelft.nl/fews/archive" elementFormDefault="qualified"
		attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="archive_sharedTypes.xsd"/>
	<element name="mapping" type="fews:MappingComplexType"/>
	<complexType name="MappingComplexType">
		<sequence>
			<element name="url" type="anyURI"/>
			<element name="idMapping" type="fews:SobekFewsArchiveMappingComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="SobekFewsArchiveMappingComplexType">
		<sequence>
			<element name="modelParameter" type="fews:ModelParameterComplexType"/>
			<element name="dataSourceParameter" type="fews:DataSourceParameterComplexType"/>
			<element name="locationMappings" type="fews:LocationMappingsComplexType"/>
		</sequence>
	</complexType>
	<complexType name="LocationMappingsComplexType">
		<sequence>
			<element name="locationMapping" type="fews:LocationMappingComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="LocationMappingComplexType">
		<attribute name="modelLocationId" type="fews:idStringType"/>
		<attribute name="dataSourceLocationId" type="fews:idStringType"/>
	</complexType>
	<complexType name="ModelParameterComplexType">
		<sequence>
			<element name="type" type="fews:modelTimeSeriesType"/>
			<element name="parameter" type="fews:idStringType"/>
		</sequence>
	</complexType>
	<complexType name="DataSourceParameterComplexType">
		<sequence>
			<element name="parameter" type="fews:idStringType"/>
		</sequence>
	</complexType>
	<simpleType name="modelTimeSeriesType">
		<restriction base="string">
			<maxLength value="255"/>
			<enumeration value="boundary data"/>
			<enumeration value="lateral data"/>
		</restriction>
	</simpleType>
</schema>