<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="whatIfScenario.xsd"/>
	<include schemaLocation="eventActions.xsd"/>
	<include schemaLocation="taskList.xsd"/>
	<element name="mc" type="fews:MCComplexType">
		<annotation>
			<documentation>Since 2020.02. Contains all the Master Controller configuration and scheduling for up- and download with the AdminInterface or the API. When uploaded this file is used by both the Master Controller and the Admin Interface. The textual elements in this xml file can use variable tags between % characters which are then replaced by pre-defined Operating System environment variables. For instance, %FEWS_AI_TITLE% could be used as Admin Interface title so that the same mc config file is used for all development / testing / acceptance and production systems, except that each AI has a different FEWS_AI_TITLE system OS variable.</documentation>
		</annotation>
	</element>
	<complexType name="MCLoggingComplexType">
		<sequence>
			<element name="debugEnabled" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Enables debug logging. Defaults to false.</documentation>
				</annotation>
			</element>
			<element name="rollingTotalSizeMB" type="fews:positiveInteger" default="10" minOccurs="0">
				<annotation>
					<documentation>Defines the total amount of rolling log file sizes. Defaults to 10 Mb.</documentation>
				</annotation>
			</element>
			<element name="queryMinimalExecutionTime" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Logs slow queries as INFO message when exceeding this timespan. No effect when already in debug mode.</documentation>
				</annotation>
			</element>
			<element name="logEntryExpiryTime" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Default ExpiryTime for LogEntries written into the database created by the AdminInterface and the Master Controller. Defaults to 5 days for the Admin Interface and 10 days for the Master Controller.</documentation>
				</annotation>
			</element>
			<element name="windowsEventLogEnabled" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Enables logging of errors to the windows event logger. False by default. Ignored under linux. It will be necessary to register Delft-FEWS as an event source using: %SystemRoot%\\System32\\EventCreate.exe /SO "Delft-FEWS" /t SUCCESS /ID 99 /d "Initialise WindowsNTEventLogger" /L Application</documentation>
				</annotation>
			</element>
			<element name="linuxSyslogFacility" type="fews:syslogFacilityEnumStringType" minOccurs="0">
				<annotation>
					<documentation>Enables logging of errors to the linux syslog using the specified facility. Ignored under Windows.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="dateFormatPatternType">
		<restriction base="string">
			<maxLength value="255"/>
			<pattern value="(MM/dd/yyyy HH:mm:ss)|(dd/MM/yyyy HH:mm:ss)"/>
		</restriction>
	</simpleType>
	<complexType name="DateFormatComplexType">
		<sequence>
			<element name="dateTimePattern" type="fews:dateFormatPatternType">
				<annotation>
					<documentation>Pattern for this dateFormat. Defaults to dd/MM/yyyy HH:mm:ss.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FolderComplexType">
		<sequence>
			<element name="url" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>Directory on file system, link to website or url to ftp server.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nonEmptyStringType" use="required">
			<annotation>
				<documentation>Descriptive name of the resource. Defaults to the id.</documentation>
			</annotation>
		</attribute>
		<attribute name="mcId" type="fews:mcIdStringType" use="optional">
			<annotation>
				<documentation>Descriptive name of the resource.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="FoldersComplexType">
		<sequence>
			<element name="folder" type="fews:FolderComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Directory on file system or url to ftp server.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="BookmarkComplexType">
		<sequence>
			<element name="url" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>Directory on file system, link to website or url to ftp server.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nonEmptyStringType" use="optional">
			<annotation>
				<documentation>Descriptive name of the resource. Defaults to the id.</documentation>
			</annotation>
		</attribute>
		<attribute name="mcId" type="fews:mcIdStringType" use="optional">
			<annotation>
				<documentation>Descriptive name of the resource.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="BookmarksComplexType">
		<sequence>
			<element name="bookmark" type="fews:BookmarkComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Directory on file system or url to ftp server.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="AdminInterfaceComplexType">
		<sequence>
			<element name="title" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>Title of the region home in the admin interface, defaults to mcId from the LocalMcId table.</documentation>
				</annotation>
			</element>
			<element name="dateFormat" type="fews:DateFormatComplexType" minOccurs="0">
				<annotation>
					<documentation>The date format that is used in the Admin Interface GUI and its date components and the Admin Interface API. The following formats are supported: 'dd/MM/yyyy HH:mm:ss' and 'MM/dd/yyyy HH:mm:ss'. If no date format is specified, the default date format is used: 'dd/MM/yyyy HH:mm:ss'.</documentation>
				</annotation>
			</element>
			<element name="timeZone" type="fews:TimeZoneComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>If no time zone is defined, then uses GMT. The configured time zones can only be used when scheduling tasks.</documentation>
				</annotation>
			</element>
			<element name="autoRefreshDelay" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Interval for autorefreshing the system status page of the Admin Interface. Default is 600 seconds.</documentation>
				</annotation>
			</element>
			<element name="heartbeatMaxAge" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Threshold for heartbeat status. Default is to two minutes.</documentation>
				</annotation>
			</element>
			<element name="logEntriesMaxDisplayCount" type="integer" minOccurs="0">
				<annotation>
					<documentation>Maximum number of entries displayed in the ViewLogs page. Default is 100.</documentation>
				</annotation>
			</element>
			<element name="activeSessionMaxAge" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Defines when a session is too old to be displayed in the list of active sessions. Default is one hour.</documentation>
				</annotation>
			</element>
			<element name="taskFormDefaultRunExpiryTime" type="fews:CalendarTimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Default ExpiryTime for TaskRuns filled in the Task Form. This value is ignored for workflow descriptors with a runExpiryTime. Default is ten days.</documentation>
				</annotation>
			</element>
			<element name="folders" type="fews:FoldersComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional list of browsable directories, either on the file system or via ftp.</documentation>
				</annotation>
			</element>
			<element name="bookmarks" type="fews:BookmarksComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional list of url links.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TaskRunDispatcherComplexType">
		<sequence>
			<element name="taskRunMaxLateTime" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Terminate a taskRun when it's overdue time exceeds the specified value. Defaults to 15 minutes.</documentation>
				</annotation>
			</element>
			<element name="preferLongestIdleForecastingShell" type="boolean" minOccurs="0" default="false">
				<annotation>
					<documentation>When true the work is more evenly distributed over the ready forecasting shells. When true the forecasting shell never goto sleep</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FssGroupComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description of the FssGroup.</documentation>
				</annotation>
			</element>
			<element name="allowUnmapped" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>When false this FSSGroup can only process workflows explicitly mapped to it. Use false for a dedicated FssGroup, e.g. for a models with license limitations. By default true.</documentation>
				</annotation>
			</element>
			<element name="minAwakeCount" type="integer" default="0" minOccurs="0">
				<annotation>
					<documentation>Defines the minimal amount of ForecastingShells that the FssLauncher will always keep awake in this FssGroup. Defaults to 1, meaning one fss is kept awake. For always using hot start set this at least to the number of available Fss. This value is also used by the SystemHealthChecker to set the mc health status when there are not enough FSS awake.</documentation>
				</annotation>
			</element>
			<element name="maxAwakeCount" type="integer" minOccurs="0">
				<annotation>
					<documentation>Defines the maximum amount of ForecastingShells that the FssLauncher will always keep awake in this FssGroup.</documentation>
				</annotation>
			</element>
			<element name="releaseSlotsMillis" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>When not defined, slots are not released automatically.</documentation>
				</annotation>
			</element>
			<element name="gotoSleepMillis" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Defines timespan after which spare FSSes are instructed to go to sleep mode. When not defined, fss are not instructed to sleep automatically.</documentation>
				</annotation>
			</element>
			<element name="priority" type="integer" default="0" minOccurs="0">
				<annotation>
					<documentation>Defines the priority of an FssGroup. Slow FssGroups, expensive cloud FssGroups or FssGroups with a model license get a high number so they are only used when there is no alternative.For instance an FssGroup with a license model with lower priority rank (greater integer value) will only run imports when the higher priority FssGroup normally used for imports is busy or down for maintenance.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>FssGroup identifier. Typical defined as a capability, e.g. windows, linux or a specific model such as SOBEK.</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nameStringType" use="optional">
			<annotation>
				<documentation>Optional name of the FssGroup. When absent, defaults to the id.</documentation>
			</annotation>
		</attribute>
		<attribute name="mcId" type="fews:mcIdStringType" use="optional"/>
	</complexType>
	<complexType name="FssGroupAzureComplexType">
		<sequence>
			<element name="fssGroup" minOccurs="1" maxOccurs="1" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>Specifies the FSS Group id this configuration applies to.</documentation>
				</annotation>
			</element>
			<element name="tenantId" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>Unique identifier of the Azure TenantID.</documentation>
				</annotation>
			</element>
			<element name="subscriptionId" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>Unique identifier of the Azure Subscription. The subscription has to be in the tenant is configured by the tenant id</documentation>
				</annotation>
			</element>
			<element name="resourceGroup" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>Azure Resource Group. Has to be part of the configured subscription</documentation>
				</annotation>
			</element>
			<element name="clientId" type="string" minOccurs="0">
				<annotation>
					<documentation>Required if used from on premise. The client id of the app registration with the appropriate permissions.</documentation>
				</annotation>
			</element>
			<element name="clientSecret" type="string" minOccurs="0">
				<annotation>
					<documentation>Required if used from on premise. The client secret of the app registration.</documentation>
				</annotation>
			</element>
			<element name="autoDeallocateFssVMs" type="boolean" minOccurs="0" default="true">
				<annotation>
					<documentation>Deallocate an Azure Virtual Machine containing an IDLE forecasting shell without workflows in the queue automatically.</documentation>
				</annotation>
			</element>
			<element name="wakingUpFromHibernationMaxLateTime" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Maximum time it should take for a VM to wake up from hibernation. Default is 15 minutes if not configured. Minimum is 5 minute. If the FSS doesn't give a heartbeat after this time the VM will be brought back into hibernation. For very large VMs this time may have to be set larger.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FssGroupsComplexType">
		<sequence>
			<element name="fssGroup" type="fews:FssGroupComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>An fssGroup with its autoscaling options.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="failoverType">
		<restriction base="string">
			<enumeration value="no failover">
				<annotation>
					<documentation>Default operation. Not in manual failover.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="manual failover">
				<annotation>
					<documentation>Sets the system in manual failover. By setting manual failover, the Master Controller will start operating as it were alone in the pool of Master Controllers. Synchronization of forecast data from other Master Controllers is suspended. The remote Master Controllers also suspend synchronizing forecast data from this Master Controller. See also failover policy in Task.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="failover">
				<annotation>
					<documentation>When the mc.xml is downloaded this setting indicates that the Master Controller has automatically been put into fail over mode. Ignored when uploaded.</documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>
	<complexType name="DatabaseServerComplexType">
		<sequence>
			<element name="url" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>jdbc url. jdbc:postgresql://host:port/database OR jdbc:oracle:thin:@//host:port/service_name OR jdbc:oracle:thin:@host:port:SID OR jdbc:oracle:thin:@TNSName OR jdbc:sqlserver://host:port/database.</documentation>
				</annotation>
			</element>
			<element name="user" type="string" minOccurs="0">
				<annotation>
					<documentation>Only required when not when using Kerberos or AD integration.</documentation>
				</annotation>
			</element>
			<element name="encryptedPassword" type="string" minOccurs="0">
				<annotation>
					<documentation>Only required when not using Kerberos or AD integration. Encrypted user's password. Password is encrypted with clipboard utils in F12 menu in (any) SA/OC.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="MCSynchProfileComplexType">
		<choice>
			<element name="statusOnly" type="fews:VoidComplexType">
				<annotation>
					<documentation>When used, only status is synchronized, e.g. heart beats. No Configuration or Forecast data. Status tables are SystemActivities, ComponentLogFileSnapshots, MasterControllers, FSSGroups, ForecastingShells, FssStatus and LiveMcAvailabilities.</documentation>
				</annotation>
			</element>
			<sequence>
				<element name="includeConfig" type="boolean" default="true" minOccurs="0">
					<annotation>
						<documentation>If set to false, no config tables are to be synchronized. Default is true.</documentation>
					</annotation>
				</element>
				<element name="includeLogEntries" type="boolean" default="true" minOccurs="0">
					<annotation>
						<documentation>If set to false, synchronization for the LogEntries table is disabled. Defaults to true.</documentation>
					</annotation>
				</element>
				<element name="includeReports" type="boolean" default="true" minOccurs="0">
					<annotation>
						<documentation>If set to false synchronization for the Reports table is disabled. Defaults to true. </documentation>
					</annotation>
				</element>
				<element name="includeThresholdEvents" type="boolean" default="true" minOccurs="0">
					<annotation>
						<documentation>if set to false, synchronization for the ThresholdEvents table is disabled. Defaults to true. </documentation>
					</annotation>
				</element>
				<element name="includeTimeSeries" type="boolean" default="true" minOccurs="0">
					<annotation>
						<documentation>If set to false, synchronization for the TimeSeries table is disabled. Defaults to true. </documentation>
					</annotation>
				</element>
				<element name="includeUsers" type="boolean" default="true" minOccurs="0">
					<annotation>
						<documentation>If set to false, no Users, UserSettings, AccessKeyHashes and UserToGroupsMappings are synchronized.</documentation>
					</annotation>
				</element>
				<element name="includeWarmStates" type="boolean" default="true" minOccurs="0">
					<annotation>
						<documentation>If set to false, synchronization for the WarmStates table is disabled. Defaults to true. </documentation>
					</annotation>
				</element>
				<element name="timeSeriesSynchLevel" type="integer" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>Controls which timeseries with what synchLevels are enabled to be synchronized. When none specified, only the default synchLevels for Timeseries are synchronized, e.g. synchLevels 0, 2, 5, 8, 30.</documentation>
					</annotation>
				</element>
			</sequence>
		</choice>
		<attribute name="id" type="fews:idStringType" use="required"/>
	</complexType>
	<complexType name="MCSynchProfilesComplexType">
		<sequence>
			<element name="synchProfile" type="fews:MCSynchProfileComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Define synchronization profiles.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="RemoteMCComplexType">
		<sequence>
			<element name="databaseIntId" type="int" minOccurs="0">
				<annotation>
					<documentation>Optional databaseIntId to validate the remote Master Controller databaseIntId.</documentation>
				</annotation>
			</element>
			<element name="databaseServer" type="fews:DatabaseServerComplexType" minOccurs="0">
				<annotation>
					<documentation>Only required for remote Master Controllers. It is preferred to use Active Directory or Kerberos for connecting to remote Master Controller databases when possible. The actual user and encrypted password are normally put in the mcConfig file. If this is not allowed it is also possible to use variables, e.g. %FEWS_MC_MC01_DATABASE_URL%, %FEWS_MC_MC01_DATABASE_USER% and %FEWS_MC_MC01_DATABASE_ENCRYPTED_PASSWORD% can be put in the synch remote Master Controller databaseServer element. Also this allows the ICT to manage the connection details without changing the mc.xml file which is the responsibility of the Application Manager.</documentation>
				</annotation>
			</element>
			<element name="synchProfileId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Refers to one of the synchProfiles.</documentation>
				</annotation>
			</element>
			<element name="failoverPriority" type="integer" minOccurs="0">
				<annotation>
					<documentation>Only applies to Master Controllers with Failover Tasks. The Master Controller with the top Priority rank (lowest number) will take over failover Tasks when the owner Master Controller fails over. Best practice is to specify the remote mcIds first in the preferred order. The current mcId is most commonly to be placed last. This prevents the Master Controller to run duplicate tasks. See the wiki for optimal guidance.</documentation>
				</annotation>
			</element>
			<element name="synchEnabled" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>When false the MC-MC Synchronization is disabled. By default true meaning synchronization is enabled.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:mcIdStringType" use="required">
			<annotation>
				<documentation>Identifies the remote Master Controller. Must match the contents of the mcId in the LocalMcId table.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="RemoteMCsComplexType">
		<sequence>
			<element name="remoteMC" type="fews:RemoteMCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="SynchComplexType">
		<sequence>
			<element name="failoverPriority" type="integer" minOccurs="0">
				<annotation>
					<documentation>Only applies to Master Controllers with Failover Tasks. The Master Controller with the top Priority rank (lowest number) will take over failover Tasks when the owner Master Controller fails over. Best practice is to specify the remote mcIds first in the preferred order. The current mcId is always placed last. This prevents the Master Controller to run duplicate tasks.</documentation>
				</annotation>
			</element>
			<element name="failoverType" type="fews:failoverType" default="no failover" minOccurs="0">
				<annotation>
					<documentation>By setting this status, this Master Controller will start operating as it were alone in the pool of Master Controllers. This Master Controller will stop synchronizing forecast data from other Master Controllers The remote Master Controllers also stop synchronizing forecast data from this Master Controller. See also failover policy in Task. Defaults to no failover.</documentation>
				</annotation>
			</element>
			<element name="remoteMCs" type="fews:RemoteMCsComplexType" minOccurs="0">
				<annotation>
					<documentation>List of one or more remote Master Controllers to synchronize from.</documentation>
				</annotation>
			</element>
			<element name="synchProfiles" type="fews:MCSynchProfilesComplexType" minOccurs="0">
				<annotation>
					<documentation>Define synchronization profiles.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="WorkflowMappingComplexType">
		<attribute name="workflowId" type="fews:idStringType" use="required"/>
		<attribute name="fssGroupId" type="fews:idStringType" use="required"/>
		<attribute name="mcId" type="fews:mcIdStringType" use="optional"/>
		<attribute name="allowFailover" type="boolean" use="optional" default="true"/>
	</complexType>
	<complexType name="WorkflowMappingsComplexType">
		<sequence>
			<element name="workflowMapping" type="fews:WorkflowMappingComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Maps a workflowId to a single FssGroup. Not required when the FSSGroup is allowing unmapped workflows. Always use workflow mappings for deploying dedicated FssGroups that are not allowing unmapped workflowIds.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="WhatIfScenarioComplexType">
		<sequence>
			<group ref="fews:WhatIfScenarioGroup"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:idStringType" use="required"/>
	</complexType>
	<complexType name="WhatIfScenariosComplexType">
		<sequence>
			<element name="whatIfScenario" type="fews:WhatIfScenarioComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Defines a WhatIfScenario.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="failoverPolicyType">
		<restriction base="string">
			<enumeration value="run duty">
				<annotation>
					<documentation>Run this Task only on the Master Controller that owns it (default).</documentation>
				</annotation>
			</enumeration>
			<enumeration value="run duty and failover">
				<annotation>
					<documentation>When the Duty Master Controller is in Failover mode, run this task on the top priority Failover Master Controller, but also run this task on the Duty Master Controller that owns it.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="suspend duty in failover">
				<annotation>
					<documentation>When the Duty Master Controller is in Failover mode, run this task on the top priority Failover Master Controller and do not run this task on the Duty Master Controller that owns it.</documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>
	<complexType name="TaskEntryComplexType">
		<sequence>
			<element name="taskStatus" type="fews:TaskStatusEnumStringType">
				<annotation>
					<documentation>Task status: pending, suspended, finished</documentation>
				</annotation>
			</element>
			<element name="taskTag" type="fews:maxLength64StringType" minOccurs="0">
				<annotation>
					<documentation>Task tag for events and action mappings</documentation>
				</annotation>
			</element>
			<element name="failoverPolicy" type="fews:failoverPolicyType" default="run duty" minOccurs="0">
				<annotation>
					<documentation>Task runs on remote Master Controller on failover. Defaults to "run duty".</documentation>
				</annotation>
			</element>
			<element name="runOption" type="fews:TaskRunOptionEnumStringType" minOccurs="0"/>
			<element name="taskProperties" type="fews:TaskPropertiesComplexType">
				<annotation>
					<documentation>Task properties</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TaskComplexType">
		<sequence>
			<group ref="fews:TaskGroup"/>
		</sequence>
		<attribute name="mcId" type="fews:mcIdStringType" use="optional">
			<annotation>
				<documentation>Only required when not present in all Master Controllers.</documentation>
			</annotation>
		</attribute>
		<attribute name="description" type="string" use="optional">
			<annotation>
				<documentation>.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="TasksComplexType">
		<sequence>
			<element name="task" type="fews:TaskComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Defines a scheduled Task or a suspended one-off Task in the Master Controller.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="EventActionConfigsComplexType">
		<sequence>
			<element name="eventAction" type="fews:EventActionComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Defines the action to be triggered by the LogEventProcessor when an eventCode is logged.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="EventActionMappingComplexType">
		<attribute name="eventCode" type="fews:idStringType" use="required">
			<annotation>
				<documentation>EventCode that is to trigger the specified Action Configuration. Asterisks '*' may be used for matching a eventCode wildcard pattern.</documentation>
			</annotation>
		</attribute>
		<attribute name="actionId" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Id of the Action Configuration.</documentation>
			</annotation>
		</attribute>
		<attribute name="mcId" type="fews:mcIdStringType" use="optional">
			<annotation>
				<documentation>Only required when not present in all Master Controllers.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="EventActionMappingsComplexType">
		<sequence>
			<element name="eventActionMapping" type="fews:EventActionMappingComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Defines a trigger for an eventAction when an eventCode is logged in the LogEntries table. The LogEventProcessor in the Master Controller will detect and execute these.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="MCComplexType">
		<sequence>
			<element name="mcId" type="fews:mcIdStringType" minOccurs="0">
				<annotation>
					<documentation>Optional mcId for identifying the Master Controller uniquely. The official Master Controller mcId is located in the LocalMcId table. When this mcId is provided it is merely used as validation before upload and when starting the Master Controller / Admin Interface. The mcId is an Alphanumeric non-empty identifier no longer than 30 characters wide. Typically (but not absolutely required) a lowercase concatenation of 2 chars for country, 2 chars for the organisation, 2 chars for the region configuration name, a single char indicating d (development), t (test), a (acceptance) or p (production), the string mc and finally two numbers for uniquely identifying this specific Delft-FEWS system (00-97), for instance ukeanwamc00 stands for United Kingdom Environment Agency North West Acceptance Master Controller 00.</documentation>
				</annotation>
			</element>
			<element name="name" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>Optional name of the mc. This name can be used in the config with $MC_NAME$ on OC and FSS</documentation>
				</annotation>
			</element>
			<element name="databaseIntId" type="fews:databaseIntStringType" minOccurs="0">
				<annotation>
					<documentation>Optional databaseIntId (0-97) for validating the offset of the GlobalRowId. Must be unique within the pool of MasterControllers.</documentation>
				</annotation>
			</element>
			<element name="logging" type="fews:MCLoggingComplexType" minOccurs="0">
				<annotation>
					<documentation>Defines logging options, debug mode, system logging etc.</documentation>
				</annotation>
			</element>
			<element name="jvmOption" type="fews:nonEmptyStringType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Options to tune the Java Virtual Machine for the Master Controller. When none is specified defaults to -Xmx1024m.</documentation>
				</annotation>
			</element>
			<element name="adminInterface" type="fews:AdminInterfaceComplexType" minOccurs="0">
				<annotation>
					<documentation>Configuration options for the Admin Interface.</documentation>
				</annotation>
			</element>
			<element name="taskRunDispatcher" type="fews:TaskRunDispatcherComplexType" minOccurs="0">
				<annotation>
					<documentation>TaskRunDispatcher settings.</documentation>
				</annotation>
			</element>
			<element name="synch" type="fews:SynchComplexType" minOccurs="0">
				<annotation>
					<documentation>Defines synchronization from remote MasterControlllers. Absent when using a single Master Controller.</documentation>
				</annotation>
			</element>
			<element name="azure" type="fews:FssGroupAzureComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Specify the Azure Configuration for an FSS Group required for scaling FSS.</documentation>
				</annotation>
			</element>
			<element name="fssGroups" type="fews:FssGroupsComplexType" minOccurs="0">
				<annotation>
					<documentation>Definition of Forecasting Shell Server Groups and autoscaling options.</documentation>
				</annotation>
			</element>
			<element name="workflowMappings" type="fews:WorkflowMappingsComplexType" minOccurs="0">
				<annotation>
					<documentation>Maps workflowIds to FssGroups.</documentation>
				</annotation>
			</element>
			<element name="whatIfScenarios" type="fews:WhatIfScenariosComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated and obsolete since 2021.02. No longer uploaded via the AdminInterface. Defines WhatIfScenarios so they can be also uploaded along with the Tasks that refer to them.</documentation>
				</annotation>
			</element>
			<element name="tasks" type="fews:TasksComplexType" minOccurs="0">
				<annotation>
					<documentation>Defines scheduling of Tasks. Since 2021.02, Tasks with WhatIfScenarios will no longer be uploaded.</documentation>
				</annotation>
			</element>
			<element name="eventActions" type="fews:EventActionConfigsComplexType" minOccurs="0">
				<annotation>
					<documentation>Defines EventActions. See also eventActionMappings.</documentation>
				</annotation>
			</element>
			<element name="eventActionMappings" type="fews:EventActionMappingsComplexType" minOccurs="0">
				<annotation>
					<documentation>Defines triggers for one or more eventActions. When an eventCode is logged in the LogEntries table, the LogEventProcessor in the Master Controller will detect them and trigger the mapped Event Actions.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
