<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="mc.xsd"/>
	<element name="systems" type="fews:SystemsComplexType">
		<annotation>
			<documentation>Config for CommandLineInterface.</documentation>
		</annotation>
	</element>
	<complexType name="SystemsComplexType">
		<sequence>
			<element name="system" type="fews:SystemComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="SystemComplexType">
		<sequence>
			<element name="database" type="fews:DatabaseComplexType"/>
			<element name="mc" type="fews:MCComplexType"/>
		</sequence>
	</complexType>
	<complexType name="DatabaseComplexType">
		<sequence>
			<choice>
				<element name="oracle" type="fews:OracleComplexType"/>
				<element name="postgresql" type="fews:PostgreSqlComplexType"/>
				<element name="sqlserver" type="fews:SqlServerComplexType"/>
			</choice>
			<element name="databaseServer" type="fews:DatabaseServerConnectionConfigComplexType">
				<annotation>
					<documentation>The connection details for this Master Controller connection.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OracleTablespaceComplexType">
		<sequence>
			<element name="dir" type="fews:fileStringType"/>
			<element name="size" type="fews:OracleByteSizeType"/>
		</sequence>
	</complexType>
	<group name="dbaCredentialGroup">
		<sequence>
			<element name="dbaUserVariableKey" type="string" minOccurs="0"/>
			<element name="dbaPasswordEnvironmentVariableKey" type="string" minOccurs="0"/>
		</sequence>
	</group>
	<complexType name="OracleComplexType">
		<sequence>
			<group ref="fews:dbaCredentialGroup"/>
			<element name="datTablespace" type="fews:OracleTablespaceComplexType"/>
			<element name="lobTablespace" type="fews:OracleTablespaceComplexType"/>
			<element name="idxTablespace" type="fews:OracleTablespaceComplexType"/>
		</sequence>
	</complexType>
	<simpleType name="OracleByteSizeStringType">
		<restriction base="string">
			<pattern value="[1-9][0-9]*[G|M]"/>
		</restriction>
	</simpleType>
	<simpleType name="OracleByteSizeType">
		<union memberTypes="fews:OracleByteSizeStringType fews:propertyReferenceString"/>
	</simpleType>
	<complexType name="PostgreSqlTablespaceComplexType">
		<sequence>
			<element name="dir" type="fews:fileStringType" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="PostgreSqlComplexType">
		<sequence>
			<group ref="fews:dbaCredentialGroup"/>
			<element name="dataTablespace" type="fews:PostgreSqlTablespaceComplexType"/>
			<element name="indexTablespace" type="fews:PostgreSqlTablespaceComplexType"/>
			<element name="properties" type="fews:PropertiesComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional. Properties in the form of key-value pairs. Suggested are:<br/>
						<table>
							<tr>
								<td>shared_buffers = 512MB</td>
								<td># 1/4 the physical memory</td>
							</tr>
							<tr>
								<td>work_mem = 4MB</td>
								<td>default 4MB (16MB might perform even better, but be careful in case of many users!)</td>
							</tr>
							<tr>
								<td>maintenance_work_mem = 16MB</td>
								<td>default 16MB (more might increase vacuum performance)</td>
							</tr>
							<tr>
								<td>checkpoint_completion_target = 0.9</td>
								<td>0.9 is strongly recommended together with 32+ checkpoint_segments</td>
							</tr>
							<tr>
								<td>effective_cache_size = 1GB</td>
								<td>1/2 the physical memory</td>
							</tr>
							<tr>
								<td>max_connections = 400</td>
								<td>Depending on the number of clients and Forecasting Shells connecting simultaneously with DDA the maximum amount of allowed connections should be raised.</td>
							</tr>
							<tr>
								<td>#checkpoint_segments = 32</td>
								<td>before PostgreSQL-9.5. 10..256, 32 is popular, logging might suggest even more</td>
							</tr>
							<tr>
								<td>max_wal_size = 1536MB</td>
								<td>since PostgreSQL-9.5</td>
							</tr>
							<tr>
								<td>idle_in_transaction_session_timeout = 300000</td>
								<td>since PostgreSQL-9.6: Postgres 9.4 is fine but for new installs we prefer PostgreSQL-9.6 over PostgreSQL-9.4 since it has improved handling of idle connections, see https://www.postgresql.org/docs/9.6/runtime-config-client.html</td>
							</tr>
						</table>
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SqlServerComplexType">
		<sequence>
			<group ref="fews:dbaCredentialGroup"/>
			<choice>
				<group ref="fews:SqlServerDboGroup"/>
				<group ref="fews:SqlServerFilegroupGroup"/>
			</choice>
		</sequence>
	</complexType>
	<group name="SqlServerDboGroup">
		<sequence>
			<element name="dataFileDir" type="fews:fileStringType"/>
			<element name="logFileDir" type="fews:fileStringType"/>
		</sequence>
	</group>
	<group name="SqlServerFilegroupGroup">
		<sequence>
			<element name="datFilegroupSize" type="fews:SqlServerByteSizeType"/>
			<element name="lobFilegroupSize" type="fews:SqlServerByteSizeType"/>
			<element name="idxFilegroupSize" type="fews:SqlServerByteSizeType"/>
			<element name="dataFileDir" type="fews:fileStringType"/>
			<element name="logFileDir" type="fews:fileStringType"/>
		</sequence>
	</group>
	<simpleType name="SqlServerByteSizeStringType">
		<restriction base="string">
			<pattern value="[1-9][0-9]*[GB|MB]"/>
		</restriction>
	</simpleType>
	<simpleType name="SqlServerByteSizeType">
		<union memberTypes="fews:SqlServerByteSizeStringType fews:propertyReferenceString"/>
	</simpleType>
</schema>
