<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<complexType name="MidlandsFolderNamesComplexType">
		<annotation>
			<documentation>Folder names required by the Midlands modules (MCRM and DODO)</documentation>
		</annotation>
		<sequence>
			<element name="configDir" type="fews:directoryStringType"/>
			<element name="workDir" type="fews:directoryStringType"/>
			<element name="moduleDir" type="fews:directoryStringType"/>
			<element name="importDir" type="fews:directoryStringType"/>
			<element name="exportDir" type="fews:directoryStringType"/>
		</sequence>
	</complexType>
	<complexType name="MidlandsModuleFileNamesComplexType">
		<annotation>
			<documentation>File names required by the Midlands modules</documentation>
		</annotation>
		<sequence>
			<element name="structureFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Structure file: Contains general information that is required by the Midlands module.</documentation>
				</annotation>
			</element>
			<element name="dataFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Data file: Contains data required by the Midlands module.</documentation>
				</annotation>
			</element>
			<element name="parameterFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Parameters file: Contains all parameter information that is required by the Midlands modules.</documentation>
				</annotation>
			</element>
			<element name="inputHindcastFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Input data file: Contains the hindcast data of the Midlands modules.</documentation>
				</annotation>
			</element>
			<element name="inputForecastFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Input data file: Contains the forecast data of the Midlands modules.</documentation>
				</annotation>
			</element>
			<element name="outputHindcastFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Output data file: Contains the hindcast data of the Midlands modules.</documentation>
				</annotation>
			</element>
			<element name="outputForecastFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Output data file: Contains the forecast data of the Midlands modules.</documentation>
				</annotation>
			</element>
			<element name="logFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>MCRM module log file: Contains messages produced by the Midlands modules.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="MidlandsAdapterFileNamesComplextype">
		<annotation>
			<documentation>File names required by the Midlands module adapters</documentation>
		</annotation>
		<sequence>
			<element name="stateFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>State xml file: Contains information on where to retrieve the state file that is to be used for the forecast.</documentation>
				</annotation>
			</element>
			<element name="stateTimeSeriesFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>State time series xml file: Contains non equidistant time series data for updating the state variables.</documentation>
				</annotation>
			</element>
			<element name="parameterFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>PI parameter xml file: Contains update parameter values for the parameter.properties file.</documentation>
				</annotation>
			</element>
			<element name="inputHindcastFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Input xml file: Contains all hindcast time series required by the midlands module adapters. </documentation>
				</annotation>
			</element>
			<element name="inputForecastFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Input xml file: Contains all forecast time series required by the midlands module adapters. </documentation>
				</annotation>
			</element>
			<element name="outputHindcastFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Output xml file: Contains the hindcast time series generated by the midlands module adapter.</documentation>
				</annotation>
			</element>
			<element name="outputForecastFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Output xml file: Contains the forecast time series generated by the midlands module adapter.</documentation>
				</annotation>
			</element>
			<element name="diagnosticFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Diagnostic file: Contains all messages produced by the Midlands module adapter.</documentation>
				</annotation>
			</element>
			<element name="inflowHindcastFile" type="fews:fileStringType" minOccurs="0" maxOccurs="6">
				<annotation>
					<documentation>Input xml file: Contains the hindcast inflow time series for DODO</documentation>
				</annotation>
			</element>
			<element name="inflowForecastFile" type="fews:fileStringType" minOccurs="0" maxOccurs="6">
				<annotation>
					<documentation>INput xml file: Contains the forecast inflow time series for DODO</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="MidlandsVariablesComplexType">
		<annotation>
			<documentation>Information about Midlands module variables</documentation>
		</annotation>
		<sequence>
			<element name="name" type="fews:nameStringType">
				<annotation>
					<documentation>Name of module catchment/reach. Preferably same as the location ID of the time series.</documentation>
				</annotation>
			</element>
			<element name="reservoir" type="boolean">
				<annotation>
					<documentation>Indicates presence of a reservoir</documentation>
				</annotation>
			</element>
			<element name="reservoirId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Should be included if a reservoir is present</documentation>
				</annotation>
			</element>
			<element name="area" type="float" minOccurs="0">
				<annotation>
					<documentation>Area of the catchment</documentation>
				</annotation>
			</element>
			<element name="useError" type="boolean">
				<annotation>
					<documentation>Indicates use of error module</documentation>
				</annotation>
			</element>
			<element name="outputTimeStep" type="fews:TimeStepComplexType" minOccurs="0">
				<annotation>
					<documentation>Output time step for post adapters</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="MidlandsInflowComplexType">
		<annotation>
			<documentation>Inflow information</documentation>
		</annotation>
		<sequence>
			<element name="name" type="string">
				<annotation>
					<documentation>Location id of inflow time series.</documentation>
				</annotation>
			</element>
			<element name="location" type="fews:inflowLocationEnumStringType">
				<annotation>
					<documentation>Location of the inflow time series.</documentation>
				</annotation>
			</element>
			<element name="type" type="fews:inflowTypeEnumStringType">
				<annotation>
					<documentation>Type of inflow.</documentation>
				</annotation>
			</element>
			<element name="hindcastFile" type="fews:fileStringType">
				<annotation>
					<documentation>File with hindcast inflow discharge time series.</documentation>
				</annotation>
			</element>
			<element name="forecastFile" type="fews:fileStringType">
				<annotation>
					<documentation>File with forecast inflow discharge time series.</documentation>
				</annotation>
			</element>
			<element name="proportion" type="fews:inflowProportionFloatType">
				<annotation>
					<documentation>Proportion (in %) of this inflow that is used.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="inflowLocationEnumStringType">
		<annotation>
			<documentation>Type of inflow locations</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="upstream"/>
			<enumeration value="downstream"/>
			<enumeration value="lateral"/>
		</restriction>
	</simpleType>
	<simpleType name="inflowTypeEnumStringType">
		<annotation>
			<documentation>Type of inflow types</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="catchment"/>
			<enumeration value="reach"/>
		</restriction>
	</simpleType>
	<simpleType name="inflowProportionFloatType">
		<annotation>
			<documentation>Allowable inflow proportions</documentation>
		</annotation>
		<restriction base="float">
			<minInclusive value="0"/>
			<maxInclusive value="100"/>
		</restriction>
	</simpleType>
</schema>
