<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="midlandsRiverRoutingModel.xsd"/>
	<include schemaLocation="midlandsCatchmentRunoffModel.xsd"/>
	<element name="midlandsModel" type="fews:MidlandsModelComplexType">
		<annotation>
			<documentation>Midlands model. Can be either a MCRM model or a DODO model</documentation>
		</annotation>
	</element>
	<complexType name="MidlandsModelComplexType">
		<annotation>
			<documentation>A midlands model. Either MCRM or DODO</documentation>
		</annotation>
		<choice>
			<element name="mcrm" type="fews:McrmComplexType">
				<annotation>
					<documentation>Midlands Region Catchment Runoff Model</documentation>
				</annotation>
			</element>
			<element name="dodo" type="fews:DodoComplexType">
				<annotation>
					<documentation>Midlands River Routing Model</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
</schema>
