<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- -->
	<element name="piFileGenerator" type="fews:PiFileGeneratorComplexType"/>
	<!-- -->
	<complexType name="PiFileGeneratorComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="general" type="fews:PiFileGeneratorGeneralComplexType"/>
			<element name="preActivity" type="fews:ExecuteActivityComplexType" minOccurs="0"/>
			<element name="activity" type="fews:PiFileGeneratorActivityComplexType"/>
			<element name="postActivity" type="fews:ExecuteActivityComplexType" minOccurs="0"/>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<!-- -->
	<complexType name="PiFileGeneratorActivityComplexType">
		<sequence>
			<element name="relativePeriod" type="fews:RelativePeriodComplexType">
				<annotation>
					<documentation>relative period wrt to passed time</documentation>
				</annotation>
			</element>
			<element name="timeStep" type="fews:TimeStepComplexType">
				<annotation>
					<documentation>time step</documentation>
				</annotation>
			</element>
			<element name="moduleLogFile" type="fews:fileStringType" minOccurs="0">
				<annotation>
					<documentation>Module Log file to include in diagnostics</documentation>
				</annotation>
			</element>
			<choice>
				<element name="mapStackFile" type="fews:PiMapStackFileComplexType" maxOccurs="unbounded"/>
			</choice>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="PiFileGeneratorGeneralComplexType">
		<sequence>
			<element name="workDir" type="fews:directoryStringType">
				<annotation>
					<documentation>Working directory for the common adapter.</documentation>
				</annotation>
			</element>
			<element name="diagnosticFile" type="fews:fileStringType">
				<annotation>
					<documentation>Diagnostics file</documentation>
				</annotation>
			</element>
			<element name="dateFormat" type="string" minOccurs="0">
				<annotation>
					<documentation>Contains date format for date column.</documentation>
				</annotation>
			</element>
			<element name="geoDatum" type="fews:geoDatumStringType" default="WGS 1984" minOccurs="0"/>
		</sequence>
	</complexType>
	<!-- -->
	<complexType name="PiMapStackFileComplexType">
		<annotation>
			<documentation>conversion file name is required if required for the correct location parameter or optionally on parameter</documentation>
		</annotation>
		<attribute name="mapStackXMLFile" type="fews:fileStringType" use="required"/>
		<attribute name="gridFilepattern" type="fews:fileStringType" use="required"/>
		<attribute name="gridFileType" type="fews:gridFileEnumStringType" use="required"/>
		<attribute name="parameterID" type="fews:idStringType" use="required"/>
		<attribute name="locationID" type="fews:idStringType" use="required"/>
	</complexType>
	<!-- -->
	<simpleType name="gridFileEnumStringType">
		<restriction base="string">
			<enumeration value="Ascii"/>
			<enumeration value="PCRaster"/>
			<enumeration value="USGS"/>
		</restriction>
	</simpleType>
</schema>
