<?xml version="1.0"?>
<schema targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema">
    <include schemaLocation="sharedTypes.xsd"/>
    <element name="polygons" type="fews:PolygonsComplexType"/>

    <complexType name="PolygonsComplexType">
        <sequence>
            <element name="esriShapeFile" type="fews:EsriShapeFileComplexType" maxOccurs="unbounded">
                <annotation>
                    <documentation>ESRI shape file</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="EsriShapeFileComplexType">
        <sequence>
            <element name="file" type="fews:fileStringType">
                <annotation>
                    <documentation>ESRI shape file</documentation>
                </annotation>
            </element>
            <element name="geoDatum" type="fews:geoDatumStringType"/>
            <element name="shapeIdAttributeName" type="string"/>
            <element name="areaAttributeName" type="string" minOccurs="0"/>
            <element name="areaMultiplier" type="double" minOccurs="0" default="1">
                <annotation>
                    <documentation>The multiplier that should be applied to the value in the dbf</documentation>
                </annotation>
            </element>
            <choice>
                <element name="shape" type="fews:EsriShapeComplexType" maxOccurs="unbounded"/>
                <element name="shapeIdFunction" type="fews:nonEmptyStringType">
                    <annotation>
                        <documentation>Maps all the shapes at once to the locations</documentation>
                    </annotation>
                </element>
            </choice>
        </sequence>
    </complexType>

    <complexType name="EsriShapeComplexType">
        <attribute name="locationId" type="fews:idStringType"/>
        <attribute name="shapeId" type="string"/>
    </complexType>
</schema>
