<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews/archive"
		targetNamespace="http://www.wldelft.nl/fews/archive" elementFormDefault="qualified"
		attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="archive_sharedTypes.xsd"/>
	<element name="ratingCurvesMetaData" type="fews:RatingCurvesMetaDataComplexType"/>
	<complexType name="RatingCurvesMetaDataComplexType">
		<sequence>
			<group ref="fews:SharedGeneralSettingsGroup" minOccurs="0"/>
			<element name="ratingCurves" type="fews:RatingCurvesComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RatingCurvesComplexType">
		<sequence>
			<element name="relativeFilePath" type="fews:nonEmptyStringType"/>
			<element name="areaId" type="fews:idStringType"/>
			<element name="creationTime" type="fews:DateTimeComplexType"/>
		</sequence>
	</complexType>
</schema>