<?xml version="1.0" encoding="utf-8"?>
<!--Delft FEWS (Copyright 2009 Deltares) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
  <include schemaLocation="sharedTypes.xsd"/>
  
  <element name="rdbmsExport" type="fews:RdbmsExportComplexType">
	  <annotation>
		  <documentation>LEGACY, NO LONGER USED</documentation>
	  </annotation>
  </element>
  <!-- -->
    <complexType name="RdbmsExportComplexType">
      <sequence>
        <element name="jdbcDriverClass" type="string" maxOccurs="1">
        	<annotation>
			<documentation>e.g. com.microsoft.jdbc.sqlserver.SQLServerDriver or oracle.jdbc.OracleDriver
			</documentation>
		</annotation>
        </element>
        <element name="jdbcConnectionString" type="string" maxOccurs="1">
        	<annotation>
			<documentation>Connection string to external database. Test the connection string in db visualiser before using</documentation>
		</annotation>
        </element>
        <element name="user" type="string" maxOccurs="1">
		<annotation>
			<documentation>Target database user name</documentation>
		</annotation>
        </element>
	<choice>
		<element name="password" type="string" maxOccurs="1">
			<annotation>
				<documentation>Password for database user</documentation>
			</annotation>
		</element>
		<element name="encryptedPassword" type="string" maxOccurs="1">
			<annotation>
				<documentation>Encrypted password for database user</documentation>
			</annotation>
		</element>
	</choice>
	<element name="exportTimeWindow" type="fews:RelativePeriodComplexType" maxOccurs="1"/>
	<element name="exportTimeZone" type="fews:timeZoneOffsetStringType" maxOccurs="1"/>
	<element name="moduleInstance" type="fews:ModuleInstanceIdComplexType" minOccurs="0" maxOccurs="unbounded" />
	<element name="filter" type="fews:FilterIdComplexType" minOccurs="0" maxOccurs="unbounded" />
      </sequence>
    </complexType>
    
    <!-- -->
    <complexType name="FilterIdComplexType">
    	<attribute name="filterID" type="fews:idStringType" use="required"/>
    </complexType>
    <complexType name="ModuleInstanceIdComplexType">
        	<attribute name="moduleInstanceID" type="fews:idStringType" use="required"/>
    </complexType>
</schema>