<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- -->
	<element name="sacramentoModel" type="fews:SacramentoModelComplexType"/>
	<!-- -->
	<complexType name="SacramentoModelComplexType">
		<sequence>
			<element name="general" type="fews:AdapterGeneralComplexType"/>
			<element name="activities" type="fews:AdapterActivitiesComplexType"/>
		</sequence>
	</complexType>
	<!---->
	<complexType name="AdapterActivitiesComplexType">
		<sequence>
			<element name="preAdapterActivities" type="fews:AdapterActivityComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="postAdapterActivities" type="fews:AdapterActivityComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!---->
	<complexType name="AdapterGeneralComplexType">
		<sequence>
			<element name="workDir" type="fews:directoryStringType">
				<annotation>
					<documentation>Working directory for the sacramento model.</documentation>
				</annotation>
			</element>
			<element name="importDir" type="fews:directoryStringType">
				<annotation>
					<documentation>Location to retrieve input files</documentation>
				</annotation>
			</element>
			<element name="exportDir" type="fews:directoryStringType">
				<annotation>
					<documentation>Location to write output files</documentation>
				</annotation>
			</element>
			<element name="stateFile" type="fews:fileStringType">
				<annotation>
					<documentation>State file</documentation>
				</annotation>
			</element>
			<element name="diagnosticFile" type="fews:fileStringType">
				<annotation>
					<documentation>Diagnostics file</documentation>
				</annotation>
			</element>
			<element name="missingValue" type="float">
				<annotation>
					<documentation>Missing value for adapter files.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!---->
	<complexType name="AdapterActivityComplexType">
		<sequence>
			<element name="dateFormat" type="string">
				<annotation>
					<documentation>Contains date format for date column.</documentation>
				</annotation>
			</element>
			<element name="input" type="fews:fileStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>Time series files containing input data.</documentation>
				</annotation>
			</element>
			<element name="output" type="fews:fileStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>Time series files containing output data.</documentation>
				</annotation>
			</element>
			<element name="mapping" type="fews:AdapterMappingComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Contains information on the data that is present in the columns of either the input files (post-activity) or output files (pre-activity)</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
