<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews"
		xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="sampleMetadataSchema" type="fews:SampleMetadataSchemaComplexType"/>
	<complexType name="SampleMetadataSchemaComplexType">
		<sequence>
			<element name="valueTypes" type="fews:SamplePropertyValueTypesComplexType">
				<annotation>
					<documentation>List of value types that are referenced from the property definitions</documentation>
				</annotation>
			</element>
			<element name="properties" type="fews:SamplePropertyDefsComplexType">
				<annotation>
					<documentation>List of properties that are allowed in the sample meta data</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="SamplePropertyValueTypesComplexType">
		<choice maxOccurs="unbounded">
			<element name="enumerationsCsvFile" type="fews:SampleEnumerationsCsvFileComplexType">
				<annotation>
					<documentation>Reference to csv file than contains multiple sample property enum definitions</documentation>
				</annotation>
			</element>
			<element name="enumeration" type="fews:SampleEnumerationComplexType">
				<annotation>
					<documentation>Enumeration definition</documentation>
				</annotation>
			</element>
			<element name="dateTime" type="fews:SamplePropertyValueTypeComplexType">
				<annotation>
					<documentation>Date time property definition</documentation>
				</annotation>
			</element>
			<element name="double" type="fews:SamplePropertyValueTypeComplexType">
				<annotation>
					<documentation>Number property definition</documentation>
				</annotation>
			</element>
			<element name="string" type="fews:SamplePropertyValueTypeComplexType">
				<annotation>
					<documentation>Text property definition</documentation>
				</annotation>
			</element>
	</choice>
	</complexType>

	<complexType name="SamplePropertyDefsComplexType">
		<choice maxOccurs="unbounded">
			<element name="propertiesCsvFile" type="fews:SamplePropertiesCsvFileComplexType">
				<annotation>
					<documentation>Reference to csv file than contains multiple property definitions</documentation>
				</annotation>
			</element>
			<element name="property" type="fews:SamplePropertyDefComplexType">
				<annotation>
					<documentation>Definition a property that is allowed in the sample meta data</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>

	<complexType name="SamplePropertyValueTypeComplexType">
		<attribute name="id" type="string"/>
	</complexType>

	<complexType name="SampleEnumerationComplexType">
		<sequence>
			<element name="value" type="fews:SampleEnumerationValueComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="string"/>
	</complexType>

	<complexType name="SampleEnumerationValueComplexType">
		<sequence>
			<element name="description" type="string"/>
		</sequence>
		<attribute name="code" type="fews:nonEmptyStringType" use="required"/>
		<attribute name="label" type="fews:nonEmptyStringType"/>
	</complexType>

	<complexType name="SampleEnumerationsCsvFileComplexType">
		<sequence>
			<element name="file" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>name of a csv file in the map layer files or a full absolute path to the csv file
						(*.csv).
					</documentation>
				</annotation>
			</element>
			<element name="charset" type="fews:charsetEnumStringType" default="ISO-8859-1" minOccurs="0">
				<annotation>
					<documentation>Character set of the text in the csv file. Specify only when the csv file contains
						non western characters.
					</documentation>
				</annotation>
			</element>
			<group ref="fews:SampleEnumerationsResourceSequence"/>
		</sequence>
	</complexType>


	<group name="SampleEnumerationsResourceSequence">
		<sequence>
			<element name="id" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>id of enum value type id of the filed the csv file. e.g. "%TYPE%", put the actual column name between %%.
					</documentation>
				</annotation>
			</element>
			<element name="code" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>put the actual column name between %%
					</documentation>
				</annotation>
			</element>
			<element name="label" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>put the actual column name between %%
					</documentation>
				</annotation>
			</element>
			<element name="description" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>put the actual column name between %%
					</documentation>
				</annotation>
			</element>
		</sequence>
	</group>


	<complexType name="SamplePropertiesCsvFileComplexType">
		<sequence>
			<element name="file" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>name of a csv file in the map layer files or a full absolute path to the csv file (*.csv).
					</documentation>
				</annotation>
			</element>
			<element name="charset" type="fews:charsetEnumStringType" default="ISO-8859-1" minOccurs="0">
				<annotation>
					<documentation>Character set of the text in the csv file. Specify only when the csv file contains
						non western characters.
					</documentation>
				</annotation>
			</element>
			<group ref="fews:SamplePropertiesResourceSequence"/>
		</sequence>
	</complexType>

	<group name="SamplePropertiesResourceSequence">
		<sequence>
			<element name="id" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>id of the filed the csv file. e.g. "H_%ID%", put the actual column name between %%.
					</documentation>
				</annotation>
			</element>
			<element name="name" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>Name displayed to user</documentation>
				</annotation>
			</element>
			<element name="description" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>put the actual column name between %%
					</documentation>
				</annotation>
			</element>
			<element name="valueTypeId" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>put the actual column name between %%
					</documentation>
				</annotation>
			</element>
			<element name="scope" type="fews:propertyScopeStringType" minOccurs="0">
				<annotation>
					<documentation>Determines whether the property belong to the value or whole sample. Can also refer to column with name between %%</documentation>
				</annotation>
			</element>
		</sequence>
	</group>
	<complexType name="SamplePropertyDefComplexType">
		<sequence>
			<element name="description" type="fews:nonEmptyStringType" minOccurs="0">
				<annotation>
					<documentation>Description visible for the user in the sample table
					</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:nonEmptyStringType" use="required">
			<annotation>
				<documentation>Id used to store the property value in the datastore, never change
				</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nonEmptyStringType">
			<annotation>
				<documentation>Name displayed to the user</documentation>
			</annotation>
		</attribute>
		<attribute name="valueTypeId" type="fews:nonEmptyStringType" use="required">
			<annotation>
				<documentation>Reference to the value type defined earlier in this xml file.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="scope" type="fews:propertyScopeEnumStringType" default="sample">
			<annotation>
				<documentation>Determines whether the property belong to the value or whole sample</documentation>
			</annotation>
		</attribute>
	</complexType>
	<simpleType name="propertyScopeStringType">
		<annotation>
			<documentation>Enum string defining whether a property belongs to a value or a sample, can also refer to a csv column value using %%</documentation>
		</annotation>
		<union memberTypes="fews:propertyScopeEnumStringType fews:columnReferenceString"/>
	</simpleType>
	<simpleType name="propertyScopeEnumStringType">
		<restriction base="string">
			<enumeration value="sample"/>
			<enumeration value="value"/>
		</restriction>
	</simpleType>
</schema>
