<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!--Delft FEWS (Copyright 2009 Deltares (Delft Hydraulics)) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="transformationTypes.xsd"/>
	<element name="scadaDisplay" type="fews:ScadaDisplayComplexType">
		<annotation>
			<documentation>Contains configuration for a scada display.</documentation>
		</annotation>
	</element>
	<complexType name="ScadaDisplayComplexType">
		<sequence>
			<element name="displayName" type="fews:nameStringType">
				<annotation>
					<documentation>Title of this display.</documentation>
				</annotation>
			</element>
			<element name="showTimeNavigatorToolbar" type="fews:ScadaTimeNavigatorToolbarSettingsComplexType" minOccurs="0">
				<annotation>
					<documentation>Option to show a time navigator toolbar at the top of this scada display. The time navigator toolbar can be used to select the display time for this scada display.
						It is only possible to select a display time that is contained within the configured relative period and is a valid time according to the configured time step. This period is
						always relative to the current display time. If the current system time changes, then the display time is reset to the current system time. If not specified, then time
						navigator toolbar is not shown.
					</documentation>
				</annotation>
			</element>
			<element name="globalDatumButtonViewPermission" type="fews:nameStringType" minOccurs="0">
				<annotation>
					<documentation>Since 2025.01 Configure a view permission for the new global datum button.</documentation>
				</annotation>
			</element>
			<element name="backgroundColor" type="fews:colorStringType" minOccurs="0">
				<annotation>
					<documentation>Since 206.02 Configure the default background color for all scada displays. If nothing is configured, the background will be white by default.</documentation>
				</annotation>
			</element>
			<element name="dateFormat" type="fews:ScadaDateFormatComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Definitions of dateFormats that can be used for formatting dates and times in tags in texts of svg objects.</documentation>
				</annotation>
			</element>
			<element name="numberFormat" type="fews:ScadaNumberFormatComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Definitions of numberFormats that can be used for formatting numbers in tags in texts of svg objects.</documentation>
				</annotation>
			</element>
			<element name="variable" type="fews:ScadaVariableDefinitionComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Definitions of variables that can be used as input and/or output for the components in this scada display or for the on-the-fly transformations that can be defined
						below. A variable is always a time series. Alternatively variable definitions can be embedded in the configuration below.
					</documentation>
				</annotation>
			</element>
			<element name="transformation" type="fews:TransformationFunctionComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>One or more transformations that will be carried out on-the-fly when the data in this display is updated. The results will not to be stored permanently in the local
						datastore but might be cleared when the Schematic Status Display is closed.
					</documentation>
				</annotation>
			</element>
			<choice maxOccurs="unbounded">
				<element name="scadaPanel" type="fews:ScadaPanelComplexType">
					<annotation>
						<documentation>One or more definitions of scada panels. In the user interface each scada panel will be available from the list in this scada display.</documentation>
					</annotation>
				</element>
				<element name="scadaPanelId" type="fews:idStringType">
					<annotation>
						<documentation>Since 2017.02 Id of a scadaPanel that is configured in an another ScadaDisplay.xml</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="ScadaDateFormatComplexType">
		<sequence>
			<element name="timeZone" type="fews:TimeZoneComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional time zone for this dateFormat. If no time zone is defined, then uses GMT.</documentation>
				</annotation>
			</element>
			<element name="dateTimePattern" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>Pattern for this dateFormat. This can be e.g. "yyyy-MM-dd HH:mm:ss".</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier for this dateFormat. Use this identifier to reference to this dateFormat in a tag in the text of an svg object.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="ScadaNumberFormatComplexType">
		<sequence>
			<element name="pattern" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>Pattern for this numberFormat. This can be e.g. "{0,number,#.##}" to get data values that are rounded to two decimal places.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier for this numberFormat. Use this identifier to reference to this numberFormat in a tag in the text of an svg object.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="ScadaVariableDefinitionComplexType">
		<sequence>
			<element name="variableId" type="fews:idStringType">
				<annotation>
					<documentation>Identifier for this variable. Use this identifier to reference to this variable in a component in the scada display configuration.</documentation>
				</annotation>
			</element>
			<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType">
				<annotation>
					<documentation>A time series set that can be used as input and/or output for a component in the scada display.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ScadaVariableComplexType">
		<annotation>
			<documentation>Choose between a reference to a variable or an embedded definition of a variable.</documentation>
		</annotation>
		<choice>
			<sequence>
				<element name="variableId" type="fews:idStringType">
					<annotation>
						<documentation>Identifier of a variable to use.</documentation>
					</annotation>
				</element>
				<element name="locationId" type="fews:idStringType" minOccurs="0">
					<annotation>
						<documentation>If the specified variable contains multiple locations, then specify the location to use here.</documentation>
					</annotation>
				</element>
				<element name="overrulingRelativeViewPeriod" type="fews:RelativePeriodComplexType" minOccurs="0">
					<annotation>
						<documentation>Optional time period for which data should be read. This time period overrules the viewPeriod in the timeSeriesSet of the referenced variable. This time period
							is relative to the selected display time in this scada display. The start and end of the period are both included. If the start and/or end of the period is not a valid time
							according to the timeStep of the variable, then the start and/or end is shifted to the previous valid time (e.g. for a period from 15:20 hours to 16:20 hours and a whole
							hour timeStep the period is shifted to be 15:00 hours to 16:00 hours).
						</documentation>
					</annotation>
				</element>
			</sequence>
			<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType">
				<annotation>
					<documentation>A time series set that can be used as input for a component.</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="DisplayPlotComplexType">
		<annotation>
			<documentation>Configure reference to a pre configured plot in the DisplayGroups configuration file.</documentation>
		</annotation>
		<sequence>
			<choice>
				<group ref="fews:DisplayNameGroup"/>
				<element name="displayId" type="fews:idStringType"/>
			</choice>
			<element name="overrulingRelativeViewPeriod" type="fews:RelativePeriodComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional time period for which data should be read. This view period overrules the relativeViewPeriod configured in the displayGroups configuration.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<group name="DisplayNameGroup">
		<sequence>
			<element name="displayGroupName" type="fews:nameStringType"/>
			<element name="displayName" type="fews:nameStringType"/>
		</sequence>
	</group>
	<complexType name="ScadaPanelComplexType">
		<sequence>
			<element name="svgFile" type="fews:fileStringType">
				<annotation>
					<documentation>The name of an svg (Scalable Vector Graphics) file in the ReportImageFiles directory. This scada panel shows all svg objects that are defined in the specified svg
						file. The svg objects in the svg file can be given special behaviour and/or properties using the configuration below. See http://www.w3.org/TR/SVG11/ for the SVG 1.1
						specification.
					</documentation>
				</annotation>
			</element>
			<element name="overrulingTimeNavigatorTimeStep" type="fews:TimeStepComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2015.02. Optional. The timestep by which the time navigator slider is moved for this scada panel. This overrules the timeNavigatorTimeStep that is configured
						for the scada display as a whole. This timestep is only used when showTimeNavigatorToolbar is configured for the scada display.
					</documentation>
				</annotation>
			</element>
			<element name="nodeId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Optional. Identifier that refers to a node in the topology configuration file. If specified, then the referenced topology node will be selected when this scadaPanel
						is selected in the user interface. When the topology node is selected, then that may cause other things to be selected as well, like e.g. the displayGroup in the
						TimeSeriesDisplay that corresponds to that node.
					</documentation>
				</annotation>
			</element>
			<element name="permission" type="string" minOccurs="0">
				<annotation>
					<documentation>Since 2014.01. Hides this panel when this permission is not available for the logged on user in the Permissions.xml in the SystemConfigFiles.</documentation>
				</annotation>
			</element>
			<element name="backgroundColor" type="fews:colorStringType" minOccurs="0">
				<annotation>
					<documentation>Since 2016.02 Configure the background color for the scada panel. If no color is configured, the background color configured in the scadaDisplay element will be
						used.
					</documentation>
				</annotation>
			</element>
			<choice minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>One or more items to define special behaviour and/or properties for components in this scada panel. Each item refers to an svg object that is defined in the given
						svg file. Each item also contains definitions of behaviour and/or properties for that object. This way it is possible to e.g. replace tags in the text of a text object with
						certain values from a certain time series, or to define what should happen when the user clicks on a certain component.
					</documentation>
				</annotation>
				<element name="textComponentBehaviourDefinition" type="fews:TextComponentBehaviourDefinitionComplexType">
					<annotation>
						<documentation>Definition of special behaviour and/or properties for a text component in this scada panel. This refers to an svg object of type "text" that is defined in the
							given svg file. This contains definitions of behaviour and/or properties for that svg object. An svg object of type "text" can be a "text", "tspan", "tref", "textPath" or
							"altGlyph" element.
						</documentation>
					</annotation>
				</element>
				<element name="shapeComponentBehaviourDefinition" type="fews:ShapeComponentBehaviourDefinitionComplexType">
					<annotation>
						<documentation>Definition of special behaviour and/or properties for a shape component in this scada panel. This refers to an svg object of type "shape" that is defined in the
							given svg file. This contains definitions of behaviour and/or properties for that svg object. An svg object of type "shape" can be a "path", "rect", "circle", "ellipse",
							"line", "polyline" or "polygon" element.
						</documentation>
					</annotation>
				</element>
				<element name="chartComponentBehaviourDefinition" type="fews:ChartComponentBehaviourDefinitionComplexType">
					<annotation>
						<documentation>Definition of timeseries chart to be included as embedded image in the SVG rendering. A chart can be insert using any rectangular SVG element that has width and
							height properties as a placeholder (using a rectangle is recommended>
						</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier of this scada panel.</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nameStringType">
			<annotation>
				<documentation>The name of this scada panel as it is displayed in the user interface. If not specified, then id is used as name.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="ComponentBehaviourDefinitionBaseComplexType">
		<annotation>
			<documentation>This complexType should be extended by all component behaviour definition complexTypes. This contains general options that are available for all types of components.
			</documentation>
		</annotation>
		<sequence>
			<element name="svgObjectId" type="fews:idStringType">
				<annotation>
					<documentation>The id of the object in the svg file for which this item defines special behaviour and/or properties.</documentation>
				</annotation>
			</element>
			<sequence minOccurs="0">
				<element name="leftSingleClickAction" type="fews:ScadaPanelActionComplexType" minOccurs="0">
					<annotation>
						<documentation>Action that is triggered when the user clicks once on this object with the left mouse button.</documentation>
					</annotation>
				</element>
				<element name="leftDoubleClickAction" type="fews:ScadaPanelActionComplexType" minOccurs="0">
					<annotation>
						<documentation>Action that is triggered when the user double clicks on this object with the left mouse button.</documentation>
					</annotation>
				</element>
				<element name="webOCDashboardAction" type="fews:WebOCDashboardActionComplexType" minOccurs="0">
					<annotation>
						<documentation>Action that is triggered when the user clicks in a WebOC dashboard.</documentation>
					</annotation>
				</element>
			</sequence>
		</sequence>
	</complexType>
	<complexType name="WebOCDashboardActionComplexType">
		<sequence>
			<element name="actionId" type="string"/>
			<sequence minOccurs="0">
				<element name="charts" type="fews:WebOCChartsActionComplexType" minOccurs="0"/>
				<element name="map" type="fews:WebOCMapActionComplexType" minOccurs="0"/>
			</sequence>
		</sequence>
	</complexType>
	<complexType name="WebOCChartsActionComplexType">
		<sequence>
			<element name="locationId" type="string" minOccurs="0"/>
			<element name="displayId" type="string" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="WebOCMapActionComplexType">
		<sequence>
			<element name="locationId" type="string" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="ScadaPanelActionComplexType">
		<choice>
			<element name="switchToScadaPanel" type="fews:SwitchToScadaPanelComplexType">
				<annotation>
					<documentation>Within this scada display the view will switch to the specified panel.</documentation>
				</annotation>
			</element>
			<element name="openDisplay" type="fews:OpenDisplayComplexType">
				<annotation>
					<documentation>Open another FEWS display.</documentation>
				</annotation>
			</element>
			<element name="runWorkflow" type="fews:RunWorkflowComplexType">
				<annotation>
					<documentation>Run a predefined workflow.</documentation>
				</annotation>
			</element>
			<element name="openPdfFile" type="fews:OpenPdfFileComplexType">
				<annotation>
					<documentation>Opens a PDF.</documentation>
				</annotation>
			</element>
			<element name="openURL" type="fews:OpenURLComplexType">
				<annotation>
					<documentation>Opens the specified URL.</documentation>
				</annotation>
			</element>
			<element name="enumerateValues" type="fews:EnumerateValuesComplexType">
				<annotation>
					<documentation>Changes a parameter value by stepping over the values in the specified enumerator.</documentation>
				</annotation>
			</element>
			<element name="enterValue" type="fews:EnterValueComplexType">
				<annotation>
					<documentation>Change the value of a parameter by allowing the user to enter a value in a pop-up textbox control.</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="OpenPdfFileComplexType">
		<sequence>
			<element name="filename" type="fews:fileStringType">
				<annotation>
					<documentation>The file name of the Pdf file to open. Absolute filename. May also contain supported tags such as %REGION_HOME%.</documentation>
				</annotation>
			</element>
			<element name="bookmark" type="string" minOccurs="0">
				<annotation>
					<documentation>The bookmark to jump to. The bookmark must be present in the Pdf file. Might not be supported by all pdf readers</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OpenURLComplexType">
		<sequence>
			<element name="url" type="fews:fileStringType">
				<annotation>
					<documentation>The url to open.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SwitchToScadaPanelComplexType">
		<sequence>
			<element name="scadaDisplayInstanceDescriptor" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Since 2015.02 The instance descriptor of the scada display to switch to. The scada display should be configured as an explorerTask in Explorer.xml with the
						displayInstanceDescriptor as argument, the displayInstanceDescriptor can be found in DisplayInstanceDescriptors.xml. When this element is not present the scada display
						configured in this config file will be used.
					</documentation>
				</annotation>
			</element>
			<element name="scadaPanelId" type="fews:idStringType">
				<annotation>
					<documentation>The id of the scadaPanel to switch to. If scadaDisplayInstanceDescriptor is not configured, the scadaPanel to switch to must be present in this config file.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OpenDisplayComplexType">
		<choice>
			<element name="spatialDisplay" type="fews:OpenSpatialDisplayComplexType">
				<annotation>
					<documentation>Since 2013.01. FEWS-8639. Open the spatial display (grid display) using the specified options. The period that is shown in the display is the smallest period that
						completely includes the relative view periods of all shown variables.
					</documentation>
				</annotation>
			</element>
			<element name="thresholdEventsDisplay" type="fews:OpenThresholdEventsDisplayComplexType">
				<annotation>
					<documentation>Open the threshold events table viewer. The system wide thresholds viewer is configured in Explorer.xml, ThresholdValueSets and TimeSeriesDisplayConfig and has no
						further configuration options.
					</documentation>
				</annotation>
			</element>
			<element name="timeSeriesDisplay" type="fews:OpenTimeSeriesDisplayComplexType">
				<annotation>
					<documentation>Open the timeSeriesDisplay using the specified options. The period that is shown in the display is the smallest period that completely includes the relative view
						periods of all shown variables.
					</documentation>
				</annotation>
			</element>
			<element name="timeSeriesEditor" type="fews:OpenTimeSeriesEditorComplexType">
				<annotation>
					<documentation>Open the timeSeriesEditor using the specified options. The data of the specified variables can be edited in the display. The period that is shown in the display is
						the smallest period that completely includes the relative view periods of all shown variables.
					</documentation>
				</annotation>
			</element>
			<element name="taskRunDialog" type="fews:OpenTaskRunDialogComplexType">
				<annotation>
					<documentation>Since 2014.01. Open the TaskRunDialog using the specified options.</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="OpenSpatialDisplayComplexType">
		<sequence>
			<element name="title" type="fews:nameStringType">
				<annotation>
					<documentation>Title of the display window.</documentation>
				</annotation>
			</element>
			<element name="gridPlot" type="fews:GridPlotReferenceComplexType">
				<annotation>
					<documentation>Reference to a pre-configured gridPlot in the specified gridDisplay configuration file.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="GridPlotReferenceComplexType">
		<sequence>
			<element name="gridDisplayFile" type="fews:fileStringType">
				<annotation>
					<documentation>Name of the gridDisplay configuration file that contains the gridPlot to select in the opened display. This name should not include the file extension. GridPlots are
						defined in a gridDisplay file in the DisplayConfigFiles directory.
					</documentation>
				</annotation>
			</element>
			<element name="gridPlotId" type="fews:idStringType">
				<annotation>
					<documentation>Id of a gridPlot in the specified gridDisplay configuration file that should be selected in the opened display.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OpenThresholdEventsDisplayComplexType">
		<sequence>
			<element name="title" type="fews:nameStringType" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation>Title of the display window.</documentation>
				</annotation>
			</element>
			<element name="iconFile" type="fews:fileStringType" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation>Icon to use for the display window.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OpenTimeSeriesDisplayComplexType">
		<sequence>
			<element name="title" type="fews:nameStringType">
				<annotation>
					<documentation>Title of the display window.
						Since 2017.02: %LOCATIONATTRIBUTE (ATTRIBUTE;PATTERN;VARIABLEID)% can be used if a variable with a configured location is set. VariableId can be empty if only one variable was
						configured.
						Since 2017.02: %PARAMETERNAME(VARIABLEID)% can be used if a variable was configured. Variable ID can be left out if only one variable was configured.
					</documentation>
				</annotation>
			</element>
			<choice>
				<element name="display" type="fews:DisplayPlotComplexType">
					<annotation>
						<documentation>Reference to a pre configured plot in the DisplayGroups configuration file.</documentation>
					</annotation>
				</element>
				<element name="variable" type="fews:ScadaVariableComplexType" maxOccurs="unbounded">
					<annotation>
						<documentation>One or more variables to define the data that is shown in this display.</documentation>
					</annotation>
				</element>
			</choice>
			<element name="showGraph" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>Optional. If true then a graph is shown in the opened display. If false, then the graph is not shown. Default is true.</documentation>
				</annotation>
			</element>
			<element name="showTable" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Optional. If true then a table is shown in the opened display. If false, then the table is not shown. Default is false.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OpenTimeSeriesEditorComplexType">
		<sequence>
			<element name="title" type="fews:nameStringType">
				<annotation>
					<documentation>Title of the display window.</documentation>
				</annotation>
			</element>
			<choice>
				<element name="display" type="fews:DisplayPlotComplexType">
					<annotation>
						<documentation>Reference to a pre configured plot in the DisplayGroups configuration file.</documentation>
					</annotation>
				</element>
				<element name="variable" type="fews:ScadaVariableComplexType" maxOccurs="unbounded">
					<annotation>
						<documentation>One or more variables to define the data that is shown in this display.</documentation>
					</annotation>
				</element>
			</choice>
			<element name="showGraph" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>Optional. If true then a graph is shown in the opened display. If false, then the graph is not shown. Default is true.</documentation>
				</annotation>
			</element>
			<element name="showTable" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>Optional. If true then a table is shown in the opened display. If false, then the table is not shown. Default is true.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="OpenTaskRunDialogComplexType">
		<sequence>
			<element name="title" type="fews:nameStringType">
				<annotation>
					<documentation>Title of the display window.</documentation>
				</annotation>
			</element>
			<element name="taskRunDialogFile" type="fews:fileStringType">
				<annotation>
					<documentation>Display config file specifying the TaskRunDIalog.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="RunWorkflowComplexType">
		<sequence>
			<element name="workflowId" type="fews:idStringType">
				<annotation>
					<documentation>The workflow descriptor id of the workflow to run. This id should refer to a workflow that is defined in the WorkflowDescriptors configuration file. The current
						system time is used as the time zero (T0) for the workflow run.
					</documentation>
				</annotation>
			</element>
			<element name="localRun" type="boolean" minOccurs="0" default="false">
				<annotation>
					<documentation>
						Available since 2022.01. if set to true, the workflow will be run locally instead on the server. The result of the local run will only be saved on the server if
						autoSaveToServerAfterLocalRun is set to true.
					</documentation>
				</annotation>
			</element>
			<element name="autoSaveToServerAfterLocalRun" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>
						Available since 2022.01. It can only be set to true if localRun is also true. If autoSaveToServerAfterLocalRun is configured as true, the locally un workflow will be saved on
						the server.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="EnumerateValuesComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType">
				<annotation>
					<documentation>The variable for which the values are to be enumerated as the user clicks on the SVG element. The variable needs to be defined as enumerator using a parameter group
						in region configuration parameters.xml.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="EnterValueComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType">
				<annotation>
					<documentation>The variable for which the user can enter a value using a pop-up textbox control.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="min" type="float"/>
		<attribute name="max" type="float"/>
	</complexType>
	<complexType name="LinkPropertiesToDataComplexType">
		<sequence>
			<element name="height" type="fews:LinkHeightToDataComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional. If specified, then for this component the height attribute is linked to the data values for the specified variable. This option can only be used for svg
						objects of type "rect". If the data value is less than dataLowerLimit, then the height is set to heightLowerLimit. If the data value is greater than dataUpperLimit, then the
						height is set to heightUpperLimit. If the data value is between dataLowerLimit and dataUpperLimit, then the height will be linearly interpolated between heightLowerLimit and
						heightUpperLimit. If no data is available, then this component is made invisible. Note: it is required that dataUpperLimit is greater than dataLowerLimit. However it is
						possible to define heightUpperLimit less than heightLowerLimit to control the direction of the change of the height.
					</documentation>
				</annotation>
			</element>
			<element name="width" type="fews:LinkWidthToDataComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2016.01. FEWS-13978. Optional. If specified, then for this component the width attribute is linked to the data values for the specified variable. This option
						can only be used for svg
						objects of type "rect". If the data value is less than dataLowerLimit, then the width is set to widthLowerLimit. If the data value is greater than dataUpperLimit, then the
						width is set to widthUpperLimit. If the data value is between dataLowerLimit and dataUpperLimit, then the width will be linearly interpolated between widthLowerLimit and
						widthUpperLimit. If no data is available, then this component is made invisible. Note: it is required that dataUpperLimit is greater than dataLowerLimit. However it is
						possible to define widthUpperLimit less than widthLowerLimit to control the direction of the change of the width.
					</documentation>
				</annotation>
			</element>
			<element name="rotation" type="fews:LinkRotationToDataComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional. If specified, then for this component the rotation is linked to the data values for the specified variable. The rotation that is derived from the data
						values is always relative to the rotation angle that is specified for this component in the svg file. This option can only be used for svg objects of type "path", "rect",
						"circle", "ellipse", "line", "polyline", "polygon" or "text". If the data value is less than dataLowerLimit, then the rotation is set to rotationLowerLimit. If the data value
						is greater than dataUpperLimit, then the rotation is set to rotationUpperLimit. If the data value is between dataLowerLimit and dataUpperLimit, then the rotation will be
						linearly interpolated between rotationLowerLimit and rotationUpperLimit. If no data is available, then this component is made invisible. If the data value is flagged as
						"varying direction" (e.g. varying wind direction), then the rotation will increase linearly in time (animation). In this case the rotation will increase from rotationLowerLimit
						to rotationUpperLimit and then start from rotationLowerLimit again. Note: it is required that dataUpperLimit is greater than dataLowerLimit. However it is possible to define
						rotationUpperLimit less than rotationLowerLimit to control the direction of the rotation. If rotationUpperLimit is greater than rotationLowerLimit, then increasing data values
						result in clockwise rotation.
					</documentation>
				</annotation>
			</element>
			<element name="radius" type="fews:LinkRadiusToDataComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional. If specified, then for this component the radius of a circle is linked to the data values for the specified variable.</documentation>
				</annotation>
			</element>
			<element name="x" type="fews:LinkXToDataComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional. If specified, then for this component the X coordinate is linked to the data values for the specified variable.</documentation>
				</annotation>
			</element>
			<element name="y" type="fews:LinkYToDataComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional. If specified, then for this component the Y coordinated is linked to the data values for the specified variable.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="LinkHeightToDataComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType">
				<annotation>
					<documentation>The data for this variable is used to determine the height for this component.</documentation>
				</annotation>
			</element>
			<element name="dataLowerLimit" type="float">
				<annotation>
					<documentation>If the data value is less than or equal to dataLowerLimit, then the height will be equal to heightLowerLimit.</documentation>
				</annotation>
			</element>
			<element name="dataUpperLimit" type="float">
				<annotation>
					<documentation>If the data value is greater than or equal to dataUpperLimit, then the height will be equal to heightUpperLimit.</documentation>
				</annotation>
			</element>
			<element name="heightLowerLimit" type="fews:nonNegativeDouble">
				<annotation>
					<documentation>The height that corresponds to the dataLowerLimit value.</documentation>
				</annotation>
			</element>
			<element name="heightUpperLimit" type="fews:nonNegativeDouble">
				<annotation>
					<documentation>The height that corresponds to the dataUpperLimit value.</documentation>
				</annotation>
			</element>
			<element name="anchorPoint" type="fews:linkHeightToDataAnchorPointEnumStringType">
				<annotation>
					<documentation>The anchor point describes which part of the component should remain at the same position when the height is changed.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="LinkWidthToDataComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType">
				<annotation>
					<documentation>Since 2016.01. FEWS-13978. The data for this variable is used to determine the width for this component.</documentation>
				</annotation>
			</element>
			<element name="dataLowerLimit" type="float">
				<annotation>
					<documentation>If the data value is less than or equal to dataLowerLimit, then the width will be equal to widthLowerLimit.</documentation>
				</annotation>
			</element>
			<element name="dataUpperLimit" type="float">
				<annotation>
					<documentation>If the data value is greater than or equal to dataUpperLimit, then the width will be equal to widthUpperLimit.</documentation>
				</annotation>
			</element>
			<element name="widthLowerLimit" type="fews:nonNegativeDouble">
				<annotation>
					<documentation>The width that corresponds to the dataLowerLimit value.</documentation>
				</annotation>
			</element>
			<element name="widthUpperLimit" type="fews:nonNegativeDouble">
				<annotation>
					<documentation>The width that corresponds to the dataUpperLimit value.</documentation>
				</annotation>
			</element>
			<element name="anchorPoint" type="fews:linkWidthToDataAnchorPointEnumStringType">
				<annotation>
					<documentation>The anchor point describes which part of the component should remain at the same position when the width is changed.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="linkHeightToDataAnchorPointEnumStringType">
		<annotation>
			<documentation>Indicates which part of the component should remain at the same position when the height is changed.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="bottom"/>
			<enumeration value="top"/>
			<enumeration value="center"/>
		</restriction>
	</simpleType>
	<simpleType name="linkWidthToDataAnchorPointEnumStringType">
		<annotation>
			<documentation>Since 2016.01. FEWS-13978. Indicates which part of the component should remain at the same position when the width is changed.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="left"/>
			<enumeration value="right"/>
			<enumeration value="center"/>
		</restriction>
	</simpleType>
	<complexType name="LinkRotationToDataComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType">
				<annotation>
					<documentation>The data for this variable is used to determine the rotation for this component.</documentation>
				</annotation>
			</element>
			<element name="dataLowerLimit" type="float">
				<annotation>
					<documentation>If the data value is less than or equal to dataLowerLimit, then the rotation will be equal to rotationLowerLimit.</documentation>
				</annotation>
			</element>
			<element name="dataUpperLimit" type="float">
				<annotation>
					<documentation>If the data value is greater than or equal to dataUpperLimit, then the rotation will be equal to rotationUpperLimit.</documentation>
				</annotation>
			</element>
			<element name="rotationLowerLimit" type="float">
				<annotation>
					<documentation>The rotation (in degrees) that corresponds to the dataLowerLimit value. This rotation is always relative to the rotation angle that is specified for this component
						in the svg file.
					</documentation>
				</annotation>
			</element>
			<element name="rotationUpperLimit" type="float">
				<annotation>
					<documentation>The rotation (in degrees) that corresponds to the dataUpperLimit value. This rotation is always relative to the rotation angle that is specified for this component
						in the svg file.
					</documentation>
				</annotation>
			</element>
			<element name="anchorPointX" type="float">
				<annotation>
					<documentation>The x coordinate of the anchor point. The rotation will be around the anchor point. This x coordinate has to be specified in the user space coordinate system of the
						svg object for this component in the svg file. The user space coordinate system is determined by all transforms that are specified in the parent svg objects of the svg object
						for this component. All transforms that are specified in the svg object itself are not part of the user space coordinate system and thus should be taken into account in the
						coordinates that are specified here. E.g. to rotate a "rect" svg object with attributes width="200" height="200" x="500" y="300" transform="translate(50 0)" around its center,
						use anchorPoint coordinates (x, y) = (650, 400).
					</documentation>
				</annotation>
			</element>
			<element name="anchorPointY" type="float">
				<annotation>
					<documentation>The y coordinate of the anchor point. The rotation will be around the anchor point. This y coordinate has to be specified in the user space coordinate system of the
						svg object for this component in the svg file. The user space coordinate system is determined by all transforms that are specified in the parent svg objects of the svg object
						for this component. All transforms that are specified in the svg object itself are not part of the user space coordinate system and thus should be taken into account in the
						coordinates that are specified here. E.g. to rotate a "rect" svg object with attributes width="200" height="200" x="500" y="300" transform="translate(50 0)" around its center,
						use anchorPoint coordinates (x, y) = (650, 400).
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="LinkRadiusToDataComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType">
				<annotation>
					<documentation>The data for this variable is used to determine the radius for this component.</documentation>
				</annotation>
			</element>
			<element name="dataLowerLimit" type="float" minOccurs="0">
				<annotation>
					<documentation>Optional, If the data value is less than or equal to dataLowerLimit, then the radius will be equal to radiusLowerLimit.</documentation>
				</annotation>
			</element>
			<element name="dataUpperLimit" type="float" minOccurs="0">
				<annotation>
					<documentation>Optional, If the data value is greater than or equal to dataUpperLimit, then the radius will be equal to radiusUpperLimit.</documentation>
				</annotation>
			</element>
			<element name="radiusLowerLimit" type="float">
				<annotation>
					<documentation>The radius (in SVG units) that corresponds to the dataLowerLimit value. If no dataLowerLimit is given, the specified variable is used directly, limited to this minimum.</documentation>
				</annotation>
			</element>
			<element name="radiusUpperLimit" type="float">
				<annotation>
					<documentation>The radius (in SVG units) that corresponds to the dataUpperLimit value. If no dataUpperLimit is given, the specified variable is used directly, limited to this maximum.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="LinkXToDataComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType">
				<annotation>
					<documentation>The data for this variable is used to determine the X coordinate for this component. The coordinates must be defined using the coordinate units and origin of the SVG file.</documentation>
				</annotation>
			</element>
			<element name="xLowerLimit" type="float">
				<annotation>
					<documentation>If the data value is less than or equal to xLowerLimit, then the X coordinate will be set to xLowerLimit.</documentation>
				</annotation>
			</element>
			<element name="xUpperLimit" type="float">
				<annotation>
					<documentation>If the data value is less than or equal to xUpperLimit, then the X coordinate will be set to xUpperLimit.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="LinkYToDataComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType">
				<annotation>
					<documentation>The data for this variable is used to determine the Y coordinate for this component. The coordinates must be defined using the coordinate units and origin of the SVG file.</documentation>
				</annotation>
			</element>
			<element name="yLowerLimit" type="float">
				<annotation>
					<documentation>If the data value is less than or equal to yLowerLimit, then the Y coordinate will be set to yLowerLimit.</documentation>
				</annotation>
			</element>
			<element name="yUpperLimit" type="float">
				<annotation>
					<documentation>If the data value is less than or equal to yUpperLimit, then the Y coordinate will be set to yUpperLimit.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="UseThresholdWarningLevelColorsComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>The data for this variable is used to determine threshold crossings. For crossed thresholds, warningLevels are activated. The color of the most severe activated
						warningLevel is used as the fill and/or stroke color for the component, as specified below.
					</documentation>
				</annotation>
			</element>
			<element name="thresholdGroupId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Optional. If specified, then only thresholds in the specified thresholdGroup are used in the determination of threshold crossings and warningLevels for the specified
						variable. If not specified, then thresholds in all thresholdGroups are used.
					</documentation>
				</annotation>
			</element>
			<element name="thresholdReference" type="fews:thresholdReferenceEnumStringType">
				<annotation>
					<documentation>Specify which data is used for determining threshold crossings. Either choose the first or last reliable or doubtful value within the relative view period, or choose
						all reliable or doubtful values within the relative view period.
					</documentation>
				</annotation>
			</element>
			<element name="colorType" type="fews:svgObjectColorTypeEnumStringType">
				<annotation>
					<documentation>Specify which color type (fill and/or stroke) should be changed to use warningLevel colors. Color types that are not specified here are not changed.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="UseThresholdWarningLevelSymbolsComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>The data for this variable is used to determine threshold crossings. For crossed thresholds, warningLevels are activated. The color of the most severe activated
						warningLevel is used as the fill and/or stroke color for the component, as specified below.
					</documentation>
				</annotation>
			</element>
			<element name="thresholdGroupId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Optional. If specified, then only thresholds in the specified thresholdGroup are used in the determination of threshold crossings and warningLevels for the specified
						variable. If not specified, then thresholds in all thresholdGroups are used.
					</documentation>
				</annotation>
			</element>
			<element name="thresholdReference" type="fews:thresholdReferenceEnumStringType">
				<annotation>
					<documentation>Specify which data is used for determining threshold crossings. Either choose the first or last reliable or doubtful value within the relative view period, or choose
						all reliable or doubtful values within the relative view period.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="thresholdReferenceEnumStringType">
		<annotation>
			<documentation>Indicates which of the data values within the relative view period of the variable are used for determining thresholds crossings.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="first_value"/>
			<enumeration value="last_value"/>
			<enumeration value="relative_view_period"/>
		</restriction>
	</simpleType>
	<simpleType name="svgObjectColorTypeEnumStringType">
		<annotation>
			<documentation>Indicates a color type (e.g. fill color or stroke color) of an svg object.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="fill"/>
			<enumeration value="stroke"/>
			<enumeration value="fill_and_stroke"/>
		</restriction>
	</simpleType>
	<complexType name="ScadaToolTipComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType" minOccurs="0">
				<annotation>
					<documentation>The data from this variable is used to replace the tags in the specified toolTip text. If for a given tag the required data is not available, then that tag is
						replaced by a dash symbol "-". This variable is only required if the specified toolTip text contains tags.
					</documentation>
				</annotation>
			</element>
			<element name="toolTipText" type="fews:nonEmptyStringType">
				<annotation>
					<documentation>Text that is displayed in the toolTip for this component. This text can contain tags. The tags are replaced using data from the specified variable. Tags should be
						separated by "%" signs. Text can be e.g. "Last value = %LASTVALUE(numberFormatId)%", which would be replaced by e.g. "Last value = 10.0". The following tags can be used in the
						text (numberFormatId/dateFormatId should be replaced by the id of a numberFormat/dateFormat that is defined at the start of this configuration file). %MAXVALUE(numberFormatId)%
						is replaced by the maximum reliable or doubtful value in the time series. %MINVALUE(numberFormatId)% is replaced by the minimum reliable or doubtful value in the time series.
						%LASTVALUE(numberFormatId)% is replaced by the most recent reliable or doubtful value in the time series. %LASTVALUETIME(dateFormatId)% is replaced by the date and time of the
						most recent reliable or doubtful value in the time series. %STARTTIME(dateFormatId)% is replaced by the start date and time of the relative view period of the time series.
						%ENDTIME(dateFormatId)% is replaced by the end date and time of the relative view period of the time series. %CURRENTTIME(dateFormatId)% is replaced by the Delft FEWS time.
						%EXTERNALFORECASTINGSTARTTIME(dateFormatId)% is replaced by the start of the external forecast. %MAXTIME(dateFormatId)% is replaced by the date/time of maximum value found in
						the time series. %MINTIME(dateFormatId)% is replaced by the date/time of minimum value found in the time series. %TIMEZERO(dateFormatId)% is replaced by in case of forecast
						data the forecast time, otherwise timezero. %MAXWARNINGLEVEL(thresholdId)% is replaced by name of the highest warning level threshold that has been crossed (requires an
						available thresholdValueSet). %PARAMETERNAME() is replaced by the parameter name of the configured variable.%.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TextComponentBehaviourDefinitionComplexType">
		<complexContent>
			<extension base="fews:ComponentBehaviourDefinitionBaseComplexType">
				<sequence>
					<element name="linkPropertiesToData" type="fews:LinkPropertiesToDataComplexType" minOccurs="0">
						<annotation>
							<documentation>Optional. Contains options to link properties of this component to actual data values. For example the height of the component can be changed depending on
								the data values of a specified variable.
							</documentation>
						</annotation>
					</element>
					<element name="useThresholdWarningLevelColors" type="fews:UseThresholdWarningLevelColorsComplexType" minOccurs="0">
						<annotation>
							<documentation>Optional. If specified, then the data for the specified variable within the specified relative view period is used to determine threshold crossings. For
								crossed thresholds, warningLevels are activated. The color of the most severe activated warningLevel is used as the fill and/or stroke color for the component, as
								specified.
							</documentation>
						</annotation>
					</element>
					<element name="useThresholdWarningLevelSymbols" type="fews:UseThresholdWarningLevelSymbolsComplexType" minOccurs="0">
						<annotation>
							<documentation>Optional. If specified, then the data for the specified variable within the specified relative view period is used to determine threshold crossings. For
								crossed thresholds, warningLevels are activated. The symbolId of the most severe activated warningLevel is used to reference a graphic symbol for the component, as
								specified in the defs section of a SVG file.
							</documentation>
						</annotation>
					</element>
					<element name="toolTip" type="fews:ScadaToolTipComplexType" minOccurs="0">
						<annotation>
							<documentation>Optional. If specified, then a toolTip with the specified text is displayed for this component.</documentation>
						</annotation>
					</element>
					<element name="replaceTags" type="fews:ReplaceTagsComplexType" minOccurs="0">
						<annotation>
							<documentation>If specified, then the tags in the text of this component are replaced using data from the specified variable. Tags should be separated by "%" signs. Text
								can be e.g. "Last value = %LASTVALUE(numberFormatId)%", which would be replaced by e.g. "Last value = 10.0". The following tags can be used in the text
								(numberFormatId/dateFormatId should be replaced by the id of a numberFormat/dateFormat that is defined at the start of this configuration file).
								%MAXVALUE(numberFormatId)% is replaced by the maximum reliable or doubtful value in the time series. %MINVALUE(numberFormatId)% is replaced by the minimum reliable or
								doubtful value in the time series. %LASTVALUE(numberFormatId)% is replaced by the most recent reliable or doubtful value in the time series.
								%LASTVALUETIME(dateFormatId)% is replaced by the date and time of the most recent reliable or doubtful value in the time series. %STARTTIME(dateFormatId)% is replaced
								by the start date and time of the relative view period of the time series. %ENDTIME(dateFormatId)% is replaced by the end date and time of the relative view period of
								the time series. %CURRENTTIME(dateFormatId)% is replaced by the Delft FEWS time. %EXTERNALFORECASTINGSTARTTIME(dateFormatId)% is replaced by the start of the external
								forecast. %MAXTIME(dateFormatId)% is replaced by the date/time of maximum value found in the time series. %MINTIME(dateFormatId)% is replaced by the date/time of
								minimum value found in the time series. %TIMEZERO(dateFormatId)% is replaced by in case of forecast data the forecast time, otherwise timezero.
								%MAXWARNINGLEVEL(thresholdId)% is replaced by name of the highest warning level threshold that has been crossed (requires an available thresholdValueSet).
							</documentation>
						</annotation>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="ReplaceTagsComplexType">
		<sequence>
			<element name="variable" type="fews:ScadaVariableComplexType">
				<annotation>
					<documentation>The data from this variable is used to replace the tags in the text in the svg object that this component refers to. If for a given tag the required data is not
						available, then that tag is replaced by a dash symbol "-".
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ShapeComponentBehaviourDefinitionComplexType">
		<complexContent>
			<extension base="fews:ComponentBehaviourDefinitionBaseComplexType">
				<sequence>
					<element name="linkPropertiesToData" type="fews:LinkPropertiesToDataComplexType" minOccurs="0">
						<annotation>
							<documentation>Optional. Contains options to link properties of this component to actual data values. For example the height of the component can be changed depending on
								the data values of a specified variable.
							</documentation>
						</annotation>
					</element>
					<element name="useThresholdWarningLevelColors" type="fews:UseThresholdWarningLevelColorsComplexType" minOccurs="0">
						<annotation>
							<documentation>Optional. If specified, then the data for the specified variable within the specified relative view period is used to determine threshold crossings. For
								crossed thresholds, warningLevels are activated. The color of the most severe activated warningLevel is used as the fill and/or stroke color for the component, as
								specified.
							</documentation>
						</annotation>
					</element>
					<element name="useThresholdWarningLevelSymbols" type="fews:UseThresholdWarningLevelSymbolsComplexType" minOccurs="0">
						<annotation>
							<documentation>Optional. If specified, then the data for the specified variable within the specified relative view period is used to determine threshold crossings. For
								crossed thresholds, warningLevels are activated. The symbolId of the most severe activated warningLevel is used to reference a graphic symbol for the component, as
								specified in the defs section of a SVG file.
							</documentation>
						</annotation>
					</element>
					<element name="toolTip" type="fews:ScadaToolTipComplexType" minOccurs="0">
						<annotation>
							<documentation>Optional. If specified, then a toolTip with the specified text is displayed for this component.</documentation>
						</annotation>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="ChartComponentBehaviourDefinitionComplexType">
		<annotation>
			<documentation>Insert a timeseries chart based on DisplayGroups configuration using a displayId, Since 2021.02</documentation>
		</annotation>
		<complexContent>
			<extension base="fews:ComponentBehaviourDefinitionBaseComplexType">
				<sequence>
					<element name="title" type="fews:nameStringType" minOccurs="0"/>
					<element name="display" type="fews:DisplayPlotComplexType"/>
					<element name="axisLabels" type="boolean" minOccurs="0"/>
					<element name="axisTitle" type="boolean" minOccurs="0"/>
					<element name="imageScaleFactor" type="float" minOccurs="0">
						<annotation>
							<documentation>Optionally scale the image, making the resulting image more suitable to be displayed at smaller size than the TSD it was configured for. Recommended value is
								1.5 - 2.0
							</documentation>
						</annotation>
					</element>
					<element name="toolTip" type="fews:ScadaToolTipComplexType" minOccurs="0">
						<annotation>
							<documentation>Optional. If specified, then a toolTip with the specified text is displayed for this component.</documentation>
						</annotation>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="TimeNavigatorRelativePeriodVariablesType">
		<sequence>
			<element name="variableId" type="fews:idStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>Since 2015.01. FEWS-12965</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ScadaTimeNavigatorToolbarSettingsComplexType">
		<sequence>
			<choice>
				<element name="timeNavigatorRelativePeriod" type="fews:RelativePeriodComplexType">
					<annotation>
						<documentation>Since 2015.01. FEWS-12965. This is the period of the time navigator toolbar (slider) in this scada display. The time navigator toolbar can be used to select the
							display time for this scada display. It is only possible to select a display time that is contained within this period and is a valid time according to the cardinal time
							step (which is configured in the explorer.xml config file). This period is always relative to the current system time. If the current system time changes, then the display
							time is reset to the current system time. The start and end of the period are both included.
						</documentation>
					</annotation>
				</element>
				<element name="timeNavigatorRelativePeriodVariables" type="fews:TimeNavigatorRelativePeriodVariablesType">
					<annotation>
						<documentation>Since 2015.01: Specify a list of variables that will be used to determine the relative view period from their timeSeriesSets.
						</documentation>
					</annotation>
				</element>
			</choice>
			<element name="timeNavigatorTimeStep" type="fews:TimeStepComplexType" minOccurs="0">
				<annotation>
					<documentation>The timestep by which the time navigator slider is moved, by default the cardinal timestep which is configured in the explorer.xml configuration file. This optional
						element can be used to use a different timestep for the time navigator than the cardinal timestep.
					</documentation>
				</annotation>
			</element>
			<element name="movieFrameDurationMillis" type="fews:positiveInteger" default="200" minOccurs="0">
				<annotation>
					<documentation>The duration of a frame when the time navigator is animating. This is the number of milliseconds a frame/time step is visible before the next time step becomes
						visible. If not specified, then 200 milliseconds is used by default. When the CPU is too slow to display the specified frame rate, a frame will be displayed longer than
						specified.
					</documentation>
				</annotation>
			</element>
			<element name="openAtFirstTimeStep" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Since 2015.01 When true, time slider will be set at first time step when opening Scada Display</documentation>
				</annotation>
			</element>
			<element name="activate" type="boolean" default="true" minOccurs="0">
				<annotation>
					<documentation>Since 2016.02 When false, the time slider will be grayed out and won't be functional</documentation>
				</annotation>
			</element>
			<element name="showTimeNavigatorActivationToggle" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Since 2016.02 When true, a toggle will be displayed on the timeNavigator toolbar that allows activating or deactivating the timeNavigatorToolbar</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
