<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Chris Mare (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2004 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--Top-level element Declaration -->
	<element name="statisticsSets" type="fews:StatisticsSetsComplexType"/>
	<!--Definition of StatisticsSetsComplexType-->
	<complexType name="StatisticsSetsComplexType">
		<sequence>
			<element name="statisticsSet" type="fews:StatisticsSetComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!--Definition of StatisticsSetComplexType-->
	<complexType name="StatisticsSetComplexType">
		<sequence>
			<element name="inputVariable" type="fews:VariableComplexType"/>
			<element name="statisticalFunctions" type="fews:StatisticalFunctionsComplexType"/>
			<element name="outputVariable" type="fews:VariableComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!--Definition of StatisticalFunctionsComplexType-->
	<complexType name="StatisticalFunctionsComplexType">
		<sequence>
			<element name="standard" type="fews:StandardStatisticsComplexType" minOccurs="0"/>
			<element name="higherMoment" type="fews:NoAttributesOrDataComplexType" minOccurs="0"/>
			<element name="movingAverage" type="fews:MovingAverageComplexType" minOccurs="0"/>
		</sequence>
	</complexType>
	<!--Definition of StandardStatisticsComplexType-->
	<complexType name="StandardStatisticsComplexType">
		<attribute name="upperPercentage" type="int" use="optional"/>
		<attribute name="lowerPercentage" type="int" use="optional"/>
	</complexType>
	<!--Definition of NothingFurtherComplexType-->
	<complexType name="NoAttributesOrDataComplexType"/>
	<!--Definition of MovingAverageComplexType-->
	<complexType name="MovingAverageComplexType">
		<attribute name="numberSamples" type="int" use="required"/>
	</complexType>
</schema>
