<?xml version="1.0" encoding="UTF-8"?>
<!--DEPRECATED NO LONGER USED SINCE 2017.02-->
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- Synchronisation profiles -->
	<element name="profiles" type="fews:ObsoleteSynchProfilesComplexType"/>
	<!-- SynchProfilesComplexType -->
	<complexType name="ObsoleteSynchProfilesComplexType">
		<sequence>
			<element name="defaultProfileId" type="fews:idStringType">
				<annotation>
					<documentation>Id of the default synchronisation profile.</documentation>
				</annotation>
			</element>
			<element name="profile" type="fews:ObsoleteSynchProfileComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Synchronisation profile uniquely identified by its id.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- SynchProfileComplexType -->
	<complexType name="ObsoleteSynchProfileComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description of the profile.</documentation>
				</annotation>
			</element>
			<element name="autoconnect" type="boolean" default="true">
				<annotation>
					<documentation>Optional flag indicating if a client should automatically log in on startup.</documentation>
				</annotation>
			</element>
			<element name="customizable" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Boolean flag indicating if the profile can be customized by the user.</documentation>
				</annotation>
			</element>
			<element name="maxSynchPeriod" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Maximal period of time for which synchronisation will take place.</documentation>
				</annotation>
			</element>
			<element name="activities" type="fews:ObsoleteSynchActivitiesComplexType" minOccurs="0">
				<annotation>
					<documentation>List of synchronisation activities.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
	</complexType>
	<!-- SynchActivitiesComplexType -->
	<complexType name="ObsoleteSynchActivitiesComplexType">
		<sequence>
			<element name="activity" type="fews:ObsoleteSynchActivityComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Configuration for one particular synchronisation activity.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- SynchActivityComplexType -->
	<complexType name="ObsoleteSynchActivityComplexType">
		<sequence>
			<element name="channelId" type="string">
				<annotation>
					<documentation>Id of the channel used in this activity. The channel it self must be configured in a separate file.</documentation>
				</annotation>
			</element>
			<element name="schedule" type="fews:ObsoleteScheduleTypeComplexType">
				<annotation>
					<documentation>Scheduling information for this channel.</documentation>
				</annotation>
			</element>
			<element name="timeOut" type="nonNegativeInteger">
				<annotation>
					<documentation>Timeout in milliseconds for the synchronisation process. Not used so far as synch API also provides a configurable timeout.</documentation>
				</annotation>
			</element>
			<element name="optional" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Optional boolean flag to indicate if the activity is to be used in the profile. Per default the activity won't be used. This setting may be overwritten by the profile selection dialog.</documentation>
				</annotation>
			</element>
			<element name="ignoreMaxSynchPeriod" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Boolean flag indicating if maxSynchPeriod will be ignored for this specific activity. This concerns both the maxSynchPeriod for the profile and - if present - the activity.</documentation>
				</annotation>
			</element>
			<element name="overrulingMaxSynchPeriod" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Overrules the maxSynchPeriod of the profile this activity belongs to.</documentation>
				</annotation>
			</element>
			<element name="modifiers" type="fews:ObsoleteModifiersComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional modifiers for synchronisation.</documentation>
				</annotation>
			</element>
			<element name="triggers" type="fews:ObsoleteTriggersComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional triggers of other synchronisation activity.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
	</complexType>
	<!-- ModifiersComplexType -->
	<complexType name="ObsoleteModifiersComplexType">
		<sequence>
			<element name="incoming" type="fews:ObsoleteModifierListComplexType" minOccurs="0">
				<annotation>
					<documentation>Modifiers for incoming synchronisation.</documentation>
				</annotation>
			</element>
			<element name="outgoing" type="fews:ObsoleteModifierListComplexType" minOccurs="0">
				<annotation>
					<documentation>Modifiers for outgoing synchronisation.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- ModifierListComplexType -->
	<complexType name="ObsoleteModifierListComplexType">
		<sequence>
			<element name="modifier" type="fews:ObsoleteModifierComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>A specific modifier that applies to exactly one database table.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- ModifierComplexType -->
	<complexType name="ObsoleteModifierComplexType">
		<sequence>
			<element name="tableId" type="fews:idStringType">
				<annotation>
					<documentation>Id of the table that the modifier is referring to. The Id must be available in the channel.</documentation>
				</annotation>
			</element>
			<choice>
				<element name="synchLevel" type="fews:SynchLevelSimpleType" maxOccurs="unbounded">
					<annotation>
						<documentation>Filter for table time series: 0 (default), 1 (import (data), 2 (flood maps), 3 (HyradK), 4 (astronomical data), 5 (processed external data) and 9 (not to be synchronised).</documentation>
					</annotation>
				</element>
				<element name="logType" type="fews:LogTypeSimpleType" maxOccurs="unbounded">
					<annotation>
						<documentation>Filter for table LogEntries: 0 (MC logs), 1 (system logs) or 2 (debug logs)</documentation>
					</annotation>
				</element>
				<element name="onlyActive" type="boolean">
					<annotation>
						<documentation>Option to only up- or download the active configuration files. If not present all configuration will be up-/ downloaded.</documentation>
					</annotation>
				</element>
			</choice>
				<element name="downloadDataOnDemand" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Option to indicate that the synchronisation should initially download only the metadata of a time series. The actual data (blobs) is downloaded on demand by the user</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- SynchLevelSimpleType -->
	<simpleType name="SynchLevelSimpleType">
		<restriction base="nonNegativeInteger"/>
	</simpleType>
	<!-- LogTypeSimpleType -->
	<simpleType name="LogTypeSimpleType">
		<restriction base="nonNegativeInteger">
			<enumeration value="0"/>
			<enumeration value="1"/>
			<enumeration value="2"/>
			<enumeration value="3"/>
			<enumeration value="4"/>
			<enumeration value="5"/>
            <enumeration value="6"/>
            <enumeration value="7"/>
            <enumeration value="8"/>
            <enumeration value="9"/>
		</restriction>
	</simpleType>
	<!-- TriggersComplexType -->
	<complexType name="ObsoleteTriggersComplexType">
		<sequence>
			<element name="trigger" type="fews:ObsoleteTriggerComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>A trigger for one specific synchronisation activity.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- TriggerComplexType -->
	<complexType name="ObsoleteTriggerComplexType">
		<sequence>
			<element name="activityId" type="string">
				<annotation>
					<documentation>Id of the synch activity to be triggered as it occurs in this configuration file.</documentation>
				</annotation>
			</element>
			<element name="onlyForCurrentForecasts" type="boolean">
				<annotation>
					<documentation>Boolean flag indicating if the triggered synch activity is only performed for the current forecasts.</documentation>
				</annotation>
			</element>
			<element name="useLastSynchTime" type="boolean">
				<annotation>
					<documentation>Boolean flag indicating if the triggered activity should use the time of last synchronisation as additional filter.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- ScheduleTypeComplexType -->
	<complexType name="ObsoleteScheduleTypeComplexType">
		<choice>
			<element name="single" type="fews:ObsoleteSingleSynchActivityComplexType">
				<annotation>
					<documentation>A synchronisation activity that is executed just once and is triggered by a user interaction.</documentation>
				</annotation>
			</element>
			<element name="continuous" type="fews:ObsoleteContinuousSynchActivityComplexType">
				<annotation>
					<documentation>A synchronisation activity that will continuously executed with the given period. No user interaction required.</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<!-- SingleSynchActivityComplexType-->
	<complexType name="ObsoleteSingleSynchActivityComplexType">
		<sequence>
			<element name="priority" type="fews:SynchPrioritySimpleType" default="normal" minOccurs="0">
				<annotation>
					<documentation>Optional priority for a single synchronisation activity. Default is normal.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- ContinuousSynchActivityComplexType -->
	<complexType name="ObsoleteContinuousSynchActivityComplexType">
		<sequence>
			<element name="period" type="fews:TimeSpanComplexType"/>
			<element name="priority" type="fews:SynchPrioritySimpleType" default="normal" minOccurs="0">
				<annotation>
					<documentation>Optional priority for the continuous synchronisation activity. Default is normal.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- SynchPrioritySimpleType -->
	<simpleType name="SynchPrioritySimpleType">
		<restriction base="string">
			<enumeration value="low"/>
			<enumeration value="normal"/>
			<enumeration value="high"/>
		</restriction>
	</simpleType>
</schema>
