<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!--  Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="mcSynchronisation.xsd"/>
	<include schemaLocation="mcSystemAlerter.xsd"/>
	<!-- taskProperties -->
	<element name="taskProperties" type="fews:TaskPropertiesComplexType">
		<annotation>
			<documentation>The properties of a particular task.</documentation>
		</annotation>
	</element>
	<!-- TaskPropertiesComplexType -->
	<complexType name="TaskPropertiesComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional description of the task.</documentation>
				</annotation>
			</element>
			<element name="userId" type="string" minOccurs="0">
				<annotation>
					<documentation>Id of user generating this TaskProperties.</documentation>
				</annotation>
			</element>
			<element name="workflowId" type="fews:idStringType">
				<annotation>
					<documentation>ID of the workflow this task is referencing.</documentation>
				</annotation>
			</element>
			<element name="taskSelection" type="fews:TaskSelectionComplexType">
				<annotation>
					<documentation>Selection of the type of task. This can be either manual or scheduled.</documentation>
				</annotation>
			</element>
			<element name="forecastPriority" type="fews:ForecastPriorityStringType" default="Normal">
				<annotation>
					<documentation>Priority of the forecast. This is either normal or high.</documentation>
				</annotation>
			</element>
			<element name="forecastLength" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Length of a forecast. This is optional and overrules the settings of the module instance configurations.</documentation>
				</annotation>
			</element>
			<element name="makeForcastCurrent" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Boolean flag to indicate whether the forecast should be marked as current forecast.</documentation>
				</annotation>
			</element>
			<element name="whatIfScenarioId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Optional user defined what-if id</documentation>
				</annotation>
			</element>
			<element name="stateSelection" type="fews:StateSelectionComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional state specific settings. If set they overrule the corresponding module instance configuration. Time settings are relative to time0.</documentation>
				</annotation>
			</element>
			<element name="areaSelectionShapeFileBase64" type="string" minOccurs="0">
				<annotation>
					<documentation>Base64 encoded .shp file that can be used as input for the ExportAreaSelectionActivity of the general adapter.</documentation>
				</annotation>
			</element>
			<element name="selectedLocationId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Location selection, specifying the output for the ExportLocationAreaActivity of the general adapter.</documentation>
				</annotation>
			</element>
			<element name="makeStateCurrent" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Deprecated, not used</documentation>
				</annotation>
			</element>
			<element name="runExpiryTime" type="fews:CalendarTimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Time after the dispatch a created run will be rolling barreled</documentation>
				</annotation>
			</element>
			<element name="configFiles" type="fews:ConfigFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>OBSOLETE. Configuration files to be used in the task runs that belong to this task. Optional.</documentation>
				</annotation>
			</element>
			<element name="archiveTask" type="fews:ArchiveTaskComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated, used by old archive.</documentation>
				</annotation>
			</element>
			<element name="taskRunType" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Can be set to IFD_FS</documentation>
				</annotation>
			</element>
			<element name="properties" type="fews:PropertiesComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2017.02. Additional properties of the task</documentation>
				</annotation>
			</element>
			<element name="activeModuleInstanceRuns" type="fews:ModuleInstanceRunKeyComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="mcSynchronisation" type="fews:McSynchronisationComplexType" minOccurs="0"/>
			<element name="mcSystemAlerter" type="fews:mc-system-alerter-type" minOccurs="0"/>
			<element name="ensembleParts" type="positiveInteger" minOccurs="0">
				<annotation>
					<documentation>Determines in how many parts the workflow can be split up to run in parallel for ensembles. Ensembles will only be split up if this element is specified and the  number specified is larger than 1. This number cannot be larger than the maxEnsembleParts specified in the workflowDescriptor.
						</documentation>
				</annotation>
			</element>
			<element name="ensembleMemberIndexRange" type="fews:EnsembleMemberIndexRangeComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Sub-selection of the ensemble member indices the workflow should be run for</documentation>
				</annotation>
			</element>
			<element name="moduleInstanceIndices" type="positiveInteger" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>WRONG ELEMENT NAME. correct name workflowNodeIndices.  Sub-selection of the workflow node indices to be run for.  If omitted, the complete workflow is executed</documentation>
				</annotation>
			</element>


		</sequence>
	</complexType>
	<!-- TaskSelectionComplexType -->
	<!--    todo OA rename to TaskSelectionComplexType to ScheduleProperties , then it replaces EB's SchedulerDescriptor-->
	<complexType name="TaskSelectionComplexType">
		<choice>
			<element name="singleTask" type="fews:SingleTaskComplexType">
				<annotation>
					<documentation>Task configured in the FewsExplorer GUI that is meant to run just once.</documentation>
				</annotation>
			</element>
			<element name="scheduledTask" type="fews:ScheduledTaskComplexType">
				<annotation>
					<documentation>Task that uses scheduling information to run multiple times .</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<!-- SingleTaskComplexType -->
	<complexType name="SingleTaskComplexType">
		<sequence>
			<element name="time0" type="dateTime">
				<annotation>
					<documentation>Time 0 for a manual task run.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TimesOfMonthComplexType">
		<sequence minOccurs="0">
			<element name="daysOfMonth" type="fews:daysOfMonthListType" maxOccurs="unbounded">
				<annotation>
					<documentation>The day of the month, i.e. 01 02 31. 
				</documentation>
				</annotation>
			</element>
			<element name="times" type="fews:shortTimeListType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>When no times specified, 00:00:00 hours at the start of the day in the configured timeZone.</documentation>
				</annotation>
			</element>
			<element name="timeZone" type="fews:timeZoneStringType" minOccurs="0">
				<annotation>
					<documentation>Optional time zone for the specified dates and times. If no time zone is defined, then dates and times are in GMT.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- SchedulingComplexType -->
	<complexType name="SchedulingComplexType">
		<sequence>
			<element name="daysOfMonth" type="fews:daysOfMonthListType">
				<annotation>
					<documentation>The days of the month, i.e. 01 02 31. 
				</documentation>
				</annotation>
			</element>
			<element name="times" type="fews:shortTimeListType">
				<annotation>
					<documentation>When no times specified, 00:00:00 hours at the start of the day in the configured timeZone.</documentation>
				</annotation>
			</element>
			<element name="timeZone" type="fews:timeZoneStringType" minOccurs="0">
				<annotation>
					<documentation>Optional time zone for dates and times defined in this timeStep. If no time zone is defined, then dates and times are in GMT.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="YearlySchedulingComplexType">
		<sequence>
			<element name="daysOfYear" type="fews:daysOfYearListType">
				<annotation>
					<documentation>days of year are encoded as month*100 + the day of the month. For example: july the eleventh = 7*100 + 11 = 711 or november the second = 11*100 + 2 = 112
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<!-- ScheduledTaskComplexType -->
	<complexType name="ScheduledTaskComplexType">
		<sequence>
			<element name="schedulingPeriod" type="fews:PeriodComplexType">
				<annotation>
					<documentation>Period of time in which the task should be run.</documentation>
				</annotation>
			</element>
			<choice>
				<element name="schedulingInterval" type="fews:TimeSpanComplexType">
					<annotation>
						<documentation>Repetition frequency of the task run within the scheduling period based on seconds.</documentation>
					</annotation>
				</element>
				<element name="scheduling" type="fews:SchedulingComplexType">
					<annotation>
						<documentation>Since 2015.02. Timestep for scheduling not necessarily based on seconds.</documentation>
					</annotation>
				</element>
				<element name="yearlyScheduling" type="fews:YearlySchedulingComplexType">
					<annotation>
						<documentation>Since 2020.02. Timestep for scheduling yearly.</documentation>
					</annotation>
				</element>
			</choice>
			<element name="schedulingTime0Shift" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Time 0 shift relative to the time 0 of the task run.</documentation>
				</annotation>
			</element>
			<element name="cancelAllowed" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Option indicating if this task can be cancelled by the OC</documentation>
				</annotation>
			</element>
			<element name="suspendAllowed" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Option indicating if this task can be suspended by the OC</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- ForecastPriorityStringType -->
	<simpleType name="ForecastPriorityStringType">
		<restriction base="string">
			<enumeration value="Normal"/>
			<enumeration value="High"/>
		</restriction>
	</simpleType>
	<!--  in fact making difference between cold state selection and a warm state selection makes
    no sense because a warm state selection also can find a cold state. Making the stateSearchPeriod optional
    is enough to force searching for a cold state -->
	<!-- ConfigFilesComplexType -->
	<complexType name="ConfigFilesComplexType">
		<sequence>
			<element name="regionConfigFiles" type="fews:RegionConfigFileComplexType" minOccurs="0">
				<annotation>
					<documentation>The region configuration files.</documentation>
				</annotation>
			</element>
			<element name="idMapFiles" type="fews:IdMapFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>The configuration files used to map between IDs.</documentation>
				</annotation>
			</element>
			<element name="unitConversionsFiles" type="fews:UnitConversionsFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>The configuration files used to convert units.</documentation>
				</annotation>
			</element>
			<element name="flagConversionsFiles" type="fews:FlagConversionsFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>The configuration files used to convert flags of time series.</documentation>
				</annotation>
			</element>
			<element name="workflowConfigFiles" type="fews:WorkFlowConfigFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>The workflow configuration files used.</documentation>
				</annotation>
			</element>
			<element name="workflowConfigFile" type="fews:ConfigFileComplexType" minOccurs="0">
				<annotation>
					<documentation>Deprecated! Do not use this element, it is inserted for backward compatibility only.</documentation>
				</annotation>
			</element>
			<element name="moduleConfigFiles" type="fews:ModuleConfigFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>The configuration files for the module instances.</documentation>
				</annotation>
			</element>
			<element name="moduleParameterFiles" type="fews:ModuleParameterFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>The module instance parameter files used.</documentation>
				</annotation>
			</element>
			<element name="moduleDataSetFiles" type="fews:ModuleDataSetFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>The module data set files used.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<!-- RegionConfigFileComplexType -->
	<complexType name="RegionConfigFileComplexType">
		<sequence>
			<element name="regionConfigFile" type="fews:ConfigFileComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!-- IdMapFileComplexType -->
	<complexType name="IdMapFilesComplexType">
		<sequence>
			<element name="idMapFile" type="fews:ConfigFileComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!-- UnitConversionsFilesComplexType -->
	<complexType name="UnitConversionsFilesComplexType">
		<sequence>
			<element name="unitConversionsFile" type="fews:ConfigFileComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!-- FlagConversionsFilesComplexType -->
	<complexType name="FlagConversionsFilesComplexType">
		<sequence>
			<element name="flagConversionsFile" type="fews:ConfigFileComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!-- ModuleConfigFilesComplexType -->
	<complexType name="ModuleConfigFilesComplexType">
		<sequence>
			<element name="moduleConfigFile" type="fews:ConfigFileComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!-- ModuleParameterFilesComplexType -->
	<complexType name="ModuleParameterFilesComplexType">
		<sequence>
			<element name="moduleParameterFile" type="fews:ConfigFileComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!-- ModuleDataSetFilesComplexType -->
	<complexType name="ModuleDataSetFilesComplexType">
		<sequence>
			<element name="moduleDataSetFile" type="fews:ConfigFileComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="WorkFlowConfigFilesComplexType">
		<sequence>
			<element name="workflowConfigFile" type="fews:ConfigFileComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
</schema>
