<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="thresholdEventsDisplay" type="fews:ThresholdEventsDisplayComplexType"/>
	<complexType name="ThresholdEventsDisplayComplexType">
		<annotation>
			<documentation>Configures the tab 'Threshold Events'</documentation>
		</annotation>
		<sequence>
			<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Since 2019.02 TimeSeriesSets that refer to time series of the target location id's of the threshold events (if any). Can be used to show the last received or sent warning (level)</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>