<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by tacoma (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="thresholdSkillScoreDisplay" type="fews:ThresholdSkillScoreDisplayComplexType"/>
	<!---->
	<complexType name="ThresholdSkillScoreDisplayComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="general" type="fews:ThresholdSkillScoreDisplayGeneralComplexType"/>
			<element name="group" type="fews:ThresholdSkillScoreGroupComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!---->
	<complexType name="ThresholdSkillScoreDisplayGeneralComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="displayName" type="string">
				<annotation>
					<documentation>Appears in the title bar of the dialog</documentation>
				</annotation>
			</element>
			<element name="levelThresholdId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="rateThresholdId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="maxThresholdId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>level/rate/max ThresholdId's define which threshold types must be displayed in the list box. If no Ids are configured, then all thresholds from thresholds.xml config file are displayed.</documentation>
				</annotation>
			</element>
			<element name="attributeMatching" type="fews:ThresholdSkillScoreAttributeComplexType" minOccurs="0"/>
			<element name="attributeMissingObserved" type="fews:ThresholdSkillScoreAttributeComplexType" minOccurs="0"/>
			<element name="attributeMissingForecast" type="fews:ThresholdSkillScoreAttributeComplexType" minOccurs="0"/>
			<group ref="fews:EventMatchingCriteriaGroup"/>
			<element name="parameterPairs" type="fews:ThresholdSkillScoreParameterPairComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!--    -->
	<complexType name="ThresholdSkillScoreGroupComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="groupDefaultCriteria" type="fews:EventMatchingCriteriaComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional default event matching criteria for this group. If not specified, then for this group the global criteria will be used. The global even matching criteria are defined at the start of this file inside the "general" element.</documentation>
				</annotation>
			</element>
			<choice>
				<sequence>
					<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType" maxOccurs="unbounded">
						<annotation>
							<documentation>Specify one or more time series for this group.</documentation>
						</annotation>
					</element>
					<element name="locationDefaultCriteria" type="fews:LocationEventMatchingCriteriaComplexType" minOccurs="0" maxOccurs="unbounded">
						<annotation>
							<documentation>One or more optional mappings to define default event matching criteria for different locations. If a location is present in one of the specified timeSeriesSets and in one of these mappings, then the corresponding event matching criteria are used as default criteria for that location in this group. If for a given location no criteria are defined, then for that location in this group the global criteria will be used. The global even matching criteria are defined at the start of this file inside the "general" element.</documentation>
						</annotation>
					</element>
				</sequence>
				<element name="child" type="fews:ThresholdSkillScoreGroupChildComplexType" maxOccurs="unbounded">
					<annotation>
						<documentation>Specify the ids of one or more subgroups.</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nameStringType" use="optional"/>
	</complexType>
	<!---->
	<complexType name="ThresholdSkillScoreGroupChildComplexType">
		<annotation>
			<documentation>Specifies the Id of the subgroup</documentation>
		</annotation>
		<attribute name="foreignKey" type="fews:idStringType" use="required"/>
	</complexType>
	<!---->
	<complexType name="ThresholdSkillScoreAttributeComplexType">
		<choice>
			<sequence>
				<element name="attributeMapId" type="fews:idStringType"/>
				<element name="attributeValue" type="float">
					<annotation>
						<documentation>Remark:  use float to specify a value  since ValueAttributeMap accepts only floats as values.</documentation>
					</annotation>
				</element>
			</sequence>
			<element name="color" type="fews:colorStringType"/>
		</choice>
	</complexType>
	<!---->
	<complexType name="ThresholdSkillScoreParameterPairComplexType">
		<attribute name="parameterIdObs" type="fews:idStringType" use="required"/>
		<attribute name="parameterIdFor" type="fews:idStringType" use="required"/>
	</complexType>
	<!---->
	<group name="EventMatchingCriteriaGroup">
		<annotation>
			<documentation>Groups event matching criteria.</documentation>
		</annotation>
		<sequence>
			<element name="minTimeZeroDifference" type="fews:RelativeTimeComplexType">
				<annotation>
					<documentation>Minimum between forecast T0 and detection of threshold</documentation>
				</annotation>
			</element>
			<element name="maxTimeZeroDifference" type="fews:RelativeTimeComplexType">
				<annotation>
					<documentation>Maximum between forecast T0 and detection of threshold</documentation>
				</annotation>
			</element>
			<element name="earlyDifference" type="fews:RelativeTimeComplexType">
				<annotation>
					<documentation>Maximum time of forecast threshold being too early</documentation>
				</annotation>
			</element>
			<element name="lateDifference" type="fews:RelativeTimeComplexType">
				<annotation>
					<documentation>Maximum time of forecast threshold being too late</documentation>
				</annotation>
			</element>
		</sequence>
	</group>
	<!---->
	<complexType name="EventMatchingCriteriaComplexType">
		<group ref="fews:EventMatchingCriteriaGroup"/>
	</complexType>
	<!---->
	<complexType name="LocationEventMatchingCriteriaComplexType">
		<sequence>
			<element name="locationId" type="fews:idStringType"/>
			<group ref="fews:EventMatchingCriteriaGroup"/>
		</sequence>
	</complexType>
</schema>
