<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="timeSteps" type="fews:TimeStepsComplexType">
		<annotation>
			<documentation>Predefined time steps that can be referenced from other config files
			</documentation>
		</annotation>
	</element>
	<!--    -->
	<complexType name="TimeStepsComplexType">
		<annotation>
			<documentation>Predefined time step that can be referenced from other config files.
				Especially useful for verbose time step definitions. E.g. time steps with a time zone.
				It is comparable with a global property, it makes no difference to use the global time step or the verbose time step
			</documentation>
		</annotation>
		<choice maxOccurs="unbounded">
			<element name="timeStep" type="fews:TimeStepComplexType"/>
			<element name="weeklyTimeStep" type="fews:WeeklyTimeStepComplexType">
					<annotation>
					<documentation>Since 2014.01. A timeStep that defines a pattern of times in a week. This pattern will be repeated every week</documentation>
				</annotation>
			</element>
			<element name="monthlyTimeStep" type="fews:MonthlyTimeStepComplexType">
				<annotation>
					<documentation>A timeStep that defines a pattern of days in a month. This pattern will be repeated every month. Each day in the month can have a different aggregation period. The start of the aggregation period is exclusive and the end of the aggregation period is inclusive.</documentation>
				</annotation>
			</element>
			<element name="yearlyTimeStep" type="fews:YearlyTimeStepComplexType">
				<annotation>
					<documentation>A timeStep that defines a pattern of dates in a year. This pattern will be repeated every year. Each date in the year can have a different aggregation period (season). The start of the aggregation period is exclusive and the end of the aggregation period is inclusive. This yearlyTimeStep is meant for seasons, therefore limited to four dates. If more than four dates in a year are required, then either use the monthlyTimeStep or use the monthDays option in the timeStep element instead of this yearlyTimeStep.</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
		<complexType name="WeeklyTimeStepComplexType">
		<sequence>
			<element name="timeZone" type="fews:timeZoneStringType" minOccurs="0">
				<annotation>
					<documentation>Optional time zone for dates and times defined in this timeStep. If no time zone is defined, then dates and times are in GMT.</documentation>
				</annotation>
			</element>
			<element name="sunday" type="fews:TimesOfWeekDayComplexType" minOccurs="0"/>
			<element name="monday" type="fews:TimesOfWeekDayComplexType" minOccurs="0"/>
			<element name="tuesday" type="fews:TimesOfWeekDayComplexType" minOccurs="0"/>
			<element name="wednesday" type="fews:TimesOfWeekDayComplexType" minOccurs="0"/>
			<element name="thursday" type="fews:TimesOfWeekDayComplexType" minOccurs="0"/>
			<element name="friday" type="fews:TimesOfWeekDayComplexType" minOccurs="0"/>
			<element name="saturday" type="fews:TimesOfWeekDayComplexType" minOccurs="0"/>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier of this timeStep.</documentation>
			</annotation>
		</attribute>
		<attribute name="label" type="string" use="optional">
			<annotation>
				<documentation>Short name for the time step which is shown to the user when he can chose one from a list.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="MonthlyTimeStepComplexType">
		<sequence>
			<element name="timeZone" type="fews:timeZoneStringType" minOccurs="0">
				<annotation>
					<documentation>Optional time zone for dates and times defined in this timeStep. If no time zone is defined, then dates and times are in GMT.</documentation>
				</annotation>
			</element>
			<element name="day" type="fews:DayOfMonthWithAggregationPeriodComplexType" maxOccurs="6">
				<annotation>
					<documentation>Define a day for this timestep. For each month this day will be included in the timestep. This monthlyTimeStep is limited to six days. If more than six days in a month are required, then please use the daysOfMonth option in the timeStep element instead of this monthlyTimeStep.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier of this timeStep.</documentation>
			</annotation>
		</attribute>
		<attribute name="label" type="string" use="optional">
			<annotation>
				<documentation>Short name for the time step which is shown to the user when he can chose one from a list.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="TimesOfWeekDayComplexType">
			<attribute name="times" type="fews:shortTimeListType" use="required">
		</attribute>
	</complexType>
	<complexType name="YearlyTimeStepComplexType">
		<sequence>
			<element name="timeZone" type="fews:timeZoneStringType" minOccurs="0">
				<annotation>
					<documentation>Optional time zone for dates and times defined in this timeStep. If no time zone is defined, then dates and times are in GMT.</documentation>
				</annotation>
			</element>
			<element name="monthDay" type="fews:MonthDayWithAggregationPeriodComplexType" maxOccurs="4">
				<annotation>
					<documentation>One or more dates in a year for which data values can be stored when this timeStep is used. These dates will be repeated every year. Each date in the year can have a different aggregation period (season). The start of the aggregation period is exclusive and the end of the aggregation period is inclusive. This yearlyTimeStep is meant for seasons, therefore limited to four dates. If more than four dates in a year are required, then either use the monthlyTimeStep or use the monthDays option in the timeStep element instead of this yearlyTimeStep.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier of this timeStep.</documentation>
			</annotation>
		</attribute>
		<attribute name="label" type="string" use="optional">
			<annotation>
				<documentation>Short name for the time step which is shown to the user when he can chose one from a list.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="DayOfMonthWithAggregationPeriodComplexType">
		<attribute name="value" type="fews:daysOfMonthListType" use="required">
			<annotation>
				<documentation>The day for a data value. The time is 00:00:00 hours at the start of the day (in the configured timeZone).</documentation>
			</annotation>
		</attribute>
		<attribute name="start" type="fews:daysOfMonthListType" use="required">
			<annotation>
				<documentation>The day of the start of the aggregation period for the data value. The time is 00:00:00 hours at the start of the day (in the configured timeZone). The start of the aggregation period is exclusive.</documentation>
			</annotation>
		</attribute>
		<attribute name="end" type="fews:daysOfMonthListType" use="required">
			<annotation>
				<documentation>The day of the end of the aggregation period for the data value. The time is 00:00:00 hours at the start of the day (in the configured timeZone). The end of the aggregation period is inclusive.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="MonthDayWithAggregationPeriodComplexType">
		<attribute name="value" type="fews:monthDayType" use="required">
			<annotation>
				<documentation>The month and day for a data value. The time is 00:00:00 hours at the start of the day (in the configured timeZone).</documentation>
			</annotation>
		</attribute>
		<attribute name="start" type="fews:monthDayType" use="required">
			<annotation>
				<documentation>The month and day of the start of the aggregation period (season) for the data value. The time is 00:00:00 hours at the start of the day (in the configured timeZone). The start of the aggregation period is exclusive.</documentation>
			</annotation>
		</attribute>
		<attribute name="end" type="fews:monthDayType" use="required">
			<annotation>
				<documentation>The month and day of the end of the aggregation period (season) for the data value. The time is 00:00:00 hours at the start of the day (in the configured timeZone). The end of the aggregation period is inclusive.</documentation>
			</annotation>
		</attribute>
	</complexType>
</schema>
