<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by tacoma (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified"
		version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="timeSeriesTableDisplay" type="fews:TimeSeriesTableDisplayComplexType"/>
	<complexType name="TimeSeriesTableDisplayComplexType">
		<sequence>
			<element name="general" type="fews:TimeSeriesTableDisplayGeneralComplexType"/>
			<element name="tableTab" type="fews:TimeSeriesTableTabComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="TimeSeriesTableTabComplexType">
		<sequence>
			<element name="title" type="fews:nonEmptyStringType"/>
			<element name="id" type="fews:idStringType" minOccurs="0"/>
			<element name="showValues" type="boolean"/>
			<element name="showThresholdColors" type="boolean"/>
			<element name="locationGroupingAttributeId" type="fews:idStringType" minOccurs="0"/>
			<element name="locationOrderingAttributeId" type="fews:idStringType" minOccurs="0"/>
			<element name="locationLabelAttributeId" type="fews:idStringType" minOccurs="0"/>
			<element name="thresholdGroupIdId" type="fews:idStringType" minOccurs="0"/>
			<element name="column" type="fews:TimeSeriesTableDisplayColumnComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="TimeSeriesTableDisplayGeneralComplexType">
		<annotation>
			<documentation>Configures the main display (dialog)</documentation>
		</annotation>
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="displayName" type="string">
				<annotation>
					<documentation>Title of the dialog</documentation>
				</annotation>
			</element>
			<element name="forecastFilter" type="fews:TimeSeriesTableDisplayForecastFilterComplexType" minOccurs="0">
				<annotation>
					<documentation>Filter to specify which forecast should be displayed in the dialog-combobox</documentation>
				</annotation>
			</element>
			<element name="variable" type="fews:TimeSeriesTableDisplayVariableDefinitionComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Definitions of variables that can be used for displaying table contents in tabs.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TimeSeriesTableDisplayForecastFilterComplexType">
		<sequence>
			<element name="workflowId" type="fews:idStringType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="TimeSeriesTableDisplayVariableDefinitionComplexType">
		<sequence>
			<element name="variableId" type="fews:idStringType">
				<annotation>
					<documentation>Identifier for this variable. Use this identifier to reference to this variable in a transformation.</documentation>
				</annotation>
			</element>
			<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType">
				<annotation>
					<documentation>A time series set that can be used as input or as output for a transformation function.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TimeSeriesTableDisplayColumnComplexType">
		<attribute name="variableId" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:nonEmptyStringType"/>
	</complexType>
</schema>