<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by WL | Delft Hydraulics (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!--Transformation Schema with element  transformationSets-->
	<element name="transformationSets" type="fews:TransformationSetsComplexType">
		<annotation>
			<documentation>transformation Sets element</documentation>
		</annotation>
	</element>
	<!--Complex Types definitions for different types of Transformations-->
	<!--TransformationSets-->
	<complexType name="TransformationSetsComplexType">
		<annotation>
			<documentation>Transformation Sets contains one or more transformation Set </documentation>
		</annotation>
		<sequence>
			<element name="logLevel" type="fews:logLevelEnumStringType" default="INFO" minOccurs="0">
				<annotation>
					<documentation>Currently the logLevel option is only implemented for hydroMeteoFunctions simpleratingcurve and qhrelationtable and can only be used to suppress warnings in hydroMeteoFunctions simpleratingcurve and qhrelationtable. Indicate the Logging Level : Five levels are available - (in order of increasing severity)  Debug, Info, Warn, Error and Fatal: If the user would not like to see DEBUG messages then the logLevel here should be set to INFO. This means that all INFO, WARN, ERROR and FATAL will be written but no DEBUG messages. Since DEBUG messages are of lower severity then INFO messages.</documentation>
				</annotation>
			</element>
			<element name="transformationSet" type="fews:TransformationSetComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
	</complexType>
	<!--TransformationSet-->
	<complexType name="TransformationSetComplexType">
		<annotation>
			<documentation>Transformation Set defines input + output time series set and choice of transformation</documentation>
		</annotation>
		<sequence>
			<element name="inputVariable" type="fews:VariableComplexType" maxOccurs="unbounded"/>
			<choice>
				<element name="arithmeticFunction" type="fews:ArithmeticFunctionComplexType" maxOccurs="unbounded"/>
				<element name="hydroMeteoFunction" type="fews:HydroMeteoFunctionComplexType" maxOccurs="unbounded"/>
				<element name="ruleBasedTransformation" type="fews:RuleBasedTransformationComplexType"/>
				<element name="aggregate" type="fews:AggregationComplexType"/>
				<element name="disaggregate" type="fews:DisaggregationComplexType"/>
				<element name="nonequidistantToEquidistant" type="fews:NonequidistantToEquidistantComplexType"/>
				<element name="statistics" type="fews:StatisticalMethodsComplexType"/>
			</choice>
			<element name="outputVariable" type="fews:VariableComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="transformationId" type="fews:idStringType" use="optional"/>
	</complexType>
	<!-- Arithmetic Function Transformation-->
	<complexType name="ArithmeticFunctionComplexType">
		<sequence>
			<element name="segments" type="fews:SegmentsComplexType" minOccurs="0"/>
		</sequence>
		<attribute name="function" type="fews:arithmeticFunctionEnumStringType" use="optional"/>
		<attribute name="userDefinedFunction" type="string" use="optional"/>
		<attribute name="outputVariableId" type="fews:idStringType" use="optional"/>
	</complexType>
	<!--Aggregation Transformation-->
	<complexType name="AggregationComplexType">
		<attribute name="rule" type="fews:aggregationRuleEnumStringType" use="required"/>
	</complexType>
	<!--Disaggregation Transformation-->
	<complexType name="DisaggregationComplexType">
		<sequence>
			<element name="coefficient" type="fews:CoefficientComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="rule" type="fews:disaggregationRuleEnumStringType" use="required"/>
	</complexType>
	<!--NonEquiDistant to Equidistant Transformation-->
	<complexType name="NonequidistantToEquidistantComplexType">
		<attribute name="rule" type="fews:nonequidistantToEquidistantEnumStringType" use="required"/>
	</complexType>
	<!--Hydrological and Meteorological Function Transformation -->
	<complexType name="HydroMeteoFunctionComplexType">
		<sequence>
			<element name="segments" type="fews:SegmentsComplexType" minOccurs="0"/>
			<element name="window" type="fews:TimeSpanComplexType" minOccurs="0"/>
		</sequence>
		<attribute name="function" type="fews:hydroMeteoFunctionEnumStringType" use="optional"/>
		<attribute name="userDefinedFunction" type="string" use="optional"/>
		<attribute name="inputVariableId" type="fews:idStringType" use="optional"/>
		<attribute name="outputVariableId" type="fews:idStringType" use="optional"/>
		<attribute name="useRatingCurve" type="boolean" use="optional" default="false"/>
		<attribute name="ratingCurveId" type="fews:idStringType" use="optional"/>
		<attribute name="ratingCurveType" type="fews:RatingCurveTypeEnumStringType" use="optional"/>
		<attribute name="ignoreMissings" type="boolean" use="optional" default="false"/>
		<attribute name="minVolumeIncrement" type="float" use="optional"/>
		<attribute name="rainfallEventParameter" type="fews:rainfallEventParameterEnumStringType" use="optional"/>
		<attribute name="rainfallEventTime" type="fews:rainfallEventTimeEnumStringType" use="optional"/>
		<attribute name="singleRainfallEvent" type="boolean" use="optional" default="false"/>
		<attribute name="availableObservedValues" type="float" use="optional"/>
		<attribute name="observedValuesGap" type="float" use="optional"/>
		<attribute name="consecutiveObservedValues" type="boolean" use="optional"/>
		<attribute name="transformationId" type="fews:idStringType">
			<annotation>
				<documentation>Id of the transformation to use. The transformations are defined in the RegionalTransformation file in the region config.</documentation>
			</annotation>
		</attribute>
		<attribute name="reverseTransformation" type="boolean">
			<annotation>
				<documentation>Option to use transformation in reversed direction (output -> input). If missing then false.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<!-- -->
	<complexType name="RuleBasedTransformationComplexType">
		<sequence>
			<element name="segments" type="fews:SegmentsComplexType" minOccurs="0"/>
			<element name="maxGapLength" type="fews:TimeSpanComplexType" minOccurs="0"/>
			<element name="sampleWindow" type="fews:RelativePeriodComplexType" minOccurs="0"/>
			<element name="coefficients" type="fews:RuleBasedCoefficientPerFunctionComplexType" minOccurs="0"/>
		</sequence>
		<attribute name="rule" type="fews:ruleEnumStringType" use="required"/>
		<attribute name="userDefinedFunction" type="string" use="optional"/>
		<attribute name="inputVariableId" type="fews:idStringType" use="optional"/>
		<attribute name="outputVariableId" type="fews:idStringType" use="optional"/>
		<attribute name="constant" type="float" use="optional"/>
		<attribute name="hierarchyMethod" type="fews:hierarchyMethodEnumStringType" use="optional"/>
		<attribute name="timeShiftValues" type="fews:idStringType" use="optional"/>
		<attribute name="timeDifferenceReference" type="fews:idStringType" use="optional"/>
		<attribute name="lookupDirection" type="fews:lookupDirectionEnumStringType" use="optional"/>
		<attribute name="dataHierarchyIndexOutputVariableId" type="fews:idStringType" use="optional">
			<annotation>
				<documentation>replace by element, todo add comment see, see FEWS-320</documentation>
			</annotation>
		</attribute>
	</complexType>
	<!--Definition of StatisticalFunctionsComplexType-->
	<complexType name="StatisticalMethodsComplexType">
		<sequence>
			<element name="season" type="fews:SeasonComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="function" type="fews:StatisticalFunctionComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="StatisticalFunctionComplexType">
		<attribute name="function" type="fews:StatisticalFunctionsEnumStringType" use="required"/>
		<attribute name="isBlockFunction" type="boolean" default="false"/>
		<attribute name="inputVariableId" type="fews:idStringType" use="required"/>
		<attribute name="outputVariableId" type="fews:idStringType" use="required"/>
		<attribute name="value" type="float" use="optional"/>
		<attribute name="ignoreMissing" type="boolean" use="optional" default="true"/>
		<attribute name="seasonal" type="boolean" use="optional" default="true">
			<annotation>
				<documentation>If seasonal is true, then one result value per season is returned. If seasonal is false, then for multiple seasons only one (combined) result value is returned. If using this option, a season should be defined. Default is true.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<!--Complex Type definitions for the defining the Segments per defined Transformations-->
	<!--Segments-->
	<complexType name="SegmentsComplexType">
		<sequence>
			<element name="segment" type="fews:SegmentComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="limitVariableId" type="fews:idStringType" use="optional"/>
	</complexType>
	<!--Segment-->
	<complexType name="SegmentComplexType">
		<sequence>
			<element name="limitLower" type="float" minOccurs="0"/>
			<element name="limitUpper" type="float" minOccurs="0"/>
			<choice minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>the (parent) location (sets) specifies a filter for the locations in the input and output variables. E.g. this makes it possible to use a different user defined function for each location.
                    </documentation>
				</annotation>
				<element name="locationId" type="fews:idStringType"/>
				<element name="locationSetId" type="fews:idStringType"/>
			</choice>
			<choice minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>the (parent) location (sets) specifies a filter for the locations in the input and output variables. E.g. this makes it possible to use a different user defined function for each location.
                    </documentation>
				</annotation>
				<element name="parentLocationId" type="fews:idStringType"/>
				<element name="parentLocationSetId" type="fews:idStringType"/>
			</choice>
			<element name="functionType" type="fews:functionEnumStringType" minOccurs="0"/>
			<element name="userDefinedFunction" type="string" minOccurs="0"/>
			<element name="constant" type="float" minOccurs="0"/>
			<element name="coefficient" type="fews:CoefficientComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="tableColumnData" type="fews:TableComplexType" minOccurs="0"/>
			<element name="outputVariableId" type="fews:idStringType" minOccurs="0"/>
			<element name="flag" type="fews:flagEnumStringType" minOccurs="0"/>
		</sequence>
	</complexType>
	<!--Complex Type definition for Variable and Coefficients -->
	<!--Coefficient which defines an Id and float value for each coefficient-->
	<complexType name="CoefficientComplexType">
		<attribute name="coefficientId" type="fews:idStringType" use="optional"/>
		<attribute name="coefficientType" type="fews:coefficientTypeEnumStringType" use="optional"/>
		<attribute name="value" type="float" use="required"/>
	</complexType>
	<!--Simple Types definition-->
	<!--Enumeration for disaggregation rule-->
	<simpleType name="disaggregationRuleEnumStringType">
		<restriction base="string">
			<enumeration value="instantaneous"/>
			<enumeration value="accumulative"/>
			<enumeration value="disaggregateusingweights"/>
			<enumeration value="constant"/>
		</restriction>
	</simpleType>
	<!--Enumeration for values at selected time -->
	<simpleType name="ruleEnumStringType">
		<restriction base="string">
			<enumeration value="sampleforecastvalues"/>
			<enumeration value="selectpeakvalues"/>
			<enumeration value="selectlowvalues"/>
			<enumeration value="selectpeakvalueswithincertaingap"/>
			<enumeration value="selectlowvalueswithincertaingap"/>
			<enumeration value="equitononequidistant"/>
			<enumeration value="equitononequidistantforinstantaneousseries"/>
			<enumeration value="equitononequidistantforaccumulativeseries"/>
			<enumeration value="datahierarchy"/>
			<enumeration value="typicalprofiletotimeseries"/>
			<enumeration value="typicalprofileasyearstogrid"/>
			<enumeration value="nonequitoequidistant"/>
			<enumeration value="nonequitoequidistantforinstantaneousseries"/>
			<enumeration value="nonequitoequidistantforaccumulativeseries"/>
			<enumeration value="nonequitoequidistantwithzero"/>
			<enumeration value="nonequitoequidistantwithmissing"/>
			<enumeration value="zerodegreealtitudelevel"/>
			<enumeration value="datatotimeseries"/>
			<enumeration value="shiftdata"/>
			<enumeration value="timeshift"/>
			<enumeration value="timedifference"/>
			<enumeration value="soilmoisture"/>
			<enumeration value="opticalDepth"/>
			<enumeration value="harmonictotimeseries"/>
			<enumeration value="selectmaxvalue"/>
			<enumeration value="selectminvalue"/>
			<enumeration value="convertDatumLocalToGlobal"/>
			<enumeration value="convertDatumGlobalToLocal"/>
			<enumeration value="elevationlapse"/>
			<enumeration value="samplehistorical"/>
		</restriction>
	</simpleType>
	<!--Enumeration for NonEquiDistant to Equidistant-->
	<simpleType name="nonequidistantToEquidistantEnumStringType">
		<restriction base="string">
			<enumeration value="zero"/>
			<enumeration value="missing"/>
			<enumeration value="linearinterpolated"/>
			<enumeration value="equaltolast"/>
		</restriction>
	</simpleType>
	<!--Enumeration Type for selected special Functions/transformations -->
	<simpleType name="functionEnumStringType">
		<restriction base="string">
			<enumeration value="simpleratingcurve"/>
			<enumeration value="penman"/>
			<enumeration value="weightedaverage"/>
			<enumeration value="penmannortheast"/>
			<enumeration value="degreemanipulation"/>
			<enumeration value="qhrelationtable"/>
			<enumeration value="mergesynoptic"/>
		</restriction>
	</simpleType>
	<simpleType name="arithmeticFunctionEnumStringType">
		<restriction base="string">
			<enumeration value="weightedaverage"/>
			<enumeration value="degreemanipulation"/>
		</restriction>
	</simpleType>
	<simpleType name="hydroMeteoFunctionEnumStringType">
		<restriction base="string">
			<enumeration value="simpleratingcurve"/>
			<enumeration value="penman"/>
			<enumeration value="penmannortheast"/>
			<enumeration value="qhrelationtable"/>
			<enumeration value="flatvweir"/>
			<enumeration value="crumpweir"/>
			<enumeration value="movingaverage"/>
			<enumeration value="movingmaximum"/>
			<enumeration value="movingminimum"/>
			<enumeration value="blockaverage"/>
			<enumeration value="blockmaximum"/>
			<enumeration value="blockminimum"/>
			<enumeration value="persistence"/>
			<enumeration value="originalandpersistence"/>
			<enumeration value="movingaverageandpersistence"/>
			<enumeration value="accumulation"/>
			<enumeration value="persistencetrend"/>
			<enumeration value="rainfallevent"/>
			<enumeration value="runningmeantrend"/>
			<enumeration value="mergesynoptic"/>
			<enumeration value="transformation"/>
			<enumeration value="tippingbucket"/>
		</restriction>
	</simpleType>
	<!-- Enumeration Type for selected coeffiecients-->
	<simpleType name="coefficientTypeEnumStringType">
		<annotation>
			<documentation>enumeration type for the coefficients (extra information to be passed depends on type of function selected)</documentation>
			<documentation>please note : a,b,,c is used for HydroMeteo function
			                           gaplengthinsec is synonymous with maximumgapbetweenpeaksinseconds (just to keep backward compatible)
			                           gaplengthinsec and maximumgapbetweenpeaksinseconds  is used in RuleBasedTransformation for selection of peak values
                                       use peaksbeforetimezero in combination with peaksaftertimezero to retrieve a desired number of peaks around T0
                                       totalnumberofpeaks must be left '0', if not, totalnumberofpeaks overrules peaks around T0 settings to retrieve the
                                       specified number of peaks from the start of the time series</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="a"/>
			<enumeration value="b"/>
			<enumeration value="c"/>
			<enumeration value="any"/>
			<enumeration value="gaplengthinsec"/>
			<enumeration value="maximumgapbetweenpeaksinseconds"/>
			<enumeration value="peaksbeforetimezero"/>
			<enumeration value="peaksaftertimezero"/>
			<enumeration value="totalnumberofpeaks"/>
			<enumeration value="skipjustbeforetimezero"/>
			<enumeration value="skipjustaftertimezero"/>
			<enumeration value="maximum"/>
			<enumeration value="minimum"/>
			<enumeration value="Pup"/>
			<enumeration value="Pdn"/>
			<enumeration value="A1"/>
			<enumeration value="A2"/>
			<enumeration value="A3"/>
			<enumeration value="B1"/>
			<enumeration value="B2"/>
			<enumeration value="B3"/>
			<enumeration value="Bup"/>
			<enumeration value="Bdn"/>
			<enumeration value="RH1"/>
			<enumeration value="RH2"/>
			<enumeration value="RH3"/>
			<enumeration value="sslope"/>
			<enumeration value="calculationtype"/>
			<enumeration value="energyheadcorrection"/>
			<enumeration value="crumptype"/>
			<enumeration value="ncrests"/>
			<enumeration value="cslope"/>
			<enumeration value="width"/>
			<enumeration value="dischargecoefficient"/>
			<enumeration value="constant"/>
			<enumeration value="sslopecheck"/>
			<enumeration value="cslopecheck"/>
			<enumeration value="decayvalue"/>
			<enumeration value="lowsbeforetimezero"/>
			<enumeration value="lowsaftertimezero"/>
			<enumeration value="inputVariable"/>
		</restriction>
	</simpleType>
	<!-- Enumeration for Hierarchy method-->
	<simpleType name="hierarchyMethodEnumStringType">
		<restriction base="string">
			<enumeration value="merge"/>
			<enumeration value="toggle"/>
		</restriction>
	</simpleType>
	<!-- Enumeration for lookupDirection-->
	<simpleType name="lookupDirectionEnumStringType">
		<restriction base="string">
			<enumeration value="both"/>
			<enumeration value="forward"/>
			<enumeration value="backward"/>
		</restriction>
	</simpleType>
	<!-- Enumeration for RainfallEvent Parameter to write-->
	<simpleType name="rainfallEventParameterEnumStringType">
		<restriction base="string">
			<enumeration value="medianVolume"/>
			<enumeration value="eventLength"/>
		</restriction>
	</simpleType>
	<!-- Enumeration for RainfallEvent Time to write-->
	<simpleType name="rainfallEventTimeEnumStringType">
		<restriction base="string">
			<enumeration value="startTime"/>
			<enumeration value="medianTime"/>
		</restriction>
	</simpleType>
	<!-- List Complex Type for storing data in a string of type defined by dataTypeEnumStringType and separator -->
	<complexType name="TableComplexType">
		<annotation>
			<documentation>complex type to enter the data per row or per column
			one can enter data for maximum two columns, and each column has to identified
			by the variable ID, the variable Id should match the IDs given in Input or Output variables
					</documentation>
		</annotation>
		<sequence>
			<element name="data" type="fews:TableDataComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="nrOfColumns" type="int" use="required"/>
		<attribute name="variableIdCol1" type="fews:idStringType" use="optional"/>
		<attribute name="variableIdCol2" type="fews:idStringType" use="optional"/>
	</complexType>
	<!--defines the type  for the data in data string-->
	<complexType name="TableDataComplexType">
		<attribute name="col1" type="float" use="optional"/>
		<attribute name="col2" type="float" use="optional"/>
	</complexType>
	<!-- -->
	<simpleType name="StatisticalFunctionsEnumStringType">
		<restriction base="string">
			<enumeration value="max"/>
			<enumeration value="min"/>
			<enumeration value="sum"/>
			<enumeration value="count"/>
			<enumeration value="mean"/>
			<enumeration value="median"/>
			<enumeration value="standardDeviation"/>
			<enumeration value="percentileExceedence"/>
			<enumeration value="percentileNonExceedence"/>
			<enumeration value="quartile"/>
			<enumeration value="skewness"/>
			<enumeration value="kurtosis"/>
			<enumeration value="variance"/>
			<enumeration value="rsquared"/>
			<!-- <enumeration value="empiricalDistribution"/>
			<enumeration value="cummulativePercentageLessThan"/>
			<enumeration value="cummulativePercentageLessOrEqualThan"/>
           -->
		</restriction>
	</simpleType>
	<complexType name="RuleBasedCoefficientPerFunctionComplexType">
		<choice>
			<element name="soilMoisture" type="fews:SoilMoistureCoefficientsComplexType"/>
			<element name="elevationLapse" type="fews:ElevationLapseCoefficientsComplexType"/>
			<element name="sampleHistoric" type="fews:SampleHistoricCoefficientsComplexType"/>
		</choice>
	</complexType>
	<complexType name="SoilMoistureCoefficientsComplexType">
		<attribute name="SoilPorosity" type="float" use="optional" default="0.44"/>
		<attribute name="Frequency" type="float" use="optional" default="10.65"/>
		<attribute name="SoilMoisture" type="float" use="optional" default="0.13"/>
		<attribute name="IncidenceAngle" type="float" use="optional" default="0.024315"/>
		<attribute name="ScatteringAlbedo" type="float" use="optional" default="0.06"/>
		<attribute name="AtmosphericOpacity" type="float" use="optional" default="0.01"/>
		<attribute name="PolarizationFraction" type="float" use="optional" default="0.127"/>
		<attribute name="Roughness" type="float" use="optional" default="0.18"/>
	</complexType>
	<complexType name="ElevationLapseCoefficientsComplexType">
		<annotation>
			<documentation>The formula used at each time step ios
t_out = t_in + (z_in-z_out)*lapserate
where t_out is the result temperatue
t_in is the input temp
z_in is the elvation (z) of the input location
z_out is the elevation of the output location</documentation>
		</annotation>
		<attribute name="temperatureLapseRate" type="float" use="required">
			<annotation>
				<documentation>Temperature lapse rate per 100m of elevation (typically 0.6 oC)</documentation>
			</annotation>
		</attribute>
		<attribute name="useReferenceElevation" use="required">
			<annotation>
				<documentation>If the useReferenceElevation is none - then the z levels are derived from the input/output location
if it is input - then z_in is equal to the value given in ReferenceElevation
if it is output - then z_out is equal to the value given in ReferenceElevation</documentation>
			</annotation>
			<simpleType>
				<restriction base="string">
					<enumeration value="none"/>
					<enumeration value="input"/>
					<enumeration value="output"/>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="referenceElevation" type="float" use="optional"/>
	</complexType>
	<complexType name="SampleHistoricCoefficientsComplexType">
		<attribute name="startYear" type="gYear" use="required">
			<annotation>
				<documentation>Year to start ensemble sampling.</documentation>
			</annotation>
		</attribute>
		<attribute name="ensembleSize" type="int" use="required">
			<annotation>
				<documentation>Number of ensemble members to generate</documentation>
			</annotation>
		</attribute>
	</complexType>
</schema>
