<?xml version="1.0" encoding="UTF-8"?><!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema targetNamespace="http://www.wldelft.nl/fews" xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="unreferencedNcFilesCleaner" type="fews:UnreferencedNcFilesCleanerComplexType"/>
	<!--    -->
	<complexType name="UnreferencedNcFilesCleanerComplexType">
		<sequence>
			<element name="minimalAgeNcFile" type="fews:TimeSpanComplexType">
				<annotation>
					<documentation>Minimal age of the nc files. nc file is created before the reference is added to the base. With synchronization this can even take longer.
					</documentation>
				</annotation>
			</element>
			<element name="rootDir" type="fews:NcRootDirComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>No longer used nc files in this directory are deleted. The urlPrefix is used to translate the file path to an url. Files are only deleted when at least one referenced file is found in the directory. This prevents you loose all your netcdf files on a configuration mistake.
					</documentation>
				</annotation>
			</element>

		</sequence>
	</complexType>
	<complexType name="NcRootDirComplexType">
		<attribute name="urlPrefix" type="fews:nonEmptyStringType" use="required"/>
		<attribute name="path" type="fews:directoryStringType" use="required"/>
	</complexType>

</schema>
