<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<complexType name="timeComplexType">
		<attribute name="time" type="fews:timeType" use="required"/>
	</complexType>
	<complexType name="dateTimeType">
		<attribute name="date" type="fews:dateType" use="required"/>
		<attribute name="time" type="fews:timeType" use="required"/>
	</complexType>
	<simpleType name="languageType">
		<restriction base="string">
			<enumeration value="NL"/>
			<enumeration value="EN"/>
			<enumeration value="DE"/>
			<enumeration value="FR"/>
			<enumeration value="ES"/>
			<enumeration value="ZH"/>
		</restriction>
	</simpleType>
	<complexType name="timeZoneType">
		<choice>
			<element name="offset" type="fews:timeZoneOffsetType"/>
			<element name="name" type="fews:timeZoneNameType"/>
		</choice>
	</complexType>
	<simpleType name="timeZoneOffsetType">
		<annotation>
			<documentation>Time zone type. Has following format +/-hh:mm (eg. +02:00)</documentation>
		</annotation>
		<restriction base="string">
			<pattern value="((\+|\-)([0-9]{2})(:)([0-9]{2}))|(.*[\\$|%].*)"/>
		</restriction>
	</simpleType>
	<simpleType name="timeZoneNameType">
		<restriction base="string">
			<enumeration value="GMT"/>
			<enumeration value="MIT">
				<annotation>
					<documentation>West Samoa Time, winter and summer:GMT-11</documentation>
				</annotation>
			</enumeration>
			<enumeration value="HST">
				<annotation>
					<documentation>Hawaii Standard Time, winter and summer:GMT-10</documentation>
				</annotation>
			</enumeration>
			<enumeration value="AST">
				<annotation>
					<documentation>Alaska Standard Time, winter:GMT-9 summer:GMT-8</documentation>
				</annotation>
			</enumeration>
			<enumeration value="PST">
				<annotation>
					<documentation>Pacific Standard Time, winter:GMT-8 summer:GMT-7</documentation>
				</annotation>
			</enumeration>
			<enumeration value="MST">
				<annotation>
					<documentation>Mountain Standard Time, winter and summer:GMT-7</documentation>
				</annotation>
			</enumeration>
			<enumeration value="PNT">
				<annotation>
					<documentation>Mountain Standard Time, winter and summer:GMT-7</documentation>
				</annotation>
			</enumeration>
			<enumeration value="CST">
				<annotation>
					<documentation>Central Standard Time, winter:GMT-6 summer:GMT-5</documentation>
				</annotation>
			</enumeration>
			<enumeration value="EST">
				<annotation>
					<documentation>Eastern Standard Time, winter and summer:GMT-5</documentation>
				</annotation>
			</enumeration>
			<enumeration value="IET">
				<annotation>
					<documentation>Eastern Standard Time, winter:GMT-5 summer:GMT-4</documentation>
				</annotation>
			</enumeration>
			<enumeration value="PRT">
				<annotation>
					<documentation>Atlantic Standard Time, winter and summer:GMT-4</documentation>
				</annotation>
			</enumeration>
			<enumeration value="CNT">
				<annotation>
					<documentation>Newfoundland Standard Time, winter:GMT-3:30 summer:GMT-2:30
			</documentation>
				</annotation>
			</enumeration>
			<enumeration value="AGT">
				<annotation>
					<documentation>Argentine Time, winter:GMT-3 summer:GMT-2</documentation>
				</annotation>
			</enumeration>
			<enumeration value="BET">
				<annotation>
					<documentation>Brasilia Time, winter:GMT-3 summer:GMT-2</documentation>
				</annotation>
			</enumeration>
			<enumeration value="WET">
				<annotation>
					<documentation>Western European Time, winter:GMT+0 summer:GMT+1</documentation>
				</annotation>
			</enumeration>
			<enumeration value="CET">
				<annotation>
					<documentation>Central European Time, winter:GMT+1 summer:GMT+2</documentation>
				</annotation>
			</enumeration>
			<enumeration value="MET">
				<annotation>
					<documentation>Middle Europe Time, winter:GMT+1 summer:GMT+2</documentation>
				</annotation>
			</enumeration>
			<enumeration value="CAT">
				<annotation>
					<documentation>Central African Time, winter and summer:GMT+2</documentation>
				</annotation>
			</enumeration>
			<enumeration value="EET">
				<annotation>
					<documentation>Eastern European Time, winter:GMT+2 summer:GMT+3</documentation>
				</annotation>
			</enumeration>
			<enumeration value="EAT">
				<annotation>
					<documentation>Eastern African Time, winter and summer:GMT+3</documentation>
				</annotation>
			</enumeration>
			<enumeration value="AZT">
				<annotation>
					<documentation>Azerbaijan Time, winter:GMT+4 summer:GMT+5</documentation>
				</annotation>
			</enumeration>
			<enumeration value="NET">
				<annotation>
					<documentation>Armenia Time, winter:GMT+4 summer:GMT+5</documentation>
				</annotation>
			</enumeration>
			<enumeration value="PLT">
				<annotation>
					<documentation>Pakistan Time, winter and summer:GMT+5</documentation>
				</annotation>
			</enumeration>
			<enumeration value="IST">
				<annotation>
					<documentation>India Standard Time, winter and summer:GMT+5:30</documentation>
				</annotation>
			</enumeration>
			<enumeration value="BST">
				<annotation>
					<documentation>Bangladesh Time, winter and summer:GMT+6</documentation>
				</annotation>
			</enumeration>
			<enumeration value="VST">
				<annotation>
					<documentation>Indochina Time, winter and summer:GMT+7</documentation>
				</annotation>
			</enumeration>
			<enumeration value="PRC">
				<annotation>
					<documentation>China Standard Time, winter and summer:GMT+8</documentation>
				</annotation>
			</enumeration>
			<enumeration value="JST">
				<annotation>
					<documentation>Japan Standard Time, winter and summer:GMT+9</documentation>
				</annotation>
			</enumeration>
			<enumeration value="ROK">
				<annotation>
					<documentation>Korea Standard Time, winter and summer:GMT+9</documentation>
				</annotation>
			</enumeration>
			<enumeration value="ACT">
				<annotation>
					<documentation>Central Standard Time (Northern Territory), winter and summer:GMT+9:30</documentation>
				</annotation>
			</enumeration>
			<enumeration value="AET">
				<annotation>
					<documentation>Eastern Standard Time (New South Wales), winter:GMT+10 summer:GMT+11</documentation>
				</annotation>
			</enumeration>
			<enumeration value="AWT">
				<annotation>
					<documentation>Since 2014.02. Australia Western Time, winter:GMT+8 summer:GMT+9</documentation>
				</annotation>
			</enumeration>
			<enumeration value="ACST">
				<annotation>
					<documentation>Since 2014.02. Australia Central Standard Time, winter and summer GMT+9:30</documentation>
				</annotation>
			</enumeration>
			<enumeration value="AEST">
				<annotation>
					<documentation>Since 2014.02. Australia Eastern Standard Time, winter and summer GMT+10</documentation>
				</annotation>
			</enumeration>
			<enumeration value="SST">
				<annotation>
					<documentation>Solomon Is. Time, winter and summer:GMT+11</documentation>
				</annotation>
			</enumeration>
			<enumeration value="NST">
				<annotation>
					<documentation>New Zealand Standard Time, winter:GMT+12 summer:GMT+13</documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>
	<complexType name="titleType">
		<annotation>
			<documentation>Title of story.</documentation>
		</annotation>
		<simpleContent>
			<extension base="fews:nameStringType">
				<attribute name="lang" type="fews:languageType" use="optional"/>
			</extension>
		</simpleContent>
	</complexType>
	<complexType name="fileType">
		<annotation>
			<documentation>Name of file that is executed.</documentation>
		</annotation>
		<simpleContent>
			<extension base="fews:fileStringType">
				<attribute name="lang" type="fews:languageType" use="optional"/>
			</extension>
		</simpleContent>
	</complexType>
	<complexType name="workflowType">
		<sequence>
			<element name="workflowId" type="fews:idStringType">
				<annotation>
					<documentation>Id of the Fews workflow that should be run from Watercoach</documentation>
				</annotation>
			</element>
			<element name="stateSearchPeriodStart" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>relative start of the state search period , in  time units before T0.  Cold state will be searched if  coldStateId is given, otherwise  warm state will be searched</documentation>
				</annotation>
			</element>
			<element name="coldStateId" type="fews:idStringType" minOccurs="0">
				<annotation>
					<documentation>Specify id of the cold state the workflow should start with</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="messageType">
		<annotation>
			<documentation>Message that is displayed on the screen.</documentation>
		</annotation>
		<simpleContent>
			<extension base="fews:nameStringType">
				<attribute name="lang" type="fews:languageType" use="optional"/>
			</extension>
		</simpleContent>
	</complexType>
	<complexType name="storiesType">
		<sequence>
			<element name="inbox" type="fews:inboxType" minOccurs="0">
				<annotation>
					<documentation>Inbox actions.</documentation>
				</annotation>
			</element>
			<element name="story" type="fews:storyType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>List of stories.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="frameType">
		<sequence>
			<element name="title" type="fews:titleType" maxOccurs="unbounded">
				<annotation>
					<documentation>Title of frame.</documentation>
				</annotation>
			</element>
			<element name="start" type="fews:dateTimeType" minOccurs="0">
				<annotation>
					<documentation>Date/time at which event is available/executed. If not specified, this time is set to the start time of the script.</documentation>
				</annotation>
			</element>
			<element name="stop" type="fews:dateTimeType" minOccurs="0">
				<annotation>
					<documentation>Date/time after which event is no more available. If not specified, this time is set to the end time of the script.</documentation>
				</annotation>
			</element>
			<element name="popup" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether a pop-up window is shown to draw attention to the event.</documentation>
				</annotation>
			</element>
			<element name="requiredExperienceLevel" type="int" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Specify all experience levels (defined in WatercoachDisplay.xml) for which a frame should be created. Refer the levels using the order of the level in the list, for example 0,1,2. If no experience levels are defined, the frame will be created for all. If some experience levels are defined, the frame will be created only for these levels</documentation>
				</annotation>
			</element>
			<element name="once" type="boolean" minOccurs="0">
				<annotation>
					<documentation>Indicates whether an event must be executed only once in a time frame.</documentation>
				</annotation>
			</element>
			<!-- 			<element name="delay" type="timeComplexType" minOccurs="0">-->
			<!-- 				<annotation>-->
			<!-- 					<documentation>Delay for an event after it has been activated.</documentation>-->
			<!-- 				</annotation>-->
			<!-- 			</element>-->
			<element name="condition" type="fews:conditionType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Event is available/executed if condition is satisfied.</documentation>
				</annotation>
			</element>
			<element name="file" type="fews:fileType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Name of file that is executed.</documentation>
				</annotation>
			</element>
			<element name="workflow" type="fews:workflowType" minOccurs="0">
				<annotation>
					<documentation>Fews workflow that should be started from Watercoach </documentation>
				</annotation>
			</element>
			<element name="message" type="fews:messageType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>A message that is displayed on the screen.</documentation>
				</annotation>
			</element>
			<!-- 			<element name="newTime" type="fews:dateTimeType">-->
			<!-- 				<annotation>-->
			<!-- 					<documentation>Set simulation time to the specified time.</documentation>-->
			<!-- 				</annotation>-->
			<!-- 			</element>-->
		</sequence>
		<attribute name="color" type="fews:colorStringType">
			<annotation>
				<documentation>Used  to color  the frame in ScriptDisplay. If not specified, the story color is used (if any)</documentation>
			</annotation>
		</attribute>
	</complexType>
	<simpleType name="operatorForIntegerType">
		<restriction base="string">
			<enumeration value="lt"/>
			<enumeration value="le"/>
			<enumeration value="gt"/>
			<enumeration value="ge"/>
			<enumeration value="eq"/>
			<enumeration value="ne"/>
		</restriction>
	</simpleType>
	<simpleType name="operatorForDateTimeType">
		<restriction base="string">
			<enumeration value="before"/>
			<enumeration value="after"/>
		</restriction>
	</simpleType>
	<simpleType name="operatorForBooleanType">
		<restriction base="string">
			<enumeration value="eq"/>
			<enumeration value="ne"/>
		</restriction>
	</simpleType>
	<simpleType name="forecastTableColumnTypeType">
		<restriction base="string">
			<enumeration value="string"/>
			<enumeration value="integer"/>
			<enumeration value="float"/>
			<enumeration value="boolean"/>
			<enumeration value="dateTime"/>
		</restriction>
	</simpleType>
	<complexType name="forecastValueType">
		<sequence>
			<element name="operator" type="fews:operatorForIntegerType">
				<annotation>
					<documentation>Operator for condition based on integer value.</documentation>
				</annotation>
			</element>
			<element name="value" type="int">
				<annotation>
					<documentation>Integer value for condition.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="forecastPublicationTimeType">
		<sequence>
			<element name="operator" type="fews:operatorForDateTimeType">
				<annotation>
					<documentation>Operator for condition based on date/time.</documentation>
				</annotation>
			</element>
			<element name="value" type="fews:dateTimeType">
				<annotation>
					<documentation>Date/time value for condition.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="forecastPublishedType">
		<sequence>
			<element name="operator" type="fews:operatorForBooleanType">
				<annotation>
					<documentation>Operator for condition based on boolean.</documentation>
				</annotation>
			</element>
			<element name="value" type="boolean">
				<annotation>
					<documentation>Boolean value for condition.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="conditionType">
		<sequence>
			<element name="columnId" type="string"/>
			<element name="rowId" type="string"/>
			<choice>
				<annotation>
					<documentation>Condition based on either the forecast value, the forecast publication time, or the presence of a forecast.</documentation>
				</annotation>
				<element name="ifForecastValue" type="fews:forecastValueType"/>
				<element name="ifForecastPublicationTime" type="fews:forecastPublicationTimeType"/>
				<element name="ifForecastPublished" type="fews:forecastPublishedType"/>
			</choice>
		</sequence>
	</complexType>
	<complexType name="storyType">
		<sequence>
			<element name="title" type="fews:titleType" maxOccurs="unbounded">
				<annotation>
					<documentation>Title of story.</documentation>
				</annotation>
			</element>
			<element name="frame" type="fews:frameType" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of time frame.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="color" type="fews:colorStringType">
			<annotation>
				<documentation>Default frame color. Used to color  the frame in ScriptDisplay</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="inboxType">
		<sequence>
			<element name="title" type="fews:titleType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Title of inbox.</documentation>
				</annotation>
			</element>
			<element name="frame" type="fews:frameType" maxOccurs="unbounded">
				<annotation>
					<documentation>Definition of time frame.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="color" type="fews:colorStringType">
			<annotation>
				<documentation>Default frame color. Used to color  the frame in ScriptDisplay</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="forecastTableColumnType">
		<annotation>
			<documentation>An entry in the header of the forecast table.</documentation>
		</annotation>
		<simpleContent>
			<extension base="fews:nameStringType">
				<attribute name="id" type="string" use="required"/>
				<attribute name="type" type="fews:forecastTableColumnTypeType" use="optional" default="integer"/>
				<attribute name="unit" type="string" use="optional"/>
				<attribute name="isEditable" type="boolean" use="optional"/>
				<attribute name="isExport" type="boolean" use="optional"/>
				<attribute name="exportName" type="string" use="optional"/>
				<attribute name="lang" type="fews:languageType" use="optional"/>
			</extension>
		</simpleContent>
	</complexType>
	<complexType name="forecastTableCellType">
		<annotation>
			<documentation>An entry in a row of the forecast table.</documentation>
		</annotation>
		<simpleContent>
			<extension base="fews:nameStringType">
				<attribute name="columnId" type="string" use="required"/>
				<attribute name="lang" type="fews:languageType" use="optional"/>
			</extension>
		</simpleContent>
	</complexType>
	<complexType name="forecastTableHeaderType">
		<annotation>
			<documentation>The header in the forecast table.</documentation>
		</annotation>
		<sequence>
			<element name="column" type="fews:forecastTableColumnType" maxOccurs="unbounded">
				<annotation>
					<documentation>An entry in the header of the forecast table.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="forecastTableRowType">
		<annotation>
			<documentation>A row in the forecast table.</documentation>
		</annotation>
		<sequence>
			<element name="cell" type="fews:forecastTableCellType" maxOccurs="unbounded">
				<annotation>
					<documentation>An entry in a row of the forecast table.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:nameStringType" use="required"/>
	</complexType>
	<complexType name="forecastTableType">
		<sequence>
			<element name="header" type="fews:forecastTableHeaderType">
				<annotation>
					<documentation>Header specification of forecast table.</documentation>
				</annotation>
			</element>
			<element name="row" type="fews:forecastTableRowType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Specification of a row in the forecast table.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="forecastNoteType">
		<annotation>
			<documentation>Initial text of the forecast note message box.</documentation>
		</annotation>
		<sequence>
			<element name="initialText" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<simpleContent>
						<extension base="string">
							<attribute name="lang" type="fews:languageType">
								<annotation>
									<documentation>Language associated with the initial text.</documentation>
								</annotation>
							</attribute>
						</extension>
					</simpleContent>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<complexType name="dictionaryFilesType">
		<sequence>
			<element name="dictionaryFile" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Dictionary file.</documentation>
				</annotation>
				<complexType>
					<simpleContent>
						<extension base="string">
							<attribute name="lang" type="fews:languageType">
								<annotation>
									<documentation>Language associated with the dictionary file.</documentation>
								</annotation>
							</attribute>
						</extension>
					</simpleContent>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<complexType name="scriptType">
		<sequence>
			<element name="title" type="string" minOccurs="0">
				<annotation>
					<documentation>Title of script (optional).</documentation>
				</annotation>
			</element>
			<element name="timeZone" type="fews:timeZoneType" minOccurs="0">
				<annotation>
					<documentation>Time zone (default is GMT).</documentation>
				</annotation>
			</element>
			<element name="dataStart" type="fews:dateTimeType">
				<annotation>
					<documentation>Begin date/time of data.</documentation>
				</annotation>
			</element>
			<element name="dataStop" type="fews:dateTimeType" minOccurs="0">
				<annotation>
					<documentation>End date/time of data (defaults to 1 day after dataStart).</documentation>
				</annotation>
			</element>
			<element name="displayStart" type="fews:dateTimeType" minOccurs="0">
				<annotation>
					<documentation>Start date/time that is displayed in Water Coach and FEWS (equal to dataStart if not specified).</documentation>
				</annotation>
			</element>
			<element name="scriptStart" type="fews:dateTimeType" minOccurs="0">
				<annotation>
					<documentation>Begin date/time of script (deprecated; use displayStart instead).</documentation>
				</annotation>
			</element>
			<element name="scriptStop" type="fews:dateTimeType" minOccurs="0">
				<annotation>
					<documentation>End date/time of script (deprecated; use dataStart and dataStop for specifying the length of the script).</documentation>
				</annotation>
			</element>
			<choice minOccurs="0">
				<element name="stories" type="fews:storiesType">
					<annotation>
						<documentation>List of stories for script.</documentation>
					</annotation>
				</element>
				<element name="workflow" type="fews:scheduledWorkflowComplexType" maxOccurs="unbounded">
					<annotation>
						<documentation>List of workflows to launch  in configured intervals</documentation>
					</annotation>
				</element>
			</choice>
			<element name="forecastTable" type="fews:forecastTableType" minOccurs="0">
				<annotation>
					<documentation>Specification of forecast table.</documentation>
				</annotation>
			</element>
			<element name="forecastNote" type="fews:forecastNoteType" minOccurs="0">
				<annotation>
					<documentation>Specification of the initial note text accompanying published forecast.</documentation>
				</annotation>
			</element>
			<element name="dictionaryFiles" type="fews:dictionaryFilesType" minOccurs="0">
				<annotation>
					<documentation>Specification of dictionary files.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="scheduledWorkflowComplexType">
		<complexContent>
			<extension base="fews:workflowType">
				<sequence>
					<element name="schedulingStart" type="fews:dateTimeType" minOccurs="0">
						<annotation>
							<documentation>Scheduling start should be configured relative to displayStart</documentation>
						</annotation>
					</element>
					<element name="schedulingInterval" type="fews:TimeSpanComplexType">
						<annotation>
							<documentation>Repetition frequency the workflow  will be launched by the script</documentation>
						</annotation>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<element name="script" type="fews:scriptType"/>
</schema>
