<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by WL | Delft Hydraulics (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<element name="webService" type="fews:WebServiceComplexType">
		<annotation>
			<documentation>LEGACY, NO LONGER USED</documentation>
		</annotation>
	</element>

	<complexType name="WebServiceComplexType">
		<sequence>
			<element name="port" type="nonNegativeInteger">
				<annotation>
					<documentation>A port number (above 1000) that is reachable by the client (firewall) and not in use by another 
                        service that is running on the machine were the OC or SA with embedded web service is running
                    </documentation>
				</annotation>
			</element>
			<element name="timeOutSeconds" type="nonNegativeInteger">
				<annotation>
					<documentation>When the workflow is not finished within this time an exception is thrown to prevent the web service
                        client is waiting forever.
                    </documentation>
				</annotation>
			</element>
			<element name="inputPiTimeSeriesFile" type="fews:fileStringType">
				<annotation>
					<documentation>The received time series by the web service are written to this file.
                        This file should be imported during the workflow. When the web service is running in a OC the file should be written
                        to a location that is reachable by the FS and the OC
                    </documentation>
				</annotation>
			</element>
			<element name="outputPiTimeSeriesFile" type="fews:fileStringType" maxOccurs="unbounded">
				<annotation>
					<documentation>A returned time series by the web service are read from this file.
                        This file should be written during the workflow. When the web service is running in a OC the
                        file should be written
                        to a location that is reachable by the FS and the OC
                        The parameter locations combinations should be unique among all output files 
                    </documentation>
				</annotation>
			</element>
			<element name="mcTaskWebService" type="fews:MCTaskWebServiceComplexType" minOccurs="0">
				<annotation>
					<documentation>Configuration for the MCTaskWebService, if that is used to create and run the one-off task.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="MCTaskWebServiceComplexType">
		<sequence>
			<element name="hostname" type="fews:nameStringType">
				<annotation>
					<documentation>The hostname where the MasterController is running its MCTaskWebService. Can be localhost.
					</documentation>
				</annotation>
			</element>
			<element name="port" type="nonNegativeInteger">
				<annotation>
					<documentation>The port number the MasterController MCTaskWebService is listening to.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
