<?xml version="1.0" encoding="UTF-8"?>
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns:fews="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="taskProperties.xsd"/>
	<include schemaLocation="transformationSets.xsd"/>
	<element name="whatIfScenario" type="fews:WhatIfScenarioDefinitionComplexType"/>
	<group name="WhatIfScenarioGroup">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="properties" type="fews:PropertiesComplexType" minOccurs="0">
				<annotation>
					<documentation>Since 2015.02. Optional. One or more properties that should be replaced in this what-if scenario. This only supports properties that can be referenced in nested workflow files and module config files between $ signs (e.g. $key$). The values of these properties will be replaced with the values specified here. The property $MODULE_INSTANCE_ID$ is added automatically and should not be replaced in a what-if scenario.</documentation>
				</annotation>
			</element>
			<element name="transformationSets" type="fews:TransformationSetsComplexType" minOccurs="0"/>
			<element name="configFiles" type="fews:ConfigComplexType" minOccurs="0"/>
			<element name="locationSelection" type="fews:LocationSelectionComplexType" minOccurs="0">
				<annotation>
					<documentation>Selection of location ids to be used in the General Adapter so that the model only exports data for this selection or a polygon mask based on this selection. This can be used in combination with a exportPlaceholderFile in the importActivities, or a exportLocationAreaActivity.</documentation>
				</annotation>
			</element>
			<element name="polygonSelection" type="fews:PolygonSelectionComplexType" minOccurs="0">
				<annotation>
					<documentation>Polygon to be exported by the General Adapter as a mask so that the model only exports data for this selection. Used in combination with the ExportAreaSelectionActivity.</documentation>
				</annotation>
			</element>
			<element name="isPersistent" type="boolean" default="false" minOccurs="0"/>
			<element name="isVisible" type="boolean" default="true" minOccurs="0"/>
			<element name="isPendingDeletion" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>Pending for deletion, should be automatically set for one-off tasks.</documentation>
				</annotation>
			</element>
			<element name="workflowId" type="string" minOccurs="0"/>
			<element name="visibilityEndTime" type="fews:DateTimeComplexType" minOccurs="0">
				<annotation>
					<documentation>When expired, the scenario becomes automatically invisible in the ManualForecastDialog.</documentation>
				</annotation>
			</element>
		</sequence>
	</group>
	<complexType name="WhatIfScenarioDefinitionComplexType">
		<group ref="fews:WhatIfScenarioGroup"/>
		<attribute name="version" type="fews:versionStringType" use="required" fixed="1.1"/>
		<attribute name="id" type="fews:idStringType" use="required"/>
		<attribute name="name" type="fews:idStringType" use="required"/>
	</complexType>
	<complexType name="ConfigComplexType">
		<sequence>
			<element name="moduleParameterFiles" type="fews:ModuleParameterFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>The module instance parameter files used.</documentation>
				</annotation>
			</element>
			<element name="moduleDataSetFiles" type="fews:ModuleDataSetFilesComplexType" minOccurs="0">
				<annotation>
					<documentation>The module data set files used.</documentation>
				</annotation>
			</element>
			<element name="hideModuleDataSetFilesPanel" type="fews:emptyElement" minOccurs="0">
				<annotation>
					<documentation>If this optional element is selected, the tab in the GUI which allows the user to create a what-if for moduledatasetfiles will be hidden</documentation>
				</annotation>
			</element>
			<element name="moduleParameters" type="fews:ModuleParametersComplexType" minOccurs="0">
				<annotation>
					<documentation>The module instance parameters in xml format. This element contains the same information stored in a moduleParameterFile</documentation>
				</annotation>
			</element>
			<element name="hideModuleParameterFilesPanel" type="fews:emptyElement" minOccurs="0">
				<annotation>
					<documentation>If this optional element is selected, the tab in the GUI which allows the user to create a what-if for moduleparameterfiles will be hidden</documentation>
				</annotation>
			</element>
			<element name="piModelParametersContent" type="string" minOccurs="0">
				<annotation>
					<documentation>Since 2015.01. Enter content of a PI_ModelParameter XML file as string object. On execution in General Adapter this content will we written to file without further processing</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ModuleParametersComplexType">
		<sequence>
			<element name="description" type="string" minOccurs="0"/>
			<element name="param" type="fews:ModuleParameterComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Any number of parameters > 0</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Id of moduleInstance for which these parameters are implemented
</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="ModuleParameterComplexType">
		<sequence>
			<element name="name" type="fews:nameStringType">
				<annotation>
					<documentation>name of the parameter</documentation>
				</annotation>
			</element>
			<element name="data" type="fews:ModuleParameterDataComplexType">
				<annotation>
					<documentation>Actual value/content of the parameter.
                        Four data types can be used.</documentation>
				</annotation>
			</element>
			<element name="comment" type="string" minOccurs="0">
				<annotation>
					<documentation>use this field as a notebook to add comments, suggestions
                        description of data entered etc.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="optional"/>
	</complexType>
	<complexType name="ModuleParameterDataComplexType">
		<choice>
			<element name="booleanData">
				<complexType>
					<simpleContent>
						<extension base="boolean">
							<attribute name="allowAdjust" type="boolean" use="optional" default="0">
								<annotation>
									<documentation>if this is set to true the NFFS is allowed to adjust
                                        this parameter.</documentation>
								</annotation>
							</attribute>
						</extension>
					</simpleContent>
				</complexType>
			</element>
			<element name="doubleData">
				<complexType>
					<simpleContent>
						<extension base="double">
							<attribute name="maxVal" type="double" use="required">
								<annotation>
									<documentation>maximum value allowed for this parameter</documentation>
								</annotation>
							</attribute>
							<attribute name="minVal" type="double" use="required">
								<annotation>
									<documentation>minimum value allowed for this parameter</documentation>
								</annotation>
							</attribute>
							<attribute name="allowAdjust" type="boolean" use="optional" default="0">
								<annotation>
									<documentation>if this is set to true the NFFS is allowed to adjust
                                        this parameter.</documentation>
								</annotation>
							</attribute>
							<attribute name="stepSize" type="double" use="optional">
								<annotation>
									<documentation>Optional step size hint for model calibration.
                                        Only used if allowAdjust = 1</documentation>
								</annotation>
							</attribute>
						</extension>
					</simpleContent>
				</complexType>
			</element>
			<element name="intData">
				<complexType>
					<simpleContent>
						<extension base="int">
							<attribute name="maxVal" type="int" use="required">
								<annotation>
									<documentation>maximum value allowed for this parameter</documentation>
								</annotation>
							</attribute>
							<attribute name="minVal" type="int" use="required">
								<annotation>
									<documentation>minimum value allowed for this parameter</documentation>
								</annotation>
							</attribute>
							<attribute name="allowAdjust" type="boolean" use="optional" default="0">
								<annotation>
									<documentation>if this is set to true the NFFS is allowed to adjust
                                        this parameter.</documentation>
								</annotation>
							</attribute>
							<attribute name="stepSize" type="int" use="optional">
								<annotation>
									<documentation>Optional step size hint for model calibration.
                                        Only used if allowAdjust = 1</documentation>
								</annotation>
							</attribute>
						</extension>
					</simpleContent>
				</complexType>
			</element>
			<element name="stringData" type="string"/>
		</choice>
	</complexType>
	<complexType name="LocationSelectionComplexType">
		<sequence>
			<element name="locationId" type="fews:idStringType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Series of location identifiers, can be used to restrict output of some exports in the general adapter.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="PolygonSelectionComplexType">
		<sequence>
			<element name="areaSelectionShapeFileBase64" type="string" minOccurs="0">
				<annotation>
					<documentation>Base64 encoded .shp file that can be used as input for the ExportAreaSelectionActivity of the general adapter.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
