<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Frederik van den Broek (WL|Delft Hydraulics) -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by rooij_e (WL | Delft Hydraulics) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<!-- moduleRun -->
	<element name="workflowLoopRunner" type="fews:WorkflowLoopRunnerComplexType">
		<annotation>
			<documentation>
                This module is used to loop over a configured workflow. Looping is controlled by the configuration options</documentation>
		</annotation>
	</element>
	<complexType name="WorkflowLoopRunnerComplexType">
		<sequence>
			<element name="workflowId" type="fews:idStringType">
				<annotation>
					<documentation>Id of workflow that is to be run in loop.</documentation>
				</annotation>
			</element>
			<element name="runPeriodOptions" type="fews:RunPeriodOptionsComplexType" minOccurs="0">
				<annotation>
					<documentation>Set of options to determine exactly how the workflow is rerun.</documentation>
				</annotation>
			</element>
			<element name="triggerOptions" type="fews:TriggerOptionsComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Define trigger that will provide the run periods. Multiple triggerOptions can return more run periods. When run periods overlap they will be combined.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="RunPeriodOptionsComplexType">
		<attribute name="alwaysFullPeriod" type="boolean" use="optional" default="false"/>
	</complexType>
	<complexType name="TriggerOptionsComplexType">
		<choice>
			<element name="valueTrigger" type="fews:ValueTriggerComplexType"/>
			<element name="stepValueTrigger" type="fews:StepValueTriggerComplexType"/>
		</choice>
	</complexType>
	<complexType name="ValueTriggerComplexType">
		<annotation>
			<documentation>Search for multiple trigger periods using a trigger value.</documentation>
		</annotation>
		<sequence>
			<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType"/>
			<element name="valueOption" type="fews:valueTriggerEnumStringType"/>
			<element name="value" type="float">
				<annotation>
					<documentation>Trigger value for the time series array</documentation>
				</annotation>
			</element>
			<element name="relativeRunWindow" type="fews:RelativePeriodComplexType">
				<annotation>
					<documentation>Lead- and end time to add to each trigger period.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="StepValueTriggerComplexType">
		<annotation>
			<documentation>Search for single trigger period within each step. Use the stepValueOptions to define how to search.</documentation>
		</annotation>
		<sequence>
			<element name="timeSeriesSet" type="fews:TimeSeriesSetComplexType"/>
			<element name="stepValueOption" type="fews:stepValueTriggerEnumStringType"/>
			<element name="stepSize" type="fews:TimeStepComplexType">
				<annotation>
					<documentation>Trigger value for the time series array</documentation>
				</annotation>
			</element>
			<element name="relativeRunWindow" type="fews:RelativePeriodComplexType">
				<annotation>
					<documentation>Lead- and end time to add to each trigger period.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="valueTriggerEnumStringType">
		<annotation>
			<documentation>Configure direction in which trigger is activated.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="above"/>
			<enumeration value="below"/>
		</restriction>
	</simpleType>
	<simpleType name="stepValueTriggerEnumStringType">
		<restriction base="string">
			<enumeration value="maximum"/>
			<enumeration value="minimum"/>
		</restriction>
	</simpleType>
</schema>
