"""Generator registry.

`SPECS` is the authoritative list of FEWS file types this pipeline can
produce. Each spec binds an input-JSON key, a Pydantic model, a Jinja
template, the generator callable, and the output path relative to
`examples/generated-config-tutorial/`.

Adding a new file type = append a spec here.
"""
from __future__ import annotations

from pathlib import Path

from fews_agent.schema import (
    ForecastLengthEstimator,
    ForecasterNotesDisplay,
    GeneralAdapterRun,
    GenericXmlFile,
    IdMap,
    LocationIcons,
    Locations,
    ManualForecastDisplay,
    ModifierDisplay,
    ModifierTypes,
    ModuleInstanceDescriptors,
    ModuleInstanceSets,
    ModuleParameters,
    Parameters,
    Permissions,
    Qualifiers,
    ThresholdGroups,
    ThresholdValueSets,
    ThresholdWarningLevels,
    TimeSeriesDisplay,
    TimeSeriesImportRun,
    TimeSteps,
    Topology,
    TransformationModule,
    UnitConversions,
    UserGroups,
    ValidationRuleSets,
    Workflow,
    WorkflowDescriptors,
)

from . import (
    forecast_length_estimator,
    forecaster_notes_display,
    general_adapter_run,
    generic_xml_file,
    location_icons,
    module_instance_descriptors,
    time_series_display_config,
    time_steps,
    workflow_descriptors,
    id_map,
    import_module,
    locations,
    manual_forecast_display,
    modifier_display,
    modifier_types,
    module_instance_sets,
    module_parameters,
    parameters,
    permissions,
    qualifiers,
    threshold_value_sets,
    threshold_warning_levels,
    thresholds,
    topology,
    transformation_module,
    unit_conversions,
    user_groups,
    validation_rule_sets,
    workflow,
)
from .base import GeneratorSpec

SPECS: list[GeneratorSpec] = [
    GeneratorSpec(
        name="locations",
        input_key="locations",
        model_class=Locations,
        template_name="locations.xml.j2",
        generate=locations.generate,
        output_relpath=Path("RegionConfigFiles/Locations.xml"),
    ),
    GeneratorSpec(
        name="parameters",
        input_key="parameters",
        model_class=Parameters,
        template_name="parameters.xml.j2",
        generate=parameters.generate,
        output_relpath=Path("RegionConfigFiles/Parameters.xml"),
    ),
    GeneratorSpec(
        name="qualifiers",
        input_key="qualifiers",
        model_class=Qualifiers,
        template_name="qualifiers.xml.j2",
        generate=qualifiers.generate,
        output_relpath=Path("RegionConfigFiles/Qualifiers.xml"),
    ),
    GeneratorSpec(
        name="thresholdWarningLevels",
        input_key="thresholdWarningLevels",
        model_class=ThresholdWarningLevels,
        template_name="threshold_warning_levels.xml.j2",
        generate=threshold_warning_levels.generate,
        output_relpath=Path("RegionConfigFiles/ThresholdWarningLevels.xml"),
    ),
    GeneratorSpec(
        name="moduleInstanceSets",
        input_key="moduleInstanceSets",
        model_class=ModuleInstanceSets,
        template_name="module_instance_sets.xml.j2",
        generate=module_instance_sets.generate,
        output_relpath=Path("RegionConfigFiles/ModuleInstanceSets.xml"),
    ),
    GeneratorSpec(
        name="permissions",
        input_key="permissions",
        model_class=Permissions,
        template_name="permissions.xml.j2",
        generate=permissions.generate,
        output_relpath=Path("SystemConfigFiles/Permissions.xml"),
    ),
    GeneratorSpec(
        name="importUnitConversions",
        input_key="importUnitConversions",
        model_class=UnitConversions,
        template_name="unit_conversions.xml.j2",
        generate=unit_conversions.generate,
        output_relpath=Path("UnitConversionsFiles/ImportUnitConversions.xml"),
    ),
    GeneratorSpec(
        name="exportUnitConversions",
        input_key="exportUnitConversions",
        model_class=UnitConversions,
        template_name="unit_conversions.xml.j2",
        generate=unit_conversions.generate,
        output_relpath=Path("UnitConversionsFiles/ExportUnitConversions.xml"),
    ),
    GeneratorSpec(
        name="exportRaven",
        input_key="exportRaven",
        model_class=UnitConversions,
        template_name="unit_conversions.xml.j2",
        generate=unit_conversions.generate,
        output_relpath=Path("UnitConversionsFiles/ExportRaven.xml"),
    ),
    GeneratorSpec(
        name="thresholds",
        input_key="thresholds",
        model_class=ThresholdGroups,
        template_name="thresholds.xml.j2",
        generate=thresholds.generate,
        output_relpath=Path("RegionConfigFiles/Thresholds.xml"),
    ),
    GeneratorSpec(
        name="userGroups",
        input_key="userGroups",
        model_class=UserGroups,
        template_name="user_groups.xml.j2",
        generate=user_groups.generate,
        output_relpath=Path("SystemConfigFiles/UserGroups.xml"),
    ),
    GeneratorSpec(
        name="manualForecastDisplay",
        input_key="manualForecastDisplay",
        model_class=ManualForecastDisplay,
        template_name="manual_forecast_display.xml.j2",
        generate=manual_forecast_display.generate,
        output_relpath=Path("DisplayConfigFiles/ManualForecastDisplay.xml"),
    ),
    GeneratorSpec(
        name="forecasterNotesDisplay",
        input_key="forecasterNotesDisplay",
        model_class=ForecasterNotesDisplay,
        template_name="forecaster_notes_display.xml.j2",
        generate=forecaster_notes_display.generate,
        output_relpath=Path("DisplayConfigFiles/ForecasterNotesDisplay.xml"),
    ),
    GeneratorSpec(
        name="modifierDisplay",
        input_key="modifierDisplay",
        model_class=ModifierDisplay,
        template_name="modifier_display.xml.j2",
        generate=modifier_display.generate,
        output_relpath=Path("DisplayConfigFiles/ModifiersDisplay.xml"),
    ),
    GeneratorSpec(
        name="thresholdValueSets",
        input_key="thresholdValueSets",
        model_class=ThresholdValueSets,
        template_name="threshold_value_sets.xml.j2",
        generate=threshold_value_sets.generate,
        output_relpath=Path("RegionConfigFiles/ThresholdValueSets.xml"),
    ),
    GeneratorSpec(
        name="validationRuleSets",
        input_key="validationRuleSets",
        model_class=ValidationRuleSets,
        template_name="validation_rule_sets.xml.j2",
        generate=validation_rule_sets.generate,
        output_relpath=Path("RegionConfigFiles/ValidationRuleSets.xml"),
    ),
    GeneratorSpec(
        name="modifierTypes",
        input_key="modifierTypes",
        model_class=ModifierTypes,
        template_name="modifier_types.xml.j2",
        generate=modifier_types.generate,
        output_relpath=Path("RegionConfigFiles/ModifierTypes.xml"),
    ),
    GeneratorSpec(
        name="topology",
        input_key="topology",
        model_class=Topology,
        template_name="topology.xml.j2",
        generate=topology.generate,
        output_relpath=Path("RegionConfigFiles/Topology.xml"),
    ),
    GeneratorSpec(
        name="ravenParameters",
        input_key="ravenParameters",
        model_class=ModuleParameters,
        template_name="module_parameters.xml.j2",
        generate=module_parameters.generate,
        output_relpath=Path("ModuleParFiles/RavenParameters.xml"),
    ),
    # Workflow — all 37 tutorial files share one generator + template.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=Workflow,
            template_name="workflow.xml.j2",
            generate=workflow.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("importE2OGridsWorkflow",        "WorkflowFiles/Import/Earth2Observe/ImportE2OGrids.xml"),
            ("importEOGridsWorkflow",         "WorkflowFiles/Import/EarthObservation/ImportEOGrids.xml"),
            ("importGDPSGridsWorkflow",       "WorkflowFiles/Import/ECCCGrids/ImportGDPSGrids.xml"),
            ("importHRDPAGridsWorkflow",      "WorkflowFiles/Import/ECCCGrids/ImportHRDPAGrids.xml"),
            ("importHRDPSGridsWorkflow",      "WorkflowFiles/Import/ECCCGrids/ImportHRDPSGrids.xml"),
            ("importRDPAGridsWorkflow",       "WorkflowFiles/Import/ECCCGrids/ImportRDPAGrids.xml"),
            ("importRDPSGridsWorkflow",       "WorkflowFiles/Import/ECCCGrids/ImportRDPSGrids.xml"),
            ("importREPSGridsWorkflow",       "WorkflowFiles/Import/ECCCGrids/ImportREPSGrids.xml"),
            ("importECCCScalarWorkflow",      "WorkflowFiles/Import/ECCCScalar/ImportECCCScalar.xml"),
            ("importWSCDailyWorkflow",        "WorkflowFiles/Import/ECCCScalar/ImportWSCDaily.xml"),
            ("importWSCHistoricWorkflow",     "WorkflowFiles/Import/ECCCScalar/ImportWSCHistoric.xml"),
            ("importWSCHourlyWorkflow",       "WorkflowFiles/Import/ECCCScalar/ImportWSCHourly.xml"),
            ("importGFSGridsWorkflow",        "WorkflowFiles/Import/NOAA/ImportGFSGrids.xml"),
            ("importNAMGridsWorkflow",        "WorkflowFiles/Import/NOAA/ImportNAMGrids.xml"),
            ("importNOAAGridsWorkflow",       "WorkflowFiles/Import/NOAA/ImportNOAAGrids.xml"),
            ("importSREFGridsWorkflow",       "WorkflowFiles/Import/NOAA/ImportSREFGrids.xml"),
            ("importGLOBSNOWGridsWorkflow",   "WorkflowFiles/Import/Snow/ImportGLOBSNOWGrids.xml"),
            ("importSNODASGridsWorkflow",     "WorkflowFiles/Import/Snow/ImportSNODASGrids.xml"),
            ("runLiardGDPSForecastWorkflow",  "WorkflowFiles/ModelRun/Liard/RunLiardGDPSForecast.xml"),
            ("runLiardHistoricWorkflow",      "WorkflowFiles/ModelRun/Liard/RunLiardHistoric.xml"),
            ("runLiardRDPSForecastWorkflow",  "WorkflowFiles/ModelRun/Liard/RunLiardRDPSForecast.xml"),
            ("runLiardREPSForecastWorkflow",  "WorkflowFiles/ModelRun/Liard/RunLiardREPSForecast.xml"),
            ("runSnareGDPSForecastWorkflow",  "WorkflowFiles/ModelRun/Snare/RunSnareGDPSForecast.xml"),
            ("runSnareHistoricWorkflow",      "WorkflowFiles/ModelRun/Snare/RunSnareHistoric.xml"),
            ("runSnareRDPSForecastWorkflow",  "WorkflowFiles/ModelRun/Snare/RunSnareRDPSForecast.xml"),
            ("runSnareREPSForecastWorkflow",  "WorkflowFiles/ModelRun/Snare/RunSnareREPSForecast.xml"),
            ("preprocessE2OLiardWorkflow",    "WorkflowFiles/Preprocess/Liard/PreprocessE2OLiard.xml"),
            ("preprocessGDPSLiardWorkflow",   "WorkflowFiles/Preprocess/Liard/PreprocessGDPSLiard.xml"),
            ("preprocessRDPSLiardWorkflow",   "WorkflowFiles/Preprocess/Liard/PreprocessRDPSLiard.xml"),
            ("preprocessREPSLiardWorkflow",   "WorkflowFiles/Preprocess/Liard/PreprocessREPSLiard.xml"),
            ("mergeHistoricGridsWorkflow",    "WorkflowFiles/Preprocess/MergeHistoricGrids.xml"),
            ("modifyForecastGridsWorkflow",   "WorkflowFiles/Preprocess/ModifyForecastGrids.xml"),
            ("preprocessE2OSnareWorkflow",    "WorkflowFiles/Preprocess/Snare/PreprocessE2OSnare.xml"),
            ("preprocessGDPSSnareWorkflow",   "WorkflowFiles/Preprocess/Snare/PreprocessGDPSSnare.xml"),
            ("preprocessRDPSSnareWorkflow",   "WorkflowFiles/Preprocess/Snare/PreprocessRDPSSnare.xml"),
            ("preprocessREPSSnareWorkflow",   "WorkflowFiles/Preprocess/Snare/PreprocessREPSSnare.xml"),
            ("updateHistoricGridsWorkflow",   "WorkflowFiles/Preprocess/UpdateHistoricGrids.xml"),
        ]
    ],
    # IdMap — shared generator across 14 tutorial files, one spec per file.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=IdMap,
            template_name="id_map.xml.j2",
            generate=id_map.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("idImportECCCScalar",  "IdMapFiles/ECCC/IdImportECCCScalar.xml"),
            ("idImportCanadaWCS",   "IdMapFiles/ECCC/IdImportCanadaWCS.xml"),
            ("idImportWSC",         "IdMapFiles/ECCC/IdImportWSC.xml"),
            ("idImportGFS",         "IdMapFiles/NOAA/IdImportGFS.xml"),
            ("idImportNAM",         "IdMapFiles/NOAA/IdImportNAM.xml"),
            ("idImportRaven",       "IdMapFiles/Model/IdImportRaven.xml"),
            ("idExportRaven",       "IdMapFiles/Model/IdExportRaven.xml"),
            ("idImportwflow",       "IdMapFiles/Model/IdImportwflow.xml"),
            ("idExportwflow",       "IdMapFiles/Model/IdExportwflow.xml"),
            ("idImportE2O",         "IdMapFiles/SpecialImport/IdImportE2O.xml"),
            ("idImportGLOBSNOW",    "IdMapFiles/SpecialImport/IdImportGLOBSNOW.xml"),
            ("idImportGPM",         "IdMapFiles/SpecialImport/IdImportGPM.xml"),
            ("idImportGSMAP",       "IdMapFiles/SpecialImport/IdImportGSMAP.xml"),
            ("idImportSNODAS",      "IdMapFiles/SpecialImport/IdImportSNODAS.xml"),
        ]
    ],
    # Import modules — 11 of 16 tutorial files. Deferred: WSCDaily/WSCHourly
    # (need <table>+<tolerance>+skipFirstLinesCount), GPM/GSMAP/GLOBSNOW
    # (need <fileNameDateTimeFilter>+fileNameObservationDateTimePattern).
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=TimeSeriesImportRun,
            template_name="import_module.xml.j2",
            generate=import_module.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("importGFS",          "ModuleConfigFiles/Import/NOAA/ImportGFS.xml"),
            ("importGDPS",         "ModuleConfigFiles/Import/ECCCGrids/ImportGDPS.xml"),
            ("importRDPS",         "ModuleConfigFiles/Import/ECCCGrids/ImportRDPS.xml"),
            ("importRDPA",         "ModuleConfigFiles/Import/ECCCGrids/ImportRDPA.xml"),
            ("importHRDPS",        "ModuleConfigFiles/Import/ECCCGrids/ImportHRDPS.xml"),
            ("importHRDPA",        "ModuleConfigFiles/Import/ECCCGrids/ImportHRDPA.xml"),
            ("importREPS",         "ModuleConfigFiles/Import/ECCCGrids/ImportREPS.xml"),
            ("importE2O",          "ModuleConfigFiles/Import/Earth2Observe/ImportE2O.xml"),
            ("importECCCScalar",   "ModuleConfigFiles/Import/ECCCScalar/ImportECCCScalar.xml"),
            ("importSNODAS",       "ModuleConfigFiles/Import/Snow/ImportSNODAS.xml"),
            ("importWSCHistoric",  "ModuleConfigFiles/Import/ECCCScalar/ImportWSCHistoric.xml"),
            ("importWSCDaily",     "ModuleConfigFiles/Import/ECCCScalar/ImportWSCDaily.xml"),
            ("importWSCHourly",    "ModuleConfigFiles/Import/ECCCScalar/ImportWSCHourly.xml"),
            ("importGPM",          "ModuleConfigFiles/Import/EarthObservation/ImportGPM.xml"),
            ("importGSMAP",        "ModuleConfigFiles/Import/EarthObservation/ImportGSMAP.xml"),
            ("importGLOBSNOW",     "ModuleConfigFiles/Import/Snow/ImportGLOBSNOW.xml"),
        ]
    ],
    # Preprocess + DataProcessing (transformationModule root).
    # SetForecastLength excluded — uses <forecastLengthEstimator> root.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=TransformationModule,
            template_name="transformation_module.xml.j2",
            generate=transformation_module.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("calculateEnsembleStatisticsTemplate",
             "ModuleConfigFiles/DataProcessing/CalculateEnsembleStatisticsTemplate.xml"),
            ("mergeE2OPrecip",
             "ModuleConfigFiles/Preprocess/GriddedData/MergeE2OPrecip.xml"),
            ("preprocessAccumulatedParametersNWPTemplate",
             "ModuleConfigFiles/Preprocess/GriddedData/PreprocessAccumulatedParametersNWPTemplate.xml"),
            ("preprocessInstantaneousParametersNWPTemplate",
             "ModuleConfigFiles/Preprocess/GriddedData/PreprocessInstantaneousParametersNWPTemplate.xml"),
            ("mergeForecastGridsDetTemplate",
             "ModuleConfigFiles/Preprocess/MergeData/MergeForecastGridsDetTemplate.xml"),
            ("mergeForecastGridsEnsTemplate",
             "ModuleConfigFiles/Preprocess/MergeData/MergeForecastGridsEnsTemplate.xml"),
            ("modifyForecastGridsTemplate",
             "ModuleConfigFiles/Preprocess/ModifyData/ModifyForecastGridsTemplate.xml"),
            ("modifyHistoricGridsTemplate",
             "ModuleConfigFiles/Preprocess/ModifyData/ModifyHistoricGridsTemplate.xml"),
            ("preprocessE2ORavenTemplate",
             "ModuleConfigFiles/Preprocess/RavenModelData/PreprocessE2ORavenTemplate.xml"),
            ("preprocessNWPRavenTemplate",
             "ModuleConfigFiles/Preprocess/RavenModelData/PreprocessNWPRavenTemplate.xml"),
            ("accumulateForecastPrecipTemplate",
             "ModuleConfigFiles/Preprocess/ScalarData/AccumulateForecastPrecipTemplate.xml"),
            ("preprocessECCCScalarTransform",
             "ModuleConfigFiles/Preprocess/ScalarData/PreprocessECCCScalar.xml"),
        ]
    ],
    # GeneralAdapterRun — ModelRun + Maintenance + retriever modules.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=GeneralAdapterRun,
            template_name="general_adapter_run.xml.j2",
            generate=general_adapter_run.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("updateModelPackage",
             "ModuleConfigFiles/Maintenance/UpdateModelPackage.xml"),
            ("retrieveSNODAS",
             "ModuleConfigFiles/Import/Snow/RetrieveSNODAS.xml"),
            ("retrieveGLOBSNOW",
             "ModuleConfigFiles/Import/Snow/RetrieveGLOBSNOW.xml"),
            ("liardForecastTemplate",
             "ModuleConfigFiles/ModelRun/Liard/LiardForecastTemplate.xml"),
            ("liardHistoricTemplate",
             "ModuleConfigFiles/ModelRun/Liard/LiardHistoricTemplate.xml"),
            ("snareForecastTemplate",
             "ModuleConfigFiles/ModelRun/Snare/SnareForecastTemplate.xml"),
            ("snareHistoricTemplate",
             "ModuleConfigFiles/ModelRun/Snare/SnareHistoricTemplate.xml"),
        ]
    ],
    GeneratorSpec(
        name="setForecastLengthTemplate",
        input_key="setForecastLengthTemplate",
        model_class=ForecastLengthEstimator,
        template_name="forecast_length_estimator.xml.j2",
        generate=forecast_length_estimator.generate,
        output_relpath=Path("ModuleConfigFiles/Preprocess/SetForecastLength/SetForecastLengthTemplate.xml"),
    ),
    GeneratorSpec(
        name="timeSeriesDisplayConfig",
        input_key="timeSeriesDisplayConfig",
        model_class=TimeSeriesDisplay,
        template_name="time_series_display_config.xml.j2",
        generate=time_series_display_config.generate,
        output_relpath=Path("SystemConfigFiles/TimeSeriesDisplayConfig.xml"),
    ),
    GeneratorSpec(
        name="timeSteps",
        input_key="timeSteps",
        model_class=TimeSteps,
        template_name="time_steps.xml.j2",
        generate=time_steps.generate,
        output_relpath=Path("RegionConfigFiles/TimeSteps.xml"),
    ),
    GeneratorSpec(
        name="locationIcons",
        input_key="locationIcons",
        model_class=LocationIcons,
        template_name="location_icons.xml.j2",
        generate=location_icons.generate,
        output_relpath=Path("SystemConfigFiles/LocationIcons.xml"),
    ),
    GeneratorSpec(
        name="moduleInstanceDescriptors",
        input_key="moduleInstanceDescriptors",
        model_class=ModuleInstanceDescriptors,
        template_name="module_instance_descriptors.xml.j2",
        generate=module_instance_descriptors.generate,
        output_relpath=Path("RegionConfigFiles/ModuleInstanceDescriptors.xml"),
    ),
    GeneratorSpec(
        name="workflowDescriptors",
        input_key="workflowDescriptors",
        model_class=WorkflowDescriptors,
        template_name="workflow_descriptors.xml.j2",
        generate=workflow_descriptors.generate,
        output_relpath=Path("RegionConfigFiles/WorkflowDescriptors.xml"),
    ),
    GeneratorSpec(
        name="postprocessModelOutputToStationTemplate",
        input_key="postprocessModelOutputToStationTemplate",
        model_class=TransformationModule,
        template_name="transformation_module.xml.j2",
        generate=transformation_module.generate,
        output_relpath=Path("ModuleConfigFiles/Postprocess/Model/PostprocessModelOutputToStationTemplate.xml"),
    ),
    # Generic-body file types — 7 registry/UI configs whose structure is
    # too broad for field-by-field modelling. Each uses GenericXmlFile
    # (just a `body` dict) with a tiny per-type template that wraps the
    # FEWS root tag around the dict_to_xml output.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=GenericXmlFile,
            template_name=template,
            generate=(lambda t: lambda m: generic_xml_file.generate(m, t))(template),
            output_relpath=Path(path),
        )
        for key, template, path in [
            ("productsFile",       "products.xml.j2",        "RegionConfigFiles/Products.xml"),
            ("gridsFile",          "grids.xml.j2",           "RegionConfigFiles/Grids.xml"),
            ("locationSetsFile",   "location_sets.xml.j2",   "RegionConfigFiles/LocationSets.xml"),
            ("filtersFile",        "filters.xml.j2",         "RegionConfigFiles/Filters.xml"),
            ("displayGroupsFile",  "display_groups.xml.j2",  "SystemConfigFiles/DisplayGroups.xml"),
            ("explorerFile",       "explorer.xml.j2",        "SystemConfigFiles/Explorer.xml"),
            ("spatialDisplayFile", "spatial_display.xml.j2", "DisplayConfigFiles/SpatialDisplay.xml"),
        ]
    ],
]

__all__ = ["SPECS", "GeneratorSpec"]
