"""Generator registry.

`SPECS` is the authoritative list of FEWS file types this pipeline can
produce. Each spec binds an input-JSON key, a Pydantic model, a Jinja
template, the generator callable, and the output path relative to
`examples/generated-config-tutorial/`.

Adding a new file type = append a spec here.
"""
from __future__ import annotations

from pathlib import Path

from fews_agent.schema import (
    AnnotationDisplay,
    AnnotationMetadataSchema,
    BaseBuildFileSet,
    ClobHistoricalEvent,
    ConfigRevisionSet,
    ConfigUpdateModule,
    ContentUpdateChecker,
    CorrelationEventSetsDescriptors,
    CustomColors,
    CustomFlagSources,
    DAFilter,
    DataDownloadDisplay,
    DisplayDescriptors,
    DisplayInstanceDescriptors,
    Documents,
    DoubleMassDisplay,
    EncodedPartitionSequences,
    EnvironmentAgencyTimeUnits,
    ExternalTablesMirrorUpdate,
    FlagConversions,
    FlagConversionsDescriptors,
    FlagSourceColumns,
    FloodPeriodsModule,
    ForecastProductInfoDisplay,
    GeneralSettings,
    HistoricalEvents,
    HymosTransferDbImportRun,
    ImportAmalgamate,
    ForecastLengthEstimator,
    LDAPLoginModule,
    Launcher,
    ModelRunPeriod,
    ModifierMigrationTool,
    ModuleConfigProperties,
    ModuleDescriptors,
    ModuleRunTableDisplay,
    OnTheFlyExpressionTimeSeries,
    OpenDACalibrationDisplay,
    Polygons,
    Priorities,
    RunInfoPanel,
    SampleDisplay,
    SampleMetadataSchema,
    SamplePropertiesFile,
    Security,
    StorageBasinSystem,
    SupportStationSets,
    TabularConfigFilesDisplay,
    ThresholdEventsDisplay,
    TimeSeriesModifiers,
    TimeSeriesTableDisplay,
    TravelTimes,
    TravelTimesDescriptors,
    TrendDisplay,
    UnitConversionsDescriptors,
    UnreferencedNcFilesCleaner,
    ValueAttributeMaps,
    WapdaTimeSeriesReader,
    WarningEntryDisplay,
    WebBrowserDisplay,
    WebOCMicroFrontEnds,
    WhatIfScenariosDescriptors,
    ForecasterNotesDisplay,
    GeneralAdapterRun,
    GenericXmlFile,
    IdMap,
    LocationIcons,
    Locations,
    ManualForecastDisplay,
    ModifierDisplay,
    ModifierTypes,
    ModuleInstanceDescriptors,
    ModuleInstanceSets,
    ModuleParameters,
    Parameters,
    Permissions,
    Qualifiers,
    ThresholdGroups,
    ThresholdValueSets,
    ThresholdWarningLevels,
    TimeSeriesDisplay,
    TimeSeriesImportRun,
    TimeSteps,
    Topology,
    TransformationModule,
    UnitConversions,
    UserGroups,
    ValidationRuleSets,
    Workflow,
    WorkflowDescriptors,
)

from . import (
    annotation_display,
    annotation_metadata_schema,
    base_build_file_set,
    clob_historical_event,
    config_revision_set,
    config_update_module,
    content_update_checker,
    correlation_event_sets_descriptors,
    custom_colors,
    custom_flag_sources,
    da_filter,
    data_download_display,
    display_descriptors,
    display_instance_descriptors,
    documents,
    double_mass_display,
    encoded_partition_sequences,
    environment_agency_time_units,
    external_tables_mirror_update,
    flag_conversions,
    flag_conversions_descriptors,
    flag_source_columns,
    flood_periods_module,
    forecast_product_info_display,
    general_settings,
    historical_events,
    hymos_transfer_db_import_run,
    import_amalgamate,
    launcher,
    ldap_login_module,
    model_run_period,
    modifier_migration_tool,
    module_config_properties,
    module_descriptors,
    module_run_table_display,
    on_the_fly_expression_time_series,
    openda_calibration_display,
    polygons,
    priority_list,
    run_info_panel,
    sample_display,
    sample_metadata_schema,
    sample_properties,
    security,
    storage_basin_system,
    support_station_sets,
    tabular_config_files_display,
    threshold_events_display,
    time_series_modifiers,
    time_series_table_display,
    travel_times,
    travel_times_descriptors,
    trend_display,
    unit_conversions_descriptors,
    unreferenced_nc_files_cleaner,
    value_attribute_maps,
    wapda_timeseries_reader,
    warning_entry_display,
    web_browser_display,
    weboc_micro_frontends,
    what_if_scenarios_descriptors,
    forecast_length_estimator,
    forecaster_notes_display,
    general_adapter_run,
    generic_xml_file,
    location_icons,
    module_instance_descriptors,
    time_series_display_config,
    time_steps,
    workflow_descriptors,
    id_map,
    import_module,
    locations,
    manual_forecast_display,
    modifier_display,
    modifier_types,
    module_instance_sets,
    module_parameters,
    parameters,
    permissions,
    qualifiers,
    threshold_value_sets,
    threshold_warning_levels,
    thresholds,
    topology,
    transformation_module,
    unit_conversions,
    user_groups,
    validation_rule_sets,
    workflow,
)
from .base import GeneratorSpec

SPECS: list[GeneratorSpec] = [
    GeneratorSpec(
        name="locations",
        input_key="locations",
        model_class=Locations,
        template_name="region/locations.xml.j2",
        generate=locations.generate,
        output_relpath=Path("RegionConfigFiles/Locations.xml"),
    ),
    GeneratorSpec(
        name="documents",
        input_key="documents",
        model_class=Documents,
        template_name="region/documents.xml.j2",
        generate=documents.generate,
        output_relpath=Path("RegionConfigFiles/Documents.xml"),
    ),
    GeneratorSpec(
        name="polygons",
        input_key="polygons",
        model_class=Polygons,
        template_name="region/polygons.xml.j2",
        generate=polygons.generate,
        output_relpath=Path("RegionConfigFiles/Polygons.xml"),
    ),
    GeneratorSpec(
        name="historical_events",
        input_key="historicalEvents",
        model_class=HistoricalEvents,
        template_name="region/historical_events.xml.j2",
        generate=historical_events.generate,
        output_relpath=Path("RegionConfigFiles/HistoricalEvents.xml"),
    ),
    GeneratorSpec(
        name="custom_flag_sources",
        input_key="customFlagSources",
        model_class=CustomFlagSources,
        template_name="region/custom_flag_sources.xml.j2",
        generate=custom_flag_sources.generate,
        output_relpath=Path("RegionConfigFiles/CustomFlagSources.xml"),
    ),
    GeneratorSpec(
        name="flag_source_columns",
        input_key="flagSourceColumns",
        model_class=FlagSourceColumns,
        template_name="region/flag_source_columns.xml.j2",
        generate=flag_source_columns.generate,
        output_relpath=Path("RegionConfigFiles/FlagSourceColumns.xml"),
    ),
    GeneratorSpec(
        name="annotation_metadata_schema",
        input_key="annotationMetadataSchema",
        model_class=AnnotationMetadataSchema,
        template_name="region/annotation_metadata_schema.xml.j2",
        generate=annotation_metadata_schema.generate,
        output_relpath=Path("RegionConfigFiles/AnnotationMetadataSchema.xml"),
    ),
    GeneratorSpec(
        name="sample_metadata_schema",
        input_key="sampleMetadataSchema",
        model_class=SampleMetadataSchema,
        template_name="region/sample_metadata_schema.xml.j2",
        generate=sample_metadata_schema.generate,
        output_relpath=Path("RegionConfigFiles/SampleMetadataSchema.xml"),
    ),
    GeneratorSpec(
        name="flood_periods_module",
        input_key="floodPeriodsModule",
        model_class=FloodPeriodsModule,
        template_name="module/flood_periods_module.xml.j2",
        generate=flood_periods_module.generate,
        output_relpath=Path("ModuleConfigFiles/FloodPeriodsModule.xml"),
    ),
    GeneratorSpec(
        name="content_update_checker",
        input_key="contentUpdateChecker",
        model_class=ContentUpdateChecker,
        template_name="module/content_update_checker.xml.j2",
        generate=content_update_checker.generate,
        output_relpath=Path("ModuleConfigFiles/ContentUpdateChecker.xml"),
    ),
    GeneratorSpec(
        name="config_update_module",
        input_key="configUpdateModule",
        model_class=ConfigUpdateModule,
        template_name="module/config_update_module.xml.j2",
        generate=config_update_module.generate,
        output_relpath=Path("ModuleConfigFiles/ConfigUpdateModule.xml"),
    ),
    GeneratorSpec(
        name="module_run_table_display",
        input_key="moduleRunTableDisplay",
        model_class=ModuleRunTableDisplay,
        template_name="display/module_run_table_display.xml.j2",
        generate=module_run_table_display.generate,
        output_relpath=Path("DisplayConfigFiles/ModuleRunTableDisplay.xml"),
    ),
    GeneratorSpec(
        name="unreferenced_nc_files_cleaner",
        input_key="unreferencedNcFilesCleaner",
        model_class=UnreferencedNcFilesCleaner,
        template_name="module/unreferenced_nc_files_cleaner.xml.j2",
        generate=unreferenced_nc_files_cleaner.generate,
        output_relpath=Path("ModuleConfigFiles/UnreferencedNcFilesCleaner.xml"),
    ),
    GeneratorSpec(
        name="support_station_sets",
        input_key="supportStationSets",
        model_class=SupportStationSets,
        template_name="region/support_station_sets.xml.j2",
        generate=support_station_sets.generate,
        output_relpath=Path("RegionConfigFiles/SupportStationSets.xml"),
    ),
    GeneratorSpec(
        name="import_amalgamate",
        input_key="importAmalgamate",
        model_class=ImportAmalgamate,
        template_name="module/import_amalgamate.xml.j2",
        generate=import_amalgamate.generate,
        output_relpath=Path("ModuleConfigFiles/ImportAmalgamate.xml"),
    ),
    GeneratorSpec(
        name="module_config_properties",
        input_key="moduleConfigProperties",
        model_class=ModuleConfigProperties,
        template_name="region/module_config_properties.xml.j2",
        generate=module_config_properties.generate,
        output_relpath=Path("RegionConfigFiles/ModuleConfigProperties.xml"),
    ),
    GeneratorSpec(
        name="base_build_file_set",
        input_key="baseBuildFileSet",
        model_class=BaseBuildFileSet,
        template_name="root/base_build_file_set.xml.j2",
        generate=base_build_file_set.generate,
        output_relpath=Path("RootConfigFiles/BaseBuildFileSet.xml"),
    ),
    GeneratorSpec(
        name="config_revision_set",
        input_key="configRevisionSet",
        model_class=ConfigRevisionSet,
        template_name="system/config_revision_set.xml.j2",
        generate=config_revision_set.generate,
        output_relpath=Path("SystemConfigFiles/ConfigRevisionSet.xml"),
    ),
    GeneratorSpec(
        name="run_info_panel",
        input_key="runInfoPanel",
        model_class=RunInfoPanel,
        template_name="root/run_info_panel.xml.j2",
        generate=run_info_panel.generate,
        output_relpath=Path("RootConfigFiles/RunInfoPanel.xml"),
    ),
    GeneratorSpec(
        name="display_descriptors",
        input_key="displayDescriptors",
        model_class=DisplayDescriptors,
        template_name="static/display_descriptors.xml.j2",
        generate=display_descriptors.generate,
        output_relpath=Path("SystemConfigFiles/DisplayDescriptors.xml"),
    ),
    GeneratorSpec(
        name="display_instance_descriptors",
        input_key="displayInstanceDescriptors",
        model_class=DisplayInstanceDescriptors,
        template_name="static/display_instance_descriptors.xml.j2",
        generate=display_instance_descriptors.generate,
        output_relpath=Path("SystemConfigFiles/DisplayInstanceDescriptors.xml"),
    ),
    GeneratorSpec(
        name="module_descriptors",
        input_key="moduleDescriptors",
        model_class=ModuleDescriptors,
        template_name="static/module_descriptors.xml.j2",
        generate=module_descriptors.generate,
        output_relpath=Path("SystemConfigFiles/ModuleDescriptors.xml"),
    ),
    GeneratorSpec(
        name="storage_basin_system",
        input_key="storageBasin",
        model_class=StorageBasinSystem,
        template_name="region/storage_basin_system.xml.j2",
        generate=storage_basin_system.generate,
        output_relpath=Path("RegionConfigFiles/StorageBasin.xml"),
    ),
    GeneratorSpec(
        name="unit_conversions_descriptors",
        input_key="unitConversionsDescriptors",
        model_class=UnitConversionsDescriptors,
        template_name="id_mapping/unit_conversions_descriptors.xml.j2",
        generate=unit_conversions_descriptors.generate,
        output_relpath=Path("IdMapFiles/UnitConversionsDescriptors.xml"),
    ),
    GeneratorSpec(
        name="flag_conversions_descriptors",
        input_key="flagConversionsDescriptors",
        model_class=FlagConversionsDescriptors,
        template_name="id_mapping/flag_conversions_descriptors.xml.j2",
        generate=flag_conversions_descriptors.generate,
        output_relpath=Path("IdMapFiles/FlagConversionsDescriptors.xml"),
    ),
    GeneratorSpec(
        name="what_if_scenarios_descriptors",
        input_key="whatIfScenariosDescriptors",
        model_class=WhatIfScenariosDescriptors,
        template_name="region/what_if_scenarios_descriptors.xml.j2",
        generate=what_if_scenarios_descriptors.generate,
        output_relpath=Path("RegionConfigFiles/WhatIfScenariosDescriptors.xml"),
    ),
    GeneratorSpec(
        name="travel_times_descriptors",
        input_key="travelTimesDescriptors",
        model_class=TravelTimesDescriptors,
        template_name="region/travel_times_descriptors.xml.j2",
        generate=travel_times_descriptors.generate,
        output_relpath=Path("RegionConfigFiles/TravelTimesDescriptors.xml"),
    ),
    GeneratorSpec(
        name="correlation_event_sets_descriptors",
        input_key="correlationEventSetsDescriptors",
        model_class=CorrelationEventSetsDescriptors,
        template_name="region/correlation_event_sets_descriptors.xml.j2",
        generate=correlation_event_sets_descriptors.generate,
        output_relpath=Path("RegionConfigFiles/CorrelationEventSetsDescriptors.xml"),
    ),
    GeneratorSpec(
        name="model_run_period",
        input_key="modelRunPeriod",
        model_class=ModelRunPeriod,
        template_name="root/model_run_period.xml.j2",
        generate=model_run_period.generate,
        output_relpath=Path("RootConfigFiles/ModelRunPeriod.xml"),
    ),
    GeneratorSpec(
        name="custom_colors",
        input_key="customColors",
        model_class=CustomColors,
        template_name="system/custom_colors.xml.j2",
        generate=custom_colors.generate,
        output_relpath=Path("SystemConfigFiles/CustomColors.xml"),
    ),
    GeneratorSpec(
        name="general_settings",
        input_key="generalSettings",
        model_class=GeneralSettings,
        template_name="root/general_settings.xml.j2",
        generate=general_settings.generate,
        output_relpath=Path("RootConfigFiles/GeneralSettings.xml"),
    ),
    GeneratorSpec(
        name="value_attribute_maps",
        input_key="valueAttributeMaps",
        model_class=ValueAttributeMaps,
        template_name="region/value_attribute_maps.xml.j2",
        generate=value_attribute_maps.generate,
        output_relpath=Path("RegionConfigFiles/ValueAttributeMaps.xml"),
    ),
    GeneratorSpec(
        name="sample_properties",
        input_key="sampleProperties",
        model_class=SamplePropertiesFile,
        template_name="region/sample_properties.xml.j2",
        generate=sample_properties.generate,
        output_relpath=Path("RegionConfigFiles/SampleProperties.xml"),
    ),
    GeneratorSpec(
        name="travel_times",
        input_key="travelTimes",
        model_class=TravelTimes,
        template_name="region/travel_times.xml.j2",
        generate=travel_times.generate,
        output_relpath=Path("RegionConfigFiles/TravelTimes.xml"),
    ),
    GeneratorSpec(
        name="security",
        input_key="security",
        model_class=Security,
        template_name="root/security.xml.j2",
        generate=security.generate,
        output_relpath=Path("RootConfigFiles/Security.xml"),
    ),
    GeneratorSpec(
        name="trend_display",
        input_key="trendDisplay",
        model_class=TrendDisplay,
        template_name="display/trend_display.xml.j2",
        generate=trend_display.generate,
        output_relpath=Path("DisplayConfigFiles/TrendDisplay.xml"),
    ),
    GeneratorSpec(
        name="sample_display",
        input_key="sampleDisplay",
        model_class=SampleDisplay,
        template_name="display/sample_display.xml.j2",
        generate=sample_display.generate,
        output_relpath=Path("DisplayConfigFiles/SampleDisplay.xml"),
    ),
    GeneratorSpec(
        name="warning_entry_display",
        input_key="warningEntryDisplay",
        model_class=WarningEntryDisplay,
        template_name="display/warning_entry_display.xml.j2",
        generate=warning_entry_display.generate,
        output_relpath=Path("DisplayConfigFiles/WarningEntryDisplay.xml"),
    ),
    GeneratorSpec(
        name="openda_calibration_display",
        input_key="openDACalibrationDisplay",
        model_class=OpenDACalibrationDisplay,
        template_name="display/openda_calibration_display.xml.j2",
        generate=openda_calibration_display.generate,
        output_relpath=Path("DisplayConfigFiles/OpenDACalibrationDisplay.xml"),
    ),
    GeneratorSpec(
        name="hymos_transfer_db_import_run",
        input_key="hymosTransferDbImportRun",
        model_class=HymosTransferDbImportRun,
        template_name="module/hymos_transfer_db_import_run.xml.j2",
        generate=hymos_transfer_db_import_run.generate,
        output_relpath=Path("ModuleConfigFiles/HymosTransferDbImportRun.xml"),
    ),
    GeneratorSpec(
        name="priority_list",
        input_key="priorities",
        model_class=Priorities,
        template_name="region/priority_list.xml.j2",
        generate=priority_list.generate,
        output_relpath=Path("RegionConfigFiles/Priorities.xml"),
    ),
    GeneratorSpec(
        name="flag_conversions",
        input_key="flagConversions",
        model_class=FlagConversions,
        template_name="id_mapping/flag_conversions.xml.j2",
        generate=flag_conversions.generate,
        output_relpath=Path("IdMapFiles/FlagConversions.xml"),
    ),
    GeneratorSpec(
        name="time_series_table_display",
        input_key="timeSeriesTableDisplay",
        model_class=TimeSeriesTableDisplay,
        template_name="display/time_series_table_display.xml.j2",
        generate=time_series_table_display.generate,
        output_relpath=Path("DisplayConfigFiles/TimeSeriesTableDisplay.xml"),
    ),
    GeneratorSpec(
        name="tabular_config_files_display",
        input_key="tabularConfigFilesDisplay",
        model_class=TabularConfigFilesDisplay,
        template_name="display/tabular_config_files_display.xml.j2",
        generate=tabular_config_files_display.generate,
        output_relpath=Path("DisplayConfigFiles/TabularConfigFilesDisplay.xml"),
    ),
    GeneratorSpec(
        name="data_download_display",
        input_key="dataDownloadDisplay",
        model_class=DataDownloadDisplay,
        template_name="display/data_download_display.xml.j2",
        generate=data_download_display.generate,
        output_relpath=Path("DisplayConfigFiles/DataDownloadDisplay.xml"),
    ),
    GeneratorSpec(
        name="web_browser_display",
        input_key="webBrowserDisplay",
        model_class=WebBrowserDisplay,
        template_name="display/web_browser_display.xml.j2",
        generate=web_browser_display.generate,
        output_relpath=Path("DisplayConfigFiles/WebBrowserDisplay.xml"),
    ),
    GeneratorSpec(
        name="forecast_product_info_display",
        input_key="forecastProductInfoDisplay",
        model_class=ForecastProductInfoDisplay,
        template_name="display/forecast_product_info_display.xml.j2",
        generate=forecast_product_info_display.generate,
        output_relpath=Path("DisplayConfigFiles/ForecastProductInfoDisplay.xml"),
    ),
    GeneratorSpec(
        name="weboc_micro_frontends",
        input_key="webOCMicroFrontEnds",
        model_class=WebOCMicroFrontEnds,
        template_name="display/weboc_micro_frontends.xml.j2",
        generate=weboc_micro_frontends.generate,
        output_relpath=Path("DisplayConfigFiles/WebOCMicroFrontEnds.xml"),
    ),
    GeneratorSpec(
        name="da_filter",
        input_key="dAFilter",
        model_class=DAFilter,
        template_name="module/da_filter.xml.j2",
        generate=da_filter.generate,
        output_relpath=Path("ModuleConfigFiles/DAFilter.xml"),
    ),
    GeneratorSpec(
        name="environment_agency_time_units",
        input_key="timeUnits",
        model_class=EnvironmentAgencyTimeUnits,
        template_name="id_mapping/environment_agency_time_units.xml.j2",
        generate=environment_agency_time_units.generate,
        output_relpath=Path("IdMapFiles/EnvironmentAgencyTimeUnits.xml"),
    ),
    GeneratorSpec(
        name="ldap_login_module",
        input_key="LDAPLoginModule",
        model_class=LDAPLoginModule,
        template_name="root/ldap_login_module.xml.j2",
        generate=ldap_login_module.generate,
        output_relpath=Path("RootConfigFiles/LDAPLoginModule.xml"),
    ),
    GeneratorSpec(
        name="launcher",
        input_key="launcher",
        model_class=Launcher,
        template_name="root/launcher.xml.j2",
        generate=launcher.generate,
        output_relpath=Path("RootConfigFiles/Launcher.xml"),
    ),
    GeneratorSpec(
        name="clob_historical_event",
        input_key="historicalEventClob",
        model_class=ClobHistoricalEvent,
        template_name="region/clob_historical_event.xml.j2",
        generate=clob_historical_event.generate,
        output_relpath=Path("RegionConfigFiles/HistoricalEventClob.xml"),
    ),
    GeneratorSpec(
        name="double_mass_display",
        input_key="doubleMassDisplay",
        model_class=DoubleMassDisplay,
        template_name="display/double_mass_display.xml.j2",
        generate=double_mass_display.generate,
        output_relpath=Path("DisplayConfigFiles/DoubleMassDisplay.xml"),
    ),
    GeneratorSpec(
        name="wapda_timeseries_reader",
        input_key="wapdaTimeSeriesReader",
        model_class=WapdaTimeSeriesReader,
        template_name="module/wapda_timeseries_reader.xml.j2",
        generate=wapda_timeseries_reader.generate,
        output_relpath=Path("ModuleConfigFiles/WapdaTimeSeriesReader.xml"),
    ),
    GeneratorSpec(
        name="external_tables_mirror_update",
        input_key="externalTablesMirrorUpdate",
        model_class=ExternalTablesMirrorUpdate,
        template_name="module/external_tables_mirror_update.xml.j2",
        generate=external_tables_mirror_update.generate,
        output_relpath=Path("ModuleConfigFiles/ExternalTablesMirrorUpdate.xml"),
    ),
    GeneratorSpec(
        name="on_the_fly_expression_time_series",
        input_key="onTheFlyExpressionTimeSeries",
        model_class=OnTheFlyExpressionTimeSeries,
        template_name="region/on_the_fly_expression_time_series.xml.j2",
        generate=on_the_fly_expression_time_series.generate,
        output_relpath=Path("RegionConfigFiles/OnTheFlyExpressionTimeSeries.xml"),
    ),
    GeneratorSpec(
        name="annotation_display",
        input_key="annotationDisplay",
        model_class=AnnotationDisplay,
        template_name="display/annotation_display.xml.j2",
        generate=annotation_display.generate,
        output_relpath=Path("DisplayConfigFiles/AnnotationDisplay.xml"),
    ),
    GeneratorSpec(
        name="encoded_partition_sequences",
        input_key="encodedPartitionSequences",
        model_class=EncodedPartitionSequences,
        template_name="system/encoded_partition_sequences.xml.j2",
        generate=encoded_partition_sequences.generate,
        output_relpath=Path("SystemConfigFiles/EncodedPartitionSequences.xml"),
    ),
    GeneratorSpec(
        name="threshold_events_display",
        input_key="thresholdEventsDisplay",
        model_class=ThresholdEventsDisplay,
        template_name="display/threshold_events_display.xml.j2",
        generate=threshold_events_display.generate,
        output_relpath=Path("DisplayConfigFiles/ThresholdEventsDisplay.xml"),
    ),
    GeneratorSpec(
        name="time_series_modifiers",
        input_key="timeSeriesModifiers",
        model_class=TimeSeriesModifiers,
        template_name="region/time_series_modifiers.xml.j2",
        generate=time_series_modifiers.generate,
        output_relpath=Path("RegionConfigFiles/TimeSeriesModifiers.xml"),
    ),
    GeneratorSpec(
        name="modifier_migration_tool",
        input_key="modifierMigrationTool",
        model_class=ModifierMigrationTool,
        template_name="module/modifier_migration_tool.xml.j2",
        generate=modifier_migration_tool.generate,
        output_relpath=Path("ModuleConfigFiles/ModifierMigrationTool.xml"),
    ),
    GeneratorSpec(
        name="parameters",
        input_key="parameters",
        model_class=Parameters,
        template_name="region/parameters.xml.j2",
        generate=parameters.generate,
        output_relpath=Path("RegionConfigFiles/Parameters.xml"),
    ),
    GeneratorSpec(
        name="qualifiers",
        input_key="qualifiers",
        model_class=Qualifiers,
        template_name="region/qualifiers.xml.j2",
        generate=qualifiers.generate,
        output_relpath=Path("RegionConfigFiles/Qualifiers.xml"),
    ),
    GeneratorSpec(
        name="thresholdWarningLevels",
        input_key="thresholdWarningLevels",
        model_class=ThresholdWarningLevels,
        template_name="region/threshold_warning_levels.xml.j2",
        generate=threshold_warning_levels.generate,
        output_relpath=Path("RegionConfigFiles/ThresholdWarningLevels.xml"),
    ),
    GeneratorSpec(
        name="moduleInstanceSets",
        input_key="moduleInstanceSets",
        model_class=ModuleInstanceSets,
        template_name="region/module_instance_sets.xml.j2",
        generate=module_instance_sets.generate,
        output_relpath=Path("RegionConfigFiles/ModuleInstanceSets.xml"),
    ),
    GeneratorSpec(
        name="permissions",
        input_key="permissions",
        model_class=Permissions,
        template_name="system/permissions.xml.j2",
        generate=permissions.generate,
        output_relpath=Path("SystemConfigFiles/Permissions.xml"),
    ),
    GeneratorSpec(
        name="importUnitConversions",
        input_key="importUnitConversions",
        model_class=UnitConversions,
        template_name="id_mapping/unit_conversions.xml.j2",
        generate=unit_conversions.generate,
        output_relpath=Path("UnitConversionsFiles/ImportUnitConversions.xml"),
    ),
    GeneratorSpec(
        name="exportUnitConversions",
        input_key="exportUnitConversions",
        model_class=UnitConversions,
        template_name="id_mapping/unit_conversions.xml.j2",
        generate=unit_conversions.generate,
        output_relpath=Path("UnitConversionsFiles/ExportUnitConversions.xml"),
    ),
    GeneratorSpec(
        name="exportRaven",
        input_key="exportRaven",
        model_class=UnitConversions,
        template_name="id_mapping/unit_conversions.xml.j2",
        generate=unit_conversions.generate,
        output_relpath=Path("UnitConversionsFiles/ExportRaven.xml"),
    ),
    GeneratorSpec(
        name="thresholds",
        input_key="thresholds",
        model_class=ThresholdGroups,
        template_name="region/thresholds.xml.j2",
        generate=thresholds.generate,
        output_relpath=Path("RegionConfigFiles/Thresholds.xml"),
    ),
    GeneratorSpec(
        name="userGroups",
        input_key="userGroups",
        model_class=UserGroups,
        template_name="system/user_groups.xml.j2",
        generate=user_groups.generate,
        output_relpath=Path("SystemConfigFiles/UserGroups.xml"),
    ),
    GeneratorSpec(
        name="manualForecastDisplay",
        input_key="manualForecastDisplay",
        model_class=ManualForecastDisplay,
        template_name="display/manual_forecast_display.xml.j2",
        generate=manual_forecast_display.generate,
        output_relpath=Path("DisplayConfigFiles/ManualForecastDisplay.xml"),
    ),
    GeneratorSpec(
        name="forecasterNotesDisplay",
        input_key="forecasterNotesDisplay",
        model_class=ForecasterNotesDisplay,
        template_name="display/forecaster_notes_display.xml.j2",
        generate=forecaster_notes_display.generate,
        output_relpath=Path("DisplayConfigFiles/ForecasterNotesDisplay.xml"),
    ),
    GeneratorSpec(
        name="modifierDisplay",
        input_key="modifierDisplay",
        model_class=ModifierDisplay,
        template_name="display/modifier_display.xml.j2",
        generate=modifier_display.generate,
        output_relpath=Path("DisplayConfigFiles/ModifiersDisplay.xml"),
    ),
    GeneratorSpec(
        name="thresholdValueSets",
        input_key="thresholdValueSets",
        model_class=ThresholdValueSets,
        template_name="region/threshold_value_sets.xml.j2",
        generate=threshold_value_sets.generate,
        output_relpath=Path("RegionConfigFiles/ThresholdValueSets.xml"),
    ),
    GeneratorSpec(
        name="validationRuleSets",
        input_key="validationRuleSets",
        model_class=ValidationRuleSets,
        template_name="region/validation_rule_sets.xml.j2",
        generate=validation_rule_sets.generate,
        output_relpath=Path("RegionConfigFiles/ValidationRuleSets.xml"),
    ),
    GeneratorSpec(
        name="modifierTypes",
        input_key="modifierTypes",
        model_class=ModifierTypes,
        template_name="region/modifier_types.xml.j2",
        generate=modifier_types.generate,
        output_relpath=Path("RegionConfigFiles/ModifierTypes.xml"),
    ),
    GeneratorSpec(
        name="topology",
        input_key="topology",
        model_class=Topology,
        template_name="region/topology.xml.j2",
        generate=topology.generate,
        output_relpath=Path("RegionConfigFiles/Topology.xml"),
    ),
    GeneratorSpec(
        name="ravenParameters",
        input_key="ravenParameters",
        model_class=ModuleParameters,
        template_name="module_datasets/module_parameters.xml.j2",
        generate=module_parameters.generate,
        output_relpath=Path("ModuleParFiles/RavenParameters.xml"),
    ),
    # Workflow — all 37 tutorial files share one generator + template.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=Workflow,
            template_name="workflow/workflow.xml.j2",
            generate=workflow.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("importE2OGridsWorkflow",        "WorkflowFiles/Import/Earth2Observe/ImportE2OGrids.xml"),
            ("importEOGridsWorkflow",         "WorkflowFiles/Import/EarthObservation/ImportEOGrids.xml"),
            ("importGDPSGridsWorkflow",       "WorkflowFiles/Import/ECCCGrids/ImportGDPSGrids.xml"),
            ("importHRDPAGridsWorkflow",      "WorkflowFiles/Import/ECCCGrids/ImportHRDPAGrids.xml"),
            ("importHRDPSGridsWorkflow",      "WorkflowFiles/Import/ECCCGrids/ImportHRDPSGrids.xml"),
            ("importRDPAGridsWorkflow",       "WorkflowFiles/Import/ECCCGrids/ImportRDPAGrids.xml"),
            ("importRDPSGridsWorkflow",       "WorkflowFiles/Import/ECCCGrids/ImportRDPSGrids.xml"),
            ("importREPSGridsWorkflow",       "WorkflowFiles/Import/ECCCGrids/ImportREPSGrids.xml"),
            ("importECCCScalarWorkflow",      "WorkflowFiles/Import/ECCCScalar/ImportECCCScalar.xml"),
            ("importWSCDailyWorkflow",        "WorkflowFiles/Import/ECCCScalar/ImportWSCDaily.xml"),
            ("importWSCHistoricWorkflow",     "WorkflowFiles/Import/ECCCScalar/ImportWSCHistoric.xml"),
            ("importWSCHourlyWorkflow",       "WorkflowFiles/Import/ECCCScalar/ImportWSCHourly.xml"),
            ("importGFSGridsWorkflow",        "WorkflowFiles/Import/NOAA/ImportGFSGrids.xml"),
            ("importNAMGridsWorkflow",        "WorkflowFiles/Import/NOAA/ImportNAMGrids.xml"),
            ("importNOAAGridsWorkflow",       "WorkflowFiles/Import/NOAA/ImportNOAAGrids.xml"),
            ("importSREFGridsWorkflow",       "WorkflowFiles/Import/NOAA/ImportSREFGrids.xml"),
            ("importGLOBSNOWGridsWorkflow",   "WorkflowFiles/Import/Snow/ImportGLOBSNOWGrids.xml"),
            ("importSNODASGridsWorkflow",     "WorkflowFiles/Import/Snow/ImportSNODASGrids.xml"),
            ("runLiardGDPSForecastWorkflow",  "WorkflowFiles/ModelRun/Liard/RunLiardGDPSForecast.xml"),
            ("runLiardHistoricWorkflow",      "WorkflowFiles/ModelRun/Liard/RunLiardHistoric.xml"),
            ("runLiardRDPSForecastWorkflow",  "WorkflowFiles/ModelRun/Liard/RunLiardRDPSForecast.xml"),
            ("runLiardREPSForecastWorkflow",  "WorkflowFiles/ModelRun/Liard/RunLiardREPSForecast.xml"),
            ("runSnareGDPSForecastWorkflow",  "WorkflowFiles/ModelRun/Snare/RunSnareGDPSForecast.xml"),
            ("runSnareHistoricWorkflow",      "WorkflowFiles/ModelRun/Snare/RunSnareHistoric.xml"),
            ("runSnareRDPSForecastWorkflow",  "WorkflowFiles/ModelRun/Snare/RunSnareRDPSForecast.xml"),
            ("runSnareREPSForecastWorkflow",  "WorkflowFiles/ModelRun/Snare/RunSnareREPSForecast.xml"),
            ("preprocessE2OLiardWorkflow",    "WorkflowFiles/Preprocess/Liard/PreprocessE2OLiard.xml"),
            ("preprocessGDPSLiardWorkflow",   "WorkflowFiles/Preprocess/Liard/PreprocessGDPSLiard.xml"),
            ("preprocessRDPSLiardWorkflow",   "WorkflowFiles/Preprocess/Liard/PreprocessRDPSLiard.xml"),
            ("preprocessREPSLiardWorkflow",   "WorkflowFiles/Preprocess/Liard/PreprocessREPSLiard.xml"),
            ("mergeHistoricGridsWorkflow",    "WorkflowFiles/Preprocess/MergeHistoricGrids.xml"),
            ("modifyForecastGridsWorkflow",   "WorkflowFiles/Preprocess/ModifyForecastGrids.xml"),
            ("preprocessE2OSnareWorkflow",    "WorkflowFiles/Preprocess/Snare/PreprocessE2OSnare.xml"),
            ("preprocessGDPSSnareWorkflow",   "WorkflowFiles/Preprocess/Snare/PreprocessGDPSSnare.xml"),
            ("preprocessRDPSSnareWorkflow",   "WorkflowFiles/Preprocess/Snare/PreprocessRDPSSnare.xml"),
            ("preprocessREPSSnareWorkflow",   "WorkflowFiles/Preprocess/Snare/PreprocessREPSSnare.xml"),
            ("updateHistoricGridsWorkflow",   "WorkflowFiles/Preprocess/UpdateHistoricGrids.xml"),
        ]
    ],
    # IdMap — shared generator across 14 tutorial files, one spec per file.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=IdMap,
            template_name="id_mapping/id_map.xml.j2",
            generate=id_map.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("idImportECCCScalar",  "IdMapFiles/ECCC/IdImportECCCScalar.xml"),
            ("idImportCanadaWCS",   "IdMapFiles/ECCC/IdImportCanadaWCS.xml"),
            ("idImportWSC",         "IdMapFiles/ECCC/IdImportWSC.xml"),
            ("idImportGFS",         "IdMapFiles/NOAA/IdImportGFS.xml"),
            ("idImportNAM",         "IdMapFiles/NOAA/IdImportNAM.xml"),
            ("idImportRaven",       "IdMapFiles/Model/IdImportRaven.xml"),
            ("idExportRaven",       "IdMapFiles/Model/IdExportRaven.xml"),
            ("idImportwflow",       "IdMapFiles/Model/IdImportwflow.xml"),
            ("idExportwflow",       "IdMapFiles/Model/IdExportwflow.xml"),
            ("idImportE2O",         "IdMapFiles/SpecialImport/IdImportE2O.xml"),
            ("idImportGLOBSNOW",    "IdMapFiles/SpecialImport/IdImportGLOBSNOW.xml"),
            ("idImportGPM",         "IdMapFiles/SpecialImport/IdImportGPM.xml"),
            ("idImportGSMAP",       "IdMapFiles/SpecialImport/IdImportGSMAP.xml"),
            ("idImportSNODAS",      "IdMapFiles/SpecialImport/IdImportSNODAS.xml"),
        ]
    ],
    # Import modules — 11 of 16 tutorial files. Deferred: WSCDaily/WSCHourly
    # (need <table>+<tolerance>+skipFirstLinesCount), GPM/GSMAP/GLOBSNOW
    # (need <fileNameDateTimeFilter>+fileNameObservationDateTimePattern).
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=TimeSeriesImportRun,
            template_name="module/import_module.xml.j2",
            generate=import_module.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("importGFS",          "ModuleConfigFiles/Import/NOAA/ImportGFS.xml"),
            ("importGDPS",         "ModuleConfigFiles/Import/ECCCGrids/ImportGDPS.xml"),
            ("importRDPS",         "ModuleConfigFiles/Import/ECCCGrids/ImportRDPS.xml"),
            ("importRDPA",         "ModuleConfigFiles/Import/ECCCGrids/ImportRDPA.xml"),
            ("importHRDPS",        "ModuleConfigFiles/Import/ECCCGrids/ImportHRDPS.xml"),
            ("importHRDPA",        "ModuleConfigFiles/Import/ECCCGrids/ImportHRDPA.xml"),
            ("importREPS",         "ModuleConfigFiles/Import/ECCCGrids/ImportREPS.xml"),
            ("importE2O",          "ModuleConfigFiles/Import/Earth2Observe/ImportE2O.xml"),
            ("importECCCScalar",   "ModuleConfigFiles/Import/ECCCScalar/ImportECCCScalar.xml"),
            ("importSNODAS",       "ModuleConfigFiles/Import/Snow/ImportSNODAS.xml"),
            ("importWSCHistoric",  "ModuleConfigFiles/Import/ECCCScalar/ImportWSCHistoric.xml"),
            ("importWSCDaily",     "ModuleConfigFiles/Import/ECCCScalar/ImportWSCDaily.xml"),
            ("importWSCHourly",    "ModuleConfigFiles/Import/ECCCScalar/ImportWSCHourly.xml"),
            ("importGPM",          "ModuleConfigFiles/Import/EarthObservation/ImportGPM.xml"),
            ("importGSMAP",        "ModuleConfigFiles/Import/EarthObservation/ImportGSMAP.xml"),
            ("importGLOBSNOW",     "ModuleConfigFiles/Import/Snow/ImportGLOBSNOW.xml"),
        ]
    ],
    # Preprocess + DataProcessing (transformationModule root).
    # SetForecastLength excluded — uses <forecastLengthEstimator> root.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=TransformationModule,
            template_name="module/transformation_module.xml.j2",
            generate=transformation_module.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("calculateEnsembleStatisticsTemplate",
             "ModuleConfigFiles/DataProcessing/CalculateEnsembleStatisticsTemplate.xml"),
            ("mergeE2OPrecip",
             "ModuleConfigFiles/Preprocess/GriddedData/MergeE2OPrecip.xml"),
            ("preprocessAccumulatedParametersNWPTemplate",
             "ModuleConfigFiles/Preprocess/GriddedData/PreprocessAccumulatedParametersNWPTemplate.xml"),
            ("preprocessInstantaneousParametersNWPTemplate",
             "ModuleConfigFiles/Preprocess/GriddedData/PreprocessInstantaneousParametersNWPTemplate.xml"),
            ("mergeForecastGridsDetTemplate",
             "ModuleConfigFiles/Preprocess/MergeData/MergeForecastGridsDetTemplate.xml"),
            ("mergeForecastGridsEnsTemplate",
             "ModuleConfigFiles/Preprocess/MergeData/MergeForecastGridsEnsTemplate.xml"),
            ("modifyForecastGridsTemplate",
             "ModuleConfigFiles/Preprocess/ModifyData/ModifyForecastGridsTemplate.xml"),
            ("modifyHistoricGridsTemplate",
             "ModuleConfigFiles/Preprocess/ModifyData/ModifyHistoricGridsTemplate.xml"),
            ("preprocessE2ORavenTemplate",
             "ModuleConfigFiles/Preprocess/RavenModelData/PreprocessE2ORavenTemplate.xml"),
            ("preprocessNWPRavenTemplate",
             "ModuleConfigFiles/Preprocess/RavenModelData/PreprocessNWPRavenTemplate.xml"),
            ("accumulateForecastPrecipTemplate",
             "ModuleConfigFiles/Preprocess/ScalarData/AccumulateForecastPrecipTemplate.xml"),
            ("preprocessECCCScalarTransform",
             "ModuleConfigFiles/Preprocess/ScalarData/PreprocessECCCScalar.xml"),
        ]
    ],
    # GeneralAdapterRun — ModelRun + Maintenance + retriever modules.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=GeneralAdapterRun,
            template_name="module/general_adapter_run.xml.j2",
            generate=general_adapter_run.generate,
            output_relpath=Path(path),
        )
        for key, path in [
            ("updateModelPackage",
             "ModuleConfigFiles/Maintenance/UpdateModelPackage.xml"),
            ("retrieveSNODAS",
             "ModuleConfigFiles/Import/Snow/RetrieveSNODAS.xml"),
            ("retrieveGLOBSNOW",
             "ModuleConfigFiles/Import/Snow/RetrieveGLOBSNOW.xml"),
            ("liardForecastTemplate",
             "ModuleConfigFiles/ModelRun/Liard/LiardForecastTemplate.xml"),
            ("liardHistoricTemplate",
             "ModuleConfigFiles/ModelRun/Liard/LiardHistoricTemplate.xml"),
            ("snareForecastTemplate",
             "ModuleConfigFiles/ModelRun/Snare/SnareForecastTemplate.xml"),
            ("snareHistoricTemplate",
             "ModuleConfigFiles/ModelRun/Snare/SnareHistoricTemplate.xml"),
        ]
    ],
    GeneratorSpec(
        name="setForecastLengthTemplate",
        input_key="setForecastLengthTemplate",
        model_class=ForecastLengthEstimator,
        template_name="module/forecast_length_estimator.xml.j2",
        generate=forecast_length_estimator.generate,
        output_relpath=Path("ModuleConfigFiles/Preprocess/SetForecastLength/SetForecastLengthTemplate.xml"),
    ),
    GeneratorSpec(
        name="timeSeriesDisplayConfig",
        input_key="timeSeriesDisplayConfig",
        model_class=TimeSeriesDisplay,
        template_name="system/time_series_display_config.xml.j2",
        generate=time_series_display_config.generate,
        output_relpath=Path("SystemConfigFiles/TimeSeriesDisplayConfig.xml"),
    ),
    GeneratorSpec(
        name="timeSteps",
        input_key="timeSteps",
        model_class=TimeSteps,
        template_name="region/time_steps.xml.j2",
        generate=time_steps.generate,
        output_relpath=Path("RegionConfigFiles/TimeSteps.xml"),
    ),
    GeneratorSpec(
        name="locationIcons",
        input_key="locationIcons",
        model_class=LocationIcons,
        template_name="system/location_icons.xml.j2",
        generate=location_icons.generate,
        output_relpath=Path("SystemConfigFiles/LocationIcons.xml"),
    ),
    GeneratorSpec(
        name="moduleInstanceDescriptors",
        input_key="moduleInstanceDescriptors",
        model_class=ModuleInstanceDescriptors,
        template_name="region/module_instance_descriptors.xml.j2",
        generate=module_instance_descriptors.generate,
        output_relpath=Path("RegionConfigFiles/ModuleInstanceDescriptors.xml"),
    ),
    GeneratorSpec(
        name="workflowDescriptors",
        input_key="workflowDescriptors",
        model_class=WorkflowDescriptors,
        template_name="region/workflow_descriptors.xml.j2",
        generate=workflow_descriptors.generate,
        output_relpath=Path("RegionConfigFiles/WorkflowDescriptors.xml"),
    ),
    GeneratorSpec(
        name="postprocessModelOutputToStationTemplate",
        input_key="postprocessModelOutputToStationTemplate",
        model_class=TransformationModule,
        template_name="module/transformation_module.xml.j2",
        generate=transformation_module.generate,
        output_relpath=Path("ModuleConfigFiles/Postprocess/Model/PostprocessModelOutputToStationTemplate.xml"),
    ),
    # Generic-body file types — 7 registry/UI configs whose structure is
    # too broad for field-by-field modelling. Each uses GenericXmlFile
    # (just a `body` dict) with a tiny per-type template that wraps the
    # FEWS root tag around the dict_to_xml output.
    *[
        GeneratorSpec(
            name=key,
            input_key=key,
            model_class=GenericXmlFile,
            template_name=template,
            generate=(lambda t: lambda m: generic_xml_file.generate(m, t))(template),
            output_relpath=Path(path),
        )
        for key, template, path in [
            ("productsFile",       "region/products.xml.j2",        "RegionConfigFiles/Products.xml"),
            ("gridsFile",          "region/grids.xml.j2",           "RegionConfigFiles/Grids.xml"),
            ("locationSetsFile",   "region/location_sets.xml.j2",   "RegionConfigFiles/LocationSets.xml"),
            ("filtersFile",        "region/filters.xml.j2",         "RegionConfigFiles/Filters.xml"),
            ("displayGroupsFile",  "system/display_groups.xml.j2",  "SystemConfigFiles/DisplayGroups.xml"),
            ("explorerFile",       "system/explorer.xml.j2",        "SystemConfigFiles/Explorer.xml"),
            ("spatialDisplayFile", "display/spatial_display.xml.j2", "DisplayConfigFiles/SpatialDisplay.xml"),
        ]
    ],
]

__all__ = ["SPECS", "GeneratorSpec"]
