"""Replay script: drive the wizard against EVERY tutorial spec at once.

Phases are computed at import time from
``examples/config-tutorial-input.json``: one phase per spec that's
registered in WIZARD_SPECS and has tutorial data. Each phase's answer
queue is mechanically generated by ``_generate.build_phase_answers``.

This is the regression-at-scale runner — it tests how many of the 250+
auto-derived wizard specs the parser can drive end-to-end with
formulaic answers. Per-spec byte-equivalent results land in the
project's ``report.md`` validation table.

Run cost: each item produces one parser call (~1-3k tokens on Ollama
qwen2.5:7b). Tutorial has hundreds of items across all specs, so a
full pass takes minutes. Use ``--max-phases`` on replay.py to pilot
on a slice first.
"""
from __future__ import annotations

from runners.agent.scripts._generate import build_phases


SCRIPT = {
    "project_name": "tutorial-full",
    "fixture_root": "examples/config-tutorial",
    "description": (
        "Auto-generated from examples/config-tutorial-input.json. One "
        "phase per registered WizardSpec that has tutorial data; "
        "answers formulaically rendered per spec's bulk_fields."
    ),
    "phases": build_phases(),
}
